### ISSUE TITLE
Cant enter recovery

### ISSUE THREAD

**Issue by msedekhyh** [osy86/HaC-Mini#100]
Got the first version and a windows keyboard tried ctrl+r win+r and alr+r two ways, from the computer off and from intel nuc screen all combination and Not woking.. Need yo boot there to use My time machine

**Comment by osy86** [comment]
Have you tried spamming alt+r constantly instead of holding it? Have you tried getting into OC boot picker first then holding alt+r and making a selection?

**Comment by msedekhyh** [comment]
Spamed alt+r and that did the trick.. Running My time machine now.. Thanks
