### ISSUE TITLE
Making a clone.

### ISSUE THREAD

**Issue by Jase-NZ** [osy86/HaC-Mini#101]
I would like to make a clone of my system so I have a backup, Would it just be a matter of formatting a usb drive as guid and using something like Carbon Copy then mounting both efi partitions on both drive's and copying one to the other ??

**Comment by osy86** [comment]
Hi, this isn't a support forum. Please try insanelymac.com or reddit.com/r/hackintosh with your questions.

But yes, if you CCC your OS install and copy the contents of EFI (or boot from USB and run HaC Mini installer again), it should work.
