### ISSUE TITLE
Usb wireless keyboard

### ISSUE THREAD

**Issue by lisongzhou19** [osy86/HaC-Mini#102]
2.3 和2.31 
usb无线键盘在boot menu 无法使用无法选择选项
链接usb有线键盘可以选择选项

Usb wireless keyboard can not be used in the boot menu can not select options 
Link usb wired keyboard can choose options

**Comment by osy86** [comment]
Does it work on 2.2?

**Comment by lisongzhou19** [comment]
2.2 effective
