### ISSUE TITLE
Hac 2.3.1 tbpatch not listing RP05 and with potential workaround. 

### ISSUE THREAD

**Issue by lmshsqlc** [osy86/HaC-Mini#104]
After installing 2.3.1 and I intended to proceed Thunderbolt Patcher. The GUI listed only 3 I2C items with no RP05 item. I've tried resetting nvram, hard reset, reinstalling 2.3.1 or 2.3 and thunderbolt driver(RP05) does not load. The CLI tbpatch compiled through source code also does not list any RP05 devices. 

in HAC 2.3 or 2.3.1, I've tried connect another thunderbolt device (a MacBook Air) when the MacBook Air recognises the nuc as a Thunderbolt PC and in system information/IORegistryExplorer, the thunderbolt/RP05 does not load. As well as the GUI & CLI tbpatch. 

I suspect that in 2.3.1 the installer disabled thunderbolt force power to get ready for thunderbolt native patch. However disabling thunderbolt force power also made thunderbolt to sleep preventing patcher from seeing it. 
However when I tried connecting a MacBook Air to wake thunderbolt up from cold boot but failed. 

Potential Workaround: 
In HAC 2.2, the Thunderbolt driver loads successfully. I installed HAC 2.2 then tbpatch tools recognised RP05. The IORegistryExplorer&system information loaded correct RP05 layout/information about thunderbolt bus. 
The process of dumping the firmware and patching successfully worked. 
After that installing HAC 2.3.1 worked.
BTW How do I recognise if it is Native or Legacy in IORegistryExplorer without looking at the installing process? 

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.3.1
- OSX version [e.g: 10.14.6]: 10.15
- NUC model [e.g: NUC8i7HNK]: NUC8I7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung EVO 970 1TB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Crucial 8GB 2400
- Second DIMM model (if installed): Crucial 8GB 2400
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 1080p
- Any TB3 devices: MacBook Air 
- Any USB devices: mouse, keyboard

**Comment by osy86** [comment]
May I ask why you’re looking for an RP05 device? The one you should be looking for is in I2C2 with the name AppleHPMDevice@70. It should be automatically selected when you launch the patcher.

**Comment by lmshsqlc** [comment]
> May I ask why you’re looking for an RP05 device? The one you should be looking for is in I2C2 with the name AppleHPMDevice@70. It should be automatically selected when you launch the patcher.

Before using the patcher I was looking for which device to patch cause there's 3 AppleHPMDevice devices. 
I cannot patch neither AppleHPMDevice, a dialog pops up and says error. As well as in the Patcher project readme.md it says using tbpatch CLI tool to patch RP05 device. 
That's why I was looking for a way to get the RP05 devices.

**Comment by osy86** [comment]
The readme was an example. You do not need RP05 and it’s not expected you have RP05 until after patching. File a ticket in the other project with your error log.
