### ISSUE TITLE
LG 32UD59 5k scale flickering Hac-Mini 2.3.2 connected via mini DP

### ISSUE THREAD

**Issue by jarryji** [osy86/HaC-Mini#106]
I have a LG 32UD59 5k display connected NUC8i7HVK via Mini DP to DP cable,
5120 x 2880（5K/UHD+ ),Scale to 2560 x 1440 Refresh rate @ 60hz.
Screen keep flickering most of time(especially at boot up, wakeup), if I change to HDMI cable,
All flickering gone, but refresh rate down to 30hz.
If no Scale applied (5120 x 2880,2560 x 1440) no flickering happened.

NUC: NUC8i7HVK
CABLE: Mini DP to DP
MacOS: 10.14.6
Hac_Mini: 2.3.2
boot from: Samsung SSD 960 EVO 500GB
ram: 8GB 2400mhz x 2

**Comment by osy86** [comment]
#7
