### ISSUE TITLE
MacOs 13.4.1 Patch OSX installer is disabled

### ISSUE THREAD

**Issue by kmsb-git** [osy86/HaC-Mini#1093]
**Describe the bug**
I creating OSX installer on MacOS 13.4.1, the check Patch OSX installer is disabled. Pls check that.

**Environment:**
 - Running OSX version:  13.4.1
 - Target drive OSX version: 13.4 or 13.4.1
 - HaC Mini installer version: 3.3.1
<img width="643" alt="Screenshot 2023-07-12 at 17 42 53" src="https://github.com/osy/HaC-Mini/assets/17844532/b0c5a68e-b43a-42cb-995e-3f4f2637a044">

**Comment by osy** [comment]
As stated in the guide it’s not supported on 11.0+. Please read the guide.
