### ISSUE TITLE
Wake up by itself right after going to sleep

### ISSUE THREAD

**Issue by Anycubic** [osy86/HaC-Mini#1096]
**Describe the bug**
It wakes up by itself right after going to sleep

**Expected behavior**
It should stay under sleep state

**Configuration**
- HaC Mini version [3.3.1]: 
- OSX version [10.15.7]: 
- NUC model [NUC8i7HNK]: 
- Boot SSD model and protocol [[fanxiang S660 2TB PCIe 4.0 NVMe]
- First DIMM model [[Crucial 8GB DDR4 2400MHz CL17]
- Second DIMM model (Crucial 8GB DDR4 2400MHz CL17): 
- Display port(s) used [HDMI]: 
- Display resolution(s) [2K]: 
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [N/A]: 

**Modifications**
I did no mod

**Panic log**
N/A

**Comment by Anycubic** [comment]
Ok, I found the reason for this issue, if my keyboard is plugged into front slot the NUC wakes up by itself, in the rear USB slots there is no problem at all. Is there a reason for this behaviour?
Thanks

**Comment by osy** [comment]
Hi this is specifically mentioned in the guide: https://osy.gitbook.io/hac-mini-guide/installation-guide/bios-settings

**Comment by Anycubic** [comment]
@osy sorry but I didn't understand where the issue is, I already had applied those settings in my bios
