### ISSUE TITLE
Corrupted boot entries

### ISSUE THREAD

**Issue by trevorwdunn** [osy86/HaC-Mini#1101]
**Describe the bug**
When attempting to reinstall OC on a new drive (the drive is the only part I've replaced), my Hades Canyon hangs on the boot options screen. Additionally, it gives me a pointer, and when I click with the mouse a virtual keyboard comes up. As far as I can tell, I cannot use this keyboard for input in this state. Likewise, the NUC accepts no input from my physical keyboard. 

Additionally, when attempting to install Windows or Linux, those installers appear in the Boot Menu as "OpenCore". When selected, this option returns me to the Boot Menu screen. 

**Expected behavior**
NUC boots to Opencore installation environment

**Environment:**
 - Running OSX version: 13.4
 - Target drive OSX version: Empty
 - HaC Mini installer version: All OpenCore configurations I've tested

**Additional context**
I previously ran Opencore on this machine, then attempted to update to Sonoma normally. Following this, Opencore failed, and I was only able to boot into the MacOS 14 recovery environment. At any point beyond this, I would receive graphical errors and simply turned off the machine. 

I then removed that NVME drive and used it in another Opencore build for a relative, so I no longer have the original drive. I'm now using a new, blank NVME drive. 

**Logs**
Not applicable

**Comment by osy** [comment]
You need to either run opencore (from a flash drive or something) and select the erase NVRAM option or reset your BIOS. https://osy.gitbook.io/hac-mini-guide/post-installation/support#reset-nvram
