### ISSUE TITLE
repeated efi entry

### ISSUE THREAD

**Issue by msedek** [osy86/HaC-Mini#111]
Im currently dual booting with windows, with the clean install i had just 1 macos entry and just 1 BOOTcamp entry, after updating the hac-mini from 2.2 to 2.3.3, Im getting BOOTcamp  2 times and mojave... 

Did clear the nvram and no change.. any guide on how to delete de duplicated entry?

**Comment by osy86** [comment]
Seems like an OC issue. 2.2 was using OC 0.0.4 and 2.3 uses OC 0.5.1.

**Comment by osy86** [comment]
It's also possible you installed the EFI files to both your Windows partition (NTFS) and the ESP partition (where OC resides). Anyways this is not a hac mini issue, so closing.
