### ISSUE TITLE
[Feature] Add Installer Option for graphical boot picker

### ISSUE THREAD

**Issue by PeterBurner** [osy86/HaC-Mini#114]
**Description**
According to the [Opencore Vanilla Desktop Guide](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/#opencore-tips) Opencore can be used in conjunction with rEFInd.
It would be nice to have a graphical picker for start volume selection and other useful tools like SIP management or boot to recovery.
Since not everybody needs or wants this, it should be optional in the installer.

**References**
 - https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?page=8&tab=comments#comment-2672316

**Comment by osy86** [comment]
I’ve been told there will be a better GUI coming soon based off of Apple’s GUI code. Should probably be better.
