### ISSUE TITLE
Could you please tell me what should I do if I plan to translate this repo to zh-CN?

### ISSUE THREAD

**Issue by cnyyk** [osy86/HaC-Mini#120]
Could you please tell me what should I do if I plan to translate this repo to zh-CN?

Original url: https://osy.gitbook.io/hac-mini-guide,
Translated url should be: https://osy.gitbook.io/hac-mini-guide/zh-cn ?

**Comment by osy86** [comment]
https://github.com/GitbookIO/gitbook/blob/master/docs/languages.md

Just make the translated files in a sub directory and I can take care of linking it from the main page.

**Comment by cnyyk** [comment]
OK.
Simplified Chinese translation will placed into zh-hans/ then finished.
