### ISSUE TITLE
Is there a guide for TBPatcher?

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#121]
I'd like to try the Native Thunderbolt patcher.
But I am not sure if it is secure to click the FLASH button and leave Device to default since there are multiple selections.

Besides, should I upgrade my current NUC firmware to V33, the version tested mentioned in the Warning? I purchased this device several days ago, so it may not have the newest firmware.
![截屏2019-11-14下午9 06 56](https://user-images.githubusercontent.com/38860226/68859644-96081b80-069c-11ea-9002-6633ac5da9a5.png)

![截屏2019-11-14上午5 03 31](https://user-images.githubusercontent.com/38860226/68859446-1c702d80-069c-11ea-8ec0-7dea4844159e.png)

**Comment by lmshsqlc** [comment]
The GUI guide is still working in process I think. But I have tested using a V33 firmware for Thunderbolt with no issue. I strongly recommend you to wait for the guide at GitHub repository osy86/ThunderboltPatcher

**Comment by osy86** [comment]
The latest version is in the build. It should be as simple as pressing flash.

**Comment by KrisCris** [comment]
Thanks for reply,  I am going to do the patch after upgrading my Thunderbolt firmware to v33. Since I have a HP TB3 dock, it is worth a try.
BTW, I can restore my original firmware any time by selecting the uninstall, right?

**Comment by osy86** [comment]
Yeah

**Comment by DSM2-Hackintosh** [comment]
I don't get any device for patching

**Comment by osy86** [comment]
Did you install “thunderbolt native” and reboot?

**Comment by DSM2-Hackintosh** [comment]
@osy86 yes, sure. But unfortunately nothing to choose.

**Comment by osy86** [comment]
Open a new issue with information in the issue template. Also attach your config.plist
