### ISSUE TITLE
To turn off the SIP.

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#122]
**Describe the bug**
After disabling the SIP in recovery and restart, the SIP is still enabled.

I entered Recovery by selecting it in the boot picker: *Recovery (dmg)*. Maybe I did it in a wrong way?

**Expected behavior**
The SIP should be disabled.

**Configuration**
- HaC Mini version : 2.4
- OSX version : 10.15.1
- NUC model : NUC8i7HVK
- Boot SSD model and protocol : 
- First DIMM model : Kingston HyperX Impact DDR4-2666 16GB
- Display port(s) used : Mini-DP
- Display resolution(s) : 2K
- Any TB3 devices: None yet.
- Any USB devices: Mouse receiver, Keyboard, etc.

**Modifications**
None

**Comment by KrisCris** [comment]
And why is it so slow to get into the Recovery? It took me several minutes waiting for the progress bar to show up.

**Comment by dickding** [comment]
It could not be disabled in that way. Check below:

https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/config.plist/kaby-lake#nvram

**Comment by 22dm** [comment]
In 10.15, besides @dickding said, you may also need `sudo mount -uw /` after rebooting.

**Comment by KrisCris** [comment]
Thanks! 

Some funny idea came to my mind that made me believed it may work the same as Mac, but obviously not, still the same as we did in Clover...

So what is the significance of enabling SIP by default in this project? Besides, does that mean the Recovery is useless in Hackintosh?

**Comment by osy86** [comment]
This project is designed to build the first real secure hackintosh. Eventually secure boot option in installer will be default (opt out). Intel is unique that it allows us to secure the boot almost as good as T2. https://osy.gitbook.io/hac-mini-guide/details/secure-boot

**Comment by lmshsqlc** [comment]
> This project is designed to build the first real secure hackintosh. Eventually secure boot option in installer will be default (opt out). Intel is unique that it allows us to secure the boot almost as good as T2. https://osy.gitbook.io/hac-mini-guide/details/secure-boot

HaC Mini 2.4 successfully implemented SecureBoot.

**Comment by osy86** [comment]
#78
