### ISSUE TITLE
"Image Authorization Fail." upon enabling of SecureBoot in BIOS

### ISSUE THREAD

**Issue by HorstBrack75** [osy86/HaC-Mini#124]
I read this:

> > This project is designed to build the first real secure hackintosh. Eventually secure boot option in installer will be default (opt out). Intel is unique that it allows us to secure the boot almost as good as T2. https://osy.gitbook.io/hac-mini-guide/details/secure-boot
> 
> HaC Mini 2.4 successfully implemented SecureBoot.

Therefore I upgraded to 2.4 enabling security in the installer.

HaC Mini 2.3.4 -> 2.4

Installer options:
-Keep GUIDS
-Legacy TB
-Enable Security
-DW1820A driver
 
10.14.6 (18G1012)
NUC model: NUC8I7HVK
Boot SSD model and protocol: Intel 660p 1TB, NVME
Second SSD model and protocol (if installed): Samsung 970 EVO 1TB, NVME
First DIMM model: Crucial DDR4-2400 16GB
Second DIMM model: Crucial DDR4-2400 16GB
Display port(s) used: 2x mDP
Display resolution(s): 2x1600x1200@60
Any TB3 devices: No
Any USB devices: USB Receiver for Logitech Keyboard & Mouse

Booting into OC fails with the "Image Authorization Fail" error message.

"The administrator can then use their custom PK to sign a KEK to sign OpenCore and place the OpenCore certificate inside the DB."

Am I holding it wrong? Is this supposed to be done by the installer during an upgrade?
Are there any manual steps required that I might have missed? 

With secure boot enabled, I can still boot into my windows partition but not in OC.

Everything else works great! THX!

![IMG_3189](https://user-images.githubusercontent.com/2854956/68992046-542ad100-0866-11ea-8e3f-5afc34e656ea.jpg)

**Comment by lmshsqlc** [comment]
I’ve also encountered this problem. All I did is check the last box in securable which says clear secure boot data. According to the description next time it will allow a non-secure boot system to boot. After the next boot, restart the computer and go back to secure boot settings, i found the install Intel platform key available. Check that box and mine is all right.

**Comment by osy86** [comment]
If you use secure boot you need to sign your boot efi. That is beyond the scope of this guide.

**Comment by HorstBrack75** [comment]
> If you use secure boot you need to sign your boot efi. That is beyond the scope of this guide.

Understood. Could you point me to some more reading maybe? e.g. could I use PK, KEK generated in Windows using TPM, or do I need to fallback to self-signed openssl?
