### ISSUE TITLE
A couple of issues found...

### ISSUE THREAD

**Issue by DSM2-Hackintosh** [osy86/HaC-Mini#126]
First off all : Thank you for all the work!

I found a small issue and also have a problem with the Thunderbolt 3 Chipset patcher.

Issue: 
If you do a clean install it won't be successful without an EC SSDT. 
Without the EC SSDT you will stuck at apfs_module_start.

[SSDT-EC.aml.zip](https://github.com/osy86/HaC-Mini/files/3854560/SSDT-EC.aml.zip)

Thunderbolt: 
After I installed everything with the HaCMini.pkg with this Settings 

![1](https://user-images.githubusercontent.com/56890355/68997647-05525b00-08a9-11ea-9791-c8073c240aee.png)

I stuck with a kernel panic, which I only could get rid off if I remove the 2 Thunderbolt entries  
and it doesn't matter if I use OC Bootloader or configure Clover...

![2](https://user-images.githubusercontent.com/56890355/68997650-0b483c00-08a9-11ea-8daf-0f606d59546c.png)

As soon as those are disabled I can boot up without issues...
But...I cant flash the Apple Mode Firmware on it because off this error.

<img width="483" alt="Bildschirmfoto 2019-11-16 um 19 43 26" src="https://user-images.githubusercontent.com/56890355/68997687-74c84a80-08a9-11ea-9309-10f0514194a5.png">

<img width="996" alt="Bildschirmfoto 2019-11-16 um 19 43 38" src="https://user-images.githubusercontent.com/56890355/68997689-7f82df80-08a9-11ea-8dd4-41ee7d38f177.png">

Do I have to flash the V33 Thunderbolt Firmware first before I can get this up and running?

I am running the same Bios as you did in your guide! 

ioregistryexplorer file attached
[macOSNucs Mac mini.zip](https://github.com/osy86/HaC-Mini/files/3854574/macOSNucs.Mac.mini.zip)

At the moment I try it via Clover
[EFI.zip](https://github.com/osy86/HaC-Mini/files/3854579/EFI.zip)

**Comment by osy86** [comment]
Regarding the tbpatcher issue, you’re supposed to just double click it...

**Comment by osy86** [comment]
> If you do a clean install it won't be successful without an EC SSDT.
Without the EC SSDT you will hang at apfs_module_start.

What version of OS X?

**Comment by DSM2-Hackintosh** [comment]
I double clicked it and started it also via root over terminal and so on...
Doesnt change anything unfortunately...
For what are those 2 entries exactly ? Which function do they have ?
There was no mention about them in your guide...

About EC SSDT 
10.15.1 and above :)

**Comment by osy86** [comment]
Can you post your config.plist

**Comment by DSM2-Hackintosh** [comment]
@osy86 Check the first post, EFI.zip is the complete EFI.

**Comment by KrisCris** [comment]
My TB3 works perfect after patching. (Haven't encountered any problem)
This is how I did:
1. Upgrade BIOS to latest.
2. Upgrade TB firmware to latest (V33). (But the patcher should be able to see TB devices even without the update)
3. A clean installer USB with latest MacOS from AppStore + HacMini_V2.4 with Native TB selected.
4. Then It should be straight forward.

**Comment by DSM2-Hackintosh** [comment]
@KrisCris Mate, I know you try to help but it's not like I don't know what I am doing or not familiar with hackintosh.

If you read my description I am on the latest Bios version already. The only thing I don't did is the upgrade of the firmware before patching. Also installation steps are correctly and mentioned. 

As soon the mentioned pciroot devices are in the config.plist - I can't get pass the kernel panic. 

The two entries were made by osy86 if you install the HaC-Mini.pkg

**Comment by osy86** [comment]
@DSM2-Hackintosh Those two entries enable the TI PD device which is required for Thunderbolt flashing. If possible, please attach the panic message when those are enabled. Also attach an ioreg dump.

**Comment by osy86** [comment]
Will close this issue if no panic log is provided.

**Comment by DSM2-Hackintosh** [comment]
Really busy at the moment. Can't provide you the files before the weekend.

**Comment by osy86** [comment]
Closing for now. Will reopen if more info is provided.
