### ISSUE TITLE
Failure to create USB installer

### ISSUE THREAD

**Issue by indyfromoz** [osy86/HaC-Mini#127]
**Describe the bug**

I followed the tutorial for new installation media preparation [here](https://osy.gitbook.io/hac-mini-guide/installation-guide/installation). I choose a 16Gb USB 3.0 Cruzer Mini stick to prepare the installer. Installer creation failed with a `The installation failed` error when I tried to patch the installer

**Expected behavior**
USB installation media should be created successfully 

**Environment:**
 - Running OSX version: macOS Catalina 10.15.1
 - Target drive OSX version: macOS Catalina 10.15.1
 - HaC Mini installer version: v 2.4

**Additional context**

Screenshots of patch options and the error - 

<img width="625" alt="Screen Shot 2019-11-17 at 11 31 56 am" src="https://user-images.githubusercontent.com/315443/69001246-37a69b80-092f-11ea-86e5-1f32f16a514f.png">

<img width="619" alt="Screen Shot 2019-11-17 at 11 32 47 am" src="https://user-images.githubusercontent.com/315443/69001248-3ecda980-092f-11ea-95c5-1f30ee4e3393.png">

**Logs**
[install.log](https://github.com/osy86/HaC-Mini/files/3855101/install.log)

**Comment by osy86** [comment]
Looks like the same as #96

**Comment by indyfromoz** [comment]
@osy86 Sincerely appreciate all the effort you've put in the guide and your kindness in sharing it with the rest of the world.

Marking this issue as duplicate of #96 doesn't quite make sense as it seems like a Hackintosh is required to prepare a HacMini installer. For someone like myself without a Hackintosh to prepare an installer, is it correct to assume HacMini installer can only be prepared with a Hackintosh? If yes, this can be added a note of warning in the Gitbook guide....

**Comment by osy86** [comment]
I don’t know what you’re talking about, it’s the same error as seen in the install.log?

**Comment by indyfromoz** [comment]
Yes, it is the same error from the install.log attached in #96.

What I am trying to say -- Adding a note or warning in the section - https://osy.gitbook.io/hac-mini-guide/installation-guide/installation, like here - 

![image](https://user-images.githubusercontent.com/315443/69003501-4bfe8e80-0957-11ea-8a3e-ad3b48a358e6.png)

that SIP **must be disabled** when creating USB installation media in a real Mac (not Hackintosh) will help enthusiasts not get stuck right at the beginning. 

Peace!

**Comment by osy86** [comment]
Sorry it’s indeed a bug and I haven’t had time to fix it yet. Once it’s fixed there isn’t a need to disable SIP.
