### ISSUE TITLE
Any way to monitor Fan speed in MacOS?

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#129]
Out of curiosity, is there any way to monitoring the fan speed in macOS? I haven't tried that before, but I think a ACPI patch is required. 

BTW, is there anyone whose NUC also making some weird vibration noise when fan speed goes up?

**Comment by DSM2-Hackintosh** [comment]
Yes, replace virtual smc kext and the UEFI driver with fakesmc + Plugins and add smchelper driver to the driver folder.

Also don't forget to edit the config.plist and apply the changes there aswell and you are good to go. 

![Screenshot_20191117_131341](https://user-images.githubusercontent.com/56890355/69007266-1b5d2b80-093c-11ea-8be0-50c8309d230e.jpg)

**Comment by KrisCris** [comment]
You mean virtual smc currently does not support fan speed monitoring?
and, Amazing core count :)

**Comment by DSM2-Hackintosh** [comment]
It supports some sensors but not that much as fakesmc with the Plugins available does.

Thanks, it's my Socket 3647 Hackintosh with an 3175X CPU. MacPro7.1 but much faster then the new MacPro ever could be.

**Comment by HorstBrack75** [comment]
> BTW, is there anyone whose NUC also making some weird vibration noise when fan speed goes up?

Yes, same issue her. There seems to be a resonance frequency hit somewhere in the mid rpm range.

I used to use MacsFanControl to circumvent this. 

Had the same question. 
See #95 
Won't work with VirtualSMC.

**Comment by KrisCris** [comment]
Thanks for reply!

Then I think I should stick with VirtualSMC in consideration of the compatibilities with this project :).

**Comment by DSM2-Hackintosh** [comment]
There are absolutely no compability issues at all mate. 

If you know what you are doing you never will run in issues.

**Comment by KrisCris** [comment]
> There are absolutely no compability issues at all mate.
> 
> If you know what you are doing you never will run in issues.

I understand what you mean, but I don't want to replace SMC related files every time there is an update. After all this is my major machine, so...

Anyway, your reply is really appreciated, I think I can try this out on my laptop.

**Comment by KrisCris** [comment]
> There are absolutely no compability issues at all mate.
> 
> If you know what you are doing you never will run in issues.

btw, (apologies for off the topic) my laptop is already utilizing fakesmc and its fakesmc_*Sensors kexts, but still no luck showing any fan speed information. Does it means I need to make a SSDT for that?
