### ISSUE TITLE
Incompatibility of the Bluetooth function of the 1820A NIC with ThunderBolt

### ISSUE THREAD

**Issue by ivmm** [osy86/HaC-Mini#130]
An issue was previously submitted: https://github.com/osy86/HaC-Mini/issues/125 Reported a problem with Bluetooth being visible but unable to connect to the device after using the 1820A support.

After the reminder, if you use the Native Thunderbolt, this will happen. With Legacy Thunderbolt, you can connect to Bluetooth normally.

**Comment by dickding** [comment]
Hi，I RETRIED the TB patch, and found it is not the TB problem. The bluetooth doesn't work properly, no matter with native or legacy TB.   Sometimes it works, but sometime it does not. I think it is something about the bluetooth driver.

**Comment by ivmm** [comment]
> Hi，I RETRIED the TB patch, and found it is not the TB problem. The bluetooth doesn't work properly, no matter with native or legacy TB. Sometimes it works, but sometime it does not. I think it is something about the bluetooth driver.

But after I try hot restart and cold restart many times, I can achieve Bluetooth connection.

**Comment by dickding** [comment]
After I uninstalled the patcher, the blutooth worked for a while. But, after serval reboots & reconnects, now the problem remains. So I think the TB firmware is not the cause.

**Comment by ivmm** [comment]
> After I uninstalled the patcher, the blutooth worked for a while. But, after serval reboots & reconnects, now the problem remains. So I think the TB firmware is not the cause.

It’s true that this situation has happened again, my fault.
