### ISSUE TITLE
Installing to USB Fails Due to SIP

### ISSUE THREAD

**Issue by imaducklol** [osy86/HaC-Mini#133]
**Describe the bug**
Trying to install to 32GB drive with OSX 1.14.6 on it. Default settings except for DW1820A and of course Patch OSX installer
**Expected behavior**
It should work, I am using everything according to the instructions

**Environment:**
 - Running OSX version: 1.15.1
 - Target drive OSX version: 1.14.6
 - HaC Mini installer version: 2.4

**Additional context**
N/A

**Logs**
[install.log](https://github.com/osy86/HaC-Mini/files/3872809/install.log)

**Comment by imaducklol** [comment]
Turning off SIP solved the issue

**Comment by imaducklol** [comment]
Probably shouldn't be closed i guess, as this is still an issue

**Comment by imaducklol** [comment]
I realize this is similar to the original issue in #96 but that ended up labeled as a usb error, whereas i am quite sure my error was due to SIP

**Comment by osy86** [comment]
`2019-11-20 20:32:07-08 MacBookAir installd[589]: ./postinstall: find: /Volumes/Install macOS Mojave/.Spotlight-V100: Operation not permitted`

Yup, same error as #96

I will try to fix this as soon as I return from vacation.
