### ISSUE TITLE
Can't get Haydes Canyon to boot to USB (Only boot entry is "Windows Boot Manager")

### ISSUE THREAD

**Issue by stdale** [osy86/HaC-Mini#134]
First off, this is not a bug with the software per say... But more being unable to follow the instructions in the wiki guide.  And hoping someone else also had this issue and has a solution. 

**Describe the bug**
I followed the instructions to make the bootable usb with MacOS install after running the latest HacMini installer and adding my required options.  after failing several times to be able to boot to the usb, or even get it to show as a boot option I found the troubleshooting step in regards to windows boot manager option.  I followed all the instructions to reset the bios settings.

1. removed security jumper
2. try install with security jumper off and on
2. reset bios passwords
3. reset TPM
4. BIOS recovery
5. Go into bios and enable "3rd part EFI bootloader drivers
6. Disable platform security technology
7. Enable usb as boot option

I tried all of these in different orders and still can not get the USB to show up as a bootable option. 

I have tried USB on other systems, and it boots to USB just fine and shows up in the bios etc as boot option. 

**Expected behavior**
Upon system power on and hitting F10, I should see usb as a boot option.  I don't.   

**Configuration**
- HaC Mini version [2.4]: 2.4
- OSX version [ Mojave]: Mojave
- NUC model [ NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 512GB Intel NVMe 760P SSD
- 
- Any USB devices: Kingston USB3.1 DT 50 32g, usb keyboard, usb mouse

**Modifications**
Added dell AD1820 wifi driver

**Panic log**
no log, won't boot to usb

**Comment by stdale** [comment]
This isn't a bug and should be labeled user error looking for help.

But i can't find the option to remove bug

**Comment by goodbest** [comment]
Have you tried with different USB ports?
Sometimes I can't boot from USB using the front blue port, but rear ports are fine. 

(Of course you have to make sure all usb ports are enabled in BIOS )

**Comment by dickding** [comment]
Don' t use the front USB port during installation. I had a similiar boot problem before,  and solved it by using the rear ports.

**Comment by KrisCris** [comment]
I think you should try other ports. 
This happened the first time I install MacOS that the port on image cannot detect bootable driver...No idea why.
<img width="491" alt="截屏2019-11-23下午10 56 19" src="https://user-images.githubusercontent.com/38860226/69480706-e58cdb00-0e44-11ea-807e-662a1198c080.png">

**Comment by osy86** [comment]
The cause is Windows messed up NVRAM variables to force booting from windows. If you can boot into OC picker menu you can wipe NVRAM but of course that’s the issue here. You can also do a full bios reset to wipe nvram.

**Comment by stdale** [comment]
@osy86 , what is considered a full bios reset to wipe nvram?

I pulled my security jumper and in the select option window, I picked force BIOS recovery. It reports several time and then i can get back into the bios and have same thing happen.  Am I missing a step.

Also one thing I note, when i boot to the UEFI shell, the usb doesn't show up as one of the entries when i run map.  All I see are entries that mount to the existing windows install.

Is it somehow possible to put my mac installer files on that partition and mount it from EUFI and run it from there? 
@KrisCris, thanks! I was really hoping this was it... But to no avail.

**Comment by osy86** [comment]
In uefi shell you can run the boot.efi from the usb stick. However, you need to make sure secure boot is off.

**Comment by stdale** [comment]
@osy86 , I was able to finally figure out my issue with how to correctly do a BIOS restore. and can now boot a knoppix live linux CD on the device.   Using a tool a found call rEFInd, I was able to see an option to boot install mac os moajva and launch to it.  

When it boots I get the following

[cut]
This version of Mac OS X is not supported on this platform!
Reason: NUC8i7HVB


My nuc is a: NUC8i7HVK

A) Suggestions? B) Should I close this ticket for now and open a separate one?

![20191124_003453](https://user-images.githubusercontent.com/1749679/69492172-88e4ec80-0e53-11ea-8eff-7e56c22f3e53.jpg)

**Comment by osy86** [comment]
Are you using 10.14.5+?

**Comment by stdale** [comment]
Hi @osy86,
 
  Its 10.14.6.  It was downloaded and usb created on a mac running 10.15.1.

**Comment by stdale** [comment]
Also, if it makes a difference in the Hac Mini installer I had it add the dell 1820 wifi drivers. But I currently don't have the card. So that piece of hardware is missing.  Not sure if that can cause an issue.

**Comment by stdale** [comment]
Upon exploring the .dmg that was flashed to the USB, I notice there is no EFI folder (possibly why it wouldn't boot by itself without help)...

Is there specific files in the image I can check to make sure the Hac Mini files have been installed?

**Comment by lmshsqlc** [comment]
I don’t know how you made your boot drive, but if the drive uses MBR and a single install partition as APFS then it won’t boot. The reason for that is conventional UEFI don’t recognize APFS and bootloader within. 
Usually you’ll need extra step to create this boot drive by first manually convert it to GUID format, then there’ll always be a EFI partition formatted as FAT. Only after that you use createinstallmedia you’ll be able to boot from the drive. The bootloader, in this case the opencore will be able to read by UEFI from EFI partition as it is formatted as FAT.

**Comment by osy86** [comment]
The guide goes through the process to format the drive and run the create installer script.

**Comment by stdale** [comment]
@lmshsqlc , Thank you!  That is exactly the issue I had and why it won't boot!

@osy86 , I followed the guide to create the installer script.  And now that I got it booting I'm just trying to figure out why it says my device is unsupported.

I have a NUC8i7HNK, and am trying to install 10.4.6.   I should be good to go right? Is there any boot time args I can add to get more info to share?

**Comment by osy86** [comment]
I’m confused at why that would be an issue. The guide asks you to format the usb as guid partition right?

**Comment by stdale** [comment]
@osy86 ,  I don't have local access to a mac to make the files.  I had to have a remote friend make the image (DMG) and send it to me so I could burn to a local USB to use.

**Comment by lmshsqlc** [comment]
> @lmshsqlc , Thank you! That is exactly the issue I had and why it won't boot!
> 
> @osy86 , I followed the guide to create the installer script. And now that I got it booting I'm just trying to figure out why it says my device is unsupported.
> 
> I have a NUC8i7HNK, and am trying to install 10.4.6. I should be good to go right? Is there any boot time args I can add to get more info to share?

This should not be filed as an issue as it has already written in the guide. 

In case you don’t know there’s a guide in this repository HaC-Mini/Installation-Guide and you start an issue, the template also tells you to follow the steps including troubleshooting, which will lead you to the guide.

**Comment by osy86** [comment]
I see. I’m afraid your other issues might be related as well.

**Comment by lmshsqlc** [comment]
> @osy86 , I don't have local access to a mac to make the files. I had to have a remote friend make the image (DMG) and send it to me so I could burn to a local USB to use. So while the guide did, I just didn't do it correctly in windows when I burned the image to usb.

Understandable. In this case I will suggest using a macOS virtual machine downloaded to make an installer, so that wont harm your current computer. Good luck

**Comment by stdale** [comment]
@osy86 , I'm beginning to believe so as well.. I'll close this out and try the other suggestions and open a fresh one once i've verified it's all been done correctly. 

@lmshsqlc , Thank you so much!  Thats a great idea and I didn't know you could run macOS in a VM!
