### ISSUE TITLE
Disabling SIP using csrutil & boot from Thunderbolt drive

### ISSUE THREAD

**Issue by crhendo** [osy86/HaC-Mini#135]
Firstly, many thanks for the effort that has been freely contributed to create AND support this brilliant guide and installation "kit". Like many others, I have successfully created a fully capable Mac environment on my very flexible NUC including Wifi, Bluetooth and Thunderbolt. Thank you!

While I could probably live without the issues described in the following two questions, I am hoping that others may have found a solution. So here goes....

1. There are times when I may need to enter recovery mode (eg to disable SIP). I have tried all the recommended suggestions including repeated WIN-R, ALT-R and ultimately continuous pressing of the ALT key to successfully bring up the menu. With the boot menu on screen if I select number 4 (Recovery) the number stays on the screen for a few seconds and then disappears without taking any action. Is there anything else I should try?

2. As my NUC has a dual purpose, has anybody tried to boot OpenCore from an external Thunderbolt connected NVME drive? 

As I have said, neither of these issues are "life threatening", I am simply trying to improve perfection.

**Comment by osy86** [comment]
1 has been resolved in #123 and should be in the next release. 2 I haven’t tried but it would require some extra drivers extracted from macs. I don’t have a tb drive to test with but if you do, I can extract them and let you try.

**Comment by crhendo** [comment]
Thanks for the quick response. I had read #123 but I fear I am simply not technical enough to implement the solution AND will happily wait for the next release. 

I have two of [these](https://www.newegg.com/wavlink-wl-ute02-enclosure/p/0VN-0069-00025?Item=9SIA6PFA3D8575) and was hoping I could simply slot my 1TB Samsung NVME drive containing the MacOS build in that enclosure and boot. I suspect that my lack of technical knowledge (at this level) _may_ make me a poor candidate for testing. Perhaps we should wait for a more qualified person?

**Comment by crhendo** [comment]
Hi,

Sorry, I just noticed that I could reply to this email directly. What do you prefer…GitHub or email?

Thanks for the quick response. I had read #123<https://github.com/osy86/HaC-Mini/pull/123> but I fear I am simply not technical enough to implement the solution AND will happily wait for the next release.
I have two of these<https://www.newegg.com/wavlink-wl-ute02-enclosure/p/0VN-0069-00025?Item=9SIA6PFA3D8575> and was hoping I could simply slot my 1TB Samsung NVME drive containing the MacOS build in that enclosure and boot. I suspect that my lack of technical knowledge (at this level) may make me a poor candidate for testing. Perhaps we should wait for a more qualified person?
Regards,

Chris H

**Comment by osy86** [comment]
Either way it shows up on github so whatever works for you.

I’ll attach the drivers to this issue when I get home. You can try it or you can find someone else to try it. I personally don’t know anyone else with such a setup so it’ll be hard to find testers.

**Comment by crhendo** [comment]
If I place the MacOS drive in the Thunderbolt enclosure it is currently not recognised as a bootable drive. I suspect I would need to create a new clean install?

So the process could be:-


  1.  Backup current system using Time Machine
  2.  Place NVME drive in the Thunderbolt enclosure
  3.  Create new USB installer using new drivers
  4.  Boot the new installer
  5.  Format the external NVME drive as per the current process and start the clean install (assumes the installer can see the Thunderbolt drive)
  6.  If successful, recover the system using Time Machine

Does this make sense?

**Comment by osy86** [comment]
You need to enable thunderbolt boot in bios but I’m not sure that’s compatible with the native thunderbolt patch.

**Comment by crhendo** [comment]
I’m happy to give it a try. Should the Thunderbolt Security Level be left at “Legacy Mode”?

**Comment by osy86** [comment]
Yeah

**Comment by crhendo** [comment]
I can install Catalina on the external Thunderbolt drive but the only way I can run it is if I leave the USB OpenCore installer inserted and hit the ALT key to bring up pick list. The NUC does not see the Thunderbolt drive as a bootable disk.

**Comment by crhendo** [comment]
Tried using CCC to clone to the Thunderbolt drive and then ran EFI Cloner. The external Thunderbolt drive was still not recognised as a bootable drive however I could still point to the drive and allow it to run using any OpenCore boot drive.
