### ISSUE TITLE
Use with Catalina installer

### ISSUE THREAD

**Issue by ejh4286** [osy86/HaC-Mini#136]
I tried this guide with Catalina installer and repeatedly got the “do not proceed” symbol (circle with diagonal line).  Does the guide only work with Mojave?

**Comment by osy86** [comment]
It should work with Catalina. Check the verbose logging option. And take a picture of the panic log.

**Comment by crhendo** [comment]
I can also confirm that it works fine on Catalina

**Comment by ejh4286** [comment]
I just kept hitting ctrl alt delete and it eventually made it through.  All is well now.
