### ISSUE TITLE
Installer corrupts BCD

### ISSUE THREAD

**Issue by Thundy2040** [osy86/HaC-Mini#137]
**Describe the bug**
After creating an installer usb, I boot my NUC and it gets into the installer. After it does its thing it restarts however after that there are multiple entries in the bios boot menu and none of them are bootable. Neither Windows nor Installer usb. When usb is plugged all of the boot entries show Bootloader osx too. Only thing that stays working is the UEFI shell. Which I can use to boot into windows and clean up the bcd. I also tried the installer usb with boot menu installed. If I miss the 5 second countdown it restarts and same thing happens once again. No more bootable usb. I have done this 3 times now. I don't think I'm missing a detail but let me know if I do. Apparently someone had a similar issue over at osx86 forums but he was able to pass the installation. 

**Expected behavior**
I expected to continue booting from the usb and complete the installation. 

**Environment:**
 - 10.14.4 on a VM
 - 10.14.5 
 - 2.3.4 and 2.4

**Additional context**
I discovered a bad RAM module and took it out. However it seems to have changed nothing

**Logs**
[install.log](https://github.com/osy86/HaC-Mini/files/3898841/install.log)

**Comment by lmshsqlc** [comment]
Is this closed or it doesn’t need further help?

**Comment by Thundy2040** [comment]
Solved. I tried flashing the BIOS once more after the removal of the faulty ram. Now it boots.
