### ISSUE TITLE
Creating a dual purpose NUC?

### ISSUE THREAD

**Issue by crhendo** [osy86/HaC-Mini#139]
Over the past week I had very successfully created a Catalina install on my Hades Canyon NUC. My hope was that I might be able to boot Catalina from an external Thunderbolt drive and run Windows off the Internal NVME drives ie a dual boot configuration. Unfortunately from significant research it appears that this is currently not possible. 

Three days ago, I reinstalled my Windows NVME drive inside my NUC (replacing the Catalina NVME drive) and spent 4 hours on my day job. While windows booted as it should, I eventually noticed that I had no access to my external thunderbolt drives. To cut a long story short I then went through a lot of steps including disabling the Thunderbolt controller and reinstalling the Thunderbolt drives etc etc until ultimately I elected to do a clean install of Windows 10 (1809) which happily installed the latest version of the Thunderbolt environment but did not allow me to see or attach any external Thunderbolt drives. I then spent most of the evening trying different BIOS releases (always with reset to default!) Out of pure desperation I performed a clean install on my development NUC which immediately discovered my Thunderbolt drives the installed. 

Is it possible that the Thunderbolt patching process has altered "something" that prevents Windows from correctly configuring the Thunderbolt controller?

I then replaced the Windows NVME drive with my Catalina NVME drive, did an NVRAM reset just in case, and started the boot process that took me straight to what I call the stop sign but apple calls the "prohibitory symbol" and then went through all the booting steps (including placing an OpenCore bootable USB drive in the mix) without any luck. Luckily I had a Time Machine backup on an external Thunderbolt drive so I created a brand new Catalina image and pointed it to the Thunderbolt Time Machine drive at the appropriate step. After 2 hours of restoring the system rebooted however it went straight to the dreaded "prohibitory symbol".

I spent another day on this problem without any luck.  I can create a clean install of Catalina without the Time Machine step that functions normally however the instant I boot something else on the NUC I am no longer able to start Catalina.

I am still unable to connect to Thunderbolt drives on this NUC when running Windows.

I would welcome any thoughts regarding my current dilemma.

**Comment by lmshsqlc** [comment]
> Thunderbolt patching process

This process is called “native thunderbolt support” in HaC-Mini project. In the document there’s a comparison shows whether Windows is supporting or not. So basically this process breaks windows from using thunderbolt function. But it’s all documented, so be cautious.

**Comment by osy86** [comment]
Yes, the installer and guide notes that patching Thunderbolt for OSX breaks windows support. You need to either go back to OSX and run the patcher again (checking uninstall). Or you have to reinstall the TB firmware from Windows (but you have to boot from OC with the custom ACPI patches to get Windows to see a patched TB controller). You may also be able to flash the stock FW in linux without any ACPI modifications, but that's untested.

**Comment by crhendo** [comment]
You are both right, I should have been more cautious. The installation went so well that I didn't read the fine print :). I guess I could dedicate this NUC to running MacOS however I am concerned that the traditional recovery using Time Machine doesn't appear to work. Any thoughts on a more stable backup solution?

**Comment by osy86** [comment]
Time Machine should work. Just follow the guide for making an installer but select restore from time machine backup instead of new install. I've done it in the past.

**Comment by crhendo** [comment]
OK, inserted the freshly prepared USB and booted OK. Formatted the NVME drive using Disk Utility. Selected Restore From Time Machine Backup, selected the NVME drive to restore to (which it initialised again) and the restore ran for two hours and completed. It then rebooted but no boot device was found (I had removed the USB) Shouldn’t the recovered drive be bootable? I reinserted the USB drive, booted, brought up the picker selected Mac, the Apple appeared for a brief second and then the “stop sign”. Should I have left the USB drive inserted during the whole process?

You must think the newbies like me are such a pain 😊

**Comment by osy86** [comment]
You do need to run the hac mini installer after booting into your restored system with your usb.

But since you’re hitting a panic, I would rerun the hac mini installer on your boot usb with verbose boot checked. Then when it panics take a picture of the panic message and file a new ticket.

Btw I’m assuming your time machine backup is clean, i.e. from a real Mac or an hac mini install.

**Comment by crhendo** [comment]
I created a new USB installer using the HaCMini pkg and the only change I made was to select verbose boot

I then used this USB to boot to the recovery screen where I used Disk utility to format the NVME drive.

I then selected the Restore from Time machine option and pointed to the latest backup folder and selected the NVME drive as the target

The restore took about two hours and then rebooted (the USB Installer was still inserted).

The only message that came up after post was :-

Error loading kernel cache (0x1)

which repeated on the screen every 10 seconds or so.

After a while I hit the power button and it rebooted, this time I hit the F10 key to go to the boot menu where only the USB drive was present.

I selected it then called up the picker where I selected Mac and it went back to displaying the same message again.

Hope this makes sense.

**Comment by osy86** [comment]
Is your time machine backup from 10.14.5 or later?

**Comment by crhendo** [comment]
It’s the Catalina backup from the stable system I had created last week using your guide.

**Comment by osy86** [comment]
I think your Time Machine backup is corrupted. Google "Error loading kernel cache (0x1)" and you'll find directions for rebuilding the kernel cache.

**Comment by crhendo** [comment]
Ok, I will try a backup from the previous day and see if that makes any difference

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by crhendo** [comment]
Over the past few days I have tried a number of alternatives for recovering a freshly created Hac Mini from either Time Machine or the latest version of Carbon Copy Pro, For Time machine I have tried using a number of external devices to store the backups (ie Thunderbolt, USB-C, USB). In each case I booted from a freshly created USB, erased the internal NVME drive and then selected the restore from Time Machine option which completes with no errors. In all cases I end up with an internal drive that is not bootable. 

For CCC I simply did a complete clone from my fully functional MacOS internal NVME drive to an identical NVME drive in the second internal slot. Once again I ended up with a drive that was not bootable.

Clearly fixing this is beyond my capability. The trouble is that if I can't recover my environment then I'm working with a level of risk that I am not willing to accept. 

You mentioned previously that you managed to use Time Machine recovery without any problems. Is there a step that I am missing or a special workflow I should adopt? If you believe that the product currently is not robust enough for an end user like me with limited technical capabilities, please say so and I will wait a few months and then revisit your site again.

Please understand that I sincerely appreciate all the effort you have put into this project AND I have learned a lot in the last few weeks!

**Comment by osy86** [comment]
> In all cases I end up with an internal drive that is not bootable.

That is expected. You won't have the EFI partition restored. You mentioned before that you had issues booting even with an OSX installer USB? Is that still true?

**Comment by crhendo** [comment]
Is there any easy way to backup and subsequently restore the EFI partition? I notice that CCC has the provision to run a script at the end of a restore. Would this be worth pursuing?

Re my previous issue, it appears that reintroducing a bootable Windows 10 NVME into the system and then trying to boot from a freshly created USB causes the Error loading kernel cache (0x1) no matter how much effort I put into resetting the BIOS or the NVRAM. I pursued many different ways of resetting the kernel cache however this did not appear to have any effect. As a result, I have decided to dedicate this NUC for MacOS only however I need to have a reliable way of recovering my system if something goes wrong.

**Comment by osy86** [comment]
Windows corrupts the EFI partition so you have to rerun the hac mini installer afterwards.

Backing up EFI is easy. Just mount the partition and copy the “EFI” directory.

**Comment by crhendo** [comment]
Sorry if this is a silly question but how can I rerun hac mini installer if I can't boot into my Mac environment?

I guess I have the same question regarding copying the EFI directory ie how can I achieve this if I can't boot into my Mac environment. Perhaps place a copy of the EFI directory on the USB and then somehow restore it using terminal?

**Comment by osy86** [comment]
USB installer with picker menu enabled.

**Comment by crhendo** [comment]
I'm getting closer.
1. Using "EFI Mountainshow" app mounted EFI directory of existing working system and copied the contents to the desktop
2, Using CCC cloned the existing drive (slot 1) to a new NVME drive (slot 2)
3. Created a new USB installer with picker enabled
4. Shutdown system
5. Removed the existing system drive from Slot 1 and moved the cloned drive from Slot 2 to Slot 1
6. Booted to the USB picker and selected the MacOS name of the new drive
7. System booted OK. Used "EFI Mountainshow" to mount the empty EFI folder
8. Copied the EFI contents from the backup on the desktop to the empty directory
9. Using "EFI Mountainshow" unmounted the EFI directory
10. Removed the USB drive and rebooted the system
11. Still no boot drive found!!
12. Reinserted the USB drive and booted to the picker where I selected the system drive
12. Booted OK

What have I missed?

**Comment by crhendo** [comment]
I needed to select the Startup Disk in Settings! All is now good.

Many thanks for your appropriate hints that pointed me in the right direction and allowed me to learn along the way.

**Comment by lmshsqlc** [comment]
I think what you did this you booted from the USB drive rather than from the internal. You should have a working bootloader in Your Internal EFI partition. If not run the HaC Mini installer in your system and install the boot loader in your internal EFI partition.

**Comment by crhendo** [comment]
The problem I had with both time Machine and CCC was that the EFI directory was left empty after the restore/copy to the target drive so I ended up with a system that was not bootable.  My research led me to the solution I used above. Are you suggesting that I didn't need to copy the EFI directory to the target drive and that all I needed to do was run the HaC Mini installer which would fix the EFI problem?

**Comment by lmshsqlc** [comment]
> The problem I had with both time Machine and CCC was that the EFI directory was left empty after the restore/copy to the target drive so I ended up with a system that was not bootable. My research led me to the solution I used above. Are you suggesting that I didn't need to copy the EFI directory to the target drive and that all I needed to do was run the HaC Mini installer which would fix the EFI problem?

I don’t know, but running the installer will ensure the problem will be fixed  You can’t compare the before and after when doing the install.
