### ISSUE TITLE
Image authorization fail

### ISSUE THREAD

**Issue by ejh4286** [osy86/HaC-Mini#141]
I’m trying to install macOS using your guide on second hades canyon.  I am using bios version 59 and have duplicated the bios settings in the guide.  However I keep getting this error even though secure boot is disabled.  Any thoughts or advice?

![3782E6CA-10BA-4F74-8D97-3B00A83D32B0](https://user-images.githubusercontent.com/58243146/70380378-92b52800-1908-11ea-83d1-07092e354332.jpeg)

**Comment by osy86** [comment]
Take a picture of your bios settings under boot -> secure boot

**Comment by ejh4286** [comment]
![D3DF62A6-DF76-4753-80EF-7143C26C1426](https://user-images.githubusercontent.com/58243146/70380605-ef661200-190b-11ea-93d7-8c485f0b8145.jpeg)

**Comment by osy86** [comment]
Can you try a BIOS reset? If it still doesn't work, use the security jumper to force a nvram clear.

**Comment by ejh4286** [comment]
Same result.

**Comment by osy86** [comment]
Try enable secure boot and check force secure boot defaults and clear secure boot data. Then disable it after restarting.

**Comment by ejh4286** [comment]
Still no luck.  I’ve tried this on four machines one worked flawlessly but the others wont

**Comment by osy86** [comment]
Do you have any issues booting into Ubuntu/Linux live usb?

**Comment by ejh4286** [comment]
I have no interest in running Linux.  However, I have noticed that on the machine that I was able to install macOS using your method.  The platform  key on the secure boot screen of the bios says “not installed”.  I have not figured out how to duplicate that.  I’ve tried clearing keys and then disabling secure boot but nothing seems to work.

**Comment by osy86** [comment]
> I have no interest in running Linux. 

The point is that this issue isn't specific to OSX. You can't run ANY unsigned bootloader.

**Comment by ejh4286** [comment]
Oh I’m using 2.4 of HVAC mini.  Should I try an earlier version?

**Comment by osy86** [comment]
No, try to get a Linux live USB booting. If that works, come back and we'll figure out the issue with OSX.

**Comment by ejh4286** [comment]
Ok.  I made a usb of Linux and it successfully booted from the usb.  Also, I made an install usb using unibeast and was able able to install macOS 10.14.6.  But, as expected, no graphics acceleration.  But hac mini keeps getting blocked regardless of secure boot being disabled.

**Comment by osy86** [comment]
That's really really weird. In your hac mini installer options, did you check "secure boot"? Also, any possibility that your system is blocking opencore?

**Comment by lmshsqlc** [comment]
Can you try this? 
https://github.com/osy86/HaC-Mini/issues/124#issuecomment-554643111
Mine got booted using secure boot somehow.

**Comment by ejh4286** [comment]
Turning on secure boot had no effect.  I created a new install usb using 2.3.3.  I can get into the boot picker.  I select “install Mac OS Catalina”.  I see the Apple logo and the progress bar gets about half way across the screen.  Then the screen flashes and then nothing.  I’m using the HDMI output.

**Comment by ejh4286** [comment]
Made a new installer using 2.4 and enabled security same result as above.

**Comment by osy86** [comment]
Please select verbose boot option in hac mini installer. Then when system panics, take a picture of the message.

**Comment by crhendo** [comment]
Is the USB boot drive you created the only bootable drive in the system? What M.2 NVME drives are in the system? Have the internal drive(s) been initialized or do they contain existing bootable partitions. I have had a similar problem when I had a VMWare ESXi system installed on one of the M.2 NVME drives.

**Comment by ejh4286** [comment]
Well I put it verbose mode.  As it boots there is all kinds of cryptic words that exceed my knowledge being written across the screen.  I’m waiting for it to stop so I can tAke a picture and flash!...blank screen again.

**Comment by ejh4286** [comment]
I am using Samsung 970 evo drive.  The usb is the only bootable drive.  The Samsung drive was connected to a windows machine and I used diskpart to “clean the drive” so it would show as uninitialzed.

**Comment by ejh4286** [comment]
I am using Samsung 970 evo drive.  The usb is the only bootable drive.  The Samsung drive was connected to a windows machine and I used diskpart to “clean the drive” so it would show as uninitialzed.

**Comment by crhendo** [comment]
I only have two more thoughts to offer:-

1. Clear the USB drive using DISKPART before rebuilding it again
2. Confirm that you don't have Samsung 970 Evo Plus as this drive [had issues](https://bartechtv.com/samsung-releases-new-firmware-for-970-evo-plus-that-resolves-macos-compatibility-issues/) with MacOS and required a firmware upgrade

**Comment by osy86** [comment]
If you have an iPhone you can try slow motion video.

**Comment by ejh4286** [comment]
Thank you all for your help, but I’ve reached the end of my patience with this.  Uncle!

**Comment by ejh4286** [comment]
Omg, I tried a brand new Samsung 970 EVO and Catalina 15.1 installed flawlessly.  Oh well at least I got to practice all my cuss words, repeatedly.
