### ISSUE TITLE
Update Catalina from 15.1 to 15.2.

### ISSUE THREAD

**Issue by ejh4286** [osy86/HaC-Mini#146]
Can I update my 15.1 installation to 15.2 just like a real Mac through system preferences, or it it more involved?

**Comment by osy86** [comment]
You should be able to but someone reported issues with it yesterday. I haven’t ran into the issue myself though.

**Comment by ejh4286** [comment]
I saw that and I believe they were upgrading from Mojave to Catalina.

**Comment by crhendo** [comment]
I just upgraded to 15.2 without any problems. Lots of restarts but a satisfactory conclusion.
