### ISSUE TITLE
Thunderbolt XDomain (two PCs) not working

### ISSUE THREAD

**Issue by Deftaudio** [osy86/HaC-Mini#147]
Seems I confused myself with TB options and the way they evolved in newer releases. I can't get to work Network stack on top of TB3.0 if two Macs are connected together. Can you please, let me know if it's supported and should I go with Native or Legacy mode for that? 

Running with the latest 3.4 also tested 3.3.x
External TB3.0 enclosures work fine. so TB is operational. 
I also see remote Mac listed in the TB devices on both ends. But Ethernet link is down between them.  

<img width="462" alt="Screen Shot 2019-12-10 at 4 55 21 PM" src="https://user-images.githubusercontent.com/3469541/70582044-0310b300-1b6e-11ea-8dff-a238714f6165.png">

**Comment by osy86** [comment]
I’ve never tested this before. So you take a TB3 cable and connect two macs and they show up as a network adapter on each Mac?

**Comment by Deftaudio** [comment]
Exactly, that's very basic and standard feature of TB. You can also do that trick with Win10 and Win10-OSX. super useful.  https://www.instagram.com/p/B2dlZ_sglnL/

**Comment by osy86** [comment]
I’ll have to get a TB3 cable to check. Did you choose a self assigned ip? https://9to5mac.com/2016/11/22/macbook-pro-thunderbolt-3-bridge-network-video/

**Comment by Deftaudio** [comment]
Both, self and manual.

**Comment by osy86** [comment]
I was able to reproduce this issue with two TB2-to-TB3 adapters and a TB2 cable.

**Comment by lmshsqlc** [comment]
When I connected using a MacBook Air and a Thunderbolt 3 to thunderbolt 2 adapter with a thunderbolt 2 cable, it wasn’t connecting. 
It shows inactive in thunderbolt bridge detail. 
Now I don’t have a chance to get in touch with a MacBook Air anymore but I’m looking forward to solve this.

**Comment by osy86** [comment]
Linux XDomain patches for reference: http://lkml.iu.edu/hypermail/linux/kernel/1710.0/00406.html

**Comment by Deftaudio** [comment]
> Linux XDomain patches for reference: http://lkml.iu.edu/hypermail/linux/kernel/1710.0/00406.html

Did you have a chance to figure out if any kext missing which is responsible for network strack over Thunderbolt? 
Thanks!

**Comment by osy86** [comment]
It’s not a kext issue but I’m still not sure what the problem is. Would require a lot more debugging.

**Comment by lmshsqlc** [comment]
This hackintosh project has gone way too far than I have expected. I truly hope the Thunderbolt patcher will be utilized by more and more people.
