### ISSUE TITLE
USB drive recognized as internal.

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#148]
**Describe the bug**
external hard drive is recognized as an internal one and cannot be ejected, except when using the left blue one in front.

**Expected behavior**
The external hard drive should be recognized as a usb external drive and ejectable.

**Configuration**
- HaC Mini version : 2.4 (disable-sip build)
- OSX version : 10.15.1
- NUC model : NUC8i7HVK
- Any TB3 devices: HP TB3 Dock
- Any USB devices: keyboard, WD external hard drive.

**Modifications**
None

<img width="926" alt="Screen Shot 2019-12-13 at 1 09 34 AM" src="https://user-images.githubusercontent.com/38860226/70734034-6e14e200-1d46-11ea-92fa-71f13ad1afb2.png">

**Comment by osy86** [comment]
Can you test it on a real mac? It says "USB Internal Physical Disk" which might just be what OSX does to this drive.

**Comment by osy86** [comment]
Is the drive connected via the TB3 dock?

**Comment by KrisCris** [comment]
> Is the drive connected via the TB3 dock?

No, it is connected to the NUC USB ports.

**Comment by KrisCris** [comment]
> Can you test it on a real mac? It says "USB Internal Physical Disk" which might just be what OSX does to this drive.

I will try, but the left usb port in the front of NUC can recognize it as a external one...

**Comment by osy86** [comment]
I see, it’s probably a port config issue.

**Comment by KrisCris** [comment]
> I see, it’s probably a port config issue.

I think so, all the USB-A ports show in the Hackintool are internal, except the one which recognized my WD hard drive as external. But that port won't show on Hackintool...

**Comment by goodbest** [comment]
@osy86 I have the similar confusion with @KrisCris for the `Internal` USB  shown in Hackintool.

In my experiments, I found:
Rear USB3: SS02 03 04 07 
Rear USB2: HS03 04 10 11
Front yellow USB3: SS01
Front yellow USB2: HS01
Bluetooth: HS09
Rear TB3: SSP1 SSP2

But I can't figure out the following relations between SSxx/HSxx and physical ports:
Can you please give us more info about that? (Besides the `SSDT-Xhci.dsl`)

Front Blue USB2: ???
Front Blue USB3: ???
Front Type-C: ???
???: HS01
???: HS12
???: HS13
Inner usb port on board(no physical ports on the box) : ???

**Comment by osy86** [comment]
I remember now. I used to replace the SSDT entries with my own definition which was internal. But it got messy having to add a OC patch for every port so I removed it. I guess I’ll try to find another way to do the replacement where it’s not so messy.
