### ISSUE TITLE
Thunderbolt devices limited at 20Gbps (x1)

### ISSUE THREAD

**Issue by osy86** [osy86/HaC-Mini#149]
Dual bonded lanes does not seem to work. Seems to be an EFI config issue.

*Potential solution 1*
Extract `ThunderboltNhi.efi` from Mac ROM. It adds various properties including lane bonding information. Could solve other potential issues as well. But may not work OOB.

*Potential solution 2*
Manually inject the `linkDetails` property
```
            <key>PciRoot(0x0)/Pci(0x1c,0x4)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)</key>
            <dict>
                <key>linkDetails</key>
                <data>
                CAAAAAMAAAA=
                </data>
            </dict>
```

**Comment by lmshsqlc** [comment]
Does only one link available? I’ve test test with an older MacBook Air using thunderbolt 3 to thunderbolt 2 adapter but the connection shows inactive.

**Comment by osy86** [comment]
You need an external NVMe to test. It seems like you can spoof `linkDetails` and it will show "40Gbps x1" in system profiler but the speed will still be 20Gbps. Without `linkDetails` it will show "20Gbps x2" in system profiler and the speed is 20Gbps.

**Comment by lmshsqlc** [comment]
Thank you but I replied in the wrong thread sorry.

**Comment by KrisCris** [comment]
So after latest fix, can TB running at 40Gbps?

**Comment by osy86** [comment]
So I’m actually not sure since I don’t have a fast enough device to check. But it should at least fix the bonding issue which is a prerequisite.

**Comment by KrisCris** [comment]
> So I’m actually not sure since I don’t have a fast enough device to check. But it should at least fix the bonding issue which is a prerequisite.

I just connected my PC to hacmini using TB3 cable, the network panel shows the speed is 20Gbps - So perhaps hacmini's TB3 still cannot running at 40Gbps?
