### ISSUE TITLE
Time Machine cause black screen

### ISSUE THREAD

**Issue by 22dm** [osy86/HaC-Mini#150]
**Describe the bug**
I have two displays, the "big" one has 3K resolution via TB3, the "small" one has 2K resolution via HDMI. When I open Time Machine in Launchpad, the "big" display shows like:

![IMG_0031](https://user-images.githubusercontent.com/7871070/70772166-a6e8a180-1dae-11ea-8ffd-bca6f929aacd.jpeg)

A black square is on the top left corner. I tried many different resolutions and found that the black square always has same size as the resolution of "small" display.

**Configuration**
- HaC Mini version: 2.4
- OSX version: 10.15.1
- NUC model: NUC8i7HNK
- Boot SSD model and protocol: Samsung 970 Pro 512GB NVME
- Second SSD model and protocol: Samsung 970 Pro 512GB NVME
- First DIMM model: Samsung DDR4-2666 16GB
- Second DIMM model: Samsung DDR4-2666 16GB
- Display port(s) used: TB3 / HDMI
- Display resolution(s) [e.g: 4K, 5K]: 3K(via TB3) / 2K 120Hz(via HDMI)

**Modifications**
none

**Panic log**
none

**Comment by osy86** [comment]
Does this happen with a real mac?

**Comment by 22dm** [comment]
> Does this happen with a real mac?

Well, actually I don't have a real mac with TB3 for testing, maybe it's the problem of my display itself?

**Comment by osy86** [comment]
I can’t think of anything NUC specific that may be causing this. Could be an AMD driver issue but if that’s the case it’ll be hard to fix since I can’t reproduce your setup/issue.

**Comment by 22dm** [comment]
> I can’t think of anything NUC specific that may be causing this. Could be an AMD driver issue but if that’s the case it’ll be hard to fix since I can’t reproduce your setup/issue.

May be I can close this issue and to find a real mac to test?
