### ISSUE TITLE
RAM configuration > 32GB not supported

### ISSUE THREAD

**Issue by deftdawg** [osy86/HaC-Mini#151]
With Mojave 10.14.3, I could not boot NUC8i7HVK with more than 32GB of RAM in slot 1 (top slot)...

| Slot 1 | Slot 2 | Result         |
|---------|---------|----------------|
| 32GB    | -       | Boots w/ 32GB       |
| 32GB    | 32GB    | Fails: "End randomseed" * |
| 32GB    | 8GB     | Boots w/ 8GB            |
    * in Linux boots w/ 64 GB (so RAM is okay)

I'm curious if is still an issue with newer installs of 10.14.5 and higher.

**Comment by BenjaminX** [comment]
NUC8i7HNK/NUC8i7HVK 

support 2 * 32GB in slot1&2

**Comment by osy86** [comment]
Maybe both of you should post your ram model to compare?

**Comment by BenjaminX** [comment]
FYI

https://www.virtuallyghetto.com/2019/03/64gb-memory-on-the-intel-nucs.html
https://davidhamann.de/2019/08/06/esxi-on-intel-nuc8i7hvk-64gb-ram/

**Comment by deftdawg** [comment]
@BenjaminX there is no question about that the hardware can do it; as I stated my NUC runs Linux w/64GB with no problem.  The question is whether anyone has successfully booted the OSX kernel directly off the bare metal (not through ESXi or any other virtualization) with more than 32GB.

**Comment by BenjaminX** [comment]
I think 2x32GB directly run bare metal is ok, maybe you can try testing it.

**Comment by deftdawg** [comment]
@BenjaminX I did, refer to the top of the issue.

**Comment by BenjaminX** [comment]
@deftdawg  Unfortunately the same issue for me, Slot 1&2 32GB x2

USCORSAIR DDR4 2666 32GB CMSX32GX4M1A2666C18

**Comment by BenjaminX** [comment]
@deftdawg do you try to install ‘AptioMemoryFix.kext’ ?

**Comment by deftdawg** [comment]
@BenjaminX I can't try anything with my system until my GF goes away on vacation in late January. :\

**Comment by osy86** [comment]
https://github.com/osy86/HaC-Mini/commit/93557238aa7bb93c5e5bbe80438b2ebcfe729073 might address it. Please test https://github.com/osy86/HaC-Mini/suites/407662409/artifacts/1198096 which has the fix.

**Comment by diskdude** [comment]
64GB works well for me using the following Samsung SO-DIMMs.  OpenCore on my system is configured with the changes in 9355723 that osy86 has referenced.

```
Memory Slots:

  ECC:	Disabled
  Upgradeable Memory:	Yes

BANK 0/ChannelA-DIMM0:

  Size:	32 GB
  Type:	DDR4
  Speed:	2667 MHz
  Status:	OK
  Manufacturer:	Samsung
  Part Number:	M471A4G43MB1-CTD
  Serial Number:	XXXXXXXX

BANK 2/ChannelB-DIMM0:

  Size:	32 GB
  Type:	DDR4
  Speed:	2667 MHz
  Status:	OK
  Manufacturer:	Samsung
  Part Number:	M471A4G43MB1-CTD
  Serial Number:	XXXXXXXX
```

**Comment by osy86** [comment]
Thats good to hear, I’m closing this issue.
