### ISSUE TITLE
I can't  disable SIP in 10.15.2

### ISSUE THREAD

**Issue by VAgerJnor** [osy86/HaC-Mini#152]
I can't use "csrutil disable" in Terminal.app.（I've already get into recovery mode.）
When I input  "csrutil disable" in Terminal.app，It display that I have already success and suggest me restart the machine，but it  without any effect.When I restart the machine and get into mac os,it display ：System Integrity Protection status: enabled.

**Comment by osy86** [comment]
Dup of #78 fixed in https://github.com/osy86/HaC-Mini/pull/123 but not released yet. You can download the artifact for that pull request if you wish to use the prerelease build.
