### ISSUE TITLE
Trojan:MacOS/ScarletFlash.A

### ISSUE THREAD

**Issue by Uzzus** [osy86/HaC-Mini#153]
HaCMini.pkg V2.4 seems to be infected by Trojan:MacOS/ScarletFlash.A

**Comment by osy86** [comment]
What

**Comment by Uzzus** [comment]
https://www.virustotal.com/gui/file/eea2bc166bffe7be3f45678336a326af796213d9c15339903c94a2c5f95f852f/detection

I was using windows to download the files needed to then transfer them home to mac and the microsoft antivirus gave me an alarm message, now I checked with virustotal and it seems to be only microsoft to detect trojan.

**Comment by henglinli** [comment]
https://www.virustotal.com/gui/url/e71a72db6874ac364b1db1ff5ffc08f4d4fa147f2285eace7024ed2628581207/details

https://github.com/osy86/HaC-Mini/releases/download/v2.4/HaCMini.pkg have the same sha256 eea2bc166bffe7be3f45678336a326af796213d9c15339903c94a2c5f95f852f

**Comment by osy86** [comment]
Yeah microsoft is garbage.
