### ISSUE TITLE
Installer fail on booting to the installation UI

### ISSUE THREAD

**Issue by zhxiyao** [osy86/HaC-Mini#154]
Describe the bug
I tried to install Catalina 10.5.2 directly but it failed to boot to the installation UI, and I also try to boot from installer USB with 10.4 and v2.4 but it all failed during booting without Apple logo shown up.

Expected behavior
It should success the installation UI

Environment:
Target drive OSX version: macOS Catalina/Mojave
Running OSX version: macOS Catalina(10.15.3) on MBP 13 2015
HaC Mini installer version: 2.4
Target NUC model: NUC8i7HVK
Target SSD: WD Black SN750 512g with win10 installed
Second: Intel 660p 1T
Wifi: Dell 1820A

![20191219002800](https://user-images.githubusercontent.com/15827259/71104268-82e5ef80-21f6-11ea-971e-78b56d5ed750.jpg)
![20191219002740](https://user-images.githubusercontent.com/15827259/71104316-93966580-21f6-11ea-8817-4a772106f33f.jpg)

**Comment by osy86** [comment]
Can you try without the Dell WiFi Card installed and without the WiFi kext just to see if that’s the issue?

**Comment by goodbest** [comment]
Have you disabled the PCI aspm in BIOS first?

**Comment by zhxiyao** [comment]
Update: After disabled PCI aspm and BT/wifi in BIOS, the install was done.

Remaining issues:
1 BT on Dell 1820A does not work in most cases (it worked several times.) Even the BT stoped working after switching to bootcamp windows. Reinstalling driver in windwos sometimes could soloved but sometimes not with a exclamation mark (!) in the hardware list.
 Temp solltion: a USB bt adapter is used with CSR chips and disable BT on board in BIOS.
2 the sidecar is black in Ipad pro via both usb and wireness, when BT working or no-working;
3 Thunderbolt item in the system info shows "no driver". I dont know if it is a issue coz I dont hv a TB3 device yet. I hv USB-C portable disk which can work on the ports.
