### ISSUE TITLE
Need stock ThunderBolt firmware dump

### ISSUE THREAD

**Issue by hfharry** [osy86/HaC-Mini#157]
I accidentally bricked my Thunderbolt function during flashing modified firmware file with a SPI flash clip. Sadly, I noticed that I don't have a backup dump file only after bricking it. Currently, my TB ports are not working. While USB-C functions seems fine. 

Could anyone kindly upload an stock ThunderBolt firmware dump file? So I can flash it back with the SPI flash clip. @osy86 

I wonder whether the firmware file downloaded from Intel Official Support Page (Intel_Hades_AR_HR_4C_C0_rev33_W_TI_20180109_SEC1_sign.bin) could be flashed and unbrick the ThunderBolt port. I didn't give it a try. If there is anyone with experience, please do advise. Thanks.

**Comment by lmshsqlc** [comment]
https://github.com/osy86/ThunderboltPatcher/issues/2#issuecomment-550122472

**Comment by hfharry** [comment]
> [osy86/ThunderboltPatcher#2 (comment)](https://github.com/osy86/ThunderboltPatcher/issues/2#issuecomment-550122472)

Thanks!

**Comment by osy86** [comment]
For the record you can take your OEM’s Tb update bin and flash it directly to offset 0 of the SPI NAND and it should work.

**Comment by hfharry** [comment]
> For the record you can take your OEM’s Tb update bin and flash it directly to offset 0 of the SPI NAND and it should work.

Problem solved. Thanks.
