### ISSUE TITLE
Cannot install HacMini.pkg

### ISSUE THREAD

**Issue by markwin1** [osy86/HaC-Mini#160]
I have loaded macOS Catalina installer on a 16gb USB drive. Have tried a number of times installing the 2.5 HaCmini.pkg. I am changing the destination and checking the modify box. Each time the installer starts, appears to do a couple of things and then says: The Installation Failed. The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

**Comment by Bill-lulu** [comment]
what`s the NO. of your biso ?0059?Mine is 0059.and it had me waiting so longtime on installtion window,finally l find the problem is on usb device!And l make a new usb and it works very well,but by clover!

**Comment by Bill-lulu** [comment]
you  first installing better on clover

**Comment by osy86** [comment]
Please post /var/log/install.log

**Comment by markwin1** [comment]
Thank you for the quick replies here is the install.log
[install.log](https://github.com/osy86/HaC-Mini/files/4012480/install.log)

**Comment by markwin1** [comment]
This one is solved. When erasing the USB Drive I neglected to set scheme to GUID partition. I have now done it correctly and the HaCmini.pkg worked as it is supposed to.
