### ISSUE TITLE
Some problem on bios H0059and 15.2

### ISSUE THREAD

**Issue by Bill-lulu** [osy86/HaC-Mini#161]
Hi bro !
 Thank you for your contribution for HAC-mini.Rescently l use your method(the third one,update from clover,l installing 15.2 by clover).by the way,l`m the new one on hack mac,know very few about the macOs,and Clover .but know well about XML(l`m a developer of JAVA in China)
First,the BooterMenu,Showing as you say,if l didnt choose that selection,My HVK window
is directly black.But l chosse that ,it we display a menu for me to chose which boot you wanna?(1.efi,2lulu(MACOD),3.recovery partition and so on). l dont know it just my problem or not?
Second.the safari `s TAG have version peoblem,Truddy;
Third,the hac every call me regist my icloud count everyDay,and after ever registion l will find a new mac in my icloud.l know the problem is my hac`s device uuid.just copy the OC`s fullsimple.plist can correct this problem?

**Comment by osy86** [comment]
Clover is no longer supported and the config.plist is outdated and not expected to work.

**Comment by Bill-lulu** [comment]
sir you means that?l need modify my .plist by my self?Almost all the parameters?

**Comment by lmshsqlc** [comment]
> sir you means that?l need modify my .plist by my self?Almost all the parameters?

There’re documents about how to use opencore. If you use hades canyon, you can simply use releases of HaC Mini.

**Comment by Bill-lulu** [comment]
3Q verymuch
