### ISSUE TITLE
Boot Camp Assistant - An internal error has occured - Fresh Install

### ISSUE THREAD

**Issue by MartLevi** [osy86/HaC-Mini#162]
**Describe the bug**
With a completely fresh install of macOS Catalina 10.15 (I've tried 10.15.1 and 10.15.2), Boot Camp Assistant cannot proceed to start a Windows Installation. I've just done a completely clean install following the instructions to a T (BIOS reset and copied the settings from the instructions, latest 2.5 version of the installer) and after the setup page, immediately going for Boot Camp Assistant, opening it, clicking Continue and a window at the top of it pops up saying:

Boot Camp Assistant has encountered a problem
An internal error has occured.

At which point you can only click OK and that's it. This is not a major issue for me personally, but I just wanted to mention it :)

**Expected behavior**
You should be able to open Boot Camp Assistant, go through the process and successfully install Windows, to which I think follow the instructions for drivers after the fact. Problem is I can't.

**Configuration**
- HaC Mini version: v2.5
- OSX version: 10.15.1 and 10.15.2
- NUC model: NUC8I7HVK
- Boot SSD model and protocol: Samsung SSD 970 EVO 250GB NVME
- Second SSD model and protocol: Samsung SSD 960 EVO 250GB NVME (which I want to use for Windows if its even possible)
- First DIMM model: HyperX Impact DDR4 16GB 2400 MHz CL14
- Second DIMM model: HyperX Impact DDR4 16GB 2400 MHz CL14
- Display port(s) used [e.g: USB-C, mini DP]: HDMI at the back
- Display resolution(s) [e.g: 4K, 5K]: 2560 x 1440
- Any TB3 devices: None
- Any USB devices: Just a keyboard and mouse dongle from HP

**Modifications**
No modifications, as vanilla as you can get with the setup. I do use the correct DW1820A WiFi with the kext, but I don't know if its related.

**Panic log**
No panic log, or logs of any sort, but here's a picture of the very non descriptive error macOS gives: [https://imgur.com/j6hszrs](https://imgur.com/j6hszrs)

**Comment by lmshsqlc** [comment]
Install windows like a PC. But use Opencore to boot windows installer to preserve opencore bootloader or windows installer will disable it.

**Comment by goodbest** [comment]
I have the same issue.
As far as I known, Bootcamp won't work on Macs with multiple hard drives (you have two nvme ssd).

So you have two options:
- First choice: I just want to feel the bootcamp experience.
   -  in the bios, raid your two ssd into one drive (raid 0 or 1, it's up to you). 
   - Of course then your system and data are gone, you have to reinstall your MacOS, and then you can use bootcamp.

- Second choice: One drive for mac, and the other one for windows. You don't have to use bootcamp for this purpose.
  - in bios, disable the ssd that installs your mac. (like that ssd never existed)
  - Install windows to the second ssd, set up everything right.
  - in bios, re-enable the ssd with your mac.
  - After that, you can either choose the ssd to boot via F10 boot menu, or via the Opencore boot menu(if you enable the boot menu when you install Hac-mini installer options, or if you press Option key in your keyboard)

I use the second one, of course.

**Comment by lmshsqlc** [comment]
> I have the same issue.
> As far as I known, Bootcamp won't work on Macs with multiple hard drives (you have two nvme ssd).
> 
> So you have two options:
> 
> * First choice: I just want to feel the bootcamp experience.
>   
>   * in the bios, raid your two ssd into one drive (raid 0 or 1, it's up to you).
>   * Of course then your system and data are gone, you have to reinstall your MacOS, and then you can use bootcamp.
> * Second choice: One drive for mac, and the other one for windows. You don't have to use bootcamp for this purpose.
>   
>   * in bios, disable the ssd that installs your mac. (like that ssd never existed)
>   * Install windows to the second ssd, set up everything right.
>   * in bios, re-enable the ssd with your mac.
>   * After that, you can either choose the ssd to boot via F10 boot menu, or via the Opencore boot menu(if you enable the boot menu when you install Hac-mini installer options, or if you press Option key in your keyboard)
> 
> I use the second one, of course.

Boot camp does not support Apple Raid drive

**Comment by goodbest** [comment]
> > I have the same issue.
> > As far as I known, Bootcamp won't work on Macs with multiple hard drives (you have two nvme ssd).
> > So you have two options:
> > 
> > * First choice: I just want to feel the bootcamp experience.
> >   
> >   * in the bios, raid your two ssd into one drive (raid 0 or 1, it's up to you).
> >   * Of course then your system and data are gone, you have to reinstall your MacOS, and then you can use bootcamp.
> > * Second choice: One drive for mac, and the other one for windows. You don't have to use bootcamp for this purpose.
> >   
> >   * in bios, disable the ssd that installs your mac. (like that ssd never existed)
> >   * Install windows to the second ssd, set up everything right.
> >   * in bios, re-enable the ssd with your mac.
> >   * After that, you can either choose the ssd to boot via F10 boot menu, or via the Opencore boot menu(if you enable the boot menu when you install Hac-mini installer options, or if you press Option key in your keyboard)
> > 
> > I use the second one, of course.
> 
> Boot camp does not support Apple Raid drive

Should bootcamp work on raid drives that is set up in BIOS? (not apple raid)

**Comment by lmshsqlc** [comment]
> > > I have the same issue.
> > > As far as I known, Bootcamp won't work on Macs with multiple hard drives (you have two nvme ssd).
> > > So you have two options:
> > > 
> > > * First choice: I just want to feel the bootcamp experience.
> > >   
> > >   * in the bios, raid your two ssd into one drive (raid 0 or 1, it's up to you).
> > >   * Of course then your system and data are gone, you have to reinstall your MacOS, and then you can use bootcamp.
> > > * Second choice: One drive for mac, and the other one for windows. You don't have to use bootcamp for this purpose.
> > >   
> > >   * in bios, disable the ssd that installs your mac. (like that ssd never existed)
> > >   * Install windows to the second ssd, set up everything right.
> > >   * in bios, re-enable the ssd with your mac.
> > >   * After that, you can either choose the ssd to boot via F10 boot menu, or via the Opencore boot menu(if you enable the boot menu when you install Hac-mini installer options, or if you press Option key in your keyboard)
> > > 
> > > I use the second one, of course.
> > 
> > 
> > Boot camp does not support Apple Raid drive
> 
> Should bootcamp work on raid drives that is set up in BIOS? (not apple raid)
> I haven't tried option 1 yet, it's just an solution in imagination

You can try.

**Comment by MartLevi** [comment]
> > > > I have the same issue.
> > > > As far as I known, Bootcamp won't work on Macs with multiple hard drives (you have two nvme ssd).
> > > > So you have two options:
> > > > 
> > > > * First choice: I just want to feel the bootcamp experience.
> > > >   
> > > >   * in the bios, raid your two ssd into one drive (raid 0 or 1, it's up to you).
> > > >   * Of course then your system and data are gone, you have to reinstall your MacOS, and then you can use bootcamp.
> > > > * Second choice: One drive for mac, and the other one for windows. You don't have to use bootcamp for this purpose.
> > > >   
> > > >   * in bios, disable the ssd that installs your mac. (like that ssd never existed)
> > > >   * Install windows to the second ssd, set up everything right.
> > > >   * in bios, re-enable the ssd with your mac.
> > > >   * After that, you can either choose the ssd to boot via F10 boot menu, or via the Opencore boot menu(if you enable the boot menu when you install Hac-mini installer options, or if you press Option key in your keyboard)
> > > > 
> > > > I use the second one, of course.
> > > 
> > > 
> > > Boot camp does not support Apple Raid drive
> > 
> > 
> > Should bootcamp work on raid drives that is set up in BIOS? (not apple raid)
> > I haven't tried option 1 yet, it's just an solution in imagination
> 
> You can try.

I've just tried the Intel Raid 0 config made in the BIOS and unfortunately the macOS Catalina installer does not detect it. I'll try point 2 and see how it goes, but as I said this isn't a catastrophic problem. Might as well get a single 1TB NVME and call it a day, looks like its just Apple that's doesn't support this :)

**Comment by osy86** [comment]
I don't think Boot Camp Assistant supports multiple internal drives.

**Comment by DanielMaeda** [comment]
I have the same problem. I replaced my old HDD for and Sata SSD SanDisk. I installed OSX and tried to bootcamp, got the same message...

Any Solutions?

**Comment by osy86** [comment]
Do you have multiple ssd installed?

**Comment by DanielMaeda** [comment]
Yes. I have the default SSD m2 that comes with OS, and i changed the HDD for and Sata SSD
Now when i open bootcamp assistant got this message. I think it is something with the partition. 

I was wondering to make a clean install of windows in the SSD, saw some articles about it.

Thanks in advance.

**Comment by osy86** [comment]
Is this a NUC8I7HVK?

**Comment by DanielMaeda** [comment]
Nope, it is an Imac

**Comment by osy86** [comment]
This is a support site for NUC8I7HVK hackintosh. Please post your issues to Apple discussion forums.
