### ISSUE TITLE
Razer Chroma + 5700 XT -- eGPU Support with HaC-Mini

### ISSUE THREAD

**Issue by chirimar** [osy86/HaC-Mini#163]
Hello folks
I got Hac-Mini 2.5 up and running within an hour on my new nuc8i7hvk with
- 32gb ram
- 1tb m.2 ssd

Everything works great, thank you @osy86 & this group!

I am looking to get a 5700 XT + Razer Core X Chroma eGPU enclosure for some work/gaming I do. 

Has anybody in this group had success with this setup out of the box? Or should I get some other card/enclosure?

Thanks.

**Comment by osy86** [comment]
I think any enclosure that works with Macs should work. However please report back your results here.

**Comment by chirimar** [comment]
Ok sure, will do. 

Silly question - How do I add a boot argument 'agdpmod=pikera' in my HaC-mini?

**Comment by osy86** [comment]
Modify config.plist in the EFI partition. In the next release you can use nvram command.

**Comment by chirimar** [comment]
Sorry this is really newbie of me but how do I get to the EFI partition? 

I can't seem to see it in Finder or Disk Utility.

**Comment by osy86** [comment]
You can use clover configurator tool to mount it.

**Comment by chirimar** [comment]
Great, got it. Thank you.

Would be great to add this to the guide as well.

**Comment by osy86** [comment]
If there is something that requires config.plist editing then I would rather make it as part of the installer. The goal of this project is to provide the Mac experience to non-Mac users and telling people to edit this obscure file is not mac-like.

**Comment by osy86** [comment]
Okay I guess I should also ask why you want to add a boot-arg because there’s a high probability that you think you do when you really don’t.

**Comment by chirimar** [comment]
Great point.

I was just going off this guide - https://khronokernel-3.gitbook.io/catalina-gpu-buyers-guide/modern-gpus/amd-gpu

**Comment by osy86** [comment]
Pretty sure that’s not relevant for egpus but again I don’t have experience there so please report back.

**Comment by chirimar** [comment]
Ordered. Will report after receiving/testing.

**Comment by chirimar** [comment]
Received the Razer Core X Chroma -
- plugged it in to the wall socket
- plugged TB3 cable into the Hac-Mini
- switched on Razer Core

Fail - None of the USB/Ethernet ports on the Chroma work
Expected - Ports behind the Chroma are supposed to work (https://support.razer.com/gaming-laptops/razer-core-x-chroma/)

Graphics Card - Still waiting to receive.

**Comment by chirimar** [comment]
Issue - 
1. Hotplugging the Razer Core X Chroma in the thunderbolt 3 (port next to the power one) reboots the Mac 2 of 3 times.

2. Nothing is appearing in the USB Bus list with any combination of attaching the Razer enclosure (hotplugging, plug in before switching on Mac etc).

![Mac mini 2020-01-14 23-58-25](https://user-images.githubusercontent.com/55009842/72359728-c2d2c080-3729-11ea-9012-7caa267a86d5.png)

![Mac mini 2020-01-14 23-58-45](https://user-images.githubusercontent.com/55009842/72359755-cd8d5580-3729-11ea-9bcc-8b8f9fc2d40b.png)

**Comment by osy86** [comment]
You’ve installed the native thunderbolt option and ran the patcher?

**Comment by chirimar** [comment]
I didn't do that. I was hoping for the 'Hybrid' approach, so that I could use TB in both Windows & Mac, if I understood this page (https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-3) properly. 

When I ran the Hac-Mini installer, I didn't check anything specifically for 'Hybrid' if I remember correcly.

What can I do now to enable this? 

Thanks

**Comment by osy86** [comment]
Hybrid is no longer supported because it’s super buggy (random panics on resume).

**Comment by chirimar** [comment]
Ok noted.

So I definitely prefer to be able to use the Razer Core with a windows installation. 

I am waiting for my 42mm M2 card to install Windows and for my graphics card as well. I should not patch the thunderbolt driver then right?

**Comment by chirimar** [comment]
Mac - Can't get the egpu to work without patching.

Windows 10 (running on 2nd nvme) - Works great!

Can close ticket.

**Comment by osy86** [comment]
Did it work with patching? Just cutious

**Comment by chirimar** [comment]
I didn’t patch.  

Maybe I misunderstood it - 

. 2 nvmes
. Windows 10 installed without boot camp (just disabled 1 SSD, set up and installed the other) 
. If I patched the thunderbolt Drivers, would it stop working in the windows installation too?

**Comment by osy86** [comment]
Yes but you can always uninstall the patch. Anyways I was just curious since I don’t know anyone who tried egpu with hotplug and eject.

**Comment by chirimar** [comment]
Ah ok. So I tried to setup a couple of applications and games that I would use with the egpu on Mac. But they kept crashing. So I just didnt go through with it.

**Comment by chirimar** [comment]
ps - I wrote about your amazing project here - https://vritti.net/2020/01/16/hackintosh-2020-intel-nuc8i7hvk/

Also, is there a way to send you a small gift? I couldn't find a way to even tip the project etc.

**Comment by goodbest** [comment]
Hi @chirimar , 
Can you share your benchmarks with your egpu+5700xt+nuc8i7hvk? Because you are the first person I know to have these card.
It's all OK Either in Windows or OSX. 3Dmarks, GeekBenchsk, luxmark, or whatever you like are fine.

Due to the TB3 bandwidth limits compared with PCIE,  egpu would have some performance drop.
So I want to know the *real performance gains using 5700xt +egpu*, compared with using Nuc's discrete Vega M GH.

The egpu enclosure+5700xt + TB3 cable means a lot of money. I want to know if it's worth.

**Comment by chirimar** [comment]
Hey @goodbest - Sure, will do some of that over the weekend.
