### ISSUE TITLE
Can USB-C output video signals to external displays using the Legacy TB Patch?

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#164]
Hi community, 

Currently my NUCi8HVK is running the MacOS 10.15.2 with the Native TB patch, and I am planing to install a Windows on another SSD. 

I have a portable display utilizing the usb-c to c cable which works fine under the Native TB patch. However, in consideration of the incompatibility of the Native TB Patch with Windows, the Legacy patch may be a better choice for me. So can these thunderbolt ports output videos under Legacy patch in MacOS?

**Comment by Anjiro81** [comment]
Yes, I can confirm USB-C video output is working with a NUCi8HVK running MacOS 10.15.2 with Legacy patch configuration. The monitor is a "LG 27UD88-W" with several USB devices attached to it.
