### ISSUE TITLE
failed to install the hacmini.pkg

### ISSUE THREAD

**Issue by sunisdown** [osy86/HaC-Mini#165]
**Describe the bug**
I followed the steps in the document several times, and each time it failed. The disk partition is in `GUID Partition Map` format. I can see from the `diskutil list` that the USB format has EFI partitions and normal partitions.

**Environment:**
 - Mac os 10.12(macOS Sierra)
 - Target drive OSX version: (macos 10.14)
 - HaC Mini installer version: (2.5)

**Logs**
Please attach `/var/log/install.log`
[aaa.txt](https://github.com/osy86/HaC-Mini/files/4057046/aaa.txt)

**Comment by osy86** [comment]
The problem is the files aren't actually getting installed.

```
Jan 14 00:12:48 xxxxxxxxdeMacBook-Pro installd[367]: PackageKit: Executing script "./preinstall" in /private/tmp/PKInstallSandbox.2fWBdJ/Scripts/com.osy86.hacmini.setbackup.Yq6VM7
...
Jan 14 00:12:49 xxxxxxxxdeMacBook-Pro installd[367]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.2fWBdJ/Scripts/com.osy86.hacmini.core.BQ37pu
```

As you can see, only 1 second passed before preinstall and postinstall. Maybe your download was corrupted? Check the SHA256 hash it should be `e7ff7cf63f26665b73ad08cab66b5286fd5f5c551b7028d3418898ebe69af9c2`

**Comment by sunisdown** [comment]
the SHA256 is `e7ff7cf63f26665b73ad08cab66b5286fd5f5c551b7028d3418898ebe69af9c2`.

I tried it with versions 2.3, 2.4, and 2.5, and all failed. I wonder if I need to upgrade the macOS to a higher version.  I am running under Mac os 10.12 for now.

**Comment by osy86** [comment]
Probably I’ve never tested it below 10.14

**Comment by sunisdown** [comment]
I tried again under macos 10.14 and everything was fine. thank you.
