### ISSUE TITLE
Thunderbolt 3 output Display not working

### ISSUE THREAD

**Issue by nobita0464** [osy86/HaC-Mini#166]
Monitor ASUS PA32UC-K
in system report it can be detect as normal, but no output

**Comment by osy86** [comment]
Did you install native thunderbolt option and run the firmware patcher?

**Comment by TayshunAlly** [comment]
I had an issue with my LG 4k monitor where I had to turn off freesync in the monitor's menu

**Comment by nobita0464** [comment]
> Did you install native thunderbolt option and run the firmware patcher?

i had already install native thunderbolt option and run the firmware patcher

**Comment by osy86** [comment]
Can you post a ioregistryviewer dump?

**Comment by osy86** [comment]
@nobita0464 if you don’t know how to get it you can also send me a sysdiagnose by running `sudo sysdiagnose` in Terminal

**Comment by nobita0464** [comment]
> @nobita0464 if you don’t know how to get it you can also send me a sysdiagnose by running `sudo sysdiagnose` in Terminal
hi here is the file, also I have two of the new issue 
1.When the machine wake up from sleeping mode I need to replug the hdmi cable, overwise I will not have any output 
2. the airdrop is not working
https://www.sendspace.com/file/rflk35

**Comment by osy86** [comment]
You do not seem to have connected the display through Thunderbolt. Both Thunderbolt buses are showing as not connected. Make sure you are using a Thunderbolt 3 cable and not a USB-C cable. A Thunderbolt cable has the thunderbolt logo on it. If you are using an HDMI cable, you will NOT have Thunderbolt output.

Bluetooth will be not perfect unless you use an Apple card. Airdrop not working is expected.

**Comment by iiicwx** [comment]
due to the defect minidp to dp cable, today tried the thunderbolt 3 ports output to the monitor, it works fine here with a USB C cable, not a thunderbolt 3 one. voice output works too, though volume control has to go through the display menu.

the native patcher installed, both ports show no devices connected on the system info.

But, HDMI output doesn't work in my system.

**Comment by osy86** [comment]
Closing due to lack of response from original reporter.
