### ISSUE TITLE
macOS installation won't load

### ISSUE THREAD

**Issue by aescolastico** [osy86/HaC-Mini#169]
**Describe the bug**
After selecting the boot device I get dumped to a black screen.

**Expected behavior**
macOS installation GUI should load

**Environment:**
 - Running OSX version: macOS Catalina
 - Target drive OSX version: macOS Catalina
 - HaC Mini installer version: 2.0

**Additional context**
Troubleshooting steps:
I followed the guide for creating the installation media on a 32GB usb fd. (APFS, GUID Partition Map).
Reset BIOS to defaults.
Disabled Secure Boot.
Disabled Wake on LAN
Disabled PCIE APM
Disabled Bluetooth
Set Thunderbolt Security to Legacy

**Comment by osy86** [comment]
Please follow https://osy.gitbook.io/hac-mini-guide/post-installation/support#getting-into-boot-picker-menu

**Comment by aescolastico** [comment]
> Please follow https://osy.gitbook.io/hac-mini-guide/post-installation/support#getting-into-boot-picker-menu

Ok I was able to get to the apple logo with sheet boot picker. However the loading bar just fills up and gets stuck at the end. Its been like that for an hour. No install menu or anything. Any ideas?

**Comment by chrisallen** [comment]
@aescolastico have you tried creating the USB stick with HFS+ and not APFS?

**Comment by aescolastico** [comment]
I have not. Is that the recommended option? I just chose APFS because it was the default.

**Comment by chrisallen** [comment]
I don't think it is explicitly mentioned in the install guide, but historically, I have used HFS+ for all boot USB's and I end up with a higher rate of success.

**Comment by aescolastico** [comment]
<img width="1260" alt="Screen Shot 2020-01-23 at 4 43 18 PM" src="https://user-images.githubusercontent.com/30540257/73026542-968d0300-3dff-11ea-84c1-647145c92517.png">

I don't actually see HFS+ available in the erase menu

**Comment by chrisallen** [comment]
Ahh sorry, You want `Mac OS Extended (Journaled)` (which is HFS+)

**Comment by aescolastico** [comment]
Yeah I just tried and it has the same issue.

**Comment by osy86** [comment]
Try the beta installer https://github.com/osy86/HaC-Mini/suites/407662409/artifacts/1198096 also try enabling verbose boot and take a picture when it gets stuck.

**Comment by aescolastico** [comment]
<img width="1061" alt="Screen Shot 2020-01-23 at 5 49 15 PM" src="https://user-images.githubusercontent.com/30540257/73030942-bd9c0280-3e08-11ea-84d9-3f4d489ddf32.png">

I got an error when extracting it. Should I ignore it and try to use it anyway?

**Comment by chrisallen** [comment]
@aescolastico please try using another browser to redownload the ZIP file.

**Comment by osy86** [comment]
No I think it's fine. For some reason it's trying to extract the .pkg. The .zip extract worked.

**Comment by aescolastico** [comment]
This is the verbose logging message with the beta installer.
![IMG_0588](https://user-images.githubusercontent.com/30540257/73033282-81b86b80-3e0f-11ea-8952-791c8fd4ea9e.jpeg)
![IMG_7081](https://user-images.githubusercontent.com/30540257/73033283-82510200-3e0f-11ea-9542-fd9bc5cf9dc4.jpeg)

fTimerServiceMatching timed out

**Comment by osy86** [comment]
> AppleNVMe Assert failed: ( 0 != data )

Some others had this problem before. What NVMe are you using? Can you try a different one?

**Comment by aescolastico** [comment]
Samsung PM981. Unfortunately I don't own any others. That being said, can SSD incompatibility cause the installer to not even load? I mean I haven't even tried to install to it yet.

**Comment by osy86** [comment]
Yes, there's known issues with Samsung SSDs and hackintoshes/Macs unfortunately. Booting installer is the same as booting into installed OSX.

**Comment by aescolastico** [comment]
Ah ok. Whats are the recommended SSDs to use?

**Comment by osy86** [comment]
Personally I downgraded to a SATA M2 SSD after #22 since NVMe seems to be hit or miss in general. I think if you google the error message "AppleNVMe Assert failed: ( 0 != data )" you can find other people with this issue and maybe you can debug it. If you do figure out a solution, please share it and I can update the guide.

**Comment by JeffreyName** [comment]
I met same issue, 1 whole day wasted, my working solution is:
Toggle on boot options(off only for secure boot) in HaCMini when creating USB booting stick.

**Comment by aescolastico** [comment]
ordered a sata drive to test. ill report back here with how it goes.

**Comment by aescolastico** [comment]
![IMG_0273](https://user-images.githubusercontent.com/30540257/73586245-75b85380-4478-11ea-891e-97d0cdc84893.jpg)
Ok so I tried to use a data drive and I still cannot boot. Although the logging appears to be different. I also tried both m.2 slots with the same result. I noticed the install boot menu option had "(external)" I don't think that was there with the nvme drive but I can't be sure.

**Comment by aescolastico** [comment]
@osy86 Have you encountered this error with your sata drive? 

Im sort of at a loss here. We all basically have the same hardware here.

**Comment by osy86** [comment]
I haven’t this is weird. A few other people ran into this issue but they never responded so I didn’t know if it’s been resolved or not.

**Comment by osy86** [comment]
Try disabling thunderbolt in bios (set to DP only).

**Comment by aescolastico** [comment]
![IMG_0274](https://user-images.githubusercontent.com/30540257/73599583-07749f00-4513-11ea-803d-4922e77c2243.jpg)
Ok I tried that and I get a different message.

**Comment by osy86** [comment]
And it stops there? Okay probably not the issue then. The only other thing I can think of is a full bios reset and recreate the installer and try again.

**Comment by aescolastico** [comment]
Ok I guess its worth a shot. I'll report back soon.

**Comment by aescolastico** [comment]
@osy86 Back to the 1683 message. Did intel release multiple slightly different versions of the HVK?
Could the sata drive be incompatible as well?

**Comment by osy86** [comment]
Try booting installer with no SSD installed.

**Comment by aescolastico** [comment]
![IMG_0275](https://user-images.githubusercontent.com/30540257/73602071-4ae30380-453b-11ea-8ae5-b4636d9fc4e4.jpg)

No dice.

**Comment by aescolastico** [comment]
Does your installer have the following Catalina fix?
https://khronokernel.github.io/EC-fix-guide/

This script references the issue as well:
https://github.com/corpnewt/USBMap

I unfortunately don't really know much about Hackintoshes to check myself if your package already takes this into account.

**Comment by osy86** [comment]
Yeah EC and USB patches are applied.

**Comment by osy86** [comment]
Try this. Mount EFI partition on the usb installer. Edit EFI/OC/config.plist and change this line https://github.com/osy86/HaC-Mini/blob/master/OC/config.plist#L142 to “false”.

**Comment by aescolastico** [comment]
@osy86 Yeah that didn't work either.

**Comment by aescolastico** [comment]
@osy86 Anything I should have done other than changing the value, saving and unmounting?

**Comment by osy86** [comment]
I’m not really sure what else to do. You can try going on the discord https://discord.gg/u8V7N5C and refer to this thread and ask what else you can try. I can’t really think of anything else that could be wrong.

**Comment by osy86** [comment]
Also can you dump your ACPI tables? There are instructions online but easiest way is to run Clover from a USB drive and press F4 at the menu (there won't be any GUI indication).

**Comment by aescolastico** [comment]
Is that the same as what's being described here: 
https://khronokernel.github.io/EC-fix-guide/desktop-ec.html

**Comment by osy86** [comment]
Yup but just the dumping part.

**Comment by aescolastico** [comment]
I tried pressing f4 but EFI/Clover/ACPI/origin is empty when I insert the drive back into my MacBook

**Comment by aescolastico** [comment]
I must be using the wrong boot options and or partition format
@osy86

**Comment by aescolastico** [comment]
[origin.zip](https://github.com/osy86/HaC-Mini/files/4175620/origin.zip)
Ok I figured it out. I was looking in the regular partition not the EFI partition. Heres the dump.

**Comment by aescolastico** [comment]
@osy86 
Whats next after getting the dump? Do you need to modify the installer?

**Comment by osy86** [comment]
I will take a look when I am free. Did you follow my suggestion in asking the community for help?

**Comment by aescolastico** [comment]
Yeah no response from discord.

**Comment by osy86** [comment]
:( I hopefully will have some free time in the upcoming weeks.

**Comment by aescolastico** [comment]
Ok I appreciate the help

**Comment by aescolastico** [comment]
@osy86  Do you think If I had the exact the ssd model you had that the installer would work as is?

**Comment by osy86** [comment]
I don’t think it has anything to do with ssd because you tried no ssd and it had the same issue right.

**Comment by aescolastico** [comment]
I guess

**Comment by kosgug** [comment]
mark , Same with U

**Comment by aescolastico** [comment]
@osy86 
Have you had a chance to look at the dump yet?

**Comment by osy86** [comment]
I took a look and it seems that in your ACPI and there's two differences: H_EC is disabled and a second ECDV device is added. I think the issue might be related to https://github.com/AMD-OSX/AMD_Vanilla

> - To boot 10.15 two things needs to be taken care of:
>  - If you have an EC device with ID `PNP0C09` in your DSDT then macOS might get stuck while booting at the initial stage. To fix that you need to make sure your EC device is disabled by making it return status `Zero`. You can use a custom SSDT-EC0.aml to do that and if you want to see how it works then refer [here](https://github.com/acidanthera/OpenCorePkg/blob/5e020bb06b33f12fa8b404cc3d1effaa5fbc00ea/Docs/AcpiSamples/SSDT-EC.dsl#L33). <br> -or- <br> You can change the ID of the EC device. Use this ACPI patch:
    ```
        Comment             Find        Replace
    PNP0C09 to PNPFFFF    41D00C09     41D0FFFF
    ```

I don't think the aml would work for our build but you can try the following ACPI Patch in config.plist

```xml
			<dict>
				<key>Comment</key>
				<string>patch PNP0C09 to PNPFFFF to disable all EC</string>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>QdAMCQ==</data>
				<key>Replace</key>
				<data>QdD//w==</data>
			</dict>
```

**Comment by aescolastico** [comment]
Oh ok cool. So I should make an installer, mount the EFI, and change the config.plist? Will these keys exist in the file already or do I have to add them? Sorry if that's a stupid question. Also what's the path for the config.plist file?

**Comment by osy86** [comment]
EFI/OC/config.plist

Mount EFI and open it in a text editor. You’ll see the other patches and place this under it.

**Comment by aescolastico** [comment]
That did the trick! Installing macOS as we speak. You rock @osy86

**Comment by osy86** [comment]
Interesting, so this fix won’t apply after install so you need to do that manually as well. I’m surprised that others aren’t running into this issue. Maybe it’s dependent on bios version. Idk, but I’ll submit a change to the project soon.

**Comment by osy86** [comment]
Okay I made the change. Please try installing https://github.com/osy86/HaC-Mini/suites/457786439/artifacts/1853052 on your working installation. You no longer need to modify config.plist. It should fix it on your boot drive as well.

Also after installing and rebooting and making sure everything works, please run `ioreg | grep AppleBusPowerController` in terminal and make sure you see something like
```
$ ioreg | grep AppleBusPowerController
    | | +-o AppleBusPowerController  <class AppleBusPowerController, id 0x1000002f0, registered, matched, active, busy 0 (0 ms), retain 6>
```

**Comment by aescolastico** [comment]
What you said about bios version got me thinking. Now I originally flashed my bios before I started to use the installer so I thought I was on the latest. But I thought I should try and reflash to see what happens. After that it booted just fine into the installer and macOS. So either I :
Used the wrong bios file
OR
The original flash actually failed to install and I didn’t realize this. 

Either way, this was on me for not checking my bios version. 😓

I can check that command On my unpatched boot install when I get home tonight. Does this new patch conflict at all with the latest bios or does it just increase compatibility with old ones?

**Comment by osy86** [comment]
The new patch basically does what I posted as a workaround earlier but in a better way.

**Comment by osy86** [comment]
@aescolastico Can you comment if it was indeed a BIOS version issue?

**Comment by aescolastico** [comment]
It was yes.
