### ISSUE TITLE
HaC-Mini installation failed

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#175]
**Describe the bug**
The installer said An error occurred during installation and the installation failed when I tried to install HacMini to my usb drive. 

All the files seems to be upgraded though.

**Environment:**
 - Running OSX version: 15.2
 - Target drive OSX version: 15.2
 - HaC Mini installer version: 2.6

**Additional context**
![Screen Shot 2020-01-27 at 12 33 22 PM](https://user-images.githubusercontent.com/38860226/73150525-b96e2e80-4101-11ea-8c59-e8e0e3f31ef3.png)

**Logs**
[install.log](https://github.com/osy86/HaC-Mini/files/4115590/install.log)

Edit: 
- Also failed when upgrading my current hac mini, new log:[install.log](https://github.com/osy86/HaC-Mini/files/4115638/install.log)
- And it's weird that my NUC cannot automatically boot into MacOS, only select it from OC boot menu can help.
- Later I tried reinstallation after boot into my MacOS via OC on my USB drive, it succeed. But still cannot automatically boot into MacOS.

**Comment by KrisCris** [comment]
seems some Package Authoring Error occurred, as it described in the log

**Comment by KrisCris** [comment]
OK, at least the boot problem solved: Select the startupDisk in system preferences and reboot.

**Comment by osy86** [comment]
```
installd[1770]: ./postinstall: Volume EFI on disk7s1 failed to unmount: dissented by PID 285 (/Applications/ESET Cyber Security.app/Contents/MacOS/esets_daemon)
2020-01-27 12:33:04+08 KrisCriss-Mini installd[1770]: ./postinstall: Dissenter parent PPID 273 (/Applications/ESET Cyber Security.app/Contents/MacOS/esets_daemon)
```

Seems like your AV is the issue.

**Comment by KrisCris** [comment]
> ```
> installd[1770]: ./postinstall: Volume EFI on disk7s1 failed to unmount: dissented by PID 285 (/Applications/ESET Cyber Security.app/Contents/MacOS/esets_daemon)
> 2020-01-27 12:33:04+08 KrisCriss-Mini installd[1770]: ./postinstall: Dissenter parent PPID 273 (/Applications/ESET Cyber Security.app/Contents/MacOS/esets_daemon)
> ```
> 
> Seems like your AV is the issue.

Perhaps. But I am still curious why the installation succeed when I reinstall it after the latest version already been installed.

**Comment by osy86** [comment]
Probably got lucky and the AV didn’t trigger that time.
