### ISSUE TITLE
Unusual EFI Contents

### ISSUE THREAD

**Issue by crhendo** [osy86/HaC-Mini#176]
I believe I now have a very stable version of Catalina 10.15.2 running on my NUC and I am very grateful for the enormous amount of work that has been contributed here. My only hiccup was the DW1820A which simply did not want to hold onto any Bluetooth devices since 10.15.2 was installed. While I wait for my BCM94360CS2 and adapter to arrive, an old USB Bluetooth dongle is fulfilling this role.

In an effort to better understand Opencore, I have been spending some time with Google and have just finished reading about EFI and its role. Having now mounted my EFI partition, I discovered that I appear to have two OC directories. One residing in the root directory with what appears to be kexts etc from my original clean install and the other residing in the EFI folder with the most recent kexts. Should I be concerned about the older OC directory? Is it safe to delete it? Also any thoughts about how this may have happened would be welcome.

![image](https://user-images.githubusercontent.com/56284235/73235622-43da8f00-41e3-11ea-88fe-c18e3f52c3ed.png)

**Comment by osy86** [comment]
I don't know how the other OC directory is made, but it's not used anywhere. Only `EFI/OC` is seen by the BIOS and is loaded.
