### ISSUE TITLE
Can't boot from SSD after macOs install + questions

### ISSUE THREAD

**Issue by adept7771** [osy86/HaC-Mini#177]
**Describe the bug**

After installing hackintosh i can't load into mac os without usb stick with installer. If i remove this stick - nuc try to boot from windows ssd disc.

**Expected behavior**

macOS should boot up after installing without any magic, like installation guide says.

**What i try to do to solve:**

i try to load from usb stick with rapidly pushing key alt to reset nvram. But if usb stick plugged in - there is no any loader options from this stick, each time mac os loads from my ssd.

**Environment:**

Nuc hades canyon, 2 ssd drives. One with windows, one with hackOs.
Bois was updated to HN0059 before mac os install
All BIOS options was set to mentioned in guide before installing process

**Also questions:** First of all excuse me if i wrote this message in wrong place but i didn't find any channels when i can post my questions to developers of this miracle. If this place exists - please post me the link of it.

1) Where i can do donation to your project? It's totally unbelievable that somebody without knowledges about hackintoshes can install it in few clicks. You guys did huge work! And did it perfectly.

2) Time capsule service. I have one, and as i try - hackintosh can perfectly work with it. But if something will going wrong with system? Can i restore image of os from time capsule? I suggest i must plug in flash drive with your installer and choose "restore from time capsule" ?

3) WiFi card, now i ordered mentioned wifi card and adapter from e-bay, and wait for delivery. After it will be delivered and installed, do i need something manipulate in system? Or it will work out of the box?

4) System updates. If i understood right i must turn off all system updates to prevent situations when updates can brake my system. Is it right? How can i update hackintosh in future for future versions of mac os?

**Comment by HorstBrack75** [comment]
Press F10 and see if you can select your MacOS SSD. In so, change boot order in Bios.

If MacOS SSD still boots to Windows, enable boot picker.

In the boot picker menu, you will see that you could also boot to recovery partition. You can restore from time machine using the recovery partition.

**Comment by osy86** [comment]
So 2 SSD and existing windows installs are both not well supported by OSX so YMMV. So follow @HorstBrack75 's advice above. If you still cannot see the OSX drive, you have to reset the NVRAM (see the support page).

You can restore from time machine/time capsule perfectly fine just like on a Mac. I've done it myself before.

If you use the Apple wifi card be aware that you can only use 1 SSD. If you use the Dell wifi card, be aware that BT compatibility is pretty hit or miss.

System updates are fine. In case of major OS upgrades (like 10.16 once that's a thing), you should wait for a HaC Mini update here as there'll likely be some bootloader changes you have to install first.

**Comment by adept7771** [comment]
Thx you guys! Main point of my problems was in keyboard. Logitec can't correctly work until nuc loading up, and i wasn't able to enter in boot mode properly. Now i reinstall macOS and restored my previously install correctly - it's real working feature! 
Ticket can be closed. All works fine, and i can easy switch between windows ssd and mac os ssd
