### ISSUE TITLE
SSD not bootable without Installer-USB

### ISSUE THREAD

**Issue by spasma** [osy86/HaC-Mini#179]
**Describe the bug**
Yesterday I have installed my Hac Mini completely, which worked fantastic, thanks! 

I have my USB drive on my personal key chain, so I removed my USB from the NUC today. After restarting I was getting the default "no boot drive" message from the motherboard. So the OpenCore Boot Menu is not available on the SSD, only on the bootable USB Drive. 

The was not issue here, and couldn't find anything related really. I also tried the "Preferences > Startup Disk", but this wasn't working, still showing this.

Also, the SSD isn't showing up when using F10 while booting and in the BIOS. (and the option-command isn't working when the USB is not inserted, because OpenCore is not loaded)

**Expected behavior**
I expect to see the OpenCore boot menu when I start the NUC without the Installer-USB inserted.

**Configuration**
- HaC Mini version [e.g: 2.0]:  2.6
- OSX version [e.g: 10.14.6]: 10.15.3
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK 
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung SSD 970 EVO Plus 1TB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: N/A
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Crucial DDR4 SODIMM 16GB 3200
- Second DIMM model (if installed): Crucial DDR4 SODIMM 16GB 3200
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: Quad-HD
- Any TB3 devices: N/A
- Any USB devices: Apple Magic Keyboard / Apple Magic Trackpad 2

**Modifications**
None

**Panic log**
N/A

**Comment by osy86** [comment]
Try running the hac mini installer on your new install. If it still doesn’t work post your /var/log/install.log

**Comment by spasma** [comment]
Wow, works like a charm! Thank you so much for the fast response. You really should start a Patreon account (or any kind of donation option) for your work and support. Keep up the good work, @osy86!
