### ISSUE TITLE
Intel QuickSync not working

### ISSUE THREAD

**Issue by osy86** [osy86/HaC-Mini#18]
In `/System/Library/PrivateFrameworks/AppleGVA.framework/Resources/Info.plist`, under `System Support`, the entry for `Mac-7BA5B2DFE22DDD8C` does not contain `forceOfflineRenderer`. On a real Macmini8,1 there is no dGPU, so this is fine but we need offline rendering.

Changing the model to iMac18,2 or iMac18,3 works but causes another issue: the USB-C in DP mode no longer output video.

Another solution is to use WhateverGreen's Shiki with boot-arg `shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2`. This works but currently, WG is incompatible with Polaris22Fixup until https://github.com/osy86/Polaris22Fixup/issues/3 is resolved. Additionally, WG has a whitelist system so QuickSync will only work with the apps that are whitelisted, which is not a good solution imo.

We have to either resolve the USB-C DP issues with board-id `Mac-BE088AF8C5EB4FA2` or somehow fake the `forceOfflineRenderer` check in AppleGVA without WG.

**Comment by dongyj1987** [comment]
So this is the reason why my Ultrafine 5K does not work.

**Comment by osy86** [comment]
@dongyj1987 Which part? The quicksync or the iMac18,2 spoofing? You can try the WG workaround I talked about, but you have to remove Polaris22fixup.kext first. This will cause the graphics issue to show up but you can confirm if quicksync is the issue.

**Comment by dongyj1987** [comment]
> @dongyj1987 Which part? The quicksync or the iMac18,2 spoofing? You can try the WG workaround I talked about, but you have to remove Polaris22fixup.kext first. This will cause the graphics issue to show up but you can confirm if quicksync is the issue.

The quicksync, cause it's Mac mini spoofing now. I will try WG while removing Polaris22fixup like you said and see what will happen. Thanks a lot!

**Comment by piotrasd** [comment]
I can confirm changing smbios to iMac18,3 activating QuickSync (without WG), tested with Safari (youtube) QuickTime Recording, Kodi. basically at the moment for Macmini8,1 there is no any GPU acceleration for Enc/dec. Im just wonder why nothing work through AMD GPU ?

Good for testing use Intel Power Gadget tool, at least for Intel GPU - showing if something going through GPU, iStats will no show any load. also Kodi showing Procesing info if we press O during playback.

**Comment by osy86** [comment]
> Im just wonder why nothing work through AMD GPU ?

Apple's drivers does not support video encoding/other features on many AMD chipsets including Baffin (which we're spoofing). I think they've added some support in 10.15 but I doubt it applies to older chipsets.

**Comment by piotrasd** [comment]
It has - apple using Video Toolbox which suppose to work even Buffin at least for H.264 and HEVC
https://developer.apple.com/documentation/videotoolbox
Anyway I will deep more, check what the story, people with RX460 (Polaris Buffin family)and others they got full acceleration. For me target is FXCP. 

And solve mistery of VP9

**Comment by osy86** [comment]
If so then it's probably some config in AppleGVA. Play around with the WG shiki settings I guess.

**Comment by slimx** [comment]
dos `change PEGP to GFX0` and `dAGPM.kext` necessary to active quicksync?

**Comment by osy86** [comment]
They are not necessary.

**Comment by piotrasd** [comment]
@slimx just enough change SMBIOS to Mac18,3 and you will get. Today I got info to get HW dec/enc HEVC with AMD best to change.

"Only SMBIOS iMacPro1,1 support AMD GVA H264/HEVC encoder, no other options on latest macOS."
for some reason the removed for other options after 10.14.4

@osy86 maybe config of iMacPro1,1 will work with USB-C/DP etc ?

**Comment by piotrasd** [comment]
with SMBIOS iMac19,2 im getting both HW acceleration, not everywhere. but safari, iTunes using QSV and FCP AMD ... so for me perfect.

**Comment by osy86** [comment]
Closing as the original Intel QuickSync issue was resolved. Please open a new issue to discuss AMD HW acceleration issues.

**Comment by piotrasd** [comment]
Release 2.0 didn't work at least for Chrome and safari, clean install with WG (default config nothing changed)

**Comment by keatliang2005** [comment]
@osy86 @piotrasd 

hi there,

Quick questions here Quicktime player to encode videos. seems like it's not using quick sync ?
 i trying to use handbrake to encode with quick sync, it crash.

This also including video decoding on h264, on quick time player is that known limitation of this build ?

i am using latest clean new install
OS: 10.15.6
HacMini: v2.10
