### ISSUE TITLE
How to enable AMD GPU for HW Acceleration？

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#180]
I cannot find a way to let Adobe Media Encoder using AMD GPU for HW encoding.

When I selected iGPU as codec in the installer, adobe media encoder chooses to using iGPU and the GFX frequency in Intel power gadget boosts up as soon as I start encoding.

However, when AMD GPU is selected as codec in the installer with iGPU disabled in BIOS, the adobe media encoder switched to SW encoder. And HW acceleration is not working.
![Screen Shot 2020-02-06 at 7 13 25 PM](https://user-images.githubusercontent.com/38860226/73932635-bf3fed00-4915-11ea-8859-1ff4d0132610.png)
![Screen Shot 2020-02-06 at 7 21 05 PM](https://user-images.githubusercontent.com/38860226/73932768-ef878b80-4915-11ea-82eb-6fa475660d0f.png)

**Comment by KrisCris** [comment]
Also, the Adobe Media Encoder did use HW Encoder after I enabled IGPU in BIOS. But I think it's using the IGPU since the speed is slow as before and the GFX frequency in intel power gadget boosted.
![Screen Shot 2020-02-06 at 7 28 17 PM](https://user-images.githubusercontent.com/38860226/73933431-640efa00-4917-11ea-949a-7fd4ed104947.png)
![Screen Shot 2020-02-06 at 7 32 27 PM](https://user-images.githubusercontent.com/38860226/73933451-6c673500-4917-11ea-9516-7bef5585825d.png)

**Comment by KrisCris** [comment]
And after switching to AMD, my chrome is insanely slow and impossible for watching videos.

**Comment by osy86** [comment]
After trying the whitelist, also try putting [com.apple.AppleGVA.plist.zip](https://github.com/osy86/HaC-Mini/files/4039142/com.apple.AppleGVA.plist.zip) in `~/Library/Preferences`.

**Comment by KrisCris** [comment]
> After trying the whitelist, also try putting [com.apple.AppleGVA.plist.zip](https://github.com/osy86/HaC-Mini/files/4039142/com.apple.AppleGVA.plist.zip) in `~/Library/Preferences`.

I will try, thanks.

**Comment by osy86** [comment]
Did it work? On latest version I was not able to reproduce the issues with Google Chrome.

**Comment by KrisCris** [comment]
Ah, I think the previous version has some issues so I gave up.

Here is the result for both the previous version and the latest version:

With the previous version, the HW acc was not supported no matter I use that plist or not.
<img width="801" alt="Screen Shot 2020-06-17 at 2 18 36 PM" src="https://user-images.githubusercontent.com/38860226/84865891-8a098f80-b0ab-11ea-8ca5-e81a8ddaead2.png"> Without the plist.

<img width="682" alt="Screen Shot 2020-06-17 at 2 23 35 PM" src="https://user-images.githubusercontent.com/38860226/84865924-94c42480-b0ab-11ea-9cf5-b437e12723aa.png">With the plist.

With the latest version, HW ACC works alright when iGPU is enabled - I have to enable iGPU for h.256 HW ACC. 
<img width="934" alt="Screen Shot 2020-06-17 at 2 48 37 PM" src="https://user-images.githubusercontent.com/38860226/84866151-ea003600-b0ab-11ea-9b06-21fa79546da2.png">


And the h.264 HW ACC doesn't work with Adobe media encoder for some reason. The HW option is available, but I cannot apply that, which is weird.
<img width="518" alt="Screen Shot 2020-06-17 at 2 48 11 PM" src="https://user-images.githubusercontent.com/38860226/84866226-fe443300-b0ab-11ea-936e-1483be85f2f1.png">


With the plist you uploaded, the VDADecoderChecker report this:
<img width="682" alt="Screen Shot 2020-06-17 at 2 50 32 PM" src="https://user-images.githubusercontent.com/38860226/84866250-0603d780-b0ac-11ea-8a31-617ba8c42e84.png">


So I think maybe I'd better just use Intel codec...
