### ISSUE TITLE
Can we monitor GPU activities?

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#181]
Is it possible to monitor GPU activities in the Activity Monitor as it works in a real mac?

**Comment by shoyuf** [comment]
I use FFmpeg encode my video, The CPU occupate 100% and the GPU(Vega GL M) tempreture is 50 ℃

**Comment by KrisCris** [comment]
> I use FFmpeg encode my video, The CPU occupate 100% and the GPU(Vega GL M) tempreture is 50 ℃

Then it's using software encoder, right?

**Comment by osy86** [comment]
Try adding to the WHITELIST section of https://github.com/acidanthera/WhateverGreen/blob/master/Resources/Patches.plist

**Comment by KrisCris** [comment]
> Try adding to the WHITELIST section of https://github.com/acidanthera/WhateverGreen/blob/master/Resources/Patches.plist

what is this whitelist for?

**Comment by osy86** [comment]
It forces the gpu recognization patches for an app.

**Comment by KrisCris** [comment]
I am not sure how to add to that file. Is there a "Patches.plist" or something on my disk?

**Comment by osy86** [comment]
You have to rebuild it after modifying the project.

**Comment by KrisCris** [comment]
> You have to rebuild it after modifying the project.

You mean add something like this?
<img width="1512" alt="Screen Shot 2020-02-13 at 10 55 22 PM" src="https://user-images.githubusercontent.com/38860226/74447836-f46bb280-4eb4-11ea-9194-531a1843e39b.png">

I found that my build is smaller than the one come with HaC installer, does that matter?

**Comment by osy86** [comment]
There might be another issue, I will check.

**Comment by osy86** [comment]
Sorry I was responding to the wrong issue. My advice was meant for #180 

For monitoring GPU in Activity Monitor, I need to research it more. Do you know if it's possible with AMD card on any other Mac/Hackintosh?

**Comment by KrisCris** [comment]
>For monitoring GPU in Activity Monitor, I need to research it more. Do you know if it's possible with AMD card on any other Mac/Hackintosh?

For those natively supported cards like rx580, yes. And I think a GPU with proper drivers should be able to be monitored in Activity Monitor.app (right click->monitor->show GPU History), and this option is available on my laptop with gtx1060 (high sierra).

**Comment by osy86** [comment]
I see Show GPU History on mine using these steps: https://support.apple.com/guide/activity-monitor/view-gpu-activity-actm9329b315/mac

**Comment by KrisCris** [comment]
Thanks! I didn't expect that can be shown in this way.

Then I will try what you said in #180 again again. I have just reinstalled everything without any modification, and at this point, even though I selected HW ACC, there is no GPU usage surge.

**Comment by osy86** [comment]
I don’t think VCE usage is shown there. Only GPU tasks. Have you seen it working on a real Mac (with VCE)?

**Comment by KrisCris** [comment]
> I don’t think VCE usage is shown there. Only GPU tasks. Have you seen it working on a real Mac (with VCE)?
Hmmm...
![89F44A27D7212889C2CEE48C4B12CF28](https://user-images.githubusercontent.com/38860226/80298892-1477f600-87c3-11ea-986a-ffe3fbe29509.png)

**Comment by osy86** [comment]
I see. I think the Radeon VII drivers are probably better. In any case, a fix would require adding support in the driver, which is really difficult, so I don't think it's worth it.

**Comment by KrisCris** [comment]
Ah, it's OK. It's already so nice of you made this project possible!

I just sometimes want to know if some applications really running on AMD GPU. 😂

**Comment by shoyuf** [comment]
> > I use FFmpeg encode my video, The CPU occupate 100% and the GPU(Vega GL M) tempreture is 50 ℃
> 
> How did you manage to see the GPU temperature?

iStat Menus?
