### ISSUE TITLE
Can't Disable SIP

### ISSUE THREAD

**Issue by densimpson** [osy86/HaC-Mini#182]
Hi all

I am trying to use egpu with my Nvidia GeForce GTX 1080 
According to egpu.io guide I have to install the purge-wrangler which require to Disable SIP
I am using Mojave 10.14.6 and the HaC-Mini v2.6. But I still can't disable SIP via config.plist 

My config.plist
![Screenshot 2020-02-10 at 8 23 31 PM](https://user-images.githubusercontent.com/20817902/74150531-119a4a00-4c45-11ea-86f3-7f3adc0d8630.png)
csrutil status check in Terminal
![Screenshot 2020-02-10 at 8 24 05 PM](https://user-images.githubusercontent.com/20817902/74150535-15c66780-4c45-11ea-855a-93585d64c73f.png)

**Comment by lmshsqlc** [comment]
You’ll use csrutil to configure sip just like a real Mac. However nvidia 1080 is not supported as it don’t have a web-driver supported on Mojave.

**Comment by osy86** [comment]
Yes disable from recovery but nvidia is not supported so there’s no point.
