### ISSUE TITLE
How to thank oxy86 for HaC-Mini

### ISSUE THREAD

**Issue by chirimar** [osy86/HaC-Mini#183]
Hello
Is there a way to support this project and @osy86 and paypal/venmo/tip for this amazing piece of work? 

I have been looking everywhere but I couldn't find anything.

Thank you @osy86

**Comment by spasma** [comment]
@osy86 Can you create a Paypal account? Or if you want to stay more anonymous, provide an ethereum/bitcoin address? I love your work and am very happy with your contributions to all issues in this repo. Keep up the good work!

**Comment by chirimar** [comment]
Thank you @spasma 

I feel exactly the same way.

**Comment by osy86** [comment]
Thanks for the kind words! I currently have no plan to take donations. I will close this and keep #115 open so discussion can be consolidated in one place.

**Comment by chirimar** [comment]
Sorry I didn't find the other one. Should have searched for 'patreon' as well.

**Comment by incognico** [comment]
Is there a discord or irc channel for this project?

**Comment by GetTheGuy66** [comment]
WTF 2 ISSUES WANTING TO DONATE OSY86 WITH MANY LIKES AND OSY'S LIKE: bruh..
