### ISSUE TITLE
A usb port cannot recognize usb2.0

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#186]
**Describe the bug**
The USB port I circled on image cannot read any usb2.0 devices even cannot for charging.
<img width="709" alt="Screen Shot 2020-02-14 at 4 40 42 PM" src="https://user-images.githubusercontent.com/38860226/74515239-24fd2c00-4f49-11ea-8acf-42847cd85aa5.png">

**Configuration**
- HaC Mini version : 2.6
- OSX version : 10.15.3
- NUC model : NVK
- Boot SSD model and protocol : NVME
- Second SSD model and protocol : SATA
- First DIMM model : HyperX impact
- Display port(s) used : miniDP, usb-c
- Display resolution(s) : 2k, 4k
- Any TB3 devices: HP TB3 dock
- Any USB devices: external usb disk, logitech g903 receiver, keyboard.

**Comment by osy86** [comment]
Is that the only one? Any other ports? Also place run `ioreg -l` and attach the output.

**Comment by KrisCris** [comment]
Yes, only this one.

And after trying connecting my android device to that port, I found that it can only be used for charging, no data transfer. Whereas when connecting iOS device to that, both data transfer and charging are not available. 

And I found that all the USB-A ports except the orange one are slow for connections of iOS devices, around 3-10 seconds vary from different devices, and charging starts only after my devices beings recognized. This may explain why the problem port cannot charge my iOS device. 

---

[ioreg.txt](https://github.com/osy86/HaC-Mini/files/4203893/ioreg.txt)

**Comment by osy86** [comment]
Can you try unplugging all other USB devices and see if that makes a difference?

Also try a full power cycle (unplug and re-plug).

Any difference in windows/linux?

**Comment by KrisCris** [comment]
I tried it in BIOS where my wireless mouse still not won't work, which may indicate that something went wrong with my machine.

**Comment by KrisCris** [comment]
I contacted Intel customer support for NUC replacement, seems its an hardware failure.

**Comment by KrisCris** [comment]
> I contacted Intel customer support for NUC replacement, seems its an hardware failure.

Meanwhile, I wonder if it has something to do with hackintosh, since my Laptop also had one port failed to read usb2.0 after hackintosh last year.
