### ISSUE TITLE
Can't boot when the installer USB disk unplugged 

### ISSUE THREAD

**Issue by kelvinsze** [osy86/HaC-Mini#188]
**Describe the bug**
After install successfully, reboot system and it will shows "a bootable device has not detected". I have to plug the installer disk to boot to OS

**Expected behavior**
boot to OS when disk is unplugged 

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.6
- OSX version [e.g: 10.14.6]: 10.15.3
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: C2000Pro 1TB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: ADATA DDR4 2666 16GB
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 1080p
- Any TB3 devices: 
- Any USB devices:

**Comment by osy86** [comment]
Try to install the hac mini pkg manually after boot.

**Comment by kelvinsze** [comment]
It seems work fine now, thanks

**Comment by kelvinsze** [comment]
Hello again, I think this happens cause boot camp assistant breaks boot information. The boot camp assistant didn't ask me to creat USB installer as you described, and reboot automatically. Then it won't boot to OS.

How can I use boot camp assistant correctly to install Windows? Thanks.

**Comment by lmshsqlc** [comment]
You install windows as if it is a pc. Use opencore bootloader to boot into windows installer. You can turn on showpicker or “show boot menu” in HaC mini installer.

**Comment by kelvinsze** [comment]
Thanks, installed successfully.
