### ISSUE TITLE
1.3 not work

### ISSUE THREAD

**Issue by qibinghua** [osy86/HaC-Mini#19]
![微信图片_20190727173139](https://user-images.githubusercontent.com/848684/61992724-6c4aca80-b094-11e9-81fd-4b095d5da048.jpg)

**Comment by qibinghua** [comment]
model:NUC8i7HVK with nvme sm961

**Comment by osy86** [comment]
Post your full EFI directory.

**Comment by qibinghua** [comment]
full clover directory and works fine: http://www.2b.pm/CLOVER.zip 
But with merged your  version 1.3, then works error with i2ccontroller time out.

**Comment by osy86** [comment]
Please post your nonworking merged EFI zip

**Comment by HorstBrack75** [comment]
I get the very same issue. Then eventually you will get a busy timeout [0], (60sec): ' AppleACPICPU
this only happens when booting from USB device. It can be circumvented by booting with injected kexts.

**Comment by qibinghua** [comment]
> Please post your nonworking merged EFI zip

http://www.2b.pm/clover/0728/CLOVER-notwork.zip

**Comment by qibinghua** [comment]
> I get the very same issue. Then eventually you will get a busy timeout [0], (60sec): ' AppleACPICPU
> this only happens when booting from USB device. It can be circumvented by booting with injected kexts.

It is not boot from USB device.

**Comment by osy86** [comment]
It's not working because you didn't use my config.plist.

**Comment by HorstBrack75** [comment]
What are all these kext for? This is not HacMini 1.3.....

**Comment by osy86** [comment]
Exactly. I'm not sure why people don't use my config/package and then report issues with it. Of course it doesn't work.

@qibinghua Please start with a brand new config. Back up your EFI and delete everything. Reinstall clover and use the following install options:

1. Clover for UEFI booting only
2. Install Clover in the ESP
3. UEFI Drivers -> ApfsDriverLoader-64 (for APFS support)
4. UEFI Drivers -> SMCHelper-64 (for FakeSMC support)
5. UEFI Drivers -> AptioMemoryFix-64 (for FileVault support)
6. UEFI Drivers -> HFSPlus (for HFS+ support)
7. UEFI Drivers -> UsbKbDxe-64 (needed for FileVault support)
8. FileVault 2 UEFI Drivers -> AppleUISupport-64 (for FileVault support)

Then from the 1.3 zip, copy all the files in and replace config.plist. You have so many things that are known to be broken in your EFI.

**Comment by qibinghua** [comment]
> It's not working because you didn't use my config.plist.

I change to your config.plist in clover boot menu when i boot. the config name is config-1.3.plist

**Comment by osy86** [comment]
I see, but please still follow my comment about a fresh EFI. You have kexts that are known to be broken.

**Comment by jarryji** [comment]
I supposed you installed mac on a SATA SSD, then you need a kext called as SATA-unsupported.kext to enable boot up from sata drive

**Comment by qibinghua** [comment]
> I see, but please still follow my comment about a fresh EFI. You have kexts that are known to be broken.

I click F11 clean the nvram, and I2Controller timeout is resolved, but Polaris22MetalFixup.kext will cause rebooting issue. when i change to Polaris22Fixup.kext, it is resolved.

**Comment by osy86** [comment]
> > I see, but please still follow my comment about a fresh EFI. You have kexts that are known to be broken.
> 
> I click F11 clean the nvram, and I2Controller timeout is resolved, but Polaris22MetalFixup.kext will cause rebooting issue. when i change to Polaris22Fixup.kext, it is resolved.

Is this with a fresh EFI and no other kext?

**Comment by osy86** [comment]
In another thread the issue was the user was on 10.14.3. Make sure everyone is on 10.14.5+.

**Comment by harryxh** [comment]
Get the same problem. Tried 10.14.5 and 10.14.6, both error with i2ccontroller time out. 
[EFI.zip](https://github.com/osy86/HaC-Mini/files/3488854/EFI.zip)

**Comment by harryxh** [comment]
> > I see, but please still follow my comment about a fresh EFI. You have kexts that are known to be broken.
> 
> I click F11 clean the nvram, and I2Controller timeout is resolved, but Polaris22MetalFixup.kext will cause rebooting issue. when i change to Polaris22Fixup.kext, it is resolved.

Followed your method but don't have the luck..

**Comment by 22dm** [comment]
> > > I see, but please still follow my comment about a fresh EFI. You have kexts that are known to be broken.
> > 
> > 
> > I click F11 clean the nvram, and I2Controller timeout is resolved, but Polaris22MetalFixup.kext will cause rebooting issue. when i change to Polaris22Fixup.kext, it is resolved.
> 
> Followed your method but don't have the luck..

I have the same problem, press **space** in the clover and select **boot macOS with injected kexts** solved this problem.

**Comment by klhurley** [comment]
> > > > I see, but please still follow my comment about a fresh EFI. You have kexts that are known to be broken.
> > > 
> > > 
> > > I click F11 clean the nvram, and I2Controller timeout is resolved, but Polaris22MetalFixup.kext will cause rebooting issue. when i change to Polaris22Fixup.kext, it is resolved.
> > 
> > 
> > Followed your method but don't have the luck..
> 
> I have the same problem, press **space** in the clover and select **boot macOS with injected kexts** solved this problem.

Thank you for this, it made it work to install for me.  And it did work on 10.14.6!

**Comment by osy86** [comment]
So what I don't understand is that in config.plist I have
```xml
	<key>SystemParameters</key>
	<dict>
		<key>InjectKexts</key>
		<string>Yes</string>
		<key>InjectSystemID</key>
		<true/>
	</dict>
```

This, in theory, should always inject kext without having to select that option. I wonder if Clover EFI is broken in latest builds.

**Comment by dingld** [comment]
> So what I don't understand is that in config.plist I have
> 
> ```
> 	<key>SystemParameters</key>
> 	<dict>
> 		<key>InjectKexts</key>
> 		<string>Yes</string>
> 		<key>InjectSystemID</key>
> 		<true/>
> 	</dict>
> ```
> 
> This, in theory, should always inject kext without having to select that option. I wonder if Clover EFI is broken in latest builds.

I met the same issue; Can you please  tell your clover version?

**Comment by osy86** [comment]
Closing issue since original problem appears to be resolved. Any farther issues, please open a new ticket.
