### ISSUE TITLE
The blue USB Type A port on the front of the NUC is USB 3.0？

### ISSUE THREAD

**Issue by shoyuf** [osy86/HaC-Mini#190]
https://osy.gitbook.io/hac-mini-guide/post-installation/support#usb-disconnected-on-sleep-wakeup

I can found the [document of nuc8i7hvk](https://www.intel.com/content/dam/support/us/en/documents/mini-pcs/nuc-kits/NUC8i7HVK_TechProdSpec.pdf) 2.2.1 said the blue one is USB 3.1 gen2

**Comment by osy86** [comment]
Yeah it’s 3.1 but it’s alright to refer to 3.1 ports as 3.0.
