### ISSUE TITLE
Cant boot into 1440p UW display

### ISSUE THREAD

**Issue by aescolastico** [osy86/HaC-Mini#192]
May be related to https://github.com/osy86/HaC-Mini/issues/83
However the fix for that does not work for me. 

**Describe the bug**
Booting into new, 1440p monitor, there is no display after apple logo. 
If I switch to the old one after boot, the display works. 
If I switch back to the new one, there's nothing.

Booting into old, 1080p monitor, the display is fine. 
If I switch to the new one after boot, the display appears and the resolution is correctly set to 1440p. I just can't boot directly into it. 

These are both HDMI connections. I installed the OS to the SSD on the old monitor.

**Expected behavior**
Display on 1440p 
**Configuration**
- HaC Mini version: 2
- OSX version: 10.15.2 
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: Samsung P871b, SATA 
- Display port(s) used: HDMI
- Display resolution(s): 1080p, 1440p

**Modifications**
NA

**Panic log**
NA

**Comment by chrisallen** [comment]
I currently use a Dell U3415W (3440x1440p) and it boots natively into this. I am using a miniDP to DP cable.

**Comment by aescolastico** [comment]
Another case of user (me) error. My HDMI cable was plugged into the HDMI 1.2 port on my monitor (doh!). 
Can also confirm miniDP works great for me. I was gonna switch anyways when my cable arrived. 

Closing issue.
