### ISSUE TITLE
Device powers off after > 1 day standby

### ISSUE THREAD

**Issue by osy86** [osy86/HaC-Mini#193]
Seems like if left in standby for a long enough time, the NUC just powers off. This is even though dark wakes happen periodically. I observe the shut down only happening if no user interaction happens for a long enough time (at least a day or two). I suspect it might be trying to hibernate and then shutting off.

**Comment by chrisallen** [comment]
I have seen this happen over the weekends as I leave my NUC on all the time.  I'm happy to test any fix you come up with.

**Comment by osy86** [comment]
Yeah it's super weird. I can't really reproduce it consistently, but I've noticed that as long as I'm using the NUC every day, it never happens. But if I ever leave it standby for a day or more, this sometimes happens but I can't figure out the exact conditions. And from the logs as well as visual inspection, I've seen it do dark wakes/maintenance wakes, so it isn't a matter of losing power. My hypothesis is there's some timer in OSX where it tries to go into a lower level power state (hibernation) when a long period of time passes with no user activity. However, I have hibernation disabled so idk why it would do this.

**Comment by chrisallen** [comment]
Could it be related somehow to the fact that macOS detects the NUC as having a battery?

![image](https://user-images.githubusercontent.com/203867/74977898-7bf68a00-5490-11ea-85cc-5ffa67629a4f.png)

**Comment by osy86** [comment]
I don't think so, #107 found out that it was cosmetic.

**Comment by crhendo** [comment]
My NUC is at work and I have left it running all the time for the past 4-5 months. Normally when I come in after the weekend it is simply a matter waking it from sleep and logging in as usual. Last Monday the NUC was completely turned off when I arrived at work. As we are on a UPS here, power was not the problem. When I hit the power button it simply booted as if from a cold boot and there were no messages suggesting a previous panic etc. Weird.

**Comment by osy86** [comment]
So an update: the issue is with standby. By default after 24 hours of inactivity, the device will enter standby (basically hibernate where RAM is written to storage and it shuts down). However Intel BIOS uses the RTC NVRAM and corrupts the hibernate data. I tried `RTCMemoryFixup` and `HibernateFixup` and they did not make a difference. What we need to do is isolate what memory gets corrupted by the BIOS and then patch the kernel to not use those locations but also to ignore them in the CRC checks.

`sudo pmset -a standby 0` will disable standby and mitigate the issue.

**Comment by Alhammadi3** [comment]
Thx

**Comment by candyrock** [comment]
> So an update: the issue is with standby. By default after 24 hours of inactivity, the device will enter standby (basically hibernate where RAM is written to storage and it shuts down). However Intel BIOS uses the RTC NVRAM and corrupts the hibernate data. I tried `RTCMemoryFixup` and `HibernateFixup` and they did not make a difference. What we need to do is isolate what memory gets corrupted by the BIOS and then patch the kernel to not use those locations but also to ignore them in the CRC checks.
> 
> `sudo pmset -a standby 0` will disable standby and mitigate the issue.

Do we need 'sudo pmset -a autopoweroff 0'?

**Comment by osy86** [comment]
No but the issue also had been fixed so you don’t need anything.

**Comment by candyrock** [comment]
> No but the issue also had been fixed so you don’t need anything.

Thanks @osy86. I did "sudo pmset -a standby 0". Do I need to disable hibernate too?

**Comment by osy86** [comment]
I literally said you don’t need to do anything. Hence this issue was closed.

**Comment by candyrock** [comment]
> I literally said you don’t need to do anything. Since this issue was closed.

I'm confused. Thank so much
