### ISSUE TITLE
AirDrop: No Mac mini icon shown on iOS when selecting airdrop target.

### ISSUE THREAD

**Issue by chrisallen** [osy86/HaC-Mini#195]
**Describe the bug**
Using Airdrop from my iPhone shows my HaC mini, but it lacks the 2018 mac mini icon. Is this a config error on a limitation of HaC mini?

![image](https://user-images.githubusercontent.com/203867/75025144-869c3800-54ff-11ea-84d4-ea640a049bc5.png)

**Expected behavior**

***Configuration**
- **HaC Mini version:** (package from https://github.com/osy86/HaC-Mini/pull/194)
- **OSX version:** 10.15.3
- **NUC model:** NUC8i7HNK
- **Boot SSD model and protocol:** Samsung SSD 970 PRO 1TB
- **Second SSD model and protocol:** Samsung SSD 860 EVO 1TB
- **First DIMM model:** Crucial DDR4-2400 16GB 
- **Second DIMM model:** Crucial DDR4-2400 16GB 
- **Display port(s) used:** 1x mini-DP
- **Display resolution(s):** 3440x1440 (Dell U3415W)
- **Any TB3 devices:** N/A
- **Any USB devices:** Apple Wired Keyboard, Razer Deathadder Mouse

**Modifications**
Using Native BCM943602CS Apple Card with NGFF reverse adaptor.

**Comment by osy86** [comment]
https://support.apple.com/en-us/HT203106

**Comment by chrisallen** [comment]
The issue I see is that instead of the default icon, or even the mac Mini device icon, I just get a white circle. I don't have this issue when I AirDrop to my 2018 MacBook Pro, as that shows the icon for the device.

**Comment by osy86** [comment]
That's weird, but I haven't ran into it. My guess is that it's an iOS bug. I'll wait to see if anyone else can reproduce this.

**Comment by KrisCris** [comment]
> That's weird, but I haven't ran into it. My guess is that it's an iOS bug. I'll wait to see if anyone else can reproduce this.

Agreed, also had experienced that at first, but later the icon showed up.
