### ISSUE TITLE
SIP status: disabled (Apple Internal)

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#196]
I disabled sip in recovery, then its status turned to `disabled (Apple Internal)`  which is weird that I think normally it won't display `Apple internal`.

And the script that I am using to enable HIDPI still tells me SIP need to be disabled

**Configuration**
- HaC Mini version : 2.6
- OSX version : 10.15.3

**Comment by benjaminwan** [comment]
edit efi/oc/config.plist
'NVRAM'->'Add'->'7C436110-AB2A-4BBB-A880-FE41995C9F82'
add 'csr-active-config' = E7030000(type:Data) to disable sip
```
	<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			......
			<dict>
				<key>csr-active-config</key>
				<data>5wMAAA==</data>
			</dict>
		</dict>
	</dict>
```

**Comment by osy86** [comment]
That’s not a good way because you can’t use recovery mode.

**Comment by KrisCris** [comment]
kriscris@KrisCriss-Mac-mini ~ % nvram -p
boot-args	alcid=11 -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2
BootCampHD	%02%01%0c%00%d0A%03%0a%00%00%00%00%01%01%06%00%00%17%03%12%0a%00%03%00%00%00%00%00%7f%ff%04%00
bluetoothInternalControllerInfo	%90%82%ac%05%00%00@%14%d8%96%95%f3%a1Z
prev-lang:kbd	en:252
SystemAudioVolumeDB	%00
platform-uuid	%06%f5%cb%14%83%8e[M%b91T%b2%03%08%00%01
bluetoothActiveControllerInfo	%90%82%ac%05%01%00%00%00@%14%d8%96%95%f3%a1Z
fmm-computer-name	KrisCris%e2%80%99s Mac mini
efi-boot-device-data	%02%01%0c%00%d0A%03%0a%00%00%00%00%01%01%06%00%00%1d%01%01%06%00%00%00%03%16%10%00%01%00%00%00dy%a7'%82&13%04%01*%00%02%00%00%00(@%06%00%00%00%00%00`%921w%00%00%00%00X%0d%d6k%a0w%d5M%b2%a4%c7%ac%0a%0e%1bx%02%02%04%03$%00%f7%fct%be|%0b%f3I%91G%01%f4%04.hB%e6%f2K%00o%ff%c7D%8d%fb%ba=%9a"%e9%af%04%04%9a%00\%001%00B%006%00F%000%004%00C%00D%00-%007%007%000%008%00-%004%009%006%007%00-%00A%007%006%003%00-%009%00E%00E%003%004%000%007%00F%007%00C%00D%007%00\%00S%00y%00s%00t%00e%00m%00\%00L%00i%00b%00r%00a%00r%00y%00\%00C%00o%00r%00e%00S%00e%00r%00v%00i%00c%00e%00s%00\%00b%00o%00o%00t%00.%00e%00f%00i%00%00%00%7f%ff%04%00
SystemAudioVolume	W
efi-boot-device	<array><dict><key>IOMatch</key><dict><key>IOProviderClass</key><string>IOMedia</string><key>IOPropertyMatch</key><dict><key>UUID</key><string>004BF2E6-FF6F-44C7-8DFB-BA3D9A22E9AF</string></dict></dict><key>BLLastBSDName</key><string>disk2s2</string></dict><dict><key>IOEFIDevicePathType</key><string>MediaFilePath</string><key>Path</key><string>\1B6F04CD-7708-4967-A763-9EE3407F7CD7\System\Library\CoreServices\boot.efi</string></dict></array>%00
LocationServicesEnabled	%01

There it is, not sure what's going on that they looks so messy.

**Comment by osy86** [comment]
Hmm I don’t see csr status. Try `sudo nvram csr-active-config`

**Comment by KrisCris** [comment]
`nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found`

weird...

**Comment by KrisCris** [comment]
I did reinstalled HacMini for several times switching back and forth the HW ACC options.

**Comment by osy86** [comment]
Try `ioreg -p IODeviceTree -l | grep csr-active-config`

**Comment by KrisCris** [comment]
> Try `ioreg -p IODeviceTree -l | grep csr-active-config`

It returned nothing.

**Comment by osy86** [comment]
I reversed `csrutil` and it seems like this is the default behaviour (even on real macs). You need to specify `--no-internal` to have it show up as `disabled`. But I don't think that makes any difference.

**Comment by KrisCris** [comment]
The issue is that `https://github.com/xzhih/one-key-hidpi` this tool need sip to be disabled, but after I disabled SIP in this way, it still asks me to disable SIP.

**Comment by osy86** [comment]
Then you should use the `--no-internal` flag

**Comment by KrisCris** [comment]
> Then you should use the `--no-internal` flag

Thanks, I’ll try tomorrow.
