### ISSUE TITLE
DP Audio not working

### ISSUE THREAD

**Issue by aescolastico** [osy86/HaC-Mini#198]
**Describe the bug**
The DP audio appears as a device in macOS but no sound actually comes out. 

**Expected behavior**
Audio output from DP connected monitor

**Configuration**
- HaC Mini version: 2
- OSX version: 10.15.2
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: Samsung P871b, SATA
- Display port(s) used: HDMI
- Display resolution(s): 1080p, 1440p

**Comment by aescolastico** [comment]
@osy86 whats the easiest way to apply the newest AppleALC? I hear that helps with audio. Can I use the hacmini installer for this?

**Comment by osy86** [comment]
You can replace the KEXT in the EFI partition under EFI/OC/Kexts

**Comment by osy86** [comment]
With the latest AppleALC, I tested with a miniDP to HDMI adapter and was able to get audio working on both connectors.
