### ISSUE TITLE
Temperature spiking

### ISSUE THREAD

**Issue by vitospedito** [osy86/HaC-Mini#199]
Is it just my Hac Mini (v2.6) or does everyone notice a rise in temperature when using Mac v Windows?

Temperatures are spiking. I have disable TurboBoost on the BIOS nonetheless the problem persists. Fans are also set to Quiet.

With Turbo Boost Switcher seems okay. Is there a way to stop it from the BIOS or via config.plist?

Thanks!

**Comment by welladamm** [comment]
I haven't noticed any temperature spiking yet. However I do notice a lot of fan RPM spikes. Sometimes when I open a new web page, the fans goes crazy for a minute or two. I'll check if this fan thing is linked to the temperature.

**Comment by vitospedito** [comment]
I can see "some" improvements, i.e. no fans spinning and no high temperatures.

Nonetheless, the app requires you to enter your root password every time you boot (that's annoying!).

Reading on the GitHub page, the app effectively changes the MSR table (0x1a0).

Would it be possible to incorporate this on the config.plist?

I have TurboBoost technology disabled via bios, but I presume Mac doesn't take that into account?

Thanks!

**Comment by KrisCris** [comment]
Apply a better thermal paste may help. In my case, the original thermal compound, which is poor as expected, had already been dry at the time I got this device.

**Comment by vitospedito** [comment]
I really don't want to void the warranty on this machine.

Also, is there a way to turn it off via OpenCore?

**Comment by osy86** [comment]
OSX power management is not tuned for the NUC. Developing a proper thermal profile requires a lot of testing and equipment. This is a shared problem with all hackintoshes.
