### ISSUE TITLE
What did I miss?

### ISSUE THREAD

**Issue by SpookHCK** [osy86/HaC-Mini#20]
So I can get through the installer, but the system will not boot Mac OS from the USB... gets to the point where the GPU is initialized and then reboots...

I have found a way to make it boot; so the install is good (bunch of different kexts... different method ... blah blah .... but I have no metal...) so I must have missed a step somewhere... here is my efi folder for the HaC Mini... Hopefully you can tell me what I missed. so I can boot with your method...

[EFI.zip](https://github.com/osy86/HaC-Mini/files/3439309/EFI.zip)

NUC8i7HVK BIOS Version 0058
Storage: Intel SSDPEKNW512GB (PCI-E)
32GB RAM

Thanks for any help/advise!

**Comment by osy86** [comment]
I've heard latest clover may have issues. Try another version or replace CLOVERX64.efi with the one from your working install.

Also it seems like you're not using the 1.3 HaC mini package, so I recommend updating to that.

**Comment by SpookHCK** [comment]
Same behavior with cloverx64.efi v2.5k_r5018
:( The working load uses the same version of clover

**Comment by SpookHCK** [comment]
Same bad behavior with an install of clover v2.5k_r5017

Any other ideas?

**Comment by osy86** [comment]
Maybe reset your EFI variables?

**Comment by SpookHCK** [comment]
^ not sure how to do that?

**Comment by osy86** [comment]
Then nvm that. Can you use verbose boot and capture the panic message before it restarts? Boot with -v and use a slow motion camera (like iPhone) to record the message before it reboots.

**Comment by SpookHCK** [comment]
![IMG_4605](https://user-images.githubusercontent.com/53403738/62013591-f1e08000-b151-11e9-94f0-4b081b1db40c.jpeg)

Looks like a kernel panic...

**Comment by osy86** [comment]
Sorry I wasn’t clear. The message comes before the garbage with the list of loaded modules.

**Comment by SpookHCK** [comment]
[IMG_4606.mov.zip](https://github.com/osy86/HaC-Mini/files/3439729/IMG_4606.mov.zip)

I couldn't isolate the error, so here is a movie.... 

Thank you for looking at this; hopefully it is clear enough

**Comment by SpookHCK** [comment]
[IMG_4609.mov.zip](https://github.com/osy86/HaC-Mini/files/3439738/IMG_4609.mov.zip)

This is slightly better; more in focus. and for the section most relevant to the crash?

**Comment by osy86** [comment]
Hmm I’m guessing you don’t have access to a slow motion camera? Also when you do get into OS X does a pop up about system panic and if you want to report it come up? You can also find the panic message there.

**Comment by osy86** [comment]
1. What version of OSX?
2. Can you reset your BIOS settings and then reconfig it according to the guide?

**Comment by SpookHCK** [comment]
1. 10.14.3
2. I have tried that also. 

My BIOS settings are:
BIOS( Version 0058 ):
﻿Portable Device Charging Mode : OFF
Secure Boot : OFF
Thunderbolt Security Level : Legacy Mode
 
Intel(R) Speed Shift Technology : Disabled
Package Power Limit 1 : 70
Package Power Limit 2 : 80
Package Power Time Window : 128
PCIe ASPM Support : OFF

I have additionally disabled VT-d.

**Comment by osy86** [comment]
Oh that's the issue. Only 10.14.5+ are supported. If you're on < that. Delete the OldRadeonX4000HWLibs.kext from kexts/Other

**Comment by SpookHCK** [comment]
Nice!

That worked!
I guess an upgrade is in my near future!

**Comment by SpookHCK** [comment]
Ok; Combo patch applied; OldRadeonX4000HWlibs re-applied everything works!

Thank you for your help!
