### ISSUE TITLE
Can wifi card be replaced in Frost Canyon NUC10i7FNK?

### ISSUE THREAD

**Issue by mrnags** [osy86/HaC-Mini#200]
Can wifi card be replaced in Frost Canyon NUC10i7FNK?

**Comment by glendonyeo** [comment]
Unfortunately, from the limited information i have currently, front canyon come with onboard wifi adapter

guess have no luck on this, and support of the CPU is a question mark currently

that's the main reason i just get hades canyon although its a bit late

![image](https://user-images.githubusercontent.com/5694951/75456290-492f2300-59b5-11ea-9f03-bc17e4a6d25d.png)

**Comment by osy86** [comment]
Closed for not relating to HaC Mini.
