### ISSUE TITLE
Blank screen on boot after clearing NVRAM on 2.6

### ISSUE THREAD

**Issue by msedek** [osy86/HaC-Mini#201]
Hello. installed 2.6 from 2.5 and worked perfectly, then checking a wifi issue, cleared the nvram and the nuc refuses to boot, reinstaled 2.5 and nothing, I have to boot from USB, copy the EFI folder form the USB wich have the HAC-mini verion 2.2 and it boots but then I dont have the wifi driver, reintall 2.5 or 2.6 again on top of the 2.2 from the copied usb EFI and it just wont boot.

help

**Comment by osy86** [comment]
When you clear NVRAM, you must use the boot picker menu because OC no longer knows what partition to boot to. Please read https://osy.gitbook.io/hac-mini-guide/post-installation/support#getting-into-boot-picker-menu

**Comment by msedek** [comment]
Ok, I cam boot again from there with 2.6 but, how do I Make it so it starts always yo mojave, no alt spamming

**Comment by osy86** [comment]
In System Preferences, go to Startup Disk and select your disk.

**Comment by msedek** [comment]
Worked like a charm thanks
