### ISSUE TITLE
Catalina BootCamp Installation

### ISSUE THREAD

**Issue by glendonyeo** [osy86/HaC-Mini#202]
Seems in macOS Catalina + NUC, i couldn't create Windows 10 USB Installer.

When i try to install windows 10 using bootcamp, boot record will gone, and no bootable device found will show.

I have to boot using usb, reset EFI partition using HackMini.pkg + setup back the startup disk

![image](https://user-images.githubusercontent.com/5694951/75567121-f4121080-5a8b-11ea-8d38-ba1f24267036.png)

**Comment by glacier2018** [comment]
Hi I am having the same problem. Just wonder if you have solved it? When "no protable device found" appear, has to use USB to boot first. After entering OS, you can using clover configurater to mount both your main disk and USB, and copy the Boot folder to your main disk EFI file from USB. But I still don't know how to install Windows 10 using bootcamp. Really hope someone could help.

**Comment by glendonyeo** [comment]
i just install os without bootcamp, and reset nvram to continue boot from opencore

as i having minimal usage of windows (i am using parallel desktop), need to use windows when direct connection to NUC is required, so far this is the issues i have

1. DW1820A sometime not working after reboot from windows to macOS
2. Sometime macOS time will interrupted by windows (this should be common patchable issues of dual boot, just a bit lazy for me currently)

**Comment by osy86** [comment]
Windows breaking boot is a known problem. It's documented in the support page. The boot camp installer issue is an OSX problem.
