### ISSUE TITLE
DW1820A max download bandwidth is 30Mbps

### ISSUE THREAD

**Issue by shoyuf** [osy86/HaC-Mini#203]
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
* Follow **all** the [troubleshooting steps](https://osy.gitbook.io/hac-mini-guide/post-installation/support)
* Check the open issues and make sure it is not already reported
* Delete this section from your report and continue

**Describe the bug**
DW1820A max download bandwidth is 30Mbps, upload bandwidth is normal
When I use DW1820A on Windows 10 ,it's bandwidth is normal
I think it's maybe hardware drivers problem
![截屏2020-03-04上午10 38 14](https://user-images.githubusercontent.com/27998490/75859873-cb946880-5e35-11ea-8028-cc4b227c3d57.png)
![IMG_9315](https://user-images.githubusercontent.com/27998490/75860204-6725d900-5e36-11ea-83a6-63773ce84c04.JPG)

**Expected behavior**
DW1820A max download bandwidth not limit to 30Mbps

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.6
- OSX version [e.g: 10.14.6]: 10.15.3
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung SM961
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: HIKVISION C2000
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 8 GB 2667 MHz DDR4
- Second DIMM model (if installed): 168GB 2667 MHz DDR4
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 1080P
- Any TB3 devices: No
- Any USB devices: No

**Modifications**
No

**Panic log**
No

**Comment by glendonyeo** [comment]
@shoyuf i am using same wireless card, same model, but my speed test result is ok in my hackintosh

![image](https://user-images.githubusercontent.com/5694951/75879111-bdeedb00-5e55-11ea-914d-b7aff9438b22.png)

**Comment by goodbest** [comment]
You can get more information about your wifi by holding option key and left click on your wifi icon.
Can you report the `tx rate`, `country code ` and `Channel`？
(878mbps and #a should be good).


By the way, I think the way you test your wi-fi speed is not very accurate, as it can be affected by your router, your contract speed with ISP, and the test server itself.
Can you show us what is the `normal` speed you test under Windows

**Comment by shoyuf** [comment]
> You can get more information about your wifi by holding option key and left click on your wifi icon.
> Can you report the `tx rate`, `country code ` and `Channel`？
> (878mbps and #a should be good).
> 
> By the way, I think the way you test your wi-fi speed is not very accurate, as it can be affected by your router, your contract speed with ISP, and the test server itself.
> Can you show us what is the `normal` speed you test under Windows

![截屏2020-03-05下午5 15 56](https://user-images.githubusercontent.com/27998490/75966548-82abe500-5f05-11ea-82cb-4c248a9eb922.png)

I test network speed in two places(home and office), the max download bandwidth is 30M

I can take 200Mbps(max ISP bandwidth) under Windows with same WiFi AP

these speed tests all used speedtest.net,other download tools like Thunder(Chinese most popular downloader) has same result.

I also found some same problem in chinese community
[1](http://www.pcbeta.com/archiver/tid-1802172.html)
[2](http://www.pcbeta.com/archiver/tid-1801803.html)

**Comment by shoyuf** [comment]
this question related with 5G channel
