### ISSUE TITLE
CPU frequency fixed at 3.1GHz

### ISSUE THREAD

**Issue by superwiboy** [osy86/HaC-Mini#204]
CPU frequency fixed at 3.1GHz

Maximum frequency should be 4.2GHz

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.6
- OSX version [e.g: 10.14.6]: 10.15.3
- NUC model [e.g: NUC8i7HNK]: NUC8I7HVK6
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung EVO 960 250 GB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: NONE
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 16GB
- Second DIMM model (if installed): 16GB
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 1080
- Any TB3 devices: no
- Any USB devices:

**Comment by crhendo** [comment]
![Power Gadget](https://user-images.githubusercontent.com/56284235/75950785-53de4080-5efe-11ea-87ed-bb2822448dc4.jpg)

Looks OK to me.

**Comment by osy86** [comment]
Where are you seeing this? 4.2 is the boost frequency, you don’t get that always.

**Comment by superwiboy** [comment]
> @superwiboy Where are you seeing this? 4.2 is the boost frequency, you don’t get that always.



> @superwiboy Where are you seeing this? 4.2 is the boost frequency, you don’t get that always.

TKS ，My fault😂
