### ISSUE TITLE
Only boot one OS

### ISSUE THREAD

**Issue by chaoyangnz** [osy86/HaC-Mini#205]
I installed MacOSX following the guide smoothly. Then I install Windows 10 directly to a partition. then I found I can only boot into Windows 10.

I run `bcdedit` in Windows to change the `bootmgr` to OpenCore, but now it only boots to MacOS.

So how can I make two OS bootable and show boot menu when showing bios.

My hardware is NUC Hades Canyon, the model is NUC8i7HVK.

Please help.

**Comment by lmshsqlc** [comment]
This is not a bug. Windows installwe will brutally erase other bootloader. All you have to do is using a external  drive to boot into macOS, and reinstall HaC-Mini.

**Comment by chaoyangnz** [comment]
Hi @lmshsqlc thanks for your reply. I am just going to boot both, not intend to reinstall, as Hac-Mini works well. 
I have little knowledge of UEFI, just wondering if you have a recommended approach to achieve the goal.

**Comment by lmshsqlc** [comment]
You can also try disabling the windows drive/macOS drive in UEFI if you’re using a separate drive to install your windows. However if you already installed them on a single drive, you can enter the EFI shell to manually launch opencore bootloader. That way you’ll be able to boot into macOS, and then reinstall HaC-Mini. 
Reinstalling HaC-Mini will fix the nvram
that windows installer modified for its own exclusive bootmgr.  Actually I don’t know what to do if you don’t install the package again, but this is the simplest way. 
And I found no other way to make both bootmgr and opencore work in one single drive. So the solution is to use opencore to boot windows instead.

**Comment by chaoyangnz** [comment]
Sorry I got a bit confused. Here reinstall Hac-mini, I have to boot in MacOS and install Hack-Mini.dmg , so do I have to patch the MacOS which is running? or just tick ‘boot menu’?

**Comment by lmshsqlc** [comment]
You would like to install the package again, patching the current system. 
And you can do it without the option show boot menu, because with opencore you will be able to select your boot drive just like a real Mac.

**Comment by chaoyangnz** [comment]
@lmshsqlc thanks. it works. but i am going to buy another ssd, which may make things easier.
