### ISSUE TITLE
HaC-Mini installation failed on usb

### ISSUE THREAD

**Issue by bypo** [osy86/HaC-Mini#208]
**Describe the bug**
The installer said An error occurred during installation and the installation failed when I tried to install HacMini to my usb drive.

**Environment:**
Running OSX version: 10.12.6
Target drive OSX version: 10.15.3
HaC Mini installer version: 2.6

**Additional context**
![Screen Shot 2020-03-08 at 20 29 40](https://user-images.githubusercontent.com/14150001/76169833-8dbc7a80-617c-11ea-82bd-c3aecc712036.png)

**Logs**
Please attach `/var/log/install.log`
[install.log](https://github.com/osy86/HaC-Mini/files/4303773/install.log)

**Comment by bypo** [comment]
Same issue while doing this on a MacOS X 10.14.6

**Comment by osy86** [comment]
Please post the install.log from 10.14.6

**Comment by bypo** [comment]
[install.log](https://github.com/osy86/HaC-Mini/files/4303982/install.log)
Sorry, it is a 10.15.3, not 10.14.6

**Comment by bypo** [comment]
Just tried on a clean install of a 10.15.3 and it works without problem.
