### ISSUE TITLE
Have anyone installed the "BOOTCAMP UPDATE"？

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#210]
![{D2F2A1C1-13D2-42FF-A1C8-B0C2D8BB7DE3} png](https://user-images.githubusercontent.com/38860226/76727035-d7fdb700-678d-11ea-8c79-6825f672e02b.jpg)

Shall we install this update? Will it add any support for Thunderbolt that uses the "Native" scheme?

**Comment by osy86** [comment]
It doesn't do anything. It will uninstall your AMD drivers so you will have to re-install it. But it won't add any support.
