### ISSUE TITLE
EFI boot not working - Main Drive only

### ISSUE THREAD

**Issue by hongkongkiwi** [osy86/HaC-Mini#214]
Hi there,

I've installed the latest version of HaC Mini but the only way I can boot is by showing the boot menu then selecting "Main Drive".

If I select EFI it just goes black for a second then jumps back to the boot menu.

Any idea what causes this? Any special settings to enable?

**Comment by osy86** [comment]
https://osy.gitbook.io/hac-mini-guide/post-installation/support#black-screen-after-post-when-booting-up-or-after-selecting-boot-drive
