### ISSUE TITLE
MacOS Update to 10.15.4

### ISSUE THREAD

**Issue by Anjiro81** [osy86/HaC-Mini#215]
Hi all,
Is it safe updating to 10.15.4? Has anyone tried? Will system essential kext be discarded?

Thanks for any advice and thanks @osy86 for all the hard work!

**Comment by shian15810** [comment]
During upgrading, I've seen some cmos checksum error logs from bios. It just appeared for like 1 to 2 seconds and disappeared. It ended up upgrading successfully though.

When I checked in bios after upgrading, I can see there are 3 occurrences of cmos checksum error.

**Comment by goodbest** [comment]
> During upgrading, I've seen some cmos checksum error logs from bios. It just appeared for like 1 to 2 seconds and disappeared. It ended up upgrading successfully though.
> 
> When I checked in bios after upgrading, I can see there are 3 occurrences of cmos checksum error.
> 
> Other than that, I would say the whole upgrade process is pretty smooth.
> 
> Anyway, it is out of my knowledge to know why the upgrading process triggers cmos checksum error from bios. If anyone know, please let me know. Just curious, thanks!


Maybe cmos checksum error is related with sleep/wakeup(boot) during upgrading?
It's not big issue anyway.

https://github.com/EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi/issues/26
https://github.com/daliansky/OC-little/tree/master/15-CMOS%E7%9B%B8%E5%85%B3

**Comment by Anjiro81** [comment]
I can confirm that the update went smoothly. Thanks all!
