### ISSUE TITLE
Getting 'extras' working with the Ultrafine 4k over USB-C

### ISSUE THREAD

**Issue by hepto** [osy86/HaC-Mini#217]
I have recently acquired an Ultrafine 4k (24 in) and trying to us it with my Mac-Mini.  (HVK model.)

Display itself works fine - I get the right resolution, everything looks great!  But ...

What isn't working is the in built audio, the USB-C hub, and the integration with macOS for brightness (ambient and keyboard controls).  The 'extras'.

Now, I only have a USB-C cable so initially I thought that might be the cause and I should instead use a Thunderbolt cable, but I tried it on my MacBook with the same cable and everything worked as expected - so clearly it is possible to work over USB-C cable.  (I'd rather not have to buy a Thunderbolt cable as they are quite expensive at longer lengths.)

So given that I know it is possible - now of course I want to make it work!  Has anyone else got this model and the extras are working for them?  Are you using Thunderbolt or USB-C?

One thing I did see was that on my HaC-Mini it says that `No Thunderbolt drivers are loaded`, because I don't have any Thunderbolt devices, but on my MacBook it showed the Ultrafine on the Thunderbolt bus, even though I was using a USB-C cable.

So my current line of investigation is whether I am meant to use a Thunderbolt cable OR whether I need to/should run the Thunderbolt patcher and see if that works.  I don't have a Thunderbolt cable to test, and I can't work out the technical logic of why it appears on the Thunderbolt bus when using a USB-C cable, but it is a difference between the MacBook and the HaC-Mini.

My main question for now is that I'm happy to run the patcher as a test, but if it doesn't work I'd probably want to revert the Thunderbolt controller back to the normal/default state - is that possible?  (Given that I have no Thunderbolt devices I'd rather leave it as standard so I don't have to worry about it in the future if selling on to a Windows user.)

Thanks all.

**Comment by osy86** [comment]
You need to install hac mini with native thunderbolt and do the patching. Follow the guide.

**Comment by hepto** [comment]
Ok thanks - happy to do that but can I revert the patch later on?

**Comment by osy86** [comment]
Yes but if something goes wrong in the patching process you do need to use a flasher to recover.

**Comment by hepto** [comment]
Ok thanks will give it a shot.  Maybe I should have just asked whether the patch could be reverted rather than all the preamble! :)

**Comment by hepto** [comment]
I know this is an old Issue but I have an update, didn't want to start a new one unless there is a better place to post - please advise.

Anyway, I now have the 'extras' in this monitor working with the original Thunderbolt firmware.

I reverted the patch as I reboot into Windows more regularly now, and the 'black screen on boot' issue was getting frustrating.  During a Windows Update, it set the default boot drive back to Windows, but as the screen wouldn't come on I had no way of getting into F2 BIOS, F10 boot screen or OpenCore to set it back to boot to macOS.  The power off, remove power 'trick' didn't work either - I had to borrow an HDMI monitor to get it back to macOS where the monitor then sprung to life.

So went back to the stock TB firmware and so far the screen has come back on every reboot.  The monitor works fine in Windows and actually if you use the Thunderbolt Control Centre to 'approve' the device, then under Windows the speakers and hub will also work.  So I couldn't understand why they wouldn't in macOS - and as the monitor is also meant to work over USB-C (DP) (for iPad support), I thought that it should work irrespective of Thunderbolt - so I disabled the Thunderbolt controller in BIOS entirely and sure enough the screen continued to work as expected (over DP) - but still no extras.

Anyway frankly at this point I was being a terrible troubleshooter and just flicking options on and off here and there to see if I could get something to change - then all of a sudden they appeared in macOS! The speakers, the USB hub, the ambient light sensor - all working!  Yet System Info shows the Thunderbolt drivers not loaded - so I presume this is all over USB-C now (DP++)

In an effort to work out what change made it work, I started going backwards, until I had everything back to the defaults - default BIOS (including Unique ID in Thunderbolt security), default Mac-mini install - and the extras still appear.  And on every reboot so far the monitor has powered on.  Brilliant!

So, apologies but I don't *really* know what solved it - but I have a strong suspicion that it is related to booting into Windows and using Thunderbolt Control Centre to accept and initialise the monitor, then WARM booting back into macOS, so that authentication is still active on the Thunderbolt chipset so that macOS now sees it, albeit over USB-C somehow.

The reason I say that is because if I unplug the monitor in macOS and replug it - the extras disappear.  But if I then reboot to Windows so that the Windows Thunderbolt driver reinitialises the monitor (over Thunderbolt), then when I go back into macOS everything works fine.

So still a bit of a pain in that if the monitor gets disconnected it requires a trip via Windows to get it all working, but as I very rarely unplug my monitor (now that the boot screen is constantly working), this is a minor annoyance.

@osy86 out of interest, the way I reverted the patch was to use the Intel provided Thunderbolt Firmware updater rather than to run the patcher tool you provided.  Everything seems OK so is that considered a 'good' restore?  I tried to re-run the Intel tool to double check the version numbers, but for some reason it won't run again.
