### ISSUE TITLE
Issues after 10.15.4 update-Netflix does not run on safari.

### ISSUE THREAD

**Issue by FANTOME-HISTORY** [osy86/HaC-Mini#219]
Netflix does not run on safari.
But on Chrome, Netflix is running normally.

**Comment by osy86** [comment]
Probably need to update WG.

**Comment by osy86** [comment]
Please test https://github.com/osy86/HaC-Mini/pull/222

**Comment by Anjiro81** [comment]
@shian15810 and @osy86: #222 is not solving the Netflix issue with Safari #219.

**Comment by shian15810** [comment]
As a note, updating WhateverGreen to the latest version is not solving this issue.
