### ISSUE TITLE
请问怎么安装你最新上传的基于0.5.6 oc的安装文件 没有发现pkg文件

### ISSUE THREAD

**Issue by y04551b** [osy86/HaC-Mini#223]
**Describe the bug**
A clear and concise description of what the bug is. What is the installation destination (boot drive, USB installer drive, other drive)? What installation options are selected?

**Expected behavior**

**Environment:**
 - Running OSX version: 
 - Target drive OSX version: 
 - HaC Mini installer version: 

**Additional context**

**Logs**
Please attach `/var/log/install.log`

**Comment by KrisCris** [comment]
You can find it on page `https://github.com/osy86/HaC-Mini/actions/runs/64139663`.

你可以在上面那个链接里下载。。有个叫installer的artifacts。。。。（吐槽一下，你这个issue里面自动填写的东西。。hmmm。。。）

**Comment by osy86** [comment]
Updated release to 2.7
