### ISSUE TITLE
shiki-id=Mac-BE088AF8C5EB4FA2 这个是干什么的参数

### ISSUE THREAD

**Issue by y04551b** [osy86/HaC-Mini#224]
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
* Follow **all** the [troubleshooting steps](https://osy.gitbook.io/hac-mini-guide/post-installation/support)
* Check the open issues and make sure it is not already reported
* Delete this section from your report and continue

**Describe the bug**

**Expected behavior**

**Configuration**
- HaC Mini version [e.g: 2.0]: 
- OSX version [e.g: 10.14.6]: 
- NUC model [e.g: NUC8i7HNK]: 
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 
- Any TB3 devices: 
- Any USB devices: 

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by osy86** [comment]
Enabling codec decode.

**Comment by KrisCris** [comment]
> Enabling codec decode.

Excuse me... Are there any benefits using MacMini8,1 than iMac18,3? Because I found the codec is enabled by default in iMac18,3 without Shiki things in boot-args, and iMac18,3 supports using headless iGPU.

**Comment by osy86** [comment]
Not all ports work with 18,3

**Comment by KrisCris** [comment]
> Not all ports work with 18,3

Hmm, what kind of ports are you talking about, I haven't found anything wrong yet.

**Comment by osy86** [comment]
I can’t get USB-C DP working with that model.

**Comment by KrisCris** [comment]
> I can’t get USB-C DP working with that model.

That's interesting, mine works.
