### ISSUE TITLE
How to install default Windows TB3 firmware?

### ISSUE THREAD

**Issue by DreGilley** [osy86/HaC-Mini#225]
Had to revert my HaC NUC back to Windows 10.  Tried installing the default NUC TB3 firmware and it says no TB3 service is present.  Nothing plugged in to the TB3 port is receiving power or working.

How do I re-install the default Intel TB3 firmware?

**Comment by osy86** [comment]
You need to run Thunderbolt Patcher and check uninstall.

**Comment by bowes332frank** [comment]
After uninstall @76 @70 @7E

**Comment by bowes332frank** [comment]
Facing same situation.
After uninstall @76 @70 @7e Devices--YES,I click uninstall then flash for each "device".
Reboot to win10 1909, install Intel's ThunderBolt Legacy Driver(Which has an operating GUI).
insulation succeed, but when you open "ThunderBolt Software" ,it report an error about the software was outdate and can be delated.
Which means I cannot run Intel's firmware update tool.
