### ISSUE TITLE
boot camp install win10, can not boot

### ISSUE THREAD

**Issue by conphi** [osy86/HaC-Mini#226]
When boot camp finished, it rebooted automatically.
Then pop up this message "a bootable device has not been detected".
Can't boot Opencore.
I try to use a usb to save this(the usb used to be winPE), bios can Not find the usb device even reset the default bios configuration.
The message "a bootable device has not been detected" still exists.

**Comment by osy86** [comment]
https://osy.gitbook.io/hac-mini-guide/post-installation/support#only-boot-entry-is-windows-boot-manager

**Comment by darkread** [comment]
@conphi would you solve this problem? i do it follow what  @osy86 commented,  reset the NVRAM  on the boot menu, but when i pull out the usb disk,reboot it, the message "a bootable device has not been detected" came back.

**Comment by osy86** [comment]
Run hac mini package installer.

**Comment by darkread** [comment]
> Run hac mini package installer.

I deal with this problem by this way, but macos boot fixed,but boot camp intalling win10 Interrupted and the bootcamp partition is built.
I made another attempt to installing win10 by offical iso usb stick, then boot by an external media with OC installed to run hac mini package installer. But the reality is that installing win10 successful,   booting by an external media with OC failed ,to the opposite it booting to win10.
I have to use win10 iso usb stick, boot to winpe and delete the all partition ,and reinstall macos.

**Comment by darkread** [comment]
I  have only one m.2 hd, Intel 760p 1T ssd. win10 ver 1909, macos catalina download from app store yestoday.

**Comment by lmshsqlc** [comment]
The correct way to do a single drive dual boot is: 
1. Install MacOS using external drive with opencore. 
2. Boot into internal MacOS using external drive with opencore. 
3. Install HaC Mini on internal drive. 
4. Boot into windows installer on external drive  using internal opencore bootloader. 
5. Install windows and use internal opencore to boot both of them.

**Comment by darkread** [comment]
> The correct way to do a single drive dual boot is:
> 
> 1. Install MacOS using external drive with opencore.
> 2. Boot into internal MacOS using external drive with opencore.
> 3. Install HaC Mini on internal drive.
> 4. Boot into windows installer on external drive  using internal opencore bootloader.
> 5. Install windows and use internal opencore to boot both of them.

step 4\5，would you show me a guide page ,please？

**Comment by lmshsqlc** [comment]
There’s no guide. Opencore scans for boot entries including external ones. So use it to boot your windows installer drive.

**Comment by conphi** [comment]
> @conphi would you solve this problem? i do it follow what @osy86 commented, reset the NVRAM on the boot menu, but when i pull out the usb disk,reboot it, the message "a bootable device has not been detected" came back.

@darkread You need to open the case and remove the **BIOS Security Jumper** (yellow) to reset all BIOS settings. (my bios version 0059)

I use the following steps to recover the problem( "a bootable device has not been detected" )
BIOS Update and Recovery Instructions for Intel® NUC

1. Use a USB flash drive then get Bios file HN0059.bio 
2. Disconnect the power adapter and remove the bottom cover from your NUC. 
3. Remove the yellow security jumper. (You can check the TPS to locate it Page 45 figure H ) 
4. Insert the USB with the HN0059.bio file. 
5. Reconnect the power adapter and power ON the NUC. Wait 30 sec - 2min. The Recovery process will start automatically and will end after 2 -5 minutes. 
6. When bios recovery completed, switch the power OFF, remove the power adapter and replace the Security Jumper (pins 1-2) 
7. Power your NUC ON. 

By the way:
I am still struggling to find a way install dual win10 and MacOs.
