### ISSUE TITLE
I can't use sidecar with iPad.

### ISSUE THREAD

**Issue by linlinsunny** [osy86/HaC-Mini#229]
Thanks All your doing.

and I wish you test Sidecar , and find out how make it work.

**Comment by lmshsqlc** [comment]
It works.

**Comment by osy86** [comment]
Follow apple’s support documents. Make sure you’re on the same iCloud account.

**Comment by lmshsqlc** [comment]
Checkout this Apple support link. 
https://support.apple.com/zh-cn/HT210380
