### ISSUE TITLE
Anyone, who tested eGPUs with the NUCs?

### ISSUE THREAD

**Issue by philffm** [osy86/HaC-Mini#23]
Hi there!

Thank you in first place for the well documented project! I tried to apply your given approach on TB3 hot plug to my setup (Lenovo T480S). Finally, hotplugging with my eGPU case (Charging, internal SSD, Ethernet, GPU detected) works reliable (after boot, after standby - all circumstances). This was never so reliable before and thus is a already a huge milestone! 

However, the actual GPU is not really spinning up, but shows up for a short time in IORegistryExplorer - and so does the eGPU Icon in the top menu.

**_Did someone of you already try to get an eGPU running with the NUC?_** 

Because if it works with the NUC, it should be easy to apply to the ThinkPads as well. Otherwise I'm happy to share the IOREG dumps of a working MacBook Pro vs. my device. 

At least there is evidence, that it works in general because if you leave out the Thunderbolt aml and have the eGPU plugged while booting, the whole thing is detected as PCI hub and GPU runs as "internal" - but once pulled, the computer crashes.

Best, Phil

**Comment by osy86** [comment]
Unfortunately I don’t have an egpu to test with. I’ll leave this open for anyone else to comment.

**Comment by osy86** [comment]
Tracking in #44
