### ISSUE TITLE
Support > 48 kHz audio out?

### ISSUE THREAD

**Issue by hepto** [osy86/HaC-Mini#230]
Would it be possible to support greater than 48 kHz audio out over the analog ports?

According to pg 25 of the [Technical Product Specification](https://www.intel.com/content/dam/support/us/en/documents/mini-pcs/nuc-kits/NUC8i7HVK_TechProdSpec.pdf), 96 kHz and 192 kHz are also supported, but in Audio MIDI Setup the maximum is 48.0 kHz.

Is this a limitation of the HDA fix or might it be possible?

<img width="743" alt="image" src="https://user-images.githubusercontent.com/4923370/78228541-bf4c0b80-74c6-11ea-9e55-dcd24961e41a.png">

**Comment by osy86** [comment]
It’s probably something you can patch with AppleALC. You can confirm it works in windows?

**Comment by hepto** [comment]
Good shout to check Windows - just looked and that also seems to top out at 24/48.  Double checked the drivers and I am using the latest official ones from Intel.

Oh well, shame the capability does not match the documentation - we won't know which side is wrong!  Maybe it's possible but I'm really capable or inclined to try and make it work if there isn't a benchmark to compare against. 😞

**Comment by osy86** [comment]
Yeah, I don't think there's anything we can do if even Windows doesn't support it.

**Comment by molexey** [comment]
Looks like this bug has been fixed.
![Screenshot 2020-11-13 at 23 42 20](https://user-images.githubusercontent.com/25736069/99114793-d5987900-260a-11eb-908d-e1a65d78e56b.png)

The BIOS Version 0064 Update Release Notes:
"Fixed with analog audio output sample rate support."
