### ISSUE TITLE
v2.7 Installer "Installation" Step Failing 

### ISSUE THREAD

**Issue by StanKatsyuk** [osy86/HaC-Mini#231]
**Describe the bug**
When attempting to install onto a USB installer drive using HaCMini, upon reaching the installation step, I get a "The installation failed" alert.

Options selected: 
-All Default except for Destination Selected which is: `Install macOS Catalina` as defined by the [osy guide](https://osy.gitbook.io/hac-mini-guide/installation-guide/installation). 

**Expected behavior**
The installer completes without error

**Environment:**
 - Running OSX version: 10.14.6
 - Target drive OSX version: 10.15.4
 - HaC Mini installer version: 2.7

**Additional context**
If I use v2.1 of the installer, it succeeds but obviously that won't work for my target OS version. 
**Logs**
[install.log](https://github.com/osy86/HaC-Mini/files/4432619/install.log)

**Comment by osy86** [comment]
```
installd[12770]: ./preinstall: Creating /Volumes/Install macOS Catalina/private/tmp
2020-04-04 14:56:07-07 Stans-MBP installd[12770]: ./preinstall: Mounting ESP to /Volumes/Install macOS Catalina/private/tmp/EFIROOTDIR
2020-04-04 14:56:07-07 Stans-MBP installd[12770]: ./preinstall: Partition is FDisk_partition_scheme, not GUID_partition_scheme!
```

Make sure your installer usb is formatted GUID as explained in the guide.

**Comment by StanKatsyuk** [comment]
Thanks @osy86 I didin't realize I hadn't done that correctly. 

Can/Should I open a PR for an amendment to the readme to explain this process clearly for other novice Hackintoshers like me?

This article helped me: https://www.macobserver.com/tips/quick-tip/how-to-format-drive-guid/

**Comment by osy86** [comment]
I mean I don't think that article explains it any better than https://osy.gitbook.io/hac-mini-guide/installation-guide/installation except it just has images.
