### ISSUE TITLE
Intel Wi-Fi

### ISSUE THREAD

**Issue by mr-vito** [osy86/HaC-Mini#233]
I thought I would post this here, as it might be worth implementing either kexts in the future:

- https://github.com/AppleIntelWifi/adapter/
- https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330

Some Intel cards are not yet fully compatible, although this is likely to change as development seems consistent.

Partially/Fully working (although not yet stable):
AC-3165, AC-7265, AC-8265

Source: https://www.tonymacx86.com/threads/success-working-intel-wifi-drivers-for-7265ac-on-catalina.292207/ (Nobody likes Tonymac, yet useful comments on there!)

Let me know your thoughts or whether you have tested either kexts.

**Comment by itdawn** [comment]
You can refer to this [zxystd/itlwm](https://github.com/zxystd/itlwm).

**Comment by goodbest** [comment]
You should also refer to the bluetooth kext.
https://github.com/zxystd/IntelBluetoothFirmware

**Comment by chirimar** [comment]
This would be amazing!

**Comment by Malumen** [comment]
> You should also refer to the bluetooth kext.
> https://github.com/zxystd/IntelBluetoothFirmware

I also agree that it would be awesome if Osy86 could include an option for the HaC installer to include the IntelBluetooth Kext for those of us that don't need WiFi and just want BlueTooth with the stock intel chipsets.

**Comment by osy86** [comment]
Sure I can include any kext. Just let me know if there's any additional config that's needed (boot-args, etc).

**Comment by Malumen** [comment]
> Sure I can include any kext. Just let me know if there's any additional config that's needed (boot-args, etc).

Hi Osy!! Thank you for taking interest. There **does not** _appear_ to be any special boot arguments needed. If I may suggest for the installer .pkg you made: if it can be either-or for the M.2 section: DW1820A support OR IntelBluetooth support.

For the .pkg description on that section:
Only the following Intel WiFi M.2 cards are supported for Bluetooth injection:
- Intel Dual Band Wireless-AC 3165
- Intel Dual Band Wireless-AC 3168
- Intel Dual Band Wireless-AC 726x
- Intel Dual Band Wireless-AC 8265
- Intel Dual Band Wireless-AC 926x
- Intel Dual Band Wireless-AC 9560
- Intel Wi-Fi 6 AX200
- Intel Wi-Fi 6 AX201

or just

3165, 3168, 726x, 8265, 926x, 9560, AX200, AX201

**Comment by lmshsqlc** [comment]
I can’t learn how to use git again. But I came up with some phrases might be useful for future development: 
———on Update log 
Added some Intel Wireless Network Card support (Not Stable, Use at your own risk) 
添加了一些Intel无线网卡支持（不稳定，请酌情使用）


———Might be used in update log
Intel Wireless Network Card Support
Intel无线网卡支持


———wireless kext option title
Wireless Network and Bluetooth support
无线网卡及蓝牙支持


———wireless kext option explanation 
Select this option to install specific kexts to support 3rd party network cards. If you are using Apple Airport Card, you don’t have to select this option. 
选中此选项以获得对应的第三方无线网卡支持。如果你使用的是Apple Airport无线网卡，那么你不需要使用此选项。


———Intel option title
Intel
英特尔


———Intel option explanation
Add kext support for original Intel Dual Band Wireless-AC 8265. It also adds support for some other Intel wireless network cards including Intel WiFi 6 network card, checkout the HaC-Mini gitbook for more information. 
添加对原机Intel Wireless AC 8265的无线网络支持。该选项还会提供对其他Intel无线网卡，包括Intel WiFi 6无线网卡的支持。前往HaC-Mini的Gitbook获取更多信息。


———Dell dw1820a option title
Dell Wireless DW1820A
戴尔DW1820A


———dell dw1820a option explaination
Add kext support for DW1820A network card. 
添加对DW1820A的支持。

**Comment by zealucard** [comment]
Hello everybody,

I don't know if it could help, but I use the IntelBluetoothKext for one week now on my laptop thinkpad with Intel DW8265ac and it works very well, and it is stable. I just have to disable then enable bluetooth after sleep of the computer.

About he intel wifi driver, it works well for Internet but, when I want to download a file from my NAS, it is completely unstable and it stops working after 30s. Also, I must enter the SSID/pwd information into the info.plist file included in the kext package.

I don't need the WiFi on my NUC, but I need bluetooth, and it could be nice if you could include this kext into your intall. I just copied the kext package into my CLOVER/drivers/Other folder and it works. How can I do it with OC ?

Thank you for your work !

**Comment by goodbest** [comment]
@zealucard 
I suppose the intel BT & wifi kexts are still in experimental status, so maybe it's not the right time to include them in the installer.

For loading kexts in OpenCore, you should put the kexts in `EFI\OC\Kexts`, and then edit the `EFI\OC\config.plist` file to load the kext. You can take the existing kexts loading in `Kernel->Add`  as examples.

**Comment by zealucard** [comment]
@goodbest 
You're right, the wifi driver is clearly not stable for now, but the bluetooth driver is probably stable enough.

So, I downloaded the kext files from here [IntelBluetoothFirmware](https://github.com/zxystd/IntelBluetoothFirmware), I copied the files into EFI\OC\Kexts folder, and I added this into config.plist file :
`			<dict>`
`				<key>BundlePath</key>`
`				<string>IntelBluetoothFirmware.kext</string>`
`				<key>Enabled</key>`
`				<true/>`
`				<key>ExecutablePath</key>`
`				<string>Contents/MacOS/IntelBluetoothFirmware</string>`
`				<key>PlistPath</key>`
`				<string>Contents/Info.plist</string>`
`			</dict>`
`			<dict>`
`				<key>BundlePath</key>`
`				<string>IntelBluetoothInjector.kext</string>`
`				<key>Enabled</key>`
`				<true/>`
`				<key>PlistPath</key>`
`				<string>Contents/Info.plist</string>`
`			</dict>`

Now, bluetooth is working very well, and I can use my wireless headset !

Thank you for the tips.

**Comment by osy86** [comment]
Please test https://github.com/osy86/HaC-Mini/suites/646220359/artifacts/5470857

**Comment by chirimar** [comment]
I just tested this build. Re-installed the Intel chip that came with the Nuc and rebooted twice.

-  BT can be switched on for me. 
- Doesn't find any new devices till the BT device is very close to the machine. 
- Somehow managed to get my Airpods Pro to show up.
- But connection drops every 2-3 seconds.

Maybe this is something to do with my machine or if I reinstalled the card and the antennas incorrectly.

**Comment by osy86** [comment]
Seems like you didn’t attach the antennas correctly. Make sure they clicked in place. It might take a little bit of pressure. Once they’re in it actually takes some force to remove it again.

**Comment by chirimar** [comment]
Oh ok. Will do that today then.

**Comment by chirimar** [comment]
Sorry it took me a week to get to this. 
So, @osy86 was right. One of the antennas had come off. Put it back and also put on some electrical tape to hold them in place and they work!
Tested with iPhone and Airpods Pro!
