### ISSUE TITLE
DP display output not coming on

### ISSUE THREAD

**Issue by esulat** [osy86/HaC-Mini#236]
After installation, about a month ago, I switched the output to miniDP rather than HDMI, it works for a while.  Now, it won't boot to miniDP even though the LED Cinema Display is plug-in to it.  I have to drag another display plug it in one of the HDMI output then power cycle the miniDP port then it will come up.  Though, sometimes it works and it will come up on miniDP.
Is there a way to default the output to one of the miniDP port where the Cinema Display is plug-in to?
Or is it an issue with the monitor?

**Configuration**
- HaC Mini version: 2.0 
- OSX version: 10.15.5
- NUC model: NUC8i7HVK 
- Boot SSD model and protocol: Addlink S70 2TB, NVME
- First DIMM model: Crucial 8GB 
- Second DIMM model: Crucial 8GB 
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 1444p
- Any TB3 devices: 
- Any USB devices: Keyboard/Mouse combo - logitech k500
- Upgraded BCM94360NG

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

Updated to OpenCore 0.5.7

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by KrisCris** [comment]
> * OSX version: 10.5.5

Hmmm, seriously?

**Comment by esulat** [comment]
correction - 10.15.5

**Comment by osy86** [comment]
I've been using a mDP to DP adapter on my display for a few days now and have not run into this issue.
