### ISSUE TITLE
Cannot boot windows 10 via OC

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#239]
**Describe the bug**
I cannot figure out why but after I received a exchanged NUC8i7HVK from Intel, the OC just doesn't boot windows anymore, even the windows installer.

When I boot USB Windows 10 Installer using OC, it ends up posting an error, or simply restart.
![IMG_20200419_231432](https://user-images.githubusercontent.com/38860226/79758795-70202a80-8350-11ea-9979-2c6d2cd7aeac.jpg)

If I use F10 to pick bootable device and install, after I set bootloader to OC by executing
`bcdedit /set '{bootmgr}' path \EFI\OC\OpenCore.efi`,
the OC still failed to boot windows, it's less than 3 sec did the windows 10 stuck and restart. 

However, the Windows 10 installed in last NUC worked fine in this machine until I upgraded BIOS to 0059, after which it refused to boot and ran into blue screen immediately after being picked, reporting ACPI_BIOS_ERROR, and no luck after downgrading.

**Expected behavior**
I think it should be able to boot windows 10 without much pain, as my last NUC did. On my last NUC, I simply let OC to boot Windows installer and install and it worked fine.

**Configuration**
- HaC Mini version : https://github.com/osy86/HaC-Mini/actions/runs/42725807
- OSX version : 10.15.3
- NUC model : NUC8i7HVK
- Boot SSD model and protocol : NVME 1TB, **MacOS**
- Second SSD model and protocol : SATA 512GB, **Windows**
- First DIMM model : Kingston 2666 16GB
- Display port(s) used : MiniDP, USB-C
- Display resolution(s) : 2K, 4K
- Any TB3 devices: HP TB3 DOCK
- Any USB devices: DIY Keyboard, Logitech G903

**Modifications**
No

**Panic log**
Above

**Comment by osy86** [comment]
I don’t think this is related to OC. Does the USB work on another machine? According to microsoft the error code means corrupted files.

**Comment by KrisCris** [comment]
F10->USB UEFI, it works. But in OC, NO.

**Comment by osy86** [comment]
This feels like an OC issue to me. Can you manually update OC for the USB and see if that helps? You might have to manually update the config.plist as well.

**Comment by osy86** [comment]
This feels like an OC issue to me. Can you manually update OC for the USB and see if that helps? You might have to manually update the config.plist as well.

**Comment by KrisCris** [comment]
> This feels like an OC issue to me. Can you manually update OC for the USB and see if that helps? You might have to manually update the config.plist as well.

I think I kinda fixed the problem by erase all my disks and reinstalled the system, which is tough but worked. But to install windows 10 still I have to boot the installer via F10 otherwise it ended up showing the same error message.

BTW, when booting windows via OC, NUC is recognized as a MAC MINI so that some drivers for NUC is not available at this point, like the IGPU.
