### ISSUE TITLE
Not a bug report, but a thunderbolt firmware updater question

### ISSUE THREAD

**Issue by alikaylan** [osy86/HaC-Mini#241]
The Thunderbolt firmware updater is designed to work on TPS65982 chip with Alpine Ridge JHL6540 based on my reverse lookup based on the NUCs used. Would it also work on a non-NUC (ASROCK Fatal1ty z270) also with TPS65982 but instead with Alpine Ridge JHL6240? Thank you so much.

**Comment by osy86** [comment]
https://github.com/osy86/ThunderboltPatcher has various documents on how the patch process works. If you’re running v33 then maybe you’ll get lucky and all the patches will work. Otherwise you may have to change some patches. The patcher will tell you if any patch is not compatible.
