### ISSUE TITLE
Catalina 10.15.4 supplemental update

### ISSUE THREAD

**Issue by dougdalton** [osy86/HaC-Mini#242]
**Describe the bug**

install the supplemental update and it works

**Expected behavior**

after installing the computer reboots the hangs at the apple logo and no progress bar ever appears,  the os has to be reinstalled

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.7
- OSX version [e.g: 10.14.6]: 10.15.4
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung SSD 970 PRO 1TB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Corsair CMSX32GX4M2A2400C16 Vengeance 32GB
 Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 
- Any TB3 devices: 
- Any USB devices: 

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by HorstBrack75** [comment]
You need to enable OC boot picker and make sure to select MacOS installer upon every reboot (there are several reboots) until the MacOS installer entry disappears.

**Comment by osy86** [comment]
I think this is an OSX problem unfortunately. It is hard to reproduce.

**Comment by dougdalton** [comment]
how do I enable the OC boot picker?

**Comment by osy86** [comment]
https://osy.gitbook.io/hac-mini-guide/post-installation/support#getting-into-boot-picker-menu

**Comment by dougdalton** [comment]
After doing as stated above with the OS picker,  It still hangs at the apple screen, as before immediately after boot,  I can get back into the os picker,  I have also removed the "My Passport" drive and all other connected devices. with no success. 

Is there a way to fix or recover from this?

![IMG_5561](https://user-images.githubusercontent.com/5828863/80642385-3f5c8700-8a1b-11ea-8b32-2d99b54a2f15.jpg)
