### ISSUE TITLE
Plug in Android phone, there is a chance to cause downtime

### ISSUE THREAD

**Issue by lwlbeng** [osy86/HaC-Mini#244]
Plug in Android phone, there is a chance to cause downtime

**Comment by lwlbeng** [comment]
macos :10.15.4
Hac-Mini:v2.7

**Comment by goodbest** [comment]
What do you mean examtly for the `downtime` ?

Sudden shutdown of the Nuc, or sudden reboot, or Nuc is no-response for a (un)certain time?
Or the Android phone is no-response?

Meanwhile, which port in Nuc do you plug in? Have you tried other ports?
The front USB-A, front yellow charing, front USB3, or the rear USB-A, rear Thunderbolt 3?

**Comment by osy86** [comment]
Is the problem on the phone or on the NUC?

**Comment by lwlbeng** [comment]
on the NUC

usb-a, Thunderbolt 3, after not plugging in the phone for a while, then plug in the phone, nuc will be stuck

**Comment by lwlbeng** [comment]
> 您对这个词的确切含义是什么`downtime`？
> 
> Nuc突然关闭，或突然重启，或者Nuc在（不确定的）时间内无响应？
> 还是Android手机没有响应？
> 
> 同时，您插入Nuc中的哪个端口？您是否尝试过其他端口？
> 正面USB-A，正面黄色充电，正面USB-C或背面USB-A，背面Thunderbolt 3？

sorry，Because my english is poor
