### ISSUE TITLE
Can not boot, from MacOS reboot function

### ISSUE THREAD

**Issue by kiddtam** [osy86/HaC-Mini#245]
- HaC Mini version [e.g: 2.0]: 2.7
- OSX version [e.g: 10.14.6]: 10.15.4
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: SM961 512G
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: SM961 512G
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: SAMSUNG DDR4-2667 16GB
- Second DIMM model (if installed): SAMSUNG DDR4-2667 16GB
- Display port(s) used [e.g: USB-C, mini DP]: miniDP - DP
- Display resolution(s) [e.g: 4K, 5K]: 4K, simulate 5K HiDPI 2560 x 1440
- Any TB3 devices: No
- Any USB devices: 

Press Reboot button from MacOS, it shutdown, and always will stop in NUC logo screen. However, it goes good if I boot it from the power off status.

**Comment by HorstBrack75** [comment]
What startup disk did you select in MacOS system preferences?

**Comment by osy86** [comment]
You need to reset NVRAM https://osy.gitbook.io/hac-mini-guide/post-installation/support#reset-nvram and then re-select startup disk.
