### ISSUE TITLE
Bootcamp install 

### ISSUE THREAD

**Issue by dapostman** [osy86/HaC-Mini#248]
Initial setup worked perfectly.

Decided to go to dual boot via bootcamp; I've got the license with the machine, so...

Fired up the bootcamp setup assistant. It offers only a choice of prompting for the .iso file, no build a USB option...?

**Comment by osy86** [comment]
This is not a HaC mini issue. You can find guides for Boot Camp online.

**Comment by dapostman** [comment]
I do understand…just pointing out that the guide is dated.

Thanks for all of your hard work!

jp
