### ISSUE TITLE
Fixed boot speed sleep wakeup speed.

### ISSUE THREAD

**Issue by a583679361** [osy86/HaC-Mini#25]
This configuration file is fixed, boot speed, sleep wake-up speed, you can refer to[https://drive.google.com/drive/folders/1sMtr5KddHxEAlrwcclYxpVoh9ZD4lvHM](url)

**Comment by osy86** [comment]
I cannot access the file.

**Comment by a583679361** [comment]
The link has been deleted, there are new ones here.
https://drive.google.com/drive/folders/1sMtr5KddHxEAlrwcclYxpVoh9ZD4lvHM 



------------------ Original ------------------

**Comment by osy86** [comment]
Tracking in #26
