### ISSUE TITLE
GPU memory leaking?

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#251]
**Following is based on the assumption that the iStat Menus**
<img width="159" alt="Screen Shot 2020-04-30 at 7 41 44 PM" src="https://user-images.githubusercontent.com/38860226/80706346-c04e7800-8b1a-11ea-8751-2acc03784c1f.png">
 **can correctly monitor the GPU Usage...**

**Describe the bug**
- The GPU memory usage maximized after I opened Launchpad and some folders in it. Initially I thought this was caches or something, but it kept maximized for the entire afternoon.
<img width="646" alt="Screen Shot 2020-04-30 at 7 06 07 PM" src="https://user-images.githubusercontent.com/38860226/80705714-7ca73e80-8b19-11ea-8dfa-8b870e0214b8.png">

- Even I open the same folder for several times can it use up the GPU Memory... Just a folder with 8 icons:
<img width="1480" alt="Screen Shot 2020-04-30 at 7 34 46 PM" src="https://user-images.githubusercontent.com/38860226/80705795-a8c2bf80-8b19-11ea-9b5d-b95f192cd52c.png">
<img width="279" alt="Screen Shot 2020-04-30 at 7 39 49 PM" src="https://user-images.githubusercontent.com/38860226/80706155-63eb5880-8b1a-11ea-9ca4-d5f9492afb1c.png">

- Ways I currently found to release GPU memory are:
1. Change the screen resolution and change back.
2. Let NUC sleep then wake up.

**Expected behavior**
The gpu memory should be released automatically.

**Configuration**
- HaC Mini version : 2.7
- OSX version : 10.15.3
- NUC model : HVK
- Boot SSD model and protocol : NVME 1TB
- Second SSD model and protocol : SATA 512GB
- First DIMM model : Kingston HyperX impact 2666Mhz
- Display port(s) used : DELL U2518D 2K, Mini-DP
- Any USB devices: Keyboard, Logitech G903

**Modifications**
NO

**Comment by petermaple** [comment]
Why do you think it's the Hac-Mini problem?
I've got the same problem. But even though the GPU Mem is 100% full, the system run smoothly without any animation delay.
So I always think it's the imemu's bug in detecting the particular GPU.

**Comment by KrisCris** [comment]
> Why do you think it's the Hac-Mini problem?
> I've got the same problem. But even though the GPU Mem is 100% full, the system run smoothly without any animation delay.
> So I always think it's the imemu's bug in detecting the particular GPU.

OK. I think you are right
