### ISSUE TITLE
unplugged internal wifi card

### ISSUE THREAD

**Issue by b05at** [osy86/HaC-Mini#253]
Dear @osy86, i unplugged my internal wifi card, for the hope that now my nuc will only use my external bluetooth dongle, but after sleep it still shows up as an Ericsson one (the internal one always showed up like this.). How can i tell the System to only use the dongle. 

![Bildschirmfoto 2020-05-01 um 09 01 47](https://user-images.githubusercontent.com/55507841/80788860-9896f880-8b8a-11ea-9093-21b4edffb784.png)

PS: Using Bluetooh explorer i can not change the dongle to active. I did not remove the card completely, because i dont know how to remove the screw above it. 

thanks for your amazing Project.

**Comment by HorstBrack75** [comment]
Are you using a NUC? (Ericsson?) Why did you unplug it? There is a bios setting to turn it off.

**Comment by b05at** [comment]
> Are you using a NUC? (Ericsson?) Why did you unplug it? There is a bios setting to turn it off. 

Yes iam using the the intel nuc hades canyon. Turning it off in the bios doesnt make any difference, so i decided unplugging it. I will remove it completely this afternoon and see what is changing.

**Comment by hepto** [comment]
> > Are you using a NUC? (Ericsson?) Why did you unplug it? There is a bios setting to turn it off.
> 
> Yes iam using the the intel nuc hades canyon. Turning it off in the bios doesnt make any difference, so i decided unplugging it. I will remove it completely this afternoon and see what is changing.

If by unplugged you mean you just took the _antennas_ off, which sounds likely as you also said you couldn't remove the screw, then the card is still attached to the mainboard and therefore will be recognised.

If the BIOS disable isn't working for you, then you will have to remove the card entirely to prevent the OS from seeing it.

**Comment by b05at** [comment]
> > > Are you using a NUC? (Ericsson?) Why did you unplug it? There is a bios setting to turn it off.
> 
> > 
> 
> > Yes iam using the the intel nuc hades canyon. Turning it off in the bios doesnt make any difference, so i decided unplugging it. I will remove it completely this afternoon and see what is changing.
> 
> 
> 
> If by unplugged you mean you just took the _antennas_ off, which sounds likely as you also said you couldn't remove the screw, then the card is still attached to the mainboard and therefore will be recognised.
> 
> 
> 
> If the BIOS disable isn't working for you, then you will have to remove the card entirely to prevent the OS from seeing it.

Thanks after completely removing it, everything works perfektly.
