### ISSUE TITLE
How to boot Windows in a PC way?

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#256]
I appreciate OpenCore that are making Hackintosh working more like a real Mac, but I just don't feel right booting Windows in the BootCamp way as it brought unnecessary configurations of Hackintosh into Windows and caused unknown devices showing in Device Manager.

Now I have Windows and macOS and their corresponding EFI installed in different SSDs so that Windows boot manager should be available in F10 boot picker, but it disappeared every time after I have booted into macOS and I have to reset NVRAM to restore it. I have googled it but no one talked about that, seems people all happy with BootCamp Windows :(

Is there any way to preserve the Windows Boot Manager in F10 from disappearing?

**Comment by hepto** [comment]
I'm also using separate drives with separate EFI's to dual boot and it's been working great for me.

Are you absolutely sure there are two EFI partitions, one per SSD?  On my first install of Windows I left the macOS drive in, and Windows installed it's boot loader to the macOS SSD anyway, so I re-did it and physically removed the other drive while installing to avoid such risk.

Like I said, I've had no problems since then using F10 to choose the drive to boot.

If you F2 into BIOS do you see both drives also?

**Comment by KrisCris** [comment]
>Are you absolutely sure there are two EFI partitions, one per SSD?

Yes! I unplugged SSD of MacOS when installing Windows 10.

**Comment by osy86** [comment]
You can but it'll cause you a lot of pain when updating Windows. Basically you need a second FAT partition as the EFI partition and put all the windows EFI files there. I think there's guides online on doing this.

**Comment by KrisCris** [comment]
> You can but it'll cause you a lot of pain when updating Windows. Basically you need a second FAT partition as the EFI partition and put all the windows EFI files there. I think there's guides online on doing this.

I have had a separate EFI partition for Windows. But it just keeps disappearing after I booted MacOS.
![Screen Shot 2020-05-08 at 12 18 10 AM](https://user-images.githubusercontent.com/38860226/81318831-68d37d80-90c1-11ea-9d86-d8b07e4d17af.png)

**Comment by osy86** [comment]
Is disk1s2 the EFI partition? I think Windows require both an EFI partition and a "System" partition. I think the EFI partition also has to be larger than 100MB. Anyways it's a huge pain to do.

**Comment by KrisCris** [comment]
> Is disk1s2 the EFI partition?

Yes.

>I think Windows require both an EFI partition and a "System" partition. I think the EFI partition also has to be larger than 100MB. 
Hmmm, all the partitions in Disk1 is created by windows automatically, I didn't touch them. 
Also I had edited my last comments.

>Anyways it's a huge pain to do.
I agree, but I just don't feel right letting OC do the boot like we had many ACPI modifications and stuffs like that... Won't they have impacts on Windows?

**Comment by hepto** [comment]
I have never had to reset NVRAM and it has never disappeared.   I did manual set my partitions up before installing - @osy86 is right that Windows expects a particular layout.

I followed the guide below - basically boot to the Windows 10 installer and get a terminal up. Use diskpart to clean the disk and remove all existing partitions, then create them in the way described on that page. Then run the installer and as all the correct partitions exist it will install without modifying the partitions.

Maybe the other way of letting the installer create the partitions is what is causing the problem?

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions#partition-layout

**Comment by hepto** [comment]
(Unrelated bonus tip - if you manually set your partitions up in this order you can then delete the recovery partition later trivially as it is at the end of the drive! Windows 10 will create a recovery partition at the start of the drive on a blank disk, which makes it almost impossible to reclaim the space.)

**Comment by hepto** [comment]
P.s. I didn’t find it that big a pain to partition the drive if you’re able to clean the disk first - if you follow the guide and put the diskpart commands into a text file onto the Installer USB then it’s only an extra 3 commands just before running the installer. But, if you need to save data so fiddling with partitions AFTER you’ve installed Windows then yes you’re in for a world of pain.

**Comment by KrisCris** [comment]
> I have never had to reset NVRAM and it has never disappeared. I did manual set my partitions up before installing - @osy86 is right that Windows expects a particular layout.

May I ask if your F10 menu shows something like UEFI : DISKNAME : PART ? : **Windows Boot Manager**?

> I followed the guide below - basically boot to the Windows 10 installer and get a terminal up. Use diskpart to clean the disk and remove all existing partitions, then create them in the way described on that page. Then run the installer and as all the correct partitions exist it will install without modifying the partitions.
> 
> Maybe the other way of letting the installer create the partitions is what is causing the problem?
> 
> https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-uefigpt-based-hard-drive-partitions#partition-layout

Thanks for reminding me that! I think your assumption is right because I only deleted the OS partition... Ah, I should know that.

**Comment by hepto** [comment]
It just says Windows Boot Manager for me.

**Comment by KrisCris** [comment]
> It just says Windows Boot Manager for me.

Then it make sense. I think there are possibly some wrong files remaining in that EFI partition.

I'll give it a try tomorrow.

**Comment by KrisCris** [comment]
Hmm, I thought the installer is showing all the partitions.

**Comment by osy86** [comment]
> I agree, but I just don't feel right letting OC do the boot like we had many ACPI modifications and stuffs like that... Won't they have impacts on Windows?

No because I wrote all the ACPI modifications manually and it is compliant with Microsoft's requirements.

**Comment by KrisCris** [comment]
> No because I wrote all the ACPI modifications manually and it is compliant with Microsoft's requirements.

That’s good to know!

In fact what bugs me most is that OC passed the fake system information to windows and made it looks like a real bootcamp machine. Last month I had some issues with my NUC and a technician  of Intel wanted me to dump all the system information in Windows... But I just don’t want let him know I am running on MacOS. LOL

**Comment by KrisCris** [comment]
@hepto You are right! It is working fine after I reinstalled the Windows following that guide. 
Thanks a lot.

@osy86 Would you like to include these to the hacmini guide, as Microsoft has provided the formatting and partition script so that it should be super easy to do - Save the script to a text file and execute it by running `DiskPart /s scripts.txt` in cmd.

[Install Windows from USB drive.pdf](https://github.com/osy86/HaC-Mini/files/4610512/Install.Windows.from.USB.drive.pdf)
[UEFI:GPT - based hard drive partitions.pdf](https://github.com/osy86/HaC-Mini/files/4610513/UEFI.GPT.-.based.hard.drive.partitions.pdf)

**Comment by osy86** [comment]
I will keep this in mind if I decide to rewrite the boot camp part now that Apple has removed the USB creation.
