### ISSUE TITLE
OpenCore 5.8 -> new installer release?

### ISSUE THREAD

**Issue by Malumen** [osy86/HaC-Mini#260]
Hi Osy86, 

There doesn't seem to be another way to get a hold of you on here. Hope you are well in these trying times!!

Have you looked at the list of new features for [**OpenCore 5.8**](https://github.com/acidanthera/OpenCorePkg/releases)? I am not an expert like you, but it looks like _perhaps_ there are some major fixes for problems you have been working on (problems we have all been bothering you with!). 

If testing is OK for OpenCore 5.8, will you be releasing a new version in `releases` tab?  :>

**Comment by osy86** [comment]
Sure it’s on my todo list but it’s not high priority.

**Comment by shian15810** [comment]
If I'm free I could send a PR again.

**Comment by goodbest** [comment]
I have manually updated to 0.58 (with mods on EFI), and it's working just fine.

It's even better for having boot gui picker with OpenCanopy(and with bugs).

**Comment by Malumen** [comment]
> I have manually updated to 0.58 (with mods on EFI), and it's working just fine.
> 
> It's even better for having boot gui picker with OpenCanopy(and with bugs).

What do you mean "and with bugs"? Are _new_ bugs present or does this seem to fix previous bugs identified with HaC mini? Does this fix screen flickering and other bugs for you?

**Comment by osy86** [comment]
I doubt it would fix any bug as the bootloader doesn't affect much after boot.

**Comment by Malumen** [comment]
@osy86  it mentions some screen fixes. Could the new public release that @shian15810 mentioned _include_ some of your fixes for the various bugs that have been solved since version 2.7??

**Comment by goodbest** [comment]
Try at your own risk.
https://github.com/osy86/HaC-Mini/pull/264
https://github.com/osy86/HaC-Mini/suites/671549728/artifacts/6053225
