### ISSUE TITLE
Feature Inquiry - Apple Pay

### ISSUE THREAD

**Issue by aescolastico** [osy86/HaC-Mini#261]
Is there a way to enable apple pay with iPhone continuity if you have an official apple bluetooth card?

**Comment by hepto** [comment]
This works for me.

**Comment by aescolastico** [comment]
DO you have apple wallet in system preferences? I do not.

**Comment by osy86** [comment]
Just to confirm, I was able to use Apple Pay on a website with both my Apple Watch and iPhone. There's no apple wallet in preferences because that requires Touch ID which you won't find on any hackintosh (or any mac desktops).
