### ISSUE TITLE
HDMI output is black screen, miniDP to DP is ok

### ISSUE THREAD

**Issue by engome** [osy86/HaC-Mini#266]
**Configuration**
- HaC Mini version [e.g: 2.0]: 2.8
- OSX version [e.g: 10.14.6]: 10.15.4
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK6
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: toshiba RD500 500GB NVEM
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: DRR4-2666-16GB
- Second DIMM model (if installed): DRR4-2666-16GB
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: 
- Any USB devices:

**Comment by petermaple** [comment]
Got the same problem when first install the Hac-mini. Using HDMI cable can't light up the screen during the MAC OS installation. Used to think my NUC was broken for this problem. But after OS installed, HDMI output should be fine.

**Comment by osy86** [comment]
I believe this is an Intel BIOS issue. Do you see the Intel BIOS logo when powering on?

If you do an unplug+replug then power on THEN ctrl+alt+delete right after powering on, you can reset the graphics config and see the Intel logo.
