### ISSUE TITLE
thunderbolt accessories are not supported on this mac after installation

### ISSUE THREAD

**Issue by gerardverschuren** [osy86/HaC-Mini#267]
Getting the error "thunderbolt accessories are not supported on this mac" when plugging in a TB hard drive. 

Brand new Hades NUC8i7HVK and followed the installation instructions as accurately as possible.

There were however two areas where the instructions/guide did not match my experience which may be related to this bug report.

(1) The section on Thunderbolt suggests "If you've selected to install Native Thunderbolt support, run Thunderbolt Patcher from Applications after rebooting and patch your Thunderbolt controller." However the thunderbolt patcher does not appear as an app on the HaC after installation. This might be relevant?

(2) The Wifi Card description suggested there should have been an option to select the recommended Dell Wifi Card when running the HaCmini.pkg but that package did not present *any* options other than selecting target drive. (Probably not relevant to the TB issue) but still a departure from the documentation

I cannot work out if I have missed a step or option or if the instructions are out of date perhaps? I have repeated the entire process twice with same results.

The TB port does work as a USB port so it is partially functional.

I have looked at the Thunderbolt Patcher docs and github but there is no precompiled app and I am wary of going down that path without some advice that it is indeed the correct action.

Summary: The docs don't match up with the actual process and may have given rise to a missed step or TB issue.

**Comment by osy86** [comment]
The app is installed if you select the native thunderbolt option from the installer.

**Comment by gerardverschuren** [comment]
Got it - so the thing I missed was the options button for the installer. My apologies and thanks for your help. Third time was the charm.
