### ISSUE TITLE
NUC 

### ISSUE THREAD

**Issue by BiggerCookie** [osy86/HaC-Mini#269]

**Comment by BiggerCookie** [comment]
Thanks for the work you do.  
Wish you’d take a look at the NUC10i7FNH. 
I think it can go to 64 gig of ram. 
They run a little less than $600 bare bones.   
Tall case. 

Thanks again.

**Comment by BiggerCookie** [comment]
Sorry this was not code or a bug report.  Don’t know how to get the message to you otherwise.

**Comment by osy86** [comment]
I have no plans at this time to work on any other hackintosh projects. Thanks.
