### ISSUE TITLE
TB3 patcher failed and can't rollback 

### ISSUE THREAD

**Issue by dhlsam** [osy86/HaC-Mini#270]
Hi @osy86 ,
got Tb3 patcher app  issues in 10.15.4
Conditions:
Just bought NUC8i7HVK (second hand),thunderbolt3 ver.33,
Thunderbolt patch failed when I  re-install 10.15.4 with HaC mini v2.8,
it shows @76 @70 @4e devices in patcher app, both flash and uninstall action all failed
on Windows: tb3 not Recognized and thunderbolt update program can't opened.
I think I bricks tb3 already. 
also I have checked previous tb3 problems in Issues list, Do I have to use ch341A flasher to flash tb3 firmware bin files for my problem ? any operation guide ?

[dump.zip](https://github.com/osy86/HaC-Mini/files/4672133/dump.zip)

**Configuration**
- HaC Mini version 2.8
- OSX version 10.15.4
- NUC model : NUC8i7HVK
- Thunderbolt mod: native mode
- Any TB3 devices: egpu with vega64 and qnap-t310g1s 10gbe nic

**Panic log**
sam@hanlingdeMac-mini ~ % sudo /Users/sam/Downloads/tbpatch list
/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/I2C2@15,2/AppleIntelLpssI2C@2/AppleIntelLpssI2CController@2/HPM1@0/AppleHPMLPSS/AppleHPMDevice@4E
  Address : 0x0000004E
  PID     : 0x2831454341
  UID     : 36383710-0FBE-6DAA-564E-3EF616E9F523
  Version : 
  Build   : 708ef7fef06b3a126fd0e433f097fed7975c3730_09112017
  Device  : TPS65982 HW0011 FW0001.12.06 ZTBT1

/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/I2C1@15,1/AppleIntelLpssI2C@1/AppleIntelLpssI2CController@1/HPM0@0/AppleHPMLPSS/AppleHPMDevice@76
  Address : 0x00000076
  PID     : 0x2831454341
  UID     : 2F383710-FF8F-2D84-4F43-9EB0DC4667E4
  Version : 
  Build   : 708ef7fef06b3a126fd0e433f097fed7975c3730_09112017
  Device  : TPS65982 HW0011 FW0001.12.06 ZTBT1

/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/I2C2@15,2/AppleIntelLpssI2C@2/AppleIntelLpssI2CController@2/HPM1@0/AppleHPMLPSS/AppleHPMDevice@70
  Address : 0x00000070
  PID     : 0x2831454341
  UID     : 6E383710-0C9D-65B0-2C48-77EBA8B6ECD9
  Version : 
  Build   : 708ef7fef06b3a126fd0e433f097fed7975c3730_09112017
  Device  : TPS65982 HW0011 FW0001.12.06 ZTBT1

![Screen Shot 2020-05-24 at 12 27 14 AM](https://user-images.githubusercontent.com/390439/82735589-62960000-9d55-11ea-957b-583a5a59d6b5.png)

![screenshot2020-05-24 12 14 43](https://user-images.githubusercontent.com/390439/82735591-66298700-9d55-11ea-845b-a2b85ca3ee56.png)

**Comment by osy86** [comment]
If you can still see the device in the patcher then it’s not bricked. You can always recover the original firmware by booting into windows and installing the older windows tb driver from intel and reflashikg.

**Comment by dhlsam** [comment]
> If you can still see the device in the patcher then it’s not bricked. You can always recover the original firmware by booting into windows and installing the older windows tb driver from intel and reflashing.

Thanks ,I will get a try to recover ， where I can download the older tb drivers?

**Comment by osy86** [comment]
https://downloadcenter.intel.com/download/28658/Thunderbolt-3-Legacy-Driver-for-Windows-10-for-Intel-NUC?product=126143

Make sure the newer driver is completely uninstalled and wiped.

**Comment by dhlsam** [comment]
> https://downloadcenter.intel.com/download/28658/Thunderbolt-3-Legacy-Driver-for-Windows-10-for-Intel-NUC?product=126143
> 
> 
> 
> Make sure the newer driver is completely uninstalled and wiped. 

I wiped windows10 and fresh install windows in second ssd, then I install tb3 legacy driver that download links you provided , also I install tb-fw-updater.

But windows still not recognized tb devices

**Comment by mtdcy** [comment]
I have issues with tb3 native too. 

My machine uses one dp screen(connect to usb-c) and one egpu + screen, after bootup it works fine, but after sleep, it can not wakeup and reboot fails. I have to unplug the power source to make it work again.

Any help?

**Comment by osy86** [comment]
@mtdcy Please don’t hijack someone else’s issue. File your own ticket.

**Comment by mtdcy** [comment]
> @mtdcy Please don’t hijack someone else’s issue. File your own ticket.

sorry about that. please let me known what attachments should i prepare. I'm a newbee...

**Comment by osy86** [comment]
> > https://downloadcenter.intel.com/download/28658/Thunderbolt-3-Legacy-Driver-for-Windows-10-for-Intel-NUC?product=126143
> > Make sure the newer driver is completely uninstalled and wiped.
> 
> I wiped windows10 and fresh install windows in second ssd, then I install tb3 legacy driver that download links you provided , also I install tb-fw-updater. The tb updater could not open after reboot by instruction
> 
> But windows still not recognized tb devices

You might need to open Device Manager and find the thunderbolt NHI device and manually update the driver. Make sure the driver version matches the one on intel’s website.

**Comment by KrisCris** [comment]
> The tb updater could not open after reboot by instruction

What did the updater say?

**Comment by dhlsam** [comment]
> > The tb updater could not open after reboot by instruction
> 
> What did the updater say?

nothing ,can't open updater

**Comment by dhlsam** [comment]
I use ch341a spi flash to restore the offical ver.33 thunderbolt firmware from Intel, then using native thunderbolt option in Hac-mini app and patch the thunderbolt ,everything works fine now.
Thank you @osy86 ,this issues can be closed.

![IMG_3714](https://user-images.githubusercontent.com/390439/82889849-f34f2480-9f7d-11ea-824a-932aa2cb0667.jpeg)

**Comment by xiaooloong** [comment]
@dhlsam ch341a 求推荐店铺，我也搞坏了，准备硬刷。

**Comment by xiaooloong** [comment]
> I use ch341a spi flash to restore the offical ver.33 thunderbolt firmware from Intel, then using native thunderbolt option in Hac-mini app and patch the thunderbolt ,everything works fine now. Thank you @osy86 ,this issues can be closed.
> 
> ![IMG_3714](https://user-images.githubusercontent.com/390439/82889849-f34f2480-9f7d-11ea-824a-932aa2cb0667.jpeg)

谢谢兄弟，我参照这你的方法修好了。
