### ISSUE TITLE
is it safe to update to 10.15.5?

### ISSUE THREAD

**Issue by youngoris** [osy86/HaC-Mini#272]

**Comment by hepto** [comment]
I upgraded this morning and it was successful.

The only thing to note is that on the first reboot it did drop me into the OpenCore menu, where you have to select the update entry rather than the usual macOS entry so it continues the installation.  Maybe if you select the wrong one it is clever enough to switch back, I don't know.  Also I have multiple OS installs, maybe if you are macOS only it will skip that.

I did encounter an expected monitor issue as described in # , but I don't believe that is update related.

**Comment by youngoris** [comment]
> I upgraded this morning and it was successful.
> 
> The only thing to note is that on the first reboot it did drop me into the OpenCore menu, where you have to select the update entry rather than the usual macOS entry so it continues the installation. Maybe if you select the wrong one it is clever enough to switch back, I don't know. Also I have multiple OS installs, maybe if you are macOS only it will skip that.
> 
> I did encounter an expected monitor issue as described in #258, but I don't believe that is update related.

thank you! i'll give a try later.

**Comment by doowzs** [comment]
I have only macOS installed on the machine and met the same issue as @hepto described.

During the upgrade the system was once stuck at EFI menu, choosing 'macOS' didn't make the upgrade proceed. Only need to choose the 'installer' in the EFI menu (the second entry for me) and the upgrade continued smoothly.

**Comment by thegass** [comment]
update went smooth (besides messages about cmos checksum error after bios-post).

**Comment by Anjiro81** [comment]
I can confirm. No problems updating to 10.15.5 on my side too.

**Comment by testkam2018** [comment]
i can say, that update was failed for me
1 - restart - select install 15.5.5
2 - restart during update (no force, nuc restarted as requested, by itself)
3 - select "install" - finished success
4 - tried to log to my ssd - stuck at apple logo 
wait for 20 minutes
reboot by button
revert back from installation usb and time_machine backup (no local snapshots were available)

**Comment by dougdalton** [comment]
I made a mistake in my config,  I have a HVK not HNK,  is that what is causing my issue with the upgrades,  I have not had success upgrading to 10.15.4 supplemental,  I can try the prelinked kernel removal again but that doesnt seem to help.



HaC Mini version [e.g: 2.0]: 2.7
OSX version [e.g: 10.14.6]: 10.15.4
NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung SSD 970 PRO 1TB
Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]:
First DIMM model [e.g: Patriot DDR4-2666 16GB]: Corsair CMSX32GX4M2A2400C16 Vengeance 32GB
Second DIMM model (if installed):
Display port(s) used [e.g: USB-C, mini DP]:
Display resolution(s) [e.g: 4K, 5K]:
Any TB3 devices:
Any USB devices:

**Comment by dougdalton** [comment]
I got the same result on upgrading and had to go back to 10.15.4 the upgrading happened flawlessly and then on reboot it hangs at the apple logo with the same panic posted here:

https://github.com/osy86/HaC-Mini/issues/252

**Comment by suki3014** [comment]
I just updated to the 10.15.5 supplementary update. I had to do a manual restart in the middle of the updating process, but in the end it was a success. Can we get rid of this checksum errors that keep popping up in the process?

**Comment by Jase-NZ** [comment]
Never had a problem here and never had to touch a thing, Launched update and it rebooted a couple of times during update other than that all good. :-)

**Comment by osy86** [comment]
> I just updated to the 10.15.5 supplementary update. I had to do a manual restart in the middle of the updating process, but in the end it was a success. Can we get rid of this checksum errors that keep popping up in the process?

I think in bios you can reset the event log.

**Comment by osy86** [comment]
Closing this as many people including me had no issues installing 10.15.5 with an unaltered OSX+HaC Mini.
