### ISSUE TITLE
HaC 2.9 with OpenCanopy boots BootCamp into "AutoRepair"

### ISSUE THREAD

**Issue by lmshsqlc** [osy86/HaC-Mini#273]
updated HaC Mini 2.9 from 2.6 and BootCamp now boots into AutoRepair, cannot boot into Windows. 
device: nuc8i7hnk
SSD 1 with macos Catalina 10.15 installed
SSD 2 with BootCamp Windows 10 installed. 
BootCamp is installed via opencore & has always been boot via opencore. 
Now using opencanopy I didnt find anywhere to modify the boot entry. 

macos boots fine.

**Comment by goodbest** [comment]
Maybe issue irrelevant,

 if you have multiple ssd/hdd driver in your machine, how can you use bootcamp to install windows?

**Comment by osy86** [comment]
I've re-uploaded v2.9 with this fix.

**Comment by lmshsqlc** [comment]
> I've re-uploaded v2.9 with this fix.

Proved fixed with this. Thanks 
Also @goodbest

**Comment by Anjiro81** [comment]
Had the same issue. Can confirm that it is fixed with the update. Thanks!
