### ISSUE TITLE
Display boot menu on booting after upgrading to 2.9

### ISSUE THREAD

**Issue by errorstack** [osy86/HaC-Mini#276]
**Describe the bug**
My startup disk is BOOTCAMP, computer boot from windows by default without boot menu. But after upgrading to 2.9, it displays boot menu on booting everytime. But after I set the startup disk as MacintoshHD, it boot without boot menu. I didn't check the "show boot menu" option when installing HaC Mini.  How can I fix this?

**Expected behavior**
Computer boot from windows by default without boot menu

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.9
- OSX version [e.g: 10.14.6]: 10.15.5
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK

**Modifications**
none

**Comment by osy86** [comment]
Can you try setting startup disk to BOOTCAMP again? Also older instructions said to modify the BCD entry. That is no longer needed and if you did that you should revert the change. If you didn't do it, then you don't need to do anything.

**Comment by errorstack** [comment]
> Can you try setting startup disk to BOOTCAMP again? Also older instructions said to modify the BCD entry. That is no longer needed and if you did that you should revert the change. If you didn't do it, then you don't need to do anything.

I tried setting startup disk to BOOTCAMP again, it didn't work. I think the reason is the BCD entry, I used to set {bootmgr} path to \EFI\OC\OpenCore.efi with bcdedit. How to revert the change, please?

**Comment by osy86** [comment]
Try `Bcdedit /set {bootmgr} path \efi\microsoft\boot\bootmgfw.efi`

**Comment by errorstack** [comment]
> Try `Bcdedit /set {bootmgr} path \efi\microsoft\boot\bootmgfw.efi`

It works. Thank you!
