### ISSUE TITLE
This copy of the install macos is damaged..

### ISSUE THREAD

**Issue by mcemce13** [osy86/HaC-Mini#281]
Clean install in my new NUC nuc8i7hvk, everything goes fine, installer boot from first time then I run the disk utlity but then I go to the install I get the error

This copy of the Install macos Catalina application is damaged, and cant be used to install macOS.

I followed the guides

https://osy.gitbook.io/hac-mini-guide/post-installation/support

Pachted the install, tried with 3 times with 3 diff USB, all same outcome.

Any ideas? Thanks!

**Comment by osy86** [comment]
Can you try the OSX installer without ethernet or WiFi connected?

**Comment by mcemce13** [comment]
Yes, machine is not connected via ethernet nor wifi

**Comment by Niquau** [comment]
I also had this problem with Mojave 10.14.6. :-(
Then I tried with Catalina 10.15.5 and all works great.

**Comment by mcemce13** [comment]
Yep, Catalina 10.15.5 is the one giving me the error

**Comment by sffjawsh** [comment]
@mcemce13 Long shot but check your Date & Time in the BIOS and the Installer to make sure it is correct.

**Comment by andreyantipov** [comment]
@mcemce13 I fixed this issue just by deleting InstallInfo.plist file in SharedSupport

**Comment by osy86** [comment]
Deleting InstallInfo.plist means it will install from network and also you won’t get the HaC mini package installed. I suspect Apple fixed the hole that let’s us patch the installer without breaking the signature check. If so then you cannot use the patch installer option anymore.

**Comment by osy86** [comment]
Can someone attach their /var/log/install.log so I can check this?

**Comment by bopamo** [comment]
I just had this issue as well. I will try deleting the InstallInfo.plist as @andreyantipov recommended.

**Comment by osy86** [comment]
Big Sur removes the ability to patch the installer. The guide will be updated in the future and patched installer will no longer be supported.

**Comment by bopamo** [comment]
@osy86 thank you very much for the update. What versions of macOS are valid with the current guide as-is?

**Comment by osy86** [comment]
Added support section https://osy.gitbook.io/hac-mini-guide/post-installation/support#this-copy-is-damaged-and-cant-be-used-to-install-macos
