### ISSUE TITLE
Blackscreen powering

### ISSUE THREAD

**Issue by candyrock** [osy86/HaC-Mini#282]
Sometimes I have a black screen powering if I use the method native thunderbolt. The Black screen for a while and then it resets. I have to unplug and plug again for booting. It just occurred with a thunderbolt patcher. I think a driver has an issue. I tried to reinstall the patcher again but it still has a problem. I don't have this issue with the method thunderbolt legacy. Thank you for helping and the last build with update Polaris22Fixup

**Configuration**
- HaC Mini version: The last build
- OSX version: 10.15.4 
- NUC model: NUC8i7HVK
- Boot SSD model and protocol Samsung 970 Evo
- Second SSD model and protocol (if installed): Inland Premium
- First DIMM model: Kingston DDR4 8GB
- Second DIMM model (if installed): Kingston DDR4 8GB
- Display port(s) used [e.g: USB-C, mini DP]: HDMI, USB C, mini DP
- Display resolution(s) [e.g: 4K, 5K]: 4K and FHD
- Any TB3 devices: 
- Any USB devices: mouse and keyboard

**Comment by osy86** [comment]
Yeah I’ve seen this issue as well. I don’t think it’s fixable as it’s a hardware issue due to incompatible thunderbolt firmware.

**Comment by petermaple** [comment]
So when the TB bridge crash, the system just boot with no display? or just won't boot? 
in my case, the system won't boot because the HDD LED won't flash.
