### ISSUE TITLE
install HaC-Mini to Macbook system disk,How to uninstall?

### ISSUE THREAD

**Issue by cn0xroot** [osy86/HaC-Mini#283]
Thanks for all developer for this project,my nuc is work fine now.

But when I frist install this pkg,I installed  it to macbook system disk, 

How to uninstall,  is there  any ideal ? Thanks

**Comment by osy86** [comment]
If you only had the default options, it should be enough to mount the ESP partition and delete EFI/OC and EFI/BOOT. If you had boot camp you might have to recover the bootloader. Depending on the other options you might have Thunderbolt Patcher installed into /Applications and you can just delete that. Finally if you selected the flickering tweak, delete /usr/local/bin/SLForceFPS and the launchagent.

**Comment by cn0xroot** [comment]
Thanks so much. 


Best
