### ISSUE TITLE
After installing HaC-Mini on my NUC8i5BEH, I can't enter the desktop after booting, and the loading progress bar is stuck at about 100%.

### ISSUE THREAD

**Issue by xiaoyan94** [osy86/HaC-Mini#284]
**Describe the bug**
_After installing HaC-Mini on my NUC8i5BEH（with opencore）, I can't enter the desktop after booting, and the loading progress bar is stuck at about 100%._

**Expected behavior**
*I originally wanted to install this software so that my box can use the Thunderbolt 3 interface function normally.*

**Configuration**
- HaC Mini version [e.g: 2.0]: **2.9**
- OSX version [e.g: 10.14.6]: **10.15.5**
- NUC model [e.g: NUC8i7HNK]: **NUC8i5BEH**
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung EVO 860 500TB, SATA
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: HyperX Impact DDR4-2666 16GB
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 2K
- Any TB3 devices: 
- Any USB devices: 

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

**Panic log**
Include a screenshot of the panic message if applicable.

**PLEASE HELP ME !**
**What should I do to fix it ？**

**Comment by osy86** [comment]
NUC8i5BEH Is not supported
