### ISSUE TITLE
Geekbench's score low with new polaris22fixup

### ISSUE THREAD

**Issue by candyrock** [osy86/HaC-Mini#286]
I tested with the old kext. Score is over 30000 -32000 with GB5. But with new polaris22fixup, a maximum score is 26000. Thanks
Configuration

HaC Mini version: The last build
OSX version: 10.15.4
NUC model: NUC8i7HVK
Boot SSD model and protocol Samsung 970 Evo
Second SSD model and protocol (if installed): Inland Premium
First DIMM model: Kingston DDR4 8GB
Second DIMM model (if installed): Kingston DDR4 8GB
Display port(s) used [e.g: USB-C, mini DP]: HDMI, USB C, mini DP
Display resolution(s) [e.g: 4K, 5K]: 4K and FHD
Any TB3 devices:
Any USB devices: mouse and keyboard

**Comment by osy86** [comment]
Can you download https://github.com/osy86/HaC-Mini/releases/download/v1.0/HaCMiniSupport-v1.0.zip and install the OldRadeonX4000HWLibs.kext? And see if that makes a difference?

**Comment by candyrock** [comment]
> Can you download https://github.com/osy86/HaC-Mini/releases/download/v1.0/HaCMiniSupport-v1.0.zip and install the OldRadeonX4000HWLibs.kext? And see if that makes a difference?

Yeah I tried this kext in 3 hrs ago and score grown-up again. The lasted build is not included this kext. thank you

In Whatevergreen's FAQ, if we use this kext, we should delete the basic patch as HDAS to HDEF, GFX0 to IGPU, HECI to IMEI, -disablegfxfirmware. This kext can handle them

**Comment by osy86** [comment]
No those patches are needed and is not related to WG.

The latest version removed the Old kext because it uses the latest version from Apple. I guess this means that the newest Apple kext performs worse which is concerning but I think macOS 11 won’t work with the old kext anymore.

**Comment by candyrock** [comment]
I tried to delete all patches that I said above and check, this worked in ioreg. I have read from here -> https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md.

From 10.15.5 Apple also break Navi's driver. I see the vega m has Device ID same RX570, 580. Can we use named framebuffer as RX 580 uses Orinoco to get high performance. Did you try about this?

**Comment by osy86** [comment]
Those instructions don’t apply here. Changing the frame buffer won’t do anything in any modern AMD cards.

**Comment by candyrock** [comment]
k

> Those instructions don’t apply here. Changing the frame buffer won’t do anything in any modern AMD cards.

thank you @osy86

**Comment by candyrock** [comment]
@osy86 Update!!! We cannot use OldRadeonX4000HWLibs.kext because the VDA decoder broken.

**Comment by osy86** [comment]
I think you should stick to v2.9

**Comment by candyrock** [comment]
> I think you should stick to v2.9. Make sure to clear nvram after downgrading.

Thanks for your advice. But I still use 2.10 due to 2..9 is not working.on DRM..
