### ISSUE TITLE
No DisplayPort Output

### ISSUE THREAD

**Issue by rjocoleman** [osy86/HaC-Mini#288]
**Describe the bug**

 I get only black screen out of DP using Mini-DP to DisplayPort adapters.

I have a brand new install yesterday (only ever install 2.10/10.15.5). Bios 0059. Bios setting as per the guide.
No Intel logo or Apple boot logo via Mini-DP. Black screen only in installer via Mini-DP.

Installed via HDMI. Once installed same behaviour with DP.
macOS detects the display in System Report but I get no output out of either Mini-DP (tried with/without HDMI and the combinations of Mini-DP).
HDMI works as expected.

Linux boots fine and shows output via the same cables and Mini-DP.

**Expected behaviour**

Expect DisplayPort to display more than a black screen.

**Configuration**
- HaC Mini version: 2.10
- OSX version: 10.15.5
- NUC model: NUC8i7HNK
- Boot SSD model and protocol: Intel SSD 660p Series PCIe 3.0 x4, NVMe
- Second SSD model and protocol (if installed): N/A
- First DIMM model: Crucial 16GB DDR4-2400 SODIMM
- Second DIMM model (if installed): Crucial 16GB DDR4-2400 SODIMM
- Display port(s) used: mini-DP x2, HDMI
- Display resolution(s): 4K
- Any TB3 devices: none
- Any USB devices: Logitech Unifying Receiver

**Modifications**
None.

**Panic log**
None.

**Comment by osy86** [comment]
Can you try v2.9 and see if it works?

**Comment by rjocoleman** [comment]
Yes! If I run the v2.9 package on the already installed macOS and clear NVRAM/boot args is that sufficient? or shall I clean install?

**Comment by osy86** [comment]
Clear nvram is enough. Did it work though?

**Comment by rjocoleman** [comment]
Sorry, I was just checking before I did it.

I have now downgraded to v2.9, reset NVRAM and rebooted. I have no output on Mini-DP (the display periodically flicks on and off between black and off)
When connected by Minin-DP the display EDID is showing under System Report seemingly with the correct EDID/res/model number etc.

**Comment by osy86** [comment]
What display do you have? Does it work on windows/Linux? Can you test with a real Mac or another hackintosh?

**Comment by rjocoleman** [comment]
Samsung 28" UE590 UHD Monitor.

On the NUC works fine via Mini-DP under Linux.

Also works on other Hackintoshes via DisplayPort (OpenCore 0.59, WEG)

**Comment by rjocoleman** [comment]
Turns out I had my MiniDP to DisplayPort cables were v1.1. MacOS doesn't like that for the 4K resolution (red-herring is that Linux didn't care and worked).

Switching out to MiniDP to DisplayPort v1.2 cables resolved everything. Thanks!
