### ISSUE TITLE
The screen is black for the first boot until the login interface

### ISSUE THREAD

**Issue by Good0007** [osy86/HaC-Mini#289]
**Describe the bug**
     I feel the display output is slow when I first boot. I can see the opencore boot interface after I restart the system.
When i using HDMI2.0 to boot,I get only black screen and I cannot even enter BOIS. But after I use Mini-DP to DisplayPort enter the system, and then connect hdmi2.0, it can work well.
     I think this problem may have nothing to do with EFI, but I can't find the reason, so I want to ask for help.
     Finally, thank you for your dedication.

**Expected behavior**

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.10
- OSX version [e.g: 10.14.6]: 10.15.5
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: SN750 512G
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: ZHIKE DDR4 2666 16G
- Second DIMM model (if installed): ZHIKE DDR4 2666 16G
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: 
- Any USB devices: 

**Modifications**

**Panic log**

**Comment by osy86** [comment]
I’ve experienced this with usbc and I think it’s an Intel issue. I would use ctrl+alt+del after reboot to see POST.

**Comment by Good0007** [comment]
> I’ve experienced this with usbc and I think it’s an Intel issue. I would use ctrl+alt+del after reboot to see POST.

Thank you, I will try

**Comment by Good0007** [comment]
> I’ve experienced this with usbc and I think it’s an Intel issue. I would use ctrl+alt+del after reboot to see POST.

I use ctrl+alt+del to reset config, but it still doesn't work. I did some tests:

|  |  using minidp  |   using hdmi(connected hdmi1.4)| using hdmi(connected hdmi2.0)  |
| ------------ | ------------ | ------------ | ------------ |
|first boot(do an unplug+replug)|  Not displayed until entering the system |normal   |  Always black screen(cannot enter bois) |
|after reboot | normal  |  normal | Not displayed until entering the system  |

**Comment by petermaple** [comment]
TB3 can display instantly after power on.

**Comment by osy86** [comment]
This is a hardware issue with NUC or Intel BIOS. The graphics hardware sometimes does not get initialized properly. I'm not sure it can be fixed except by Intel.
