### ISSUE TITLE
is this built can work on macOS Mojave 10.14.6?

### ISSUE THREAD

**Issue by jiaoxj86** [osy86/HaC-Mini#29]
I completely followed the guid downloaded Mojave 10.14.6 and make a install usb disk.
But when I finished installation and selected **Boot macOS from ...** ,after a long time waiting,it just stuck at **kextd stall[n],(240s):'appleACPICPU'.**
Is that mean this built only work on macOS Mojave 10.14.5?

**Comment by 22dm** [comment]
Same problem, waited for nearly 20 mins, it rebooted, then I met the #19, try to press **space** in the clover and select **Boot macOS with injected kexts**.

**Comment by dapostman** [comment]
I followed the guide meticulously, and was successful. The only thing I did slightly differently was the first thing I did when booting into the USB was to go to Terminal (before Disk Utility) and zero out the SSD for a few thousand blocks (dd if=/dev/zero of=/dev/diskx bs=1m), Ctrl-C out, quit terminal, and then back to Disk Utility for a fresh erase/partition.

**Comment by adriavidal** [comment]
Instalation with the guide was ok, but after clover install to hd, efi replace when booting ( sloow), finally the NUC reboot. (i7-8705G 16+16 Gb `RAM) Mojave 10.14.6

Bios defaul + changes done

![IMG_20190828_231304](https://user-images.githubusercontent.com/9115153/63893975-c6b8ad00-c9eb-11e9-8462-85654d9ed032.jpg)

booting with these EFI

[full.default.efi.zip](https://github.com/osy86/HaC-Mini/files/3552967/full.default.efi.zip)

Could someone provide a succesful EFI i could try?

**Comment by adriavidal** [comment]
After 10.14.6 suplemental upgrade get a new kernel panic.

![10 14 6 update](https://user-images.githubusercontent.com/9115153/63982689-c855a400-cac3-11e9-9a2f-e3e070d3b488.jpg)

any suggestion ?

**Comment by osy86** [comment]
Add this patch to disable the extra log entries otherwise I cannot see the error message. https://github.com/RehabMan/Intel-NUC-DSDT-Patch/blob/master/config_nuc8_bc.plist#L261

**Comment by dapostman** [comment]
> After 10.14.6 suplemental upgrade get a new kernel panic.


Similar issue...I got to the clover screen, but it didn’t count down and auto boot, and it fails to recognize a usb keyboard.

I’ll mess with it some more tonight.

**Comment by adriavidal** [comment]
> Add this patch to disable the extra log entries otherwise I cannot see the error message. https://github.com/RehabMan/Intel-NUC-DSDT-Patch/blob/master/config_nuc8_bc.plist#L261

![nuc crash cpu](https://user-images.githubusercontent.com/9115153/64069123-a3883a80-cc43-11e9-9ad1-2b4ba825f9f2.png)

seems to be CPU related, checked at clover BIOS the TRUST to yes as someone suggested, without succes

**Comment by adriavidal** [comment]
> > Add this patch to disable the extra log entries otherwise I cannot see the error message. https://github.com/RehabMan/Intel-NUC-DSDT-Patch/blob/master/config_nuc8_bc.plist#L261
> 
> ![nuc crash cpu](https://user-images.githubusercontent.com/9115153/64069123-a3883a80-cc43-11e9-9ad1-2b4ba825f9f2.png)
> 
> seems to be CPU related, checked at clover BIOS the TRUST to yes as someone suggested, without succes

forget about it.
done a clean install, upgrade with combo and all is up & running.
thanks for the great work!!
