### ISSUE TITLE
I can't shutdown the Windows 10 with opencore

### ISSUE THREAD

**Issue by JerryXu-code** [osy86/HaC-Mini#292]
I am using:
- HaC Mini version:v2.7
- OSX version:10.15.0
- Windows 10 version:1909 Enterprise
- NUC model:NUC8i7HVK
- Boot SSD model and protocol:Hikvision C2000Pro
And I can't shutdown,it will hangs at dots and says"Shutting down..."
plz help me!

**Comment by osy86** [comment]
How long did you wait?

**Comment by JerryXu-code** [comment]
for about 10min

**Comment by osy86** [comment]
Keep waiting

**Comment by JerryXu-code** [comment]
Finally,I can shut it down for now

**Comment by JerryXu-code** [comment]
but i have to wait for a long time

**Comment by JerryXu-code** [comment]
hello?

**Comment by JerryXu-code** [comment]
Finally, I can shutdown normally.
