### ISSUE TITLE
No bootloader installed in System

### ISSUE THREAD

**Issue by Zekcode** [osy86/HaC-Mini#293]
Hey Champs

Just installede MaC-Mini on my hades Nuc. everything is working perfect except ofc wifi, never mind ordered a new wifi card.

my problem is, that after i boot camped with windows, there is no OpenCore bootloader on the computer?
i followed the guide linked in the FAQ, but no help. the command does nothing for me.

if i boot when the patchet USB is in the computer, i can boot into OpenCore loader and do my stuff.
without im getting stuckd at no bootable devices (windows bootloader)

Any ideas how to fix this?

Kind regards

Zek

**Comment by Malumen** [comment]
ＯＫ I know this is perhaps not what you were looking for, but here is how I got both OS:

Two SSDs: one Intel 1TB and one Samsung 512GB.
MacOS on the Intel 1TB with HaC Mini installer, got it installed and updated and made sure everything worked ok.
Boot into BIOS and logically disable the MacOS SSD port, then go ahead with installing Windows 10 Pro onto the 512 SSD. 
The system still retained the bootloader for OpenCore and did not get overwritten during the install of Windows 10 Pro, in fact it probably used the bootloader it already saw in use. 

Run all updates and make sure the Windows SSD is working OK, create a restore point when you know it works. 

Then boot into BIOS again and enable the MacOS SSD. 

From now on you will need to boot and pick which drive to boot into. 

Yes, it's a slight bit less one-button-click than Bootcamp, but everything *works* properly. When you need to switch OS, full shutdown, then on boot pick the desired OS. 

I hear a lot of problems people have with getting both OS to work. I've never had any issues with this setup.

**Comment by Zekcode** [comment]
Hello Malumen

Bots OSses is working fine :) no problems, its the boot in to them there is the problem, i could just leave my USB stick in the computer and then it would be fine. just want the bootloader to be on the SSD and not the USB stick?

does it makes sence?

**Comment by KrisCris** [comment]
https://osy.gitbook.io/hac-mini-guide/installation-guide/boot-camp#fixing-boot
