### ISSUE TITLE
issue with thunderbolt patcher 

### ISSUE THREAD

**Issue by candyrock** [osy86/HaC-Mini#294]
The thunderbolt doesn't see in system report after running a thunderbolt patcher. it runs a script successfully. I can not open update thunderbolt firmware to rollback original on Windows (I have uninstalled patcher without fail before rollback)

HaC Mini version: The last build
OSX version: 10.15.5
NUC model: NUC8i7HVK
Boot SSD model and protocol Samsung 970 Evo +
Second SSD model and protocol (if installed): 
First DIMM model: Crucial DDR4 8GB
Second DIMM model (if installed): Crucial DDR4 8GB
Display port(s) used [e.g: USB-C, mini DP]: HDMI, USB C, mini DP
Display resolution(s) [e.g: 4K, 5K]: 4K
Any TB3 devices:
Any USB devices: mouse and keyboard

[thunderbolt report.zip](https://github.com/osy86/HaC-Mini/files/4905927/thunderbolt.report.zip)
<img width="483" alt="Screen Shot 2020-07-10 at 7 46 57 PM" src="https://user-images.githubusercontent.com/67130100/87211150-32df8f00-c2e6-11ea-8527-be4758303128.png">
<img width="481" alt="Screen Shot 2020-07-10 at 7 43 19 PM" src="https://user-images.githubusercontent.com/67130100/87211180-4b4fa980-c2e6-11ea-9985-fa2f404ca957.png">

**Comment by osy86** [comment]
I’m confused the second screenshot shows a successful uninstallation and the first screenshot shows that your firmware has been reverted to the original. What’s the issue?

**Comment by candyrock** [comment]
> I’m confused the second screenshot shows a successful uninstallation and the first screenshot shows that your firmware has been reverted to the original. What’s the issue?

Both pictures also ran Uninstall to make sure it still has original after uninstall. I just want to report for you clear. I don't know why the patcher runs very quickly. It's not like the first time I ran a patch

**Comment by osy86** [comment]
It seemed to have uninstalled successfully. I don’t know what your issue is.

**Comment by candyrock** [comment]
> It seemed to have uninstalled successfully. I don’t know what your issue is.

yeah me too. At this time, only USB C works on thunderbolt port. I use method thunderbolt legacy and it doesn't work anymore

**Comment by osy86** [comment]
Does it work on windows?

**Comment by candyrock** [comment]
> Does it work on windows?

It doesn't work.

**Comment by hepto** [comment]
I found Thunderbolt in Windows strange to manage - I had to install/open Thunderbolt Control Center then 'approve' my TB device before it would work - have you tried that?

Also don't forget to set the BIOS Thunderbolt settings back from Legacy Mode, if you made that change.

**Comment by candyrock** [comment]
> I found Thunderbolt in Windows strange to manage - I had to install/open Thunderbolt Control Center then 'approve' my TB device before it would work - have you tried that?
> 
> Also don't forget to set the BIOS Thunderbolt settings back from Legacy Mode, if you made that change.

yes, I tried but still not open firmware update. Maybe the firmware has a problem

**Comment by hepto** [comment]
Oh I see you can't run the Intel firmware update on Windows? Yes I have the same issue and I think it's an issue with the updater, not the firmware.  You can use Thunderbolt Control Centre to check the firmware version of the controller and if it's the same as the downloaded on I wouldn't worry about it. (I think v33?)

**Comment by candyrock** [comment]
> Oh I see you can't run the Intel firmware update on Windows? Yes I have the same issue and I think it's an issue with the updater, not the firmware. You can use Thunderbolt Control Centre to check the firmware version of the controller and if it's the same as the downloaded one I wouldn't worry about it. (I think v33?)

![IMG_20200711_121715](https://user-images.githubusercontent.com/67130100/87228819-bbefd800-c371-11ea-8d96-f99443cdc993.jpg)

Have you fixed this problem yet?

**Comment by hepto** [comment]
Mine shows 33 - will take a picture tomorrow (UK time). Not sure what's going on in your picture, but don't forget you need a device plugged in for certain aspects of the driver to work ...

**Comment by hepto** [comment]
Do you have the latest drivers / software? That's not the screen I have and both Windows Update and the Intel Driver Update program day I'm on the latest. Attached are the details on my system.

![image](https://user-images.githubusercontent.com/4923370/87243380-8c060a80-c42d-11ea-9fb2-5bc29ad68446.jpeg)

**Comment by candyrock** [comment]
> Do you have the latest drivers / software? That's not the screen I have and both Windows Update and the Intel Driver Update software say I'm on the latest. Attached are the details on my system.
> 
> ![image](https://user-images.githubusercontent.com/4923370/87243380-8c060a80-c42d-11ea-9fb2-5bc29ad68446.jpeg)

thanks for your help. But certainly, I have to flash the firmware with PSI chip

**Comment by hepto** [comment]
Fair enough, pleased you've worked it out.

Actually I was curious why I myself couldn't run the Thunderbolt FW updater even though my firmware was OK ... turns out that it will only work with the so-called 'legacy' Thunderbolt driver / software and if you've ever installed the newer 'DCH' drivers it's a little tricky to go back to the legacy ones (you have to remove them from Device Manager but install the new ones before Windows attempts to reinstall).

Also, by default it expects a Thunderbolt device plugged in to run the updater, which I was trying with a Thunderbolt monitor but at the end of the update the monitor would reconnect and throw the updater out.  So instead if you start the updater with the Thunderbolt ports empty, then it installs a work around to power the controller on without there being something plugged in and therefore the updater will proceed.

So anyway I re-ran the updater successfully so I am sure I am back to the original firmware now.

**Comment by candyrock** [comment]
fixed with Ch341a flash. thx @osy86 and @hepto support me
