### ISSUE TITLE
upgrade to 10.15.6

### ISSUE THREAD

**Issue by edotyg** [osy86/HaC-Mini#296]
did any one successfully apgraded the system from 10.15.5 to 10.15.6?
thanks

**Comment by hepto** [comment]
Running through now will report back shortly - don't forget that when it reboots you have to ensure you choose the Installer boot option.

**Comment by hepto** [comment]
Installed fine, if I notice anything weird will post here.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/4923370/87643910-60439700-c743-11ea-9e5d-c82b79a7e167.png">

**Comment by edotyg** [comment]
it worked fine

**Comment by oldflag2333333** [comment]
installed, also fine

**Comment by dshan0411** [comment]
I've installed it and everything is fine

**Comment by youngoris** [comment]
installed, works fine so far. Nothing weired.

**Comment by Anjiro81** [comment]
Confirmed, no problem updating to 10.15.6 for me.

**Comment by havvk** [comment]
Updated to 10.15.6. Everything is OK.

**Comment by keatliang2005** [comment]
Just got my Nuc last week updated 0059 and create install with 10.15.6, install all went fine.

**Comment by Niquau** [comment]
Updated also to 10.15.6. All is OK also for me :-)
