### ISSUE TITLE
Display issue on 4k 120hz monitor

### ISSUE THREAD

**Issue by oldflag2333333** [osy86/HaC-Mini#297]
Thanks a lot  for your contribution.
When I open 120hz mode with RDM, I get a display issue.But if i turn it off, everything works fine.
The issue is that under 120hz some frames have a strange area (looks like a window which appears at wrong place, but a im not totally sure, because its really fast) .It suddenly appear and then disappear, looks like flickering (the screen itselt is not flickering).I turned on scale in system preference and used a miniDP to Dp cable to connect the monitor. Its not serious, but a little bit annoying. 

**Configuration**
- HaC Mini version : 2.10
- OSX version : 10.15.6 （10.15.5 also has the same issue）
- NUC model :NUC8i7HNK 
- Boot SSD model and protocol :western digital sn 550 1tb(nvme)
- Second SSD model and protocol (if installed) : none
- First DIMM model [e.g: Patriot DDR4-2666 16GB]:kinston ddr4 2666 16g
- Second DIMM model (if installed): kinston ddr4 2666 16g
- Display port(s) used [e.g: USB-C, mini DP]: hacmini using miniDP display using standard DP
- Display resolution(s) [e.g: 4K, 5K]: 4k (3840×2160)
- Any TB3 devices: no
- Any USB devices: no
- wifi card:1820a

**Comment by KrisCris** [comment]
Have you tried the workaround for reducing screen flickering in the installer?

**Comment by oldflag2333333** [comment]
Its really weird.I’ve just change my wifi card from 1820a to 94352z few days ago, and changed some bios settings, such as turn on and turn off the onboard bluetooth and wifi, after that the issue seen to be gone.Maybe its a bios bug.
