### ISSUE TITLE
NUC 8I7HVK Sidecar Blackscreen on the Ipad Pro 2018 12.9

### ISSUE THREAD

**Issue by Kl0neU5** [osy86/HaC-Mini#298]
**Describe the bug**

Sidecar is available in the System Properties.
I PAd can also Connect through wireless or USB Cable.  But shows only Blackscreen

I need help to solve this Problem

**Configuration**
- HaC Mini version [None]: Configurated from DSM2 from the german Hackintosh Forum Was made with Open Core 0.5.9
- OSX version [e.g: 10.15.6]: 
- NUC model [e.g: NUC8i7HVK]: 
- Boot SSD Samsung Pro 970  1TB, Nvme]: 
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [16 GB Kingston 2400 MHz DDR4 ]: 
- Second DIMM model[16 GB Kingston 2400 MHz DDR4 ]: 
- Display port(s) used [HDMI]: 
- Display resolution(s) [: 4K LG HDR 43" Display]: 
- Any TB3 devices:  No
- Any USB devices: Motu M4 Audio Interface

**Modifications**
I attach my Config.plist. and a Picture of my EFI Folder.
**Panic log**
Include a screenshot of the panic message if applicable.

<img width="617" alt="Efi Folder 1" src="https://user-images.githubusercontent.com/66927204/87972802-d3dcff80-cac7-11ea-937a-5fb16a424530.png">
<img width="606" alt="Efi Folder 2" src="https://user-images.githubusercontent.com/66927204/87972812-d8091d00-cac7-11ea-87ab-dd910c03c6eb.png">

<img width="769" alt="myconfigplist 1" src="https://user-images.githubusercontent.com/66927204/87973772-54503000-cac9-11ea-9119-fb28e2de0f33.png">
<img width="828" alt="myconfigplist 2" src="https://user-images.githubusercontent.com/66927204/87973781-587c4d80-cac9-11ea-90aa-c082248d98ba.png">
<img width="821" alt="myconfigplist 3" src="https://user-images.githubusercontent.com/66927204/87973789-5914e400-cac9-11ea-8af2-01067b8d7a3f.png">
<img width="838" alt="myconfigplist 4" src="https://user-images.githubusercontent.com/66927204/87973792-5a461100-cac9-11ea-8a78-7fa9222b6647.png">
<img width="836" alt="myconfigplist 5" src="https://user-images.githubusercontent.com/66927204/87973795-5adea780-cac9-11ea-80dc-83e45854e825.png">
<img width="838" alt="myconfigplist 6" src="https://user-images.githubusercontent.com/66927204/87973798-5b773e00-cac9-11ea-8e5a-cde6ec23b1f0.png">
<img width="840" alt="myconfigplist 7" src="https://user-images.githubusercontent.com/66927204/87973800-5ca86b00-cac9-11ea-9515-93c8423687c3.png">
<img width="837" alt="myconfigplist 8" src="https://user-images.githubusercontent.com/66927204/87973802-5d410180-cac9-11ea-92e3-edc39b7df1b7.png">
<img width="834" alt="myconfigplist 9" src="https://user-images.githubusercontent.com/66927204/87973804-5dd99800-cac9-11ea-9ca8-5db8c9e525b2.png">

**Comment by osy86** [comment]
You probably selected AMD codec. Only intel codec supports sidecar. You need to reinstall with Intel codec and reset boot args options.

**Comment by Kl0neU5** [comment]
Thanks for the answer. So you mean i have to reinstall everything new? so from scratch?  What is it about to reset the boot args options?
What command line is this?

And always thanks for your Help Osy86.

**Comment by osy86** [comment]
No just the hac mini installer. Follow directions for “upgrading hac mini” in the guide.

**Comment by Kl0neU5** [comment]
OK, thanks again for this quick answer.

One last thing.

how to do ---° Note that for this release you must reset your boot-args when installing the update by selecting "Boot Options -> Reset boot-args".  Or better, where to do.

**Comment by osy86** [comment]
It’s in the installer options. Same place you select amd/intel codec.

**Comment by Kl0neU5** [comment]
Yes i found it then.....   Thanks a lot for your support Osy86!!!!!!  :-)).  Sidecar is running now.  Running like a charme.

I am so happy now.

You can close this thing here, if you like. Problem solved.
