### ISSUE TITLE
Unlocking with Apple Watch

### ISSUE THREAD

**Issue by sammy1881** [osy86/HaC-Mini#299]
Hey, 

First of all kudos and thanks for making this work. It has been my main machine for over a year and is very very stable. I love it.

The issue I'm having is not a huge deal, it's just a minor annoyance and I want to try and make it work. I don't know where to look at because everything seems to work including Bluetooth, wireless, Airplay, Airdrop, and continuity. 

The card I'm using is DW1560 and I'm not able to make unlocking with Apple Watch.

When I enable that option I get an error. 
![image](https://user-images.githubusercontent.com/19999589/88098357-45b45800-cb5f-11ea-945b-dcfa6a78943f.png)

**Comment by osy86** [comment]
You need to use the Apple wireless card. That’s the only way to get 100% compatibility. 3rd party cards are very hit or miss.
