### ISSUE TITLE
Low graphics score in geekbench

### ISSUE THREAD

**Issue by 22dm** [osy86/HaC-Mini#30]
I'm running macOS 10.14.6 on nuc8i7hvk, thanks to this project, everything works fine, except for one thing:

I noticed some game got a very low fps. Then I have done the geekbench compute benchmark (for graphics) for many times, got only about 65000, for example:

https://browser.geekbench.com/v4/compute/4424008

However, I noticed that lots of people have got a really high score for more than 90000:

https://browser.geekbench.com/v4/compute/4179987

I did some research and found that the "Compute Units" is only 12 on mine while others have 24.

From the [Intel-8809G Product Specifications](https://ark.intel.com/content/www/us/en/ark/products/130409/intel-core-i7-8809g-processor-with-radeon-rx-vega-m-gh-graphics-8m-cache-up-to-4-20-ghz.html), Vega M GH actually have 24 compute units.

I can't confirm whether it's geekbench's bug or hac-mini's bug.

**Comment by gaowenzhen** [comment]
my config.plist   > Properties
	<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>device-id</key>
				<data>
				32cAAA==
				</data>
			   <key>revision-id</key>
				<data>
				wgAAAA==
				</data>
			</dict>

**Comment by 22dm** [comment]
> my config.plist > Properties
> `<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key> <dict> <key>device-id</key> <data> 32cAAA== </data> <key>revision-id</key> <data> wgAAAA== </data> </dict>`

Wow, it works like a charm. Thanks.

**Comment by Dagvelo** [comment]
d

> my config.plist > Properties
> `<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key> <dict> <key>device-id</key> <data> 32cAAA== </data> <key>revision-id</key> <data> wgAAAA== </data> </dict>`

do i need to replace it with something else or just add it ?

**Comment by 22dm** [comment]
> d
> 
> > my config.plist > Properties
> > `<key>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)</key> <dict> <key>device-id</key> <data> 32cAAA== </data> <key>revision-id</key> <data> wgAAAA== </data> </dict>`
> 
> do i need to replace it with something else or just add it ?

replace the **<key>PciRoot(0)/Pci(1,0)/Pci(0,0)</key> <dict> ... </dict>** part

**Comment by osy86** [comment]
Anyone knows what happens if you run this on a NUC8i7HNK which only has 20 compute units? I will update the config to use this, but I don't want to break compatibility with NUC8i7HNK.
