### ISSUE TITLE
Thunderbolt: No drivers are loaded.

### ISSUE THREAD

**Issue by mokapsing** [osy86/HaC-Mini#300]
**Describe the bug**
In System Information, it shows "Thunderbolt: No drivers are loaded." 
![QQ20200723-0](https://user-images.githubusercontent.com/39441028/88292984-f2900000-cd2c-11ea-8c2b-0b1ed6d351fc.png)

**Expected behavior**
show the Thunderbolt correctly.

**Configuration**
- HaC Mini version: 2.10
- OSX version: 10.15.6 (19G73)
- NUC model: NUC8i7HVK
- Boot SSD model and protocol : Intel 760p m.2 nvme 512g
- Second SSD model and protocol (if installed): Intel 760p m.2 nvme 512g
- First DIMM model:  Kingsdon HyperX Impact DDR4 2666 8G
- Second DIMM model (if installed): Kingsdon HyperX Impact DDR4 2666 8G
- Display port(s) used: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 2K
- Any TB3 devices: No any device
- Any USB devices: Niz keyboard, Microsoft mouse, USB wifi, USB earphone

**Modifications**
 Just install the original HaC Mini 2.10, I installed it as below:
![image](https://user-images.githubusercontent.com/39441028/88293480-a42f3100-cd2d-11ea-8864-ce4c14c8a68e.png)

**Panic log**
N/A

**Comment by osy86** [comment]
That is the expected behaviour for legacy.

**Comment by mokapsing** [comment]
@osy86 But both Native(successfully patched) and Legacy mode have same behavior, is it expected?
