### ISSUE TITLE
All OS are represented as HardDrive.icns

### ISSUE THREAD

**Issue by DasXardas** [osy86/HaC-Mini#301]
**Describe the bug**
1. I have installed dual boot macOS 10.15.6 and Win10 x64, but both OS on boot screen is shown as a hard drive, not as Mac OS and Windows drive icon. Also, I can't change the boot entries with OpenCore configurator, because I see an empty list, but boot options are work perfectly.

2. Unable to patch installer of 10.16 Bug Sur with installer 2.10 (in customizing list is greyed option Patch Installer and cannot be selected)

**Expected behaviour**
1. Fix detection of OS drives (or Am I able to fix it manually, if yes how?) Also is possible to use 3rd party picker NDK for example, if yes, how? Because if I import NDK picker and edited plist to load it, so it is ignored, or shown only text selection, and also in OpenCore Editor are many options blank.

2. Fix installer 2.10 for Big Sur installation media patching.

**Configuration**
- HaC Mini version 2.10 
- OSX version 10.15.6 
- NUC model NUC8i7HVK 
- Boot SSD model and protocol Adata XPG Gammix S11 NVMe (macOS) 
- Second SSD model and protocol Adata SX8200PNP NVMe (Win10)

**Modifications**
I only tried to load NDK picker without success (screen of the plist included)

![obrazek](https://user-images.githubusercontent.com/50460934/88575448-2c6e4880-d044-11ea-9658-5e4a2b40f7f9.png)

**Comment by osy86** [comment]
1. This will not be a supported use case. You are free to ask the hackintosh community for help.
2. Big Sur will not support patched installer. Once Big Sur is released, the installation guide will be updated.
