### ISSUE TITLE
iMessage and FaceTime does't work

### ISSUE THREAD

**Issue by TheProjectM** [osy86/HaC-Mini#303]
**Describe the bug**
I have searched the Issue page about iMessage and FaceTime issues, got no results. I also have done some search on Google and Youtube & Baidu, tried to change the SN BSN and SmUUID twice and fresh install once, but still not work. Other frequently used services all worked well, such as iCloud, App Store, handoff, sidecar, airdrop...

**Expected behavior**
iMessage and FaceTime wrok.

**Configuration**

HaC Mini version [e.g: 2.0]: v2.0
OSX version [e.g: 10.14.6]: 10.15.6
Spoofing device: Mac mini 8,1
NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung 970 PRO 512G
Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]:
First DIMM model [e.g: Patriot DDR4-2666 16GB]: Corsair DDR4-2666 16GB
Second DIMM model (if installed): Corsair DDR4-2666 16GB
Display port(s) used [e.g: USB-C, mini DP]: HDMI
Display resolution(s) [e.g: 4K, 5K]: 4K
Any TB3 devices:
Any USB devices:

**Comment by osy86** [comment]
Run the hac mini installer again and select the option to regenerate identifiers.

**Comment by TheProjectM** [comment]
> Run the hac mini installer again and select the option to regenerate identifiers.

Okay， I will try this tonight and feedback tommorrow.

**Comment by TheProjectM** [comment]
> Run the hac mini installer again and select the option to regenerate identifiers.

I need to reinstall system right?   clean nvram first?

**Comment by TheProjectM** [comment]
Yesterday I had dong the following modifications but all didn't work (Region and Country set to China Mainland).
- change SN only
- reset nvram only
- regenerate identifiers and fresh install 
- use hacktools to generate an valid  SN BSN and SmUUID and use them.
- use hacktools to generate an invalid  SN BSN and SmUUID and use them.

Today morning I do a fresh install again, neither iCloud working now (Region and Country set to US).  Going to give up iMessage and FaceTime (ㄒoㄒ)

**Comment by TheProjectM** [comment]
It's not a big issue using without iMessage and FaceTime.

**Comment by xiaooloong** [comment]
在 nvram 功能正常的情况下，有可能是你的 Apple ID 账号受到限制了。

我有两个 Apple ID，其中一个是我在 iPhone 上一直使用的，这个 Apple ID 在我使用过的三台黑苹果上 iMessage 和 FaceTime 都正常使用。

另外一个 Apple ID 却一直无法使用，直到我在 iPhone 上登录过一次这个 Apple ID 并在 iPhone 上使用过 iMessage 和 FaceTime 之后，这个 Apple ID 在黑苹果上也可以正常使用了。
