### ISSUE TITLE
BCM94360CS2 Bluetooth but no WiFi

### ISSUE THREAD

**Issue by spillinova** [osy86/HaC-Mini#305]
**Describe the bug**
Both the BCM94360CS2 and the BCM94360CS with NGFF(M.2) Key A/E 2230 adapter do not show as a WiFi device in Mojave and Windows 10.  Bluetooth shows up and works in both OSs, but not WiFi.

**Expected behavior**
Expect Wifi to show up as network device in MacOS network settings.  Windows 10 driver installs and says "successful install", but WiFi device doesn't exist in network choices.

Tried refreshing NVRAM

**Configuration**
- HaC Mini version 2.10
- OSX version 10.14.6: 
- NUC model NUC8i7HVK: 
- Boot SSD model and protocol Sabrent 1TB Rocket NVMe PCIe M.2 2280: 
- First DIMM model OLOy DDR4 RAM 32GB 2666 MHz CL19 1.2V 260-Pin: 
- Second DIMM model OLOy DDR4 RAM 32GB 2666 MHz CL19 1.2V 260-Pin: 
- Display port(s) used HDMI: 
- Display resolution(s) 1080p: 

**Modifications**

**Panic log**

![Screen Shot 2020-08-07 at 5 39 56 PM](https://user-images.githubusercontent.com/5526129/89698267-22b2d380-d8d5-11ea-8b67-f0a9ff39b7f4.png)
![Screen Shot 2020-08-07 at 5 43 18 PM](https://user-images.githubusercontent.com/5526129/89698347-8a691e80-d8d5-11ea-8776-aa9e2d43bd96.png)
![Screen Shot 2020-08-07 at 5 38 16 PM](https://user-images.githubusercontent.com/5526129/89698269-23e40080-d8d5-11ea-97e8-9582bd96a442.png)
![Screen Shot 2020-08-07 at 5 39 25 PM](https://user-images.githubusercontent.com/5526129/89698270-25152d80-d8d5-11ea-8985-f896fb769898.png)

**Comment by KrisCris** [comment]
Have you tried to reinstall the card? This shouldn't be an OS issue.

**Comment by candyrock** [comment]
> **Describe the bug**
> Both the BCM94360CS2 and the BCM94360CS with NGFF(M.2) Key A/E 2230 adapter do not show as a WiFi device in Mojave and Windows 10. Bluetooth shows up and works in both OSs, but not WiFi.
> 
> **Expected behavior**
> Expect Wifi to show up as network device in MacOS network settings. Windows 10 driver installs and says "successful install", but WiFi device doesn't exist in network choices.
> 
> Tried refreshing NVRAM
> 
> **Configuration**
> 
> * HaC Mini version 2.10
> * OSX version 10.14.6:
> * NUC model NUC8i7HVK:
> * Boot SSD model and protocol Sabrent 1TB Rocket NVMe PCIe M.2 2280:
> * First DIMM model OLOy DDR4 RAM 32GB 2666 MHz CL19 1.2V 260-Pin:
> * Second DIMM model OLOy DDR4 RAM 32GB 2666 MHz CL19 1.2V 260-Pin:
> * Display port(s) used HDMI:
> * Display resolution(s) 1080p:
> 
> **Modifications**
> 
> **Panic log**
> 
> ![Screen Shot 2020-08-07 at 5 39 56 PM](https://user-images.githubusercontent.com/5526129/89698267-22b2d380-d8d5-11ea-8b67-f0a9ff39b7f4.png)
> ![Screen Shot 2020-08-07 at 5 43 18 PM](https://user-images.githubusercontent.com/5526129/89698347-8a691e80-d8d5-11ea-8776-aa9e2d43bd96.png)
> ![Screen Shot 2020-08-07 at 5 38 16 PM](https://user-images.githubusercontent.com/5526129/89698269-23e40080-d8d5-11ea-97e8-9582bd96a442.png)
> ![Screen Shot 2020-08-07 at 5 39 25 PM](https://user-images.githubusercontent.com/5526129/89698270-25152d80-d8d5-11ea-8985-f896fb769898.png)

I have a T440s the same issue. but it doesn't work on Windows and works perfectly on macOS

**Comment by spillinova** [comment]
> Have you tried to reinstall the card? This shouldn't be an OS issue.

Yeah. Cuz I have 2 cards (BCM94360CS2 and the BCM94360CS)...so I switched the cards and tried switching the antennas.

**Comment by candyrock** [comment]
> > Have you tried to reinstall the card? This shouldn't be an OS issue.
> 
> Yeah. Cuz I have 2 cards (BCM94360CS2 and the BCM94360CS)...so I switched the cards and tried switching the antennas.

Maybe due to adapter

**Comment by spillinova** [comment]
> > > Have you tried to reinstall the card? This shouldn't be an OS issue.
> > 
> > 
> > Yeah. Cuz I have 2 cards (BCM94360CS2 and the BCM94360CS)...so I switched the cards and tried switching the antennas.
> 
> Maybe due to adapter

Have you heard anything bad about this adapter? 

Deal4GO for Broadcom BCM94360CS2 BCM94360CD BCM943602CS BCM94331CD BCM943224P WLAN Card to NGFF(M.2) Key A/E 2230 Converter Adapter for Mac OS Hackintosh https://www.amazon.com/dp/B082Y4YPLZ/ref=cm_sw_r_cp_api_i_bSZlFbCMD0FT4

**Comment by spillinova** [comment]
BTW...thanks for all the replies! I may try another adapter. My BCM94360CS2 card is actually brand new and not a refurb...so I doubt that’s the problem, since I also tried a BCM94360CS and had the exact same problem.

**Comment by KrisCris** [comment]
Yeah, perhaps the adapter is not well-soldered.

**Comment by spillinova** [comment]
Confirmed...the adapter was bad.  New adapter and wifi card combo works perfectly.
