### ISSUE TITLE
How to uninstall the workaround for screen flickering?

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#307]
**Describe the bug**

In the latest hacmini update, I didn't select to install SLForceFPS, so I thought it was uninstalled... Until today I saw a lot crash reports about it.

<img width="1226" alt="Screen Shot 2020-08-13 at 3 02 49 PM" src="https://user-images.githubusercontent.com/38860226/90104199-6a72a880-dd76-11ea-9e66-09647a47c763.png">

**Expected behavior**
Way to uninstall it.

**Comment by KrisCris** [comment]
OK, I just deleted it from /usr/local/bin, wondering if this is the right way.

**Comment by osy86** [comment]
There is also a file in LaunchAgents I think. Or LaunchDaemons.

**Comment by KrisCris** [comment]
OK, I've removed that.
