### ISSUE TITLE
TB3 Device Coldplug, but no Hotplug in MacOS

### ISSUE THREAD

**Issue by spillinova** [osy86/HaC-Mini#309]
**Describe the bug**
Cannot hotplug Thunderbolt device (UAD Apollo Twin) in Mojave.  NUC only sees device if connected on boot.  Successful hotplug on Windows 10.

**Expected behavior**
Expected to be able to able to plug in TB3 device while OS is running.

**Configuration**
HaC Mini version 2.10
OSX version 10.14.6:
NUC model NUC8i7HVK:
Boot SSD model and protocol Sabrent 1TB Rocket NVMe PCIe M.2 2280:
First DIMM model OLOy DDR4 RAM 32GB 2666 MHz CL19 1.2V 260-Pin:
Second DIMM model OLOy DDR4 RAM 32GB 2666 MHz CL19 1.2V 260-Pin:

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by osy86** [comment]
Did you install the native thunderbolt patch?

**Comment by spillinova** [comment]
I chose the Legacy Thunderbolt driver when I installed HaCMini.pkg, but otherwise no other thunderbolt patches.  I assumed that because Legacy Thunderbolt was chosen by default, then that was all that was needed.

**Comment by spillinova** [comment]
> Did you install the native thunderbolt patch?

Done and done.  I patched it and now I'm all set.  Thanks!
