### ISSUE TITLE
FreeSync doesn't work 

### ISSUE THREAD

**Issue by piotrasd** [osy86/HaC-Mini#31]
I got monitor with FreeSync im activated that mode on Monitor, but no special option in settings of monitor appear, just to confirm I rebooted macOS, I did even test (because I was with maybe automatically is enabled when see compatible monitor but no :( )

maybe because is different pci-ids ? or something else ? 
any idea how to solve that ? 
https://forums.macrumors.com/threads/amd-polaris-vega-navi-gpu-macos-support.2083168/

website to test 
https://www.testufo.com/freesync#photo=quebec.jpg&pps=960&framerate=ramp&compare=1

**Comment by osy86** [comment]
I’m under the impression that OSX doesn’t support freesync period. Googling shows that maybe this changed recently for the newest cards but I highly doubt it would work for Baffin (which we are spoofing).

**Comment by osy86** [comment]
Can you provide link to a guide or tutorial where FreeSync is working on some other hackintosh so I can try to figure out the issue? I don't know if FreeSync works at all in OSX.

**Comment by macmeister1967** [comment]
I have FreeSync working on my Hack (i7-8700 + RX 580), no extra options appear in Displays prefpane :-|

Apple/AMD driver, does all the work silently in the background...

**Comment by iiicwx** [comment]
![Screenshot 2020-01-29 at 17 15 24](https://user-images.githubusercontent.com/56515855/73380547-8aec8100-42c4-11ea-9e93-c3ed21aabe76.png)
does this mean freesync enabled? I have a Benq EX3501R, which supports freesync and resolution is set as 3440*1440@100hz.

**Comment by osy86** [comment]
It’s not exactly clear to me how well that website works. My monitor is 60hz and supports freesync of 40-60hz. But that website looks the same for me on OS X and windows. As well as having freesync disables on Windows. If someone knows a better way to test freesync in OS X, I can try to fix the issue.

**Comment by osy86** [comment]
So there's actually no evidence that FreeSync DOESN'T work. Unless someone develops a adaptive sync test for OSX and/or packet sniff the DP port for the freesync packets, I am going to assume that the kernel code that sends the adaptive sync packets work fine.
