### ISSUE TITLE
Installer won't boot on i7HNK

### ISSUE THREAD

**Issue by danb35** [osy86/HaC-Mini#311]
**Describe the bug**
After creating the installer USB following the instructions at https://osy.gitbook.io/hac-mini-guide/installation-guide/installation#creating-osx-installer, on three different USB sticks, none of them will boot.  I get either a black screen with a message saying "A bootable device has not been detected", or the system boots into the existing Windows 10 installation, despite USB being set as the first boot priority.

**Expected behavior**
The installer boots.

**Environment:**
 - Running OSX version: 10.14.6
 - Target drive OSX version: 10.15.6
 - HaC Mini installer version: 2.10

**Additional context**
I created a Linux Mint USB--that booted just fine.  I used that to create an OpenCore installation USB following the instructions at https://dortania.github.io/OpenCore-Install-Guide/--that behaves the same as the HaC-mini installer USB.

I recall reading of a special procedure needed when Windows had been installed on the target machine, but I can't find a reference in the issues here.

**Logs**
N/A, doesn't get that far.

**Comment by osy86** [comment]
Can you double check you’re using GUID partitioning scheme? Also reset your bios settings.

**Comment by danb35** [comment]
Thanks for the response.  Yes, I used GUID partition tables on all three of the USB sticks; Disk Utility confirms that the last one I tried has a GUID Partition Map.  I reset the BIOS settings to defaults (F9 in the BIOS), made the three changes advised in the guide (secure boot, portable device charging, and Thunderbolt legacy mode), and tried to boot again.  Once more, it doesn't boot from the stick and goes directly to the SSD, even though the boot order has the USB device first (and it does recognize it, calling it "Opencore").

The machine came with BIOS 0058 installed, IIRC.  I updated to 0059 using the F7 menu.  The reset to defaults and updating those three settings were done after the update.

I'm thinking my next step might be to remove the SSD from the machine and see if it will boot then--it shouldn't work that way, but it would rule out boot order as a possibility.

**Comment by danb35** [comment]
> I recall reading of a special procedure needed when Windows had been installed on the target machine, but I can't find a reference in the issues here.

OK, I found what I'd been thinking of: https://osy.gitbook.io/hac-mini-guide/post-installation/support#only-boot-entry-is-windows-boot-manager  I opened the case, removed that jumper, and even re-installed BIOS 0059 from that menu.  That didn't change the results.

I think the next thing I'll try, unless I hear other recommendations before tomorrow, is toss a spare SATA SSD in a USB enclosure, remove the NVMe SSD, and see if I can boot from the USB stick with the USB SSD connected--and if so, see if I can install to that.

**Comment by osy86** [comment]
You should be good but it's extremely odd that your system didn't boot properly from the USB. I can't think of anything except maybe hardware issues.

**Comment by fwchen** [comment]
> All right, it appears to be working now, but it took a bit of doing. Here's kind of a brain dump of how I got here:
> 
> Will not boot from HaC Mini USB with NVMe SSD installed.
> 
> * USB in multiple ports
> * Any boot priority
> * Using F10 menu
> * With SSD in either slot
> 
> Removed NVMe SSD. Plugged a spare SATA SSD into a USB HDD dock, plugged that into the NUC:
> 
> * Installer USB booted just fine
> * Disk Utility saw the external SSD, partitioned it, formatted it
> * Installer saw the external SSD and installed to it
> * Installation completes (two reboots), but system doesn't boot from external SSD without USB stick installed.
>   
>   * Gives "A bootable device has not been detected"
>   * With USB installed, though, it boots from the SSD
>   * Downloaded HaC Mini onto this system, installed it to boot SSD
>   * Still won't boot without installer USB
>   * Changed BIOS setting, checked box for "boot USB first", now it boots from external SSD without installer USB (?)
> * Now that it boots from external SSD, powered down and reinstalled NVMe SSD (in original slot).  Reconnected external SSD, powered up, and it boots from the external SSD.
> * Disk Utility--erase NVMe SSD, APFS, GUID
> * Power down, remove external SSD, reconnect installer USB
> * Won't boot again--back to "A bootable device has not been detected".  F10 menu shows only the USB (listing it as "OpenCore"), but when I select that, the screen flashes black for a split second and then returns.
> * Power down, connect external SSD--it boots
> * Boot picker, select "Install macOS Catalina"
> * Install to NVMe SSD, reboot a few times
> 
> Result: The system now boots Catalina from the internal NVMe SSD, without either the USB stick or the external SSD connected. I'm not entirely clear why (or even whether) I needed to do all this in this order, but the result seems to be what I wanted. Is there anything I should be checking before I'd close this?

OMG, that's too complicated. 🤣
