### ISSUE TITLE
Black display on boot with Radeon 5700 XT in eGPU via Native Thunderbolt 3 patch

### ISSUE THREAD

**Issue by rolsanmordua** [osy86/HaC-Mini#312]
**Describe the bug**
Machine boots but there is no output to the two connected monitors (1x HDMI, 1x DisplayPort) via the eGPU that contains a Gigabyte Radeon RX 5700 XT 8 GB in Sonnet Breakaway Box 550. Machine is accessible via VNC, can run Sidecar, and even shows the eGPU-connected icon in the menu bar that reads Radeon RX 5700 XT but no output. 

**Expected behavior**
Should be able to see desktop and machine booting with monitors connected via eGPU. 

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.11
- OSX version [e.g: 10.14.6]: macOS 10.15.6 (19G73)
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: WD Black SN750 1 TB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: ADATA SX8200 (Windows) 1 TB
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Samsung DDR4-2666 32 GB
- Second DIMM model (if installed): Samsung DDR4-2666 32 GB
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 2x LG 4K via eGPU via Thunderbolt 3
- Any TB3 devices: Sonnet Breakaway Box 550
- Any USB devices: USB keyboard

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

Boot-args: 
```alcid=11 -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 -radcodec igfxmetal=1```

**Panic log**
Include a screenshot of the panic message if applicable.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/6589634/90802590-1703db80-e2dd-11ea-8660-a8c87b4d0b2c.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/6589634/90802656-2edb5f80-e2dd-11ea-9afc-0499ec3f8b78.png">

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/6589634/90802693-3ac72180-e2dd-11ea-94c8-2f4423f06817.png">

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/6589634/90802720-44e92000-e2dd-11ea-931f-8b17819b3c3c.png">

**Comment by osy86** [comment]
Try `agdpmod= ignore`

**Comment by rolsanmordua** [comment]
Can confirm ```agdpmod=ignore``` works _with_ WhateverGreen installed. Big thanks to @osy86!

**Comment by goodbest** [comment]
@rolsanmordua Glad to hear that egpu is working now.

Can you share your egpu （on nuc and on your macbook） benchmark with geekbench5 or luxmark？
It will be great for potential egpu buyers.😁

**Comment by rolsanmordua** [comment]
@goodbest thanks! Sure here's the benchmarks: 

[**MacBook Pro 15" (2018), i7-8850H w/ Sonnet Breakaway Box 550 + Gigabyte Radeon RX 5700 XT 8 GB**](https://browser.geekbench.com/v5/compute/1379594)

[**NUC8i7HVK, i7-8809G w/ Sonnet Breakaway Box 550 + Gigabyte Radeon RX 5700 XT 8 GB**](https://browser.geekbench.com/v5/compute/1383280)

[**NUC8i7HVK's built in Radeon RX Vega M GH**](https://browser.geekbench.com/v5/compute/1007264)

[My prev setup: **NUC8i7BEH, i7-8559U w/ Sonnet Breakaway Box 550 + PowerColor Red Dragon RX 580 8 GB**](https://browser.geekbench.com/v5/compute/6862)
