### ISSUE TITLE
No regenerate identifiers option

### ISSUE THREAD

**Issue by Xuemuyang** [osy86/HaC-Mini#317]
**Describe the bug**

I don't have regenerate identifiers option

**Expected behavior**

There is a regenerate identifiers option to choose

**Environment:**
 - Running OSX version: 10.15.6
 - Target drive OSX version: 10.15.6
 - HaC Mini installer version: v2.11

**Additional context**

![image](https://user-images.githubusercontent.com/25718776/90981318-dc2acd80-e592-11ea-8362-d09f9804dcee.png)

**Logs**
Please attach `/var/log/install.log`

**Comment by osy86** [comment]
It is "减少屏幕闪烁" in Chinese.

**Comment by lmshsqlc** [comment]
I will try to get it updated in 16 hours.
