### ISSUE TITLE
The screen flickers after upgrading v2.11 and can not be solved in macos big sur

### ISSUE THREAD

**Issue by dockeyZhang** [osy86/HaC-Mini#318]
I use two monitors, they are 4K and 1080P. Everything is fine when I use the v2.10 version in MacOS 10.15.6. After upgrading to v2.11, the 4K monitor severely flicker. If I check the reduce flicker option, it can work in 10.15.6. 

But I don't want to influence my CPU speed and the v2.11 update log shows that the problem has been solved in macOS Big Sur. So I upgraded macOS 10.15.6 to macOS big sur, but the flickering problem is still not solved. What's worse is that my WIFI of DW1820A cannot be used under big sur, and the startup and shutdown time is very long.

**Comment by osy86** [comment]
> So I upgraded macOS 10.15.6 to macOS big sur, but the flickering problem is still not solved.

That is unfortunate. I will have to do more testing.

**Comment by xiaooloong** [comment]
same the issue. i am using 10.15.6 and have a flickering problem on my 4k screen with displayport after upgrading to 2.11. everything is fine when i was using 2.10.

screen keeps flickering after downgrade to 2.10.

**Comment by xiaooloong** [comment]
> same the issue. i am using 10.15.6 and have a flickering problem on my 4k screen with displayport after upgrading to 2.11. everything is fine when i was using 2.10.
> 
> screen keeps flickering after downgrade to 2.10.

i had two screens, one is 4k and the other is 1080p.
the 4k monitor stop flickering after i disconnect the 1080p screen.
