### ISSUE TITLE
Preview jpg freeze after sleep

### ISSUE THREAD

**Issue by franzbu** [osy86/HaC-Mini#32]
Preview freeze bug is only gone after fresh boot. After waking from sleep it's still there.

**Comment by franzbu** [comment]
NUC8i7HNK, MacOS 10.14.6, added Thunderbolt3Unblocker.kext to /Library/Extensions (issue happens also without any
[CLOVER.zip](https://github.com/osy86/HaC-Mini/files/3552177/CLOVER.zip)
 thunderbolt devices attached)

**Comment by franzbu** [comment]
just tested; doesn't make a difference

**Comment by osy86** [comment]
Can you check if igpu is working after sleep? Easiest way is to use intel power gadget and look at the gpu line when watching an iTunes trailer and see if it goes up.

**Comment by franzbu** [comment]
running iTunes trailer on Safari:

1st screenshot: after reboot (preview with jpg working)
2nd screenshot: after sleep (preview freeze)

Intel GFX doesn't seem to be involved either way, but maybe you can see a difference:

![1](https://user-images.githubusercontent.com/54638185/63958611-f7035880-ca8a-11e9-8942-91b0633c70eb.png)
![2](https://user-images.githubusercontent.com/54638185/63958612-f7035880-ca8a-11e9-9a7e-32271aee0d48.png)

**Comment by osy86** [comment]
Sorry I wasn’t clear. I mean watch a trailer from the iTunes app both before and after sleep. When igpu works you should see the graph go up for frequency for gfx. 

Anyways I don’t see WhateverGreen in your kext. Are you using 1.3?

**Comment by franzbu** [comment]
Been watching several trailes on the iTunes app, but even after reboot (jpg on Preview working) there is not GFX activity in intel power gadget.

**Comment by osy86** [comment]
Can you play around with the workarounds in this thread? https://github.com/osy86/HaC-Mini/issues/18

**Comment by franzbu** [comment]
After changing SMBIOS to iMac18,3, iTunes trailers make use of Intel GFX, but after sleep also iTunes freezes in addition to the Preview jpg freeze.

**Comment by osy86** [comment]
Are you using the 1.3 release?

**Comment by franzbu** [comment]
You're talking about Whatevergreen, right? Neither 1.3.0 nor 1.3.1 work, am only getting bootloops. Don't want to use Whatevergreen without Polaris22MetalFixup.kext.

**Comment by osy86** [comment]
I’m talking about https://github.com/osy86/HaC-Mini/releases

**Comment by franzbu** [comment]
Yes, Hac-Mini 1.3

**Comment by piotrasd** [comment]
Franzbu check with this
`			<dict>
				<key>Comment</key>
				<string>10.14.3-KBL-ComputeLaneCount</string>
				<key>Find</key>
				<data>SP8FJFcHAA==</data>
				<key>MatchOS</key>
				<string>10.14.3</string>
				<key>Name</key>
				<string>com.apple.driver.AppleIntelKBLGraphicsFramebuffer</string>
				<key>Replace</key>
				<data>uAEAAADrdQ==</data>
			</dict>`

Put into section KernelToPatch

**Comment by osy86** [comment]
They’re not on 10.14.3

**Comment by piotrasd** [comment]
the patch applied correctly and I had same issue, I don't see any other changes, related in my config, but im not experience anymore. I will starts track my changes and post here.

**Comment by franzbu** [comment]
Unfortunately, patch doesn't help. Still igpu not working (neither before nor after sleep). Also preview jpg freeze after sleep.

**Comment by piotrasd** [comment]
ok i will track down my changes what fixed issue, im also loosed Intel QSV but I have Full AMD acceleration everywhere, but im looking combo solution. im just tested so many solution now I need to revert everything one by one

**Comment by franzbu** [comment]
Inclusion of Whatevergreen still resulting in bootloop, but HECI to IMEI patch in config.plist seems to solve preview jpg freeze after waking from sleep.

**Comment by osy86** [comment]
Boot loop only with WG? No bootloop otherwise?

**Comment by franzbu** [comment]
That's right. Putting Whatevergreen (I used the one from 1.4) into Clover/kexts/other causes the system to bootloop.However, seems I have a working system without WG: as I've already stated, your HECI to IMEI patch solves preview freeze after sleep and with iMac19,2 in SMBIOS igpu is working (before and after sleep).
--

**Comment by franzbu** [comment]
That's right. Putting Whatevergreen (I used the one from 1.4) into Clover/kexts/other causes the system to bootloop.However, seems I have a working system without WG: as I've already stated, your HECI to IMEI patch solves preview freeze after sleep and with iMac19,2 in SMBIOS igpu is working (before and after sleep).
--

**Comment by piotrasd** [comment]
@franzbu ok you found faster my solution which fix frezzes :) I know some of my changes fixed issue but I didn't know which one.
