### ISSUE TITLE
SUGGESTION: incorporate stable release of OpenIntelWireless itlwm(x) and IntelBluetooth

### ISSUE THREAD

**Issue by Malumen** [osy86/HaC-Mini#322]
Hi @osy86 !

This recent iteration (2.11) has been great. Everything is running smoothly in my macOS 1.14.6 Mojave setup.

Was wondering if the installer can roll-in [OpenIntelWireless](https://github.com/OpenIntelWireless) project's [itlwm(x)](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.0.0) (along with adding in release [1.1.2](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/tag/1.1.2) of IntelBluetoothFirmware). Note that _if_ the user installs either itlwm or itlwmx, then it should also install [HeliPort ](https://github.com/OpenIntelWireless/HeliPort/releases/tag/v1.0.0) for easy WiFi control by the user.

It would be an "exclusive OR" checkmark, as users cannot use both `itlwm` and `itlwmx` at the same time. The default for the original WiFi m.2 that comes with the Intel Hades Canyon NUC should be `itlwm`.

Note: these kexts provide WiFi speeds for 5GHz best, and max out around `80 megabit` _download_ and `20 megabit` _upload_. This is "good enough" for average internet use.

**Comment by keatliang2005** [comment]
@Malumen Great suggestion +1 for this

i would like to see this as an option for the HaC-Mini release, as i still using stock intel wireless

**Comment by osy86** [comment]
Is there any point making `itlwmx` an option if `itlwm` works for the stock card?

**Comment by Malumen** [comment]
> Is there any point making `itlwmx` an option if `itlwm` works for the stock card?

I swapped out the Hades Canyon native WiFi into my gf's laptop (she had a dead Killer chip) and bought myself the AX200 for 10$ off a mass supplier... In Windows, WiFi 6 support and BT 5.0 are great, so far the connection and clarity and range in macOS has been incredible (really good range and connection so far on everything, may even be better than Windows).

**Comment by Malumen** [comment]
@osy86 

FYI the _OpenIntelWireless_ project has merged the `itlwm` and `itlwmx` versions into one unified solution. It now *requires* the additional software "HeliPort" but now you wouldn't need to split the installer versions, just 1 option.

[https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0)

**Comment by osy86** [comment]
@Malumen Is it better to include `itlwm` or `AirportItlwm`? Seems like `AirportItlwm` doesn't require HeliPort

**Comment by Malumen** [comment]
> @Malumen Is it better to include `itlwm` or `AirportItlwm`? Seems like `AirportItlwm` doesn't require HeliPort

if I understand correctly, `AirportItlwm` requires users to write in their SSID and password info into the kext itself rather than `itlwm` and Heliport which allows the user to connect/switch using the App/GUI.

**Comment by keatliang2005** [comment]
current latest master commit from itlwm, already support WPA2, unfortunately not yet build into release yet
