### ISSUE TITLE
Restart after wakeup and get panic(cpu 2 caller 0xffffff7f9319b231): nvme: "Fatal error occurred.

### ISSUE THREAD

**Issue by XiaoLong1473** [osy86/HaC-Mini#326]
After waking up, it restarted and an nvme error occurred. The number of the cpu changes randomly. 
The Nvmefix.kext has been installed. The wireless mouse is plugged into the front blue USB.
The wifi card is DW1820A.

**Configuration**
- HaC Mini version: V2.11 
- OSX version: 10.15.6
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: Hikvision HS-SSD-C2000L 1024GB Media
- Second SSD model and protocol (if installed): No 
- First DIMM model: Hynix DDR4-2666 16GB
- Second DIMM model (if installed): No
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: No
- Any USB devices: No

**Modifications**
No Modifications

**Panic log**

panic(cpu 2 caller 0xffffff7f9319b231): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0xb5 VID=0x1987 DID=0x5013
. FW Revision=EDFM00E2\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.100.17/IONVMeController.cpp:5320
Backtrace (CPU 2), Frame : Return Address
0xffffff8203113a40 : 0xffffff800f31a65d 
0xffffff8203113a90 : 0xffffff800f454a75 
0xffffff8203113ad0 : 0xffffff800f4465fe 
0xffffff8203113b20 : 0xffffff800f2c0a40 
0xffffff8203113b40 : 0xffffff800f319d27 
0xffffff8203113c40 : 0xffffff800f31a117 
0xffffff8203113c90 : 0xffffff800fac1abc 
0xffffff8203113d00 : 0xffffff7f9319b231 
0xffffff8203113d20 : 0xffffff7f93186362 
0xffffff8203113e80 : 0xffffff7f931861a9 
0xffffff8203113ec0 : 0xffffff800f35c605 
0xffffff8203113f40 : 0xffffff800f35c131 
0xffffff8203113fa0 : 0xffffff800f2c013e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[28183FA3-6A50-3611-BC20-A0717B657AAC]@0xffffff7f93178000->0xffffff7f931bafff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[5922E20B-D148-30DC-ABBA-0E99B3BE6940]@0xffffff7f8fff9000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[DF219CC1-366A-31FC-B8ED-17C584BA2549]@0xffffff7f900b3000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[D9C4809C-7B20-3663-A9C8-4DBC261AAD86]@0xffffff7f902bb000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[3581A46A-F3F3-3CE7-BA52-7046E8D66C32]@0xffffff7f8fc65000
            dependency: com.apple.iokit.IOReportFamily(47)[8F7948CF-5C25-33F4-A687-67F8A5B7906E]@0xffffff7f8fc9f000

BSD process name corresponding to current thread: kernel_task
Boot args: alcid=11 -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 -radcodec igfxmetal=1

Mac OS version:
19G2021

Kernel version:
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
Kernel slide:     0x000000000f000000
Kernel text base: 0xffffff800f200000
__HIB  text base: 0xffffff800f100000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 1496576440325

**Comment by candyrock** [comment]
try NVMefix.kext maybe help your issue

**Comment by XiaoLong1473** [comment]
> try NVMefix.kext maybe help your issue

I have tried Nvmefix.kext. Unfortunately, nothing changed.

**Comment by candyrock** [comment]
> > try NVMefix.kext maybe help your issue
> 
> I have tried Nvmefix.kext. Unfortunately, nothing changed.

You have to change other SSD.

**Comment by XiaoLong1473** [comment]
> You have to change other SSD.

After testing, using the power button to wake up seems no problem. Can't wake up with mouse or keyboard.

**Comment by Good0007** [comment]
Hikvision C2000L is very bad SSD (I've had this problem) ,Just change it. By the way, the WD SN750 is a good choice

**Comment by XiaoLong1473** [comment]
> Hikvision C2000L is very bad SSD (I've had this problem) ,Just change it. By the way, the WD SN750 is a good choice

I've tried Toshiba's SSD before. It can not wakeup with mouse or keyboard too. Can you wakeup with 2.4G HZ wireless mouse or keyboard in nuc hvk? I can wake it up successfully with the power button.

**Comment by osy86** [comment]
Unfortunately, this issue is outside the scope of the project. It seems to be either an issue with the NVMe or macOS's drivers. I would recommend asking the wider hackintosh community for help. Maybe the maintainers of the NVMefix.kext.

**Comment by Likenttt** [comment]
WD SN530 doesn't work on a1708 as well.
