### ISSUE TITLE
Installer Guide need to be updated for DW1820A

### ISSUE THREAD

**Issue by YucongDing** [osy86/HaC-Mini#329]
If users use DW1820A wireless card, they should go to BIOS and disable `Power > PCIE ASPM` option. If you enable this option, the instaaller will stuck at the Apple Logo and display a X.

**Comment by osy86** [comment]
Done https://github.com/osy86/HaC-Mini/commit/22a6159ef4d94c4e1f5e5f97c4106f629505366d
