### ISSUE TITLE
issue with v2.12

### ISSUE THREAD

**Issue by candyrock** [osy86/HaC-Mini#330]
Hi @osy86. I have tried a new version and I can not boot with version 2.12 but boot fine with v2.11. I also noticed the last version lilu + weg breaks stuttering fix

HaC Mini version: The last release
OSX version: 10.14.6
NUC model: NUC8i7HVK
Boot SSD model and protocol Samsung 970 Evo +
Second SSD model and protocol (if installed):
First DIMM model: Crucial DDR4 8GB
Second DIMM model (if installed): Crucial DDR4 8GB
Display port(s) used [e.g: USB-C, mini DP]: HDMI, USB C, mini DP
Display resolution(s) [e.g: 4K, 5K]: 4K
Any TB3 devices:
Any USB devices: mouse and keyboard

**Comment by osy86** [comment]
Can you boot with verbose mode and take a picture of where it gets stuck?

**Comment by candyrock** [comment]
> Can you boot with verbose mode and take a picture of where it gets stuck?
it can not boot with verbose because it gets stuck at the boot picker when I chose a drive.

**Comment by candyrock** [comment]
> Can you boot with verbose mode and take a picture of where it gets stuck?

it can not boot with verbose because it gets stuck at the boot picker when I chose a drive.

**Comment by osy86** [comment]
I reuploaded v2.12 with a fix. Please give it a try.

**Comment by candyrock** [comment]
> I reuploaded v2.12 with a fix. Please give it a try.

It works but it still breaks stuttering fix

**Comment by osy86** [comment]
Is it working with just Lilu and WG downgraded to the last version? On my machine everything works fine.

**Comment by candyrock** [comment]
> Is it working with just Lilu and WG downgraded to the last version? On my machine everything works fine.

yes v2.11 works perfectly

**Comment by osy86** [comment]
There are many KEXT changes from v2.11. I’m asking if it’s only WG and Lilu that causes you issues.

**Comment by candyrock** [comment]
> There are many KEXT changes from v2.11. I’m asking if it’s only WG and Lilu that causes you issues.

yes. only WG and Lilu have issues.

**Comment by candyrock** [comment]
Can you try v.2.12 with a usb boot?

**Comment by osy86** [comment]
Yes I tested v2.12 with a USB on 10.14 10.15 and 11.0

**Comment by candyrock** [comment]
> Yes I tested v2.12 with a USB on 10.14 10.15 and 11.0

nevermind. I can use the old kext. thank you so much
