### ISSUE TITLE
Graphic glitches (no flicker)

### ISSUE THREAD

**Issue by cubytz** [osy86/HaC-Mini#331]
Thank you for the great repo and all the tremendous work you did put into this!

**Describe the bug**
I installed my NUC using the latest version of HaC-Mini. After few clicks here and there, everything worked well. The graphic card (AMD Radeon RX Vega M GH 4 GB) is recognized and my 4K monitor connected to HDMI on the back works. But I notice glitches (no flicker) when objects move through the screen, for example when I scroll or move a window.

I [made a video](https://www.youtube.com/watch?v=KsIG6NWlLPk) to show what I mean. 

**Things I tried**
- I read the exiting issues regarding glitches and flickering.
- I tried to change my configuration from Mac mini 2018 to iMac 5K 2017

Nothing worked so far. But, no problem when using windows 10.

I'm wondering if anyone has or had this issue. Thank you in advance for your help and sorry if I overlooked something obvious!

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.1.2
- OSX version [e.g: 10.14.6]: 10.15.6
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: WD Black SN750 NVMe 1TB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: addlink SSD 1TB S70 M.2
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Crucial 8GB DDR4-2400 SODIMM
- Second DIMM model (if installed): Crucial 8GB DDR4-2400 SODIMM
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: Lenovo BCM94350

**Comment by osy86** [comment]
To be clear, you’re saying the “flickering workaround” option in the installer did not work? Can you try manually running `SLForceFPS -r 20`?

**Comment by cubytz** [comment]
@osy86 Thank you for the quick reply! I just tried, no changes!

**Comment by osy86** [comment]
Which part did you try? Both? Post the output of the command.

**Comment by cubytz** [comment]
I tried running the command manually. No luck. Again, my screen do not flicker, it glitches as you can see in the video. Have you experience this?

**Comment by osy86** [comment]
Yeah glitches/flickering is the same thing to me. I don’t know what the cause is though or if there are multiple different causes. But the effect looks like what I see.

**Comment by cubytz** [comment]
I updated my NUC using 2.12 and the graphical glitches are gone! Thank you for the great work on this! I am closing this issue.
