### ISSUE TITLE
Is it safe to run security updates and are there any necessary steps to take after updating?

### ISSUE THREAD

**Issue by bosbode** [osy86/HaC-Mini#332]
Hi,

This is my fist hackintosh (hac-mini). And I was wondering if it is safe to run security updates and are there any necessary steps to take after updating?

I couldn't find an answer for this anywhere in the guide.

Thanks in advance.

**Comment by osy86** [comment]
Yes it’s safe but for major updates like macos 11 check here for other people’s results.
