### ISSUE TITLE
Failed to start Windows, and Internal Error with Boot Camp

### ISSUE THREAD

**Issue by YucongDing** [osy86/HaC-Mini#333]
**Describe the bug**
I followed the Installation Guide step by step. But when I use Boot Camp to install Windows, it hints Boot Camp encountered an internal error.
![Screen Shot 2020-09-20 at 11 18 33](https://user-images.githubusercontent.com/6185107/93693485-0a201500-fb33-11ea-8568-6766299fb566.png)
Then I use WinPE to install Windows, after installing windows, it restart to start with Windows, then Windows hinted "ACPI_BIOS_ERROR".
Also I failed to upgrade to macOS Big Sur in Mojave.

**Expected behavior**
It should be able to switch macOS and Windows smoothly.

**Configuration**
- HaC Mini version [e.g: 2.0]: latest
- OSX version [e.g: 10.14.6]: 10.15.6
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung PM961 1T NVME macOS
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: WDC SN550 1T NVME Windows
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Team DDR4-2666 16GB
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 2K
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]:  DW1820A

**Modifications**
None

**Panic log**

**Comment by cyuet** [comment]
Dual SSD can’t run boot camp, you have to remove one first

**Comment by YucongDing** [comment]
Ok I know，thanks bro.

**Comment by osy86** [comment]
Closing since this is a macOS issue.
