### ISSUE TITLE
The display is broken after upgrade os to 11 beta7/8

### ISSUE THREAD

**Issue by havvk** [osy86/HaC-Mini#334]
**Describe the bug**
When right click application in dock, the right edge of menu displays masks :
![image](https://user-images.githubusercontent.com/8110260/93782660-6b440780-fc5d-11ea-91e9-79de7d88678a.png)

When switch task(Command+Tab), the icon displays masks:
![image](https://user-images.githubusercontent.com/8110260/93783087-e60d2280-fc5d-11ea-8afa-13ded1c544b3.png)

**Expected behavior**
It should display the image correctly.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.12
- OSX version [e.g: 10.14.6]: 11.0 Beta (20A5374g)
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: WDC PC SN720 SDAPNTW-512G,NVMe
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: KXG50PNV2T04 TOSHIBA,NVMe
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Micron DDR4-3200 16GB  (set 3067Mhz in BIOS)
- Second DIMM model (if installed): Micron DDR4-3200 16GB (set 3067Mhz in BIOS)
- Display port(s) used [e.g: USB-C, mini DP]: MiniDP
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: No.
- Any USB devices: No.
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: No.

**Comment by osy86** [comment]
Can you reinstall v2.12?

**Comment by havvk** [comment]
> Can you reinstall v2.12?

I reinstalled it just now. After reboot, this issue still exists.

**Comment by fupoaiwo** [comment]
> > 可以重新安装 v2.12 吗？
> 
> 我刚刚重新安装了它。重新启动后，此问题仍然存在。

me tooooooooooo。有点后悔升级了

**Comment by goodbest** [comment]
> > > 可以重新安装 v2.12 吗？
> > 
> > 
> > 我刚刚重新安装了它。重新启动后，此问题仍然存在。
> 
> me tooooooooooo。有点后悔升级了

Do you have HNK or HVK?
If you are using HNK and have this issue, I'd assume that the current same patch won't work for HNK and HVK at the same time？

**Comment by havvk** [comment]
> > > > 可以重新安装 v2.12 吗？
> > > 
> > > 
> > > 我刚刚重新安装了它。重新启动后，此问题仍然存在。
> > 
> > 
> > me tooooooooooo。有点后悔升级了
> 
> Do you have HNK or HVK?
> If you are using HNK and have this issue, I'd assume that the current same patch won't work for HNK and HVK at the same time？

I have both NUC8i7HNK and NUC8i7HVK. There are the same issue on these two computers.

**Comment by fupoaiwo** [comment]
> > > > > 可以重新安装 v2.12 吗？
> > > > 
> > > > 
> > > > 我刚刚重新安装了它。重新启动后，此问题仍然存在。
> > > 
> > > 
> > > me tooooooooooo。有点后悔升级了
> > 
> > 
> > Do you have HNK or HVK?
> > If you are using HNK and have this issue, I'd assume that the current same patch won't work for HNK and HVK at the same time？
> 
> I have both NUC8i7HNK and NUC8i7HVK. There is the same issue on these two computers.

我的屏是4K 的。难道 4K才会有这种问题？bate 6 是没有问题 ，升级bate7  才出现的。 苹果今天又有新版本推送了。我再升级试试看吧

**Comment by havvk** [comment]
> > > > > > 可以重新安装 v2.12 吗？
> > > > > 
> > > > > 
> > > > > 我刚刚重新安装了它。重新启动后，此问题仍然存在。
> > > > 
> > > > 
> > > > me tooooooooooo。有点后悔升级了
> > > 
> > > 
> > > Do you have HNK or HVK?
> > > If you are using HNK and have this issue, I'd assume that the current same patch won't work for HNK and HVK at the same time？
> > 
> > 
> > I have both NUC8i7HNK and NUC8i7HVK. There is the same issue on these two computers.
> 
> 我的屏是4K 的。难道 4K才会有这种问题？bate 6 是没有问题 ，升级bate7 才出现的。 苹果今天又有新版本推送了。我再升级试试看吧

I have a display which resolution is 2560*1440. It still happened on it.

**Comment by goodbest** [comment]
@havvk @fupoaiwo 
Do you have this issue with beta7/8, but didn't have the issue with beta6?

Can you upload the file `/System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/AMDMTLBronzeDriver` to somewhere, so that we can see if anything changed in beta7 that makes the hot-patch not working.

**Comment by havvk** [comment]
> @havvk @fupoaiwo
> Do you have this issue with beta7/8, but didn't have the issue with beta6?
> 
> Can you upload the file `/System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/AMDMTLBronzeDriver` to somewhere, so that we can see if anything changed in beta7 that makes the hot-patch not working.

I didn't have this issue with beta6

**Comment by havvk** [comment]
Can we fix it by replacing AMDMTLBronzeDriver.bundle with the one from beta6?

**Comment by goodbest** [comment]
That is quite unexpected. We need more work to do.
Not sure whether AAPL relocate the metal driver to another path, or it's just a bug in beta7/8.

You can just try putting the beta6 binary into that folder to see if works again, however the possibility is low.
[AMDMTLBronzeDriver.zip](https://github.com/osy86/HaC-Mini/files/5268809/AMDMTLBronzeDriver.zip)

**Comment by osy86** [comment]
I think the offset changed. I’ll look into it this weekend.

**Comment by havvk** [comment]
> That is quite unexpected. We need more work to do.
> Not sure whether AAPL relocate the metal driver to another path, or it's just a bug in beta7/8.
> 
> You can just try putting the beta6 binary into that folder to see if works again, however the possibility is low.
> [AMDMTLBronzeDriver.zip](https://github.com/osy86/HaC-Mini/files/5268809/AMDMTLBronzeDriver.zip)

Unfortunately it doesn't work.
Maybe we should replace AMDMTLBronzeDriver.bundle instead of AMDMTLBronzeDriver ?

**Comment by havvk** [comment]
> That is quite unexpected. We need more work to do.
> Not sure whether AAPL relocate the metal driver to another path, or it's just a bug in beta7/8.
> 
> You can just try putting the beta6 binary into that folder to see if works again, however the possibility is low.
> [AMDMTLBronzeDriver.zip](https://github.com/osy86/HaC-Mini/files/5268809/AMDMTLBronzeDriver.zip)

IT WORKS!!!!!!
After put your file into /System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/, this issue disappeared. 

But we can not copy file into  /System easily.
We should mount / writable first.

We can mount / RW by following this video:
https://www.youtube.com/watch?v=oe2ySAadBf4&t=45s

Or this steps
```
1.Mount EFI partition

2.Modify config.plist
at NVRAM section，set csr-active-config to FF0F0000 ；
at MISC secion，turn Boot Protection to None。

3.reboot into recovery mode，open Terminal and input：
mount -uw /Volumes/SYS     (Replace all the string “SYS” in this guide with your disk volume name）
/System/Library/Filesystems/apfs.fs/Contents/Resources/apfs_systemsnapshot -v /Volumes/SYS -r ""
diskutil apfs listsnapshots /Volumes/SYS
diskutil apfs deletesnapshot /Volumes/SYS -uuid <here is the uuid list in the result of last command>
diskutil apfs listsnapshots /Volumes/SYS   ##check snapshot list again, until all of the snapshots were deleted.

4.reboot into normal mode.
Mount / writable using hackintool.
Or execute the following command in Terminal:

spctl --master-disable
mount -uw /

That's all.

```

**Comment by mr-vito** [comment]
@havvk Did your method also solve #316 ? I can see you are using a DisplayPort over HDMI 🤔

**Comment by havvk** [comment]
> @havvk Did your method also solve #316 ? I can see you are using a miniDisplayPort rather than HDMI 🤔

No, after put AMDMTLBronzeDriver into /System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/, the issue #316 happened.

But if I have this masks problem, the system menu borders will render correctly.

I'd rather have issue #316 instead of this.

**Comment by osy86** [comment]
Seems like in beta 7, Apple moved the binary to the shared cache in `/System/Library/dyld/dyld_shared_cache_x86_64h`. I'll have to re-enable the shared cache patching.
