### ISSUE TITLE
Does the native (flashed) Thunderbolt fix need any SSDT?

### ISSUE THREAD

**Issue by athei** [osy86/HaC-Mini#335]
While reading the Thunderbolt Fix [2](https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-2) and [3](https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-3) it does not become clear to me whether the SSDT from part 1 is still needed for proper sleep and hotplug.

Are those SSDTs are still needed for a flashed thunderbolt controller?

**Comment by osy86** [comment]
You need different ssdt. Apple thunderbolt needs some dsdt methods to manage stuff. In part 1 we fake these but for native support we use the ssdt directly from Apple.
