### ISSUE TITLE
Big Sur always restarts，Restart when booting to Apple logo

### ISSUE THREAD

**Issue by LockVer** [osy86/HaC-Mini#339]
hacmini:2.13
big sur beta 9
disk:sn750
1820a 
Restart when booting to Apple logo

**Comment by LockVer** [comment]
<img width="620" alt="QQ20201007-145256@2x" src="https://user-images.githubusercontent.com/3351118/95297404-00294080-08ad-11eb-9ced-2e906f166ad6.png">
<img width="620" alt="QQ20201007-145305@2x" src="https://user-images.githubusercontent.com/3351118/95297410-028b9a80-08ad-11eb-8a56-3a757bc60f28.png">
<img width="620" alt="QQ20201007-145312@2x" src="https://user-images.githubusercontent.com/3351118/95297415-04555e00-08ad-11eb-89b8-94d15a332712.png">

**Comment by osy86** [comment]
Can you boot into recovery and run `bless --folder "/Volumes/Macintosh HD/System/Library/CoreServices" --bootefi --personalize`. Replace `Macintosh HD` with your installation name.

**Comment by LockVer** [comment]
> Can you boot into recovery and run `bless --folder "/Volumes/Macintosh HD/System/Library/CoreServices" --bootefi --personalize`. Replace `Macintosh HD` with your installation name.

Unable to enter recovery mode, always restart

**Comment by osy86** [comment]
Are you able to get into the OC boot picker? https://osy.gitbook.io/hac-mini-guide/post-installation/support#getting-into-boot-picker-menu

**Comment by LockVer** [comment]
![16021179302813110669235264458186](https://user-images.githubusercontent.com/3351118/95402577-a7a48280-0942-11eb-8eb6-100dbdb2c6cb.jpg)
![16021179766448039185755292451793](https://user-images.githubusercontent.com/3351118/95402615-c30f8d80-0942-11eb-9f0f-5bf631407f95.jpg)
It's still the same

**Comment by osy86** [comment]
Can you mount EFI and post your EFI/OC/config.plist

**Comment by LockVer** [comment]
[config.plist.zip](https://github.com/osy86/HaC-Mini/files/5345109/config.plist.zip)


> Can you mount EFI and post your EFI/OC/config.plist

**Comment by LockVer** [comment]
> Can you mount EFI and post your EFI/OC/config.plist

[OC.zip](https://github.com/osy86/HaC-Mini/files/5345112/OC.zip)

**Comment by osy86** [comment]
@LockVer can you edit config.plist and remove the lines

```
			<key>ApECID</key>
			<integer>14473589959871486</integer>
```

and see if that solves the issue?

**Comment by LockVer** [comment]
> @LockVer can you edit config.plist and remove the lines
> 
> ```
> 			<key>ApECID</key>
> 			<integer>14473589959871486</integer>
> ```
> 
> and see if that solves the issue?

Will it restart

**Comment by osy86** [comment]
Did it work?

**Comment by LockVer** [comment]
> Did it work?

invalid

**Comment by osy86** [comment]
Does https://github.com/osy86/HaC-Mini/releases/tag/v2.12 work?

**Comment by LockVer** [comment]
> Does https://github.com/osy86/HaC-Mini/releases/tag/v2.12 work?

I just used 2.12 to restart to upgrade 2.13

**Comment by LockVer** [comment]
> Does https://github.com/osy86/HaC-Mini/releases/tag/v2.12 work?

Can I go back to 10.15 without clearing the data?

**Comment by LockVer** [comment]
> > Does https://github.com/osy86/HaC-Mini/releases/tag/v2.12 work?
> 
> I just used 2.12 to restart to upgrade 2.13

What process is "send_event"?This process takes up CPU when it starts up

**Comment by osy86** [comment]
Closing since it seems original issue was solved.
