### ISSUE TITLE
kernel_task running continuously over 100% CPU

### ISSUE THREAD

**Issue by estruyf** [osy86/HaC-Mini#344]
**Describe the bug**

`kernel_task` is continuously over 100%. This happened after a clean installation. Could this be related to any wrong config for OpenCore?

Already stopped the spotlight service, as this seemed to cause issues, but it doesn't affect the `kernel_task`.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.12
- OSX version [e.g: 10.14.6]: 10.15.7
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: samsung nvme evo plus 1tb
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: samsung nvme evo plus 1tb
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: DDR4-2666 16GB
- Second DIMM model (if installed): DDR4-2666 16GB
- Display port(s) used [e.g: USB-C, mini DP]: usb-c + usb-c
- Display resolution(s) [e.g: 4K, 5K]: 2*4k
- Any TB3 devices: CalDigit dock
- Any USB devices: usb-dongle
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM94360CS2

**Modifications**

 No modifications are done.

**Comment by osy86** [comment]
I believe this is an macOS issue and unrelated to hackintosh.
