### ISSUE TITLE
Radeon Polaris 4 GB instead of Radeon RX Vega M GH 4G after screen flickering workaround install using installer

### ISSUE THREAD

**Issue by cubytz** [osy86/HaC-Mini#346]
Hello, 

I added a second 4K display and experienced a lot of heavy flickering. I installed the flickering workaround in the installer and 2 things happened:

1. The flickering problem was solved, but the [glitches problem](https://github.com/osy86/HaC-Mini/issues/331) came back...
2. The display tab in the About this mac shows Radeon Polaris 4 GB instead of Radeon RX Vega M GH 4G

Side note, when I installed the workaround, it erased every kext files I previously installed. Is this a common behavior?

Thank you for your help

**Comment by cubytz** [comment]
Also, how can I uninstall this workaround?

**Comment by osy86** [comment]
To uninstall, just reinstall the pkg and uncheck the workaround.

**Comment by cubytz** [comment]
I went for a HDMI display emulator. I reverted the workaround. I will close this for now!
