### ISSUE TITLE
HDMI gives only 4k@30hz

### ISSUE THREAD

**Issue by xelanaiznac** [osy86/HaC-Mini#347]
hi.
i don0t know if it is a bug or if it is a hardware limit but I am using my 4k samsung tv trough HDMI cable and I can reach only 4k at @30hz (while on my nuc10 I have 4k@60hz).
is there any solution? thank you

**Comment by osy86** [comment]
Is it 4k@60hz on Windows?

**Comment by xelanaiznac** [comment]
hi. I didn't try on windows but if needed I can manage to install it

**Comment by osy86** [comment]
Testing it on windows will isolate any hardware or configuration issues.

**Comment by Malumen** [comment]
@xelanaiznac have you tried enabling enhanced 4k bandwidth for the HDMI port on the TV? I had this problem as well and it turned out I was using a limited-HDMI port on the TV/monitor; enabing `enhanced 4k limit` via the TV allowed the `HaC mini`  to output 4k60 easily.

**Comment by xelanaiznac** [comment]
> @xelanaiznac have you tried enabling enhanced 4k bandwidth for the HDMI port on the TV? I had this problem as well and it turned out I was using a limited-HDMI port on the TV/monitor; enabing `enhanced 4k limit` via the TV allowed the `HaC mini` to output 4k60 easily.

thank you, that was the issue!.
