### ISSUE TITLE
How to map additional USB ports for NUC header cables

### ISSUE THREAD

**Issue by Malumen** [osy86/HaC-Mini#350]
Hi Osy,

I will be migrating to use the HaC mini full-time. As such, I need more USB ports! I have purchased the additional USB2 and USB3 header cables for the board (from GORITE/MicroSataCables). Seems to work OK in Windows. Will this mess up your HaC mini files Osy? Do you have any recommended steps for identifying/merging into MacOS?

EDIT: removed unfixable hardware bug to not overload the issue post; limiting post to `additional USB port mappings` only.

**Comment by osy86** [comment]
Re: the additional USB header. I would need to add the ports to the custom port injection DSDT. You would have to follow the custom DSDT instructions and tell me the result https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/

For the power issue, can you confirm it doesn’t happen in windows?

**Comment by Malumen** [comment]
Is there already a DSDT file in there? (I don't see one)
Otherwise, have you checked out CorpNewt's SSDTTime tool? Do you think we Could leverage that at all? 


As for the USB Type-A 10Gbps port: yes, it happens in Windows as well... I will do more testing and research. I am convinced it is a _power delivery_ issue. Many other users online seem to have the same problem. Right now I'm using that port for my Logitech Unifying Receiver so it is a glorified USB2.0 port...
(I wonder if a firmware update could be delivered to the Hades Canyon via Windows that can affect the power draw for the port)

**Comment by osy86** [comment]
Like I said I made the DSDT for all the visible ports. If you want the headers to work you have to do it yourself.

If it doesn’t work on windows there’s nothing I can do.

**Comment by Malumen** [comment]
Hi again Osy,

I managed to get USBInjectAll.kext to work again, USBMap.command doesn't seem to work. In any case, looks like the two USB2.0 header ports are HS07 and HS08. Any easy way to enable them using your SSDT-Xhci file?

(there is an Asmedia controller for 2 of the front ports, for the Intel chipset that leaves 5 USB3.0 ports and 1 USB2.0 port for Bluetooth, should still be under the limit eh?)

Unfortunately my USB3.0 header cable seems to be defective: it shipped in a flimsy envelope and must have been crushed at some point.

Please see attached:
HS08
![Screen Shot 2020-10-24 at 10 26 17 PM](https://user-images.githubusercontent.com/56620641/97098971-c300d480-1648-11eb-836f-b0bb7c636580.png)
HS07
![Screen Shot 2020-10-24 at 10 26 17 PM](https://user-images.githubusercontent.com/56620641/97098972-c5632e80-1648-11eb-9d6a-b820e9960e6c.png)

**Comment by osy86** [comment]
If I understand correctly HS07 and HS08 correspond to the two USB 2.0 ports in the white IO header? And you haven't managed to test the blue USB 3.0 header yet? You can modify SSDT-Xhci.asl by replacing the _STA method with one of the other ones that's defined. I'll do it once you have the 3.0 ports mapped as well.

**Comment by Malumen** [comment]
> If I understand correctly HS07 and HS08 correspond to the two USB 2.0 ports in the white IO header? And you haven't managed to test the blue USB 3.0 header yet? You can modify SSDT-Xhci.asl by replacing the _STA method with one of the other ones that's defined. I'll do it once you have the 3.0 ports mapped as well.

`            Scope (HS07)
            {
                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    Return (Zero)
                }
            }

            Scope (HS08)
            {
                Method (_STA, 0, NotSerialized)  // _STA: Status
                {
                    Return (Zero)
                }
            }`
Changes to
`            Scope (HS07)
            {
                Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
                {
                    Local0 = Package (0x00){}
                    DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                    Return (Local0)
                }
            }

            Scope (HS08)
                Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
                {
                    Local0 = Package (0x00){}
                    DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                    Return (Local0)
                }
            }`

And I can literally just save it? Just copy from HS04 and paste?

**Comment by osy86** [comment]
Yeah then run the build script. Or just submit a pull request here and it'll build automatically.

**Comment by Malumen** [comment]
> Yeah then **run the build script**. 

_Uhh..._

> Or just submit a pull request here and it'll build automatically.

_UHHH...._

You forget Osy... I have an ant for a brain... How do I do this? I can't just save the .asl after editing it?

**Comment by Malumen** [comment]
OK, making HS07 and HS08 copies of HS04 _did not work_; Hackintool sees them as USB3.0 ports and connecting devices does not seem to do anything. I see HS09 is a _pure_ USB2.0 port but also *internal* (for use as USB->Bluetooth functionality.
            Scope (HS09)
            {
                Name (_UPC, Package (0x04)  // _UPC: USB Port Capabilities
                {
                    0xFF, 
                    0xFF, 
                    Zero, 
                    Zero
                })
                Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
                {
                    Local0 = Package (0x00){}
                    DTGP (Arg0, Arg1, Arg2, Arg3, RefOf (Local0))
                    Return (Local0)
                }
            }
If I simply change the values for 0xFF to Zero then it will change from a `255 internal` to basic USB2.0 functionality eh?

**Comment by Malumen** [comment]
(also strangely it looks like after trying to get the USB ports mapped via adding USBInjectAll kext and XhciPortLimit YES, Hackintool seems to be stuck with all ports injected...)
![Screen Shot 2020-10-25 at 3 04 45 PM](https://user-images.githubusercontent.com/56620641/97119072-744c4c80-16d3-11eb-85a8-751cd654eff9.png)

**Comment by Malumen** [comment]
@osy86 I need your help; I have been at this for a week and cannot get those ports enabled. 

I have read the guide you linked to, but you code varies completely from the SSDT-Xhci.aml file. Where did you get the language for the code? I cannot find any other .aml file example within the hackintosh community that comes close to how yours works.

I tried writing the HS07/HS08 ports like the other USBs (HS01, HS04, etc.) and tried writing it like the Bluetooth port HS09, and nothing seems to enable them.

Just looking for any help at all here. (note: the ports work fine in Windows)

**Comment by Malumen** [comment]
Hi @osy86 

With the help of @al3x from the Discord community, I can verify this SSDT-Xhci.aml WORKS for the HS07/HS08 ports (additional mainboard header ports).

[SSDT-Xhci.aml.zip](https://github.com/osy86/HaC-Mini/files/5472802/SSDT-Xhci.aml.zip)

**Comment by osy86** [comment]
Nice, and what about the USB 3 headers?

**Comment by Malumen** [comment]
> Nice, and what about the USB 3 headers?

Unfortunately the header was damaged in transit and I'm fighting the vendor's apathy right now. I may end up ordering another one except if my math is right:
The `Intel Controller` would be over the 15-port limit:
1x USB3.0-A at front 
4x USB3.0-A at back 
1x USB2.0 for BT
2x USB2.0 from mainboard
 = 13 USB count
 -->> additional 2x USB3.0-A ports from mainboard = 17 ports
I could either enable _just one_ or enable both as USB2.0 eh?

**Comment by Malumen** [comment]
Note: after my first USB3.0 (x2) header cable arrived damaged, it looks like the new replacement is in good condition. After some testing it appears as if the HS0x ports for the 3.0 header are: 
` HS05 `
and 
` HS06 `

Any USB3.0 device I plug in seems to fail to load.
This is OK because with the additional ports (if enabled for macOS) would mean I exceed the 15-port limit imposed on the intel USB controller.
4x back USB3.0 ports = 8 in macOS
1x front USB3.0 port (yellow) = 2 in macOS
1x USB2.0 internal port for the BlueTooth Module = 1 in macOS
2x USB2.0 mainboard ports = 2 in macOS
2x USB3.0 mainboard ports = 4 in macOS
--> if we leave the USB3.0 ports as only USB2.0 in macOS then we are perfectly maxed out at 15 ports (8 + 2 + 1 + 2 + 2)

**Comment by Malumen** [comment]
@osy 
Confirmed. This SSDT-Xhci.aml works. This sets the two mainboard USB3.0 ports to just USB2.0 mode and maxes out the macOS port limit. Please consider inserting this into the HaC mini project when you have time!!

`NEW:` [SSDT-Xhci.aml.zip](https://github.com/osy/HaC-Mini/files/5670919/SSDT-Xhci.aml.zip)

**Comment by osy** [comment]
@Malumen I think you've forgot about the 2x USB-C in the back running in USB 2.0 mode which is still handed by the PCH controller. I think that pushes us over the limit.

**Comment by Malumen** [comment]
> @Malumen I think you've forgot about the _2x USB-C in the back running in USB 2.0 mode which is still handed by the PCH controller._ **I think that pushes us over the limit.** With your AML, can you try plugging in a USB 2.0 device with an adapter on the back?

...You are correct! Without applying patches to undo the 15-port limit, those USB2.0s in each of the back Type-C ports (Thunderbolt 3 Controller ports) are handled by the Intel PCH Controller, ergo exceeding the 15-port limit...

In this case, the USB3.0 ports work just fine in `Windows`. I'll remove them in `macOS` and just leave the two USB2.0 ports enabled via that header cable.

For my config: I will have two external SSDs (NTFS, Windows formatted) plugged in to those cables so they are things macOS does not need to worry about anyways.
