### ISSUE TITLE
Is the 1.4 a "clean" release?

### ISSUE THREAD

**Issue by 22dm** [osy86/HaC-Mini#36]
The 1.4 version CLOVER folder has tools, themes and drivers64EFI. These will be installed during the installation of clover. Are these files the special version or just being packed by mistake?

By the way, the driver folder and the options have changed in recent version of clover, may be this should be updated in the guide, too?

**Comment by osy86** [comment]
Sorry, I included extra files by mistake.

**Comment by osy86** [comment]
Released https://github.com/osy86/HaC-Mini/releases/tag/v1.4.1
