### ISSUE TITLE
Can't use Apple Watch to unlock NUC with DW1820A BT card.

### ISSUE THREAD

**Issue by YucongDing** [osy86/HaC-Mini#379]
`Use your Apple Watch to unlock apps and your Mac` can be setup, but it doesn't produce any effect. When unlock my Mac or required to input my password, my Apple Watch doesn't pop up any notification.

My DW1820A is the same as the tutorial suggests, can anyone tell me how to use it?
![Screen Shot 2020-11-05 at 11 22 06 AM](https://user-images.githubusercontent.com/6185107/98194143-abcfba00-1f59-11eb-9c77-2489dd75c042.png)

**Comment by osy86** [comment]
Only Apple wifi cards support advanced BT features.
