### ISSUE TITLE
1.4.1+ nuc8i7hnk+ 10.14.6: I2CController timeout

### ISSUE THREAD

**Issue by dingld** [osy86/HaC-Mini#38]
Clean install 10.14.6 on nuc8i7hnk with release 1.4.1, unfortunately, failed, saying 
```
AppleIntelLpssI2CController::_serviceMatchingTimeSubr: fTimerServiceMatching timed out, fNotifications 0
```
already tried
- [ ] release 1.4.1
- [ ] release 1.4.1 + config.plist from 1.3
- [ ] release 1.4.1 + config.plist from 1.3 + Polaris22Fixup.kext from 1.0
all of those combinations failed.

**Comment by osy86** [comment]
Has it ever worked in the past? If so can you provide a working configuration to compare with?

Are you using SATA SSD or NVMe?

**Comment by 22dm** [comment]
seems like #19. try [this](https://github.com/osy86/HaC-Mini/issues/19#issuecomment-520210604)

**Comment by dingld** [comment]
> Has it ever worked in the past? If so can you provide a working configuration to compare with?
> 
> Are you using SATA SSD or NVMe?

No, it has not worked yet. I am using NVME SSD HS-SSD-C2000Pro 512G.

**Comment by dingld** [comment]
> #19

Noticing the log "adding agdp mode validate property" before timeout, I search on google, I guess it might have something to do with WhateverGreen parameter
```
agdpmod=vit9696 disables check for board-id (or add agdpmod property to external GPU).
```
It booted successfully after modifying the config.plist on boot parameters.
BTW, the bios version is 0057.
Thanks!

**Comment by osy86** [comment]
Interesting, is it a problem only in HNK? Does anyone else have HNK working?

**Comment by franzbu** [comment]
Doesn't seem to work with HNK out of the box. For me it works without Whatevergreen and with a slightly modified config.plist (don't remember the actual changes, it's attachted).
[config.plist.zip](https://github.com/osy86/HaC-Mini/files/3584705/config.plist.zip)

**Comment by osy86** [comment]
Please test with [v2.1](https://github.com/osy86/HaC-Mini/releases/tag/v2.1) and open a new issue with the issue template if the problem still exists. I will close all < 2.0 issues in two weeks.

**Comment by SSebo** [comment]
I also encounter this, workaround by just unplug my network cable

**Comment by osy86** [comment]
Closing as indicated above. Please open a new ticket and fill in the requested information if the issue persists.
