### ISSUE TITLE
Unable to Upgrade to Big Sur Beta

### ISSUE THREAD

**Issue by crowtech420** [osy86/HaC-Mini#380]
**Describe the bug**
Unable to boot into installer of Big Sur Beta when installed with OTA update, stuck with error message.
![WechatIMG10](https://user-images.githubusercontent.com/55730058/98457672-bf328d80-21c4-11eb-9205-e6d376132413.jpeg)

**Expected behavior**
It should boot into the installer with no issue

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.13
- OSX version [e.g: 10.14.6]: 10.15.7
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung 1TB, NVMe
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: N/A
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Crucial DDR4-2400 16GB
- Second DIMM model (if installed): N/A
- Display port(s) used [e.g: USB-C, mini DP]: Mini DP + HDMI
- Display resolution(s) [e.g: 4K, 5K]: 
- Any TB3 devices: N/A
- Any USB devices: N/A
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM94360CS2

**Comment by crowtech420** [comment]
When tried to boot through external USB installer, the HaC Mini Installer won't recognize the Installer USB as a installer, and when booting from it, it hangs at this error.
![IMG_0128](https://user-images.githubusercontent.com/55730058/98460811-72f64600-21e2-11eb-9206-186b1a0f72c2.jpg)

**Comment by cuteluo1983** [comment]
You can upgrade to the latest version of the Big sur system with either a freshå install or an online upgrade, and I tested the fresh install myself (following Mr. OSY86's tutorial exactly), and some other users tested the online upgrade with no problems.
However, there are some bugs, not sure whether they come from Hac-mini or Big sur, such as.
1, 4k 60hz display, the login interface resolution is too small, the content display is too large, this should be able to adjust the config file can be solved.
2. logging into the desktop stage, which will black screen and then reappear as content.
3, part of the shadow rendering of the dialog box is incorrect.
Nothing else yet, good experience, thanks Mr. OSY86!

Translated with www.DeepL.com/Translator (free version)

**Comment by crowtech420** [comment]
> You can upgrade to the latest version of the Big sur system with either a freshå install or an online upgrade, and I tested the fresh install myself (following Mr. OSY86's tutorial exactly), and some other users tested the online upgrade with no problems.
> However, there are some bugs, not sure whether they come from Hac-mini or Big sur, such as.
> 1, 4k 60hz display, the login interface resolution is too small, the content display is too large, this should be able to adjust the config file can be solved.
> 2. logging into the desktop stage, which will black screen and then reappear as content.
> 3, part of the shadow rendering of the dialog box is incorrect.
> Nothing else yet, good experience, thanks Mr. OSY86!
> 
> Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)

The installer won't boot with a OTA upgrade, as I said in the post.

**Comment by cuteluo1983** [comment]
> > You can upgrade to the latest version of the Big sur system with either a freshå install or an online upgrade, and I tested the fresh install myself (following Mr. OSY86's tutorial exactly), and some other users tested the online upgrade with no problems.
> > However, there are some bugs, not sure whether they come from Hac-mini or Big sur, such as.
> > 1, 4k 60hz display, the login interface resolution is too small, the content display is too large, this should be able to adjust the config file can be solved.
> > 2. logging into the desktop stage, which will black screen and then reappear as content.
> > 3, part of the shadow rendering of the dialog box is incorrect.
> > Nothing else yet, good experience, thanks Mr. OSY86!
> > Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)
> 
> The installer won't boot with a OTA upgrade, as I said in the post.

Please follow the hac-mini tutorial to install it without any problems. Clean up the nvram before installation, if you don't, the 4k display will be hua ping!

<img width="668" alt="Snipaste_2020-11-11_09-10-04" src="https://user-images.githubusercontent.com/16398096/98752736-c395bb00-23fd-11eb-8c5d-40ba5ffa2bd3.png">

**Comment by crowtech420** [comment]
> > > You can upgrade to the latest version of the Big sur system with either a freshå install or an online upgrade, and I tested the fresh install myself (following Mr. OSY86's tutorial exactly), and some other users tested the online upgrade with no problems.
> > > However, there are some bugs, not sure whether they come from Hac-mini or Big sur, such as.
> > > 1, 4k 60hz display, the login interface resolution is too small, the content display is too large, this should be able to adjust the config file can be solved.
> > > 2. logging into the desktop stage, which will black screen and then reappear as content.
> > > 3, part of the shadow rendering of the dialog box is incorrect.
> > > Nothing else yet, good experience, thanks Mr. OSY86!
> > > Translated with [www.DeepL.com/Translator](http://www.DeepL.com/Translator) (free version)
> > 
> > 
> > The installer won't boot with a OTA upgrade, as I said in the post.
> 
> Please follow the hac-mini tutorial to install it without any problems. Clean up the nvram before installation, if you don't, the 4k display will be hua ping!
> 
> <img alt="Snipaste_2020-11-11_09-10-04" width="668" src="https://user-images.githubusercontent.com/16398096/98752736-c395bb00-23fd-11eb-8c5d-40ba5ffa2bd3.png">

I got the PCIe error when directly OTA upgrading.

**Comment by crowtech420** [comment]
I think I have the same issue with #342 , but I do not know how to fix it. I may have to wipe and reinstall macOS all over again.

**Comment by crowtech420** [comment]
I was able to upgrade to Big Sur by disabling SIP, creating a installer USB, install HaC Mini package onto that USB (the patch installer option grayed out), and boot into that USB, and finish the installation.
