### ISSUE TITLE
Big Sur 11.0.1 Panic When Updating

### ISSUE THREAD

**Issue by jomiro19** [osy86/HaC-Mini#388]
Big Sur 11.0.1 beta worked fine, however when I updated to the release version today, it's now in a bootloop that's unrecoverable.

Finally got it to boot after multiple hours of bootloops and failed recoveries. After getting back in I recieved this:

panic(cpu 6 caller 0xffffff8021a47888): /Users/rzg/Projects/2018/02/Thunderbolt3Unblocker/xnu_override/zydis/src/Decoder.c:1343:ZydisDecodeOperandRegister: operand->reg.value
Backtrace (CPU 6), Frame : Return Address
0xffffffa0c8c0b2b0 : 0xffffff801dabc66d 
0xffffffa0c8c0b300 : 0xffffff801dbff073 
0xffffffa0c8c0b340 : 0xffffff801dbef6aa 
0xffffffa0c8c0b390 : 0xffffff801da61a2f 
0xffffffa0c8c0b3b0 : 0xffffff801dabbf0d 
0xffffffa0c8c0b4d0 : 0xffffff801dabc1f8 
0xffffffa0c8c0b540 : 0xffffff801e2bee1a 
0xffffffa0c8c0b5b0 : 0xffffff8021a47888 
0xffffffa0c8c0b5e0 : 0xffffff8021a446be 
0xffffffa0c8c0b760 : 0xffffff8021a3d3fa 
0xffffffa0c8c0b7e0 : 0xffffff8021a3c718 
0xffffffa0c8c0b890 : 0xffffff8021a3ae31 
0xffffffa0c8c0bc80 : 0xffffff8021a3ba8f 
0xffffffa0c8c0bcb0 : 0xffffff8021a3ac7c 
0xffffffa0c8c0bcf0 : 0xffffff801e186bdc 
0xffffffa0c8c0bd40 : 0xffffff801e18413c 
0xffffffa0c8c0bda0 : 0xffffff801e1989dd 
0xffffffa0c8c0bdf0 : 0xffffff801e20eebe 
0xffffffa0c8c0be40 : 0xffffff801e1ee39b 
0xffffffa0c8c0bef0 : 0xffffff801e1eddcf 
0xffffffa0c8c0bf50 : 0xffffff801e1f0b46 
0xffffffa0c8c0bfa0 : 0xffffff801da6113e 
      Kernel Extensions in backtrace:
         es.govost.ryan.Thunderbolt3Unblocker(1.0)[E6321B23-449C-366C-A128-F6B88439C8C0]@0xffffff8021a3a000->0xffffff8021a8cfff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[78808055-9D80-3318-8BEE-4C545178A586]@0xffffff801ee55000->0xffffff801ee5efff
            dependency: com.apple.iokit.IOThunderboltFamily(9.3.2)[DFEE61D2-E062-3D33-B5F7-473439AB6C1B]@0xffffff802057f000->0xffffff8020656fff

Process name corresponding to current thread: Unknown
Boot args: alcid=11 agdpmod=ignore -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 igfxmetal=1

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64
Kernel UUID: 84C6DC45-6B02-335F-9439-5D2A9BC385A4
KernelCache slide: 0x000000001d800000
KernelCache base:  0xffffff801da00000
Kernel slide:      0x000000001d810000
Kernel text base:  0xffffff801da10000
__HIB  text base: 0xffffff801d900000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization
Hibernation exit count: 0

System uptime in nanoseconds: 1148365625
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000004472b014
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000bd920bbe1da 0x0000000000000000

**Comment by osy86** [comment]
Looks to be an issue with Thunderbolt3Unblocker. Try removing that.

**Comment by jomiro19** [comment]
I figured that. Could you point me to a link of how to do this? Thanks for the help!
