### ISSUE TITLE
My Desktop is just back with small green squares as the background 

### ISSUE THREAD

**Issue by dougdalton** [osy86/HaC-Mini#392]
I cannot change it after successfully upgrading to bigsur.  everything else seems ok

**Comment by bg8erz** [comment]
me too.
nuci7hvk
BIOS:HNKBLi70.86A
HaCmini:2.14
OS: big sur 11.0.1

**Comment by dougdalton** [comment]
Here is a capture of my desktop as well as a weird border that doesnt show up on my macbook.  This could be normal though in big sur

![Screen Shot 2020-11-17 at 6 35 19 PM](https://user-images.githubusercontent.com/5828863/99475761-10005f80-2904-11eb-9f97-7a2d76f73340.png)
![Screen Shot 2020-11-17 at 6 36 00 PM](https://user-images.githubusercontent.com/5828863/99475766-1393e680-2904-11eb-9236-973e1dc74189.png)

**Comment by bluetooth29** [comment]
same here the issue confirm

**Comment by Oosram** [comment]
same issue, tried reinstall still the same, only 4 picture can be normal

**Comment by hksexybaby** [comment]
My NUC8I7NVK same issue

**Comment by starvskii** [comment]
same here on my NUC8I7NVK, the wired border is extremely obvious in dark mode..

**Comment by franco-sudo** [comment]
same issue

**Comment by Oosram** [comment]
there is a way of using wallpaper downloaded from website can work

**Comment by lidongdong89** [comment]
> Here is a capture of my desktop as well as a weird border that doesnt show up on my macbook. This could be normal though in big sur
> 
> ![Screen Shot 2020-11-17 at 6 35 19 PM](https://user-images.githubusercontent.com/5828863/99475761-10005f80-2904-11eb-9f97-7a2d76f73340.png)
> ![Screen Shot 2020-11-17 at 6 36 00 PM](https://user-images.githubusercontent.com/5828863/99475766-1393e680-2904-11eb-9236-973e1dc74189.png)

same issue

**Comment by ckrueger99** [comment]
Same problem here. I went back to Catalina.

**Comment by Uzzus** [comment]
> 
> 
> > Here is a capture of my desktop as well as a weird border that doesnt show up on my macbook. This could be normal though in big sur
> > ![Screen Shot 2020-11-17 at 6 35 19 PM](https://user-images.githubusercontent.com/5828863/99475761-10005f80-2904-11eb-9f97-7a2d76f73340.png)
> > ![Screen Shot 2020-11-17 at 6 36 00 PM](https://user-images.githubusercontent.com/5828863/99475766-1393e680-2904-11eb-9236-973e1dc74189.png)
> 
> same issue

https://github.com/osy86/HaC-Mini/issues/316#issuecomment-731925713

**Comment by qingyiquan** [comment]
confirm，same  issue

**Comment by Arthur97172** [comment]
Same issue

**Comment by bigfoot7375** [comment]
Please follow @goodbest solution - all issues (including wallpaper) are fixed.
[https://github.com/osy86/HaC-Mini/issues/316#issuecomment-731743555](url)

**Comment by ckrueger99** [comment]
Better link [here](https://github.com/osy86/HaC-Mini/issues/316#issuecomment-731743555).

**Comment by hksexybaby** [comment]
https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip

Download this can Easy Problem Solving
( replaced the kext )
