### ISSUE TITLE
How to remove "Thunderbolt3Unblocker"?

### ISSUE THREAD

**Issue by jomiro19** [osy86/HaC-Mini#393]
New to this, and not experienced with scripts and such. I receive a panic every time I boot into **Big Sur 11.0.1 RC** because of Thunderbolt3Unblocker. Can someone tell me how (or point me to how) I can do this? Thanks in advance!

**Comment by osy86** [comment]
Re-run the .pkg and don't select that option. I will make sure it's disabled in the next update.

**Comment by jomiro19** [comment]
Thanks, worked great.
