### ISSUE TITLE
 headset port doesn't work

### ISSUE THREAD

**Issue by JasonLamv-t** [osy86/HaC-Mini#395]
hvk
16G ram
an Intel 760p hard disk with 10.15.7
a SanDisk SATA hard disk with windows10

I successfully installed mac and windows, on both hard drives and successfully booted using opencore, but after updating windows, mac's headset port was recognized but there was no audio output.

**Comment by caidi1224** [comment]
Working Hardware
 GPU acceleration
 Video encoder/decoder hardware
 Multiple displays (six 4K displays max)
 5K display
 Ethernet (both ports)
 **Analog Audio (both ports, no headsets)**
 Digital Audio
 Microphone (both stereo mics)
 HDMI/DP audio
 USB A ports
 USB C ports
 Thunderbolt 3 ports (including hotplug)
 Thunderbolt IP (XDomain, internet sharing)
 eGPU (with hotplug)
 SD card slot
 NVMe/SATA SSD
 CPU power management
 Sleep/Resume
 Wifi/BT (using Apple Wifi card)
 Secure Boot (with High Security)

**Comment by JasonLamv-t** [comment]
I tried to remove the hard drive with windows and power it back on. The headphone port has been restored.
