### ISSUE TITLE
New NUC8i7HVK BIOS Available: HN0064.bio

### ISSUE THREAD

**Issue by Malumen** [osy86/HaC-Mini#454]
Anyone already tested with the _new_ BIOS **0064** (as of 10/28/2020).

Can be found [**here**](https://downloadcenter.intel.com/download/29995/BIOS-Update-HNKBLi70-86A-?product=126143).

```
New Fixes/Features:
• Updated ME firmware to 11.8.80.3746.
• Fixed issue where front USB 3.0 port could not be used.
• Fixed issue where previously programmed NVMe M.2 SSD Admin
password showed as "NOT INSTALLED" in Visual BIOS.
• Fixed with analog audio output sample rate support.
• Fixed issue where “SATA M.2 SSD type not displayed in SATA
section under Visual BIOS DEVICE”.
• Fixed issue where Blue USB ports were powered up while system
remained unpowered.
• Fixed issue with arbitrary code execution at PEI phase
(WakeUpType).
• Fixed issue where SMRAM overwritten with arbitrary data
(microcodeUpdate).
```

Likewise with a few other updates we cannot downgrade after updating to this BIOS. Hence why I am hesitant.

**Comment by keatliang2005** [comment]
been update to this bios for few weeks seems okay

**Comment by thegass** [comment]
upraded a few days ago. no issues until now. audio sample rates beside 48khz are working now.

**Comment by alenzhong** [comment]
been update，this bios seems okay.

**Comment by deftdawg** [comment]
Flashed it and it ran for 1.5 days and the machine bricked itself.  PSU shows 19.6V, so machine should be responding.  I saw one other person with similar issue to me on the intel forums and several others who have said 64 has killed all LEDs on the outside of the HaC...  I would say don't update!

**Comment by PumaOsX** [comment]
> Anyone already tested with the _new_ BIOS **0064** (as of 10/28/2020).
> 
> Can be found [**here**](https://downloadcenter.intel.com/download/29995/BIOS-Update-HNKBLi70-86A-?product=126143).
> 
> ```
> New Fixes/Features:
> • Updated ME firmware to 11.8.80.3746.
> • Fixed issue where front USB 3.0 port could not be used.
> • Fixed issue where previously programmed NVMe M.2 SSD Admin
> password showed as "NOT INSTALLED" in Visual BIOS.
> • Fixed with analog audio output sample rate support.
> • Fixed issue where “SATA M.2 SSD type not displayed in SATA
> section under Visual BIOS DEVICE”.
> • Fixed issue where Blue USB ports were powered up while system
> remained unpowered.
> • Fixed issue with arbitrary code execution at PEI phase
> (WakeUpType).
> • Fixed issue where SMRAM overwritten with arbitrary data
> (microcodeUpdate).
> ```
> 
> Likewise with a few other updates we cannot downgrade after updating to this BIOS. Hence why I am hesitant.

Yes. I updated 5 days ago and everything it's perfect no issues at all.

**Comment by Malumen** [comment]
> Flashed it and it ran for 1.5 days and the machine bricked itself. PSU shows 19.6V, so machine should be responding. I saw one other person with similar issue to me on the intel forums and several others who have said 64 has killed all LEDs on the outside of the HaC... I would say don't update!

Have you tried removing the CMOS pin and removing the power pin at the same time? Swap the RAM.

Otherwise: erase an 8GB or smaller USB flash drive to FAT32, exFAT, or ***NTFS***. Name it USB. Place the `0064.bio` file in the root with nothing else on the root of the drive. Plug in the USB to the back top left blue USB port (if you've turned the back to face you). Plug in a basic USB keyboard on any other back port. Plug in a 1080p monitor to the back HDMI port.

Press and hold the power-on button for 10 seconds* (I really really cannot remember but it is a specific amount of time to engage the auto-flash BIOS wipe). The system may boot up and ask for a prompt to engage the BIOS recovery wipe. Say yes and it should spit out the identifier for the BIOS found on the USB. Once complete, the system should attempt to reboot and will prompt you with the BIOS recovery flashback page again. Power down, unplug the power cord again, replace the jumper, plug the power cord back in, and power up.

Source: had a NUC unit with a similar issue where it looked like it bricked.

**Comment by Malumen** [comment]
I have flashed in the following manner: all devices unplugged; USB with only the `64.BIO` file on the root. USB keyboard via USB2 port from mainboard. 

Flashed OK. System seems stable.

**Comment by deftdawg** [comment]
> have you contacted Intel for RMA and/or repair cost? IIRC these units have 3 years warranty.

It died on Friday, I didn't realize until around midnight that it was still under warranty, I've opened a support/RMA ticket, hopefully someone will get back to me tomorrow when they open.

> Have you tried removing the CMOS pin and removing the power pin at the same time? Swap the RAM.

I've pulled the battery jumper, swapped ram for previously working, pulled the power barrel connector, checked the cable and PSU (there's voltage there, don't know if there's something else the MB is looking for).

It has the symptoms of a PSU failure, no power at all to the system, but I know there's voltage... Idk, we'll see what Intel says.
 
> Otherwise: erase an 8GB or smaller USB flash drive to FAT32, exFAT, or _**NTFS**_. Name it USB. Place the `0064.bio` file in the root with nothing else on the root of the drive. Plug in the USB to the back top left blue USB port (if you've turned the back to face you). Plug in a basic USB keyboard on any other back port. Plug in a 1080p monitor to the back HDMI port.
>
> Press and hold the power-on button for 10 seconds* (I really really cannot remember but it is a specific amount of time to engage the auto-flash BIOS wipe). The system may boot up and ask for a prompt to engage the BIOS recovery wipe. Say yes and it should spit out the identifier for the BIOS found on the USB. Once complete, the system should attempt to reboot and will prompt you with the BIOS recovery flashback page again. Power down, unplug the power cord again, replace the jumper, plug the power cord back in, and power up.

I tried this, I don't get any LED activity anywhere on the system at all
 
> Source: had a NUC unit with a similar issue where it looked like it bricked.

Did yours do a skull blink or anything in that case?  I don't even get a skull blink, I've read of folks recovering when they have that.  Mine's just dark.   Anyway, thanks for replying, hopefully nobody else has any issues after updating. 🤞

**Comment by deftdawg** [comment]
Not gonna like the Intel RMA support experience has been 
pretty much 💩...  They didn't have stock offered me a refund (I asked for ETA replacement), then went dark on updates that were only happening twice a week, they made zero effort to troubleshoot and don't respond to my questions and have now completely stopped updating on the days they said they would follow up.  Not impressed at all.
