### ISSUE TITLE
Random fan speed spike

### ISSUE THREAD

**Issue by KrisCris** [osy86/HaC-Mini#455]
**Describe the bug**
Actually, it has been a while that the fan speed of the HacMini surges randomly, which is extremely loud especially during the night, and it happens even during some time when the computer is idle.

And, I can barely observe any severe temperature increase, so... 

**Expected behavior**
No sudden fan speed increase

**Configuration**
- HaC Mini version: Latest
- OSX version: 10.15.7
- NUC model: HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: NVME 1tb
- First DIMM model: Kingston HyperX impact 2667 16g
- Second DIMM model (if installed): Kingston HyperX impact 2667 16g
- Display port(s) used: Mini DP, USB-C
- Display resolution(s): 2K, 4K
- Any USB devices: External HDD, Logitech receiver
- Any Wi-Fi/Bluetooth devices: BCM943602CS; Magic Trackpad2, Bluetooth keyboard

**Modifications**
None

**Panic log**
None

**Comment by keatliang2005** [comment]
what's your bios version ?

it might be old bios fan curve acting up

**Comment by KrisCris** [comment]
OK... I set the fan curve a little bit less aggressive, and it became quite... Tho very hot around 75C now
