### ISSUE TITLE
1.4.1+ nuc8i7hnk+ 10.14.6: can not boot。

### ISSUE THREAD

**Issue by rhtect** [osy86/HaC-Mini#46]
I am using version 1.4.1, there is a problem when booting the system: can't get into the system, restart repeatedly

**Comment by osy86** [comment]
Please turn on verbose boot with -v kerpsyms=1 debug=0x1000 and post the crash.

**Comment by msedek** [comment]
you might be having my same issue, once you are in the clover boot screen, press the space bar and select the option booth with injected kexts

**Comment by osy86** [comment]
Please test with [v2.1](https://github.com/osy86/HaC-Mini/releases/tag/v2.1) and open a new issue with the issue template if the problem still exists.
