### ISSUE TITLE
Sidecar not showing iPad in Catalina PB 8

### ISSUE THREAD

**Issue by lmshsqlc** [osy86/HaC-Mini#50]
**Description**
Since a Catalina issue has been brought up, I'll just bring this up too. not urgent but kind of wanna see what's going on. 
The iPad Pro 11 inches is not showing on the sidecar pref panel. connected thru USBC to USBC at the front. 

Scenarios tested: 2
HaC Mini version: 2.0
OSX version: 10.15 PB8 19A558d
NUC model: NUC8I7HNK
Boot SSD model and protocol: Samsung 970 EVO 1TB, NVME
Second SSD model and protocol (if installed):Intel 660p 1TB, NVME
First DIMM model: Crucial DDR4-2400 8GB
Second DIMM model: Crucial DDR4-2400 8GB
Display port(s) used: HDMI
Display resolution(s): 1080p@60
Any TB3 devices: No
Any USB devices: USB Receiver for Logitech Keyboard & Mouse, USB Receiver for Logitech Gaming Mouse.

Using DW1830 Wireless Card, With additional BrcmPatch Kext set.

**Modifications**

Added RehabMan's Handoff kext patch
[config.plist.zip](https://github.com/osy86/HaC-Mini/files/3612913/config.plist.zip)

**Comment by osy86** [comment]
I think once 10.15 is more widely used, people in the community will figure out a way and I can include the fix.

**Comment by mspecbmw** [comment]
Working just fine here, are you running ipad os 3.1 ??
![IMG_1064](https://user-images.githubusercontent.com/7828510/64916674-d26ee680-d7d5-11e9-81ef-4821e33cde43.JPG)

**Comment by TheBigJam** [comment]
Hello,

I also ordered the DW1830 WIFI card because i need 2 SSD. Running 10.15 Beta 8  with OC atm. 
-Which KEXTs do i need to install?
-Are there any problems with the Power-Management?
-There are two WLAN antenna connectors. Which one should be connected?
-Where can I get the KEXTs?

Thanks alot!

**Comment by osy86** [comment]
Hi, please do not take over another issue with an unrelated issue. Please do not use this tickets system for support requests unrelated to the guide.

**Comment by lmshsqlc** [comment]
> are you running ipad os 3.1 ??

I'm running iPadOS 13.0 GM. Is that relevant? other things are working properly.

**Comment by mspecbmw** [comment]
Was just asking as I think side car was for 13 onwards, But it looks like you are covered.
Nothing special with my setup was just done with OC 2.0 have not changed SMBIOS which is 18,1 mac mini. In fact my setup looks very similar to yours. 
My ipad is 11.9 inch pro , Will try it on my smaller one when I get home but I just plugged it in and it showed up under sidecar as an option to use, selected it and it was an instantly on.

**Comment by Jase-NZ** [comment]
Can confirm my 9.8" is also working ok, usb c front to lighting on the ipad.

![CE5B99FA-6C39-4AD9-A0DE-2337D8105B0E_1_105_c](https://user-images.githubusercontent.com/7828510/64936853-d2d6a400-d80c-11e9-8a91-390c44d5f61f.jpeg)
![Screen Shot 2019-09-15 at 10 57 33 PM](https://user-images.githubusercontent.com/7828510/64936856-d8cc8500-d80c-11e9-91ae-c9f38c787bbe.png)

**Comment by osy86** [comment]
@lmshsqlc can you test sidecar on another machine/mac to see if it's an iPad issue?

**Comment by lmshsqlc** [comment]
> @lmshsqlc can you test sidecar on another machine/mac to see if it's an iPad issue?

 I think this issue will suspend for sometime before I can reach a device. i'll have to wait until it finally release the public version then look for a mac from someone else. Thank you.

**Comment by lmshsqlc** [comment]
For some odd reason I turned off Bluetooth then turn it on, the iPad was found no matter whether I was connected to USB or not.
