### ISSUE TITLE
NUC8i7BEH6(Date of Manufacture: 06/2019) can not boot in system. 

### ISSUE THREAD

**Issue by panda8z** [osy86/HaC-Mini#51]
**Describe the bug**

I just follow the instruction of [Installation - HaC Mini Hackintosh](https://osy.gitbook.io/hac-mini-guide/installation-guide/installation)

But in the second step of  `Installing macOS
`, NUC8i7BEH6 can not boot in system. 
Stay at this screen.
![image](https://user-images.githubusercontent.com/24646937/65113125-8a89d280-da14-11e9-94a9-c3e81412af35.png)

![image](https://user-images.githubusercontent.com/24646937/65113199-e48a9800-da14-11e9-948f-b5840e586130.png)

**Expected behavior**

Can boot in system 

**Environment:**
 - Running OSX version:  10.14.6
 - Target drive OSX version: 10.14.6
 - HaC Mini installer version: 2.0

**Additional context**

My NUC8i7BEH6 `s  **Data of manufacture: 06/2019**

**Logs**
nothing

**Comment by 22dm** [comment]
> NUC8i7BEH6

This guide is for NUC8i7HVK/HNK.

BEH hackintosh is much simpler than is, see [here](https://github.com/sarkrui/NUC8i7BEH-Hackintosh-Build).

这个教程是给冥王峡谷的，BEH 出门左转[这里](https://github.com/sarkrui/NUC8i7BEH-Hackintosh-Build)。

**Comment by osy86** [comment]
Yes
