### ISSUE TITLE
Cant boot without pressing spacebar and select boot with injected kext

### ISSUE THREAD

**Issue by msedek** [osy86/HaC-Mini#52]
hello, I downloaded the mojave from playstore
-created the usb
-installed clover with v4982 bacause newer versions do not show the options to select with the 64 at the end
-replaced the EFI in the usb with the hac mini EFI
-installed macos
-generated the smbios
-mounted efi with clover configrator and copied the efi folder from the usb drive to my efi in the hardrive
-reboot and it wont boot unless I press space bar and select the option- boot with injected kext..

everything is working 100% no issue, the nuc boots really fast into macos but I cant get it to boot without my intervention and thats really annoying

---HELP

**Comment by osy86** [comment]
Can you try resetting your NVRAM? If you don't know how, temporarily use v2.0 which comes with OC that has an option to reset NVRAM.

**Comment by msedek** [comment]
ok will try with v2.0 and come back

**Comment by msedek** [comment]
lol nvm, installed 2.0 direct to my hard drive, rebooted and it came straight to macos .. so happy now.. thanks man

**Comment by osy86** [comment]
Please note v2.0 is still beta. Please submit a report here: https://github.com/osy86/HaC-Mini/issues/44

**Comment by msedek** [comment]
oks
