### ISSUE TITLE
Ethernet broken in 2.1

### ISSUE THREAD

**Issue by 22dm** [osy86/HaC-Mini#54]
Not this:
![截屏2019-09-2114 24 06](https://user-images.githubusercontent.com/7871070/65369084-87dce680-dc7b-11e9-81b9-5586d8f28cdd.png)
But this(ExecutablePath is wrong):
![截屏2019-09-2114 24 17](https://user-images.githubusercontent.com/7871070/65369088-8f03f480-dc7b-11e9-9677-010d93fec5df.png)

**Comment by osy86** [comment]
Reuploaded https://github.com/osy86/HaC-Mini/releases/tag/v2.1 with the old kext. I updated the kext without testing them, sorry.
