### ISSUE TITLE
Can't boot from SSD after install

### ISSUE THREAD

**Issue by nagaitsev** [osy86/HaC-Mini#58]
After clean install I tried to boot without USB installer and received error **bootable device has not been detected**

When I loading with USB installer attached - no problem, macOS loading without problem.

**Expected behavior**
Loading from ssd without USB installer

**Environment:**
Running OSX version: 10.14.6

HaC Mini installer version: 2.0

**Additional context**
Tried to run HaCMini.pkg from SSD and received error of Installer 

**Logs**
[install.log](https://github.com/osy86/HaC-Mini/files/3640226/install.log)
`

**Comment by osy86** [comment]
Can you run `diskutil list`?

**Comment by nagaitsev** [comment]
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         512.1 GB   disk0
   1:                 Apple_APFS Container disk1         511.9 GB   disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +511.9 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume 512SSD                  16.3 GB    disk1s1
   2:                APFS Volume Preboot                 44.4 MB    disk1s2
   3:                APFS Volume Recovery                510.4 MB   disk1s3
   4:                APFS Volume VM                      2.1 GB     disk1s4

**Comment by osy86** [comment]
You don't have an EFI partition. How did you format it?

**Comment by nagaitsev** [comment]
format in AFPS during install process

**Comment by osy86** [comment]
Did you follow? https://osy.gitbook.io/hac-mini-guide/installation-guide/installation#installing-macos

**Comment by nagaitsev** [comment]
Yes but maybe I did something wrong. As I see EFI partition must be created. I'll try to repeat clean install tomorrow. Thank you!

**Comment by osy86** [comment]
You might have to go to View -> Show All Devices in Disk Utility to format the whole disk. I suspect you re-formatted an existing partition into APFS which does not work. You need to see an option to select "Scheme"

**Comment by nagaitsev** [comment]
Thank you!  After disk formatting install was successful!

**Comment by JackMordaunt** [comment]
I have the same issue, except I do see an `EFI` partition. 

```
~
❯ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *512.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                 Apple_APFS Container disk1         511.9 GB   disk0s2

/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +511.9 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume Internal - Data         29.8 GB    disk1s1
   2:                APFS Volume Preboot                 89.2 MB    disk1s2
   3:                APFS Volume Recovery                528.5 MB   disk1s3
   4:                APFS Volume VM                      2.1 GB     disk1s4
   5:                APFS Volume Internal                10.7 GB    disk1s5
```

Is there a way to re-install/repair only the `EFI` post-installation?
Would rather not do another clean install because my system is setup nicely.

Thanks for this project, by the way :)

**Comment by JackMordaunt** [comment]
Nevermind! 

Running `HaCMini.pkg` on my internal SSD fixed it. 
Not sure how I missed that.
