### ISSUE TITLE
No Ethernet Cards detected after OC 2.1 install

### ISSUE THREAD

**Issue by jonseppanen** [osy86/HaC-Mini#65]
**Describe the bug**

**Expected behavior**
No Ethernet Cards detected after OC 2.1 install using the updated pkg file from my other bug report. Networksetup cmd in terminal lists nothing, system profiler lists nothing. 
No locations were configured in the network settings pane and attempting to add one did nothing. I had to use sudo to add an initial location from networksetup terminal command.

**Configuration**
- HaC Mini version: 2.1+
- OSX version: Latest Mojave installer
- NUC model: The one with the bigger GPU
- Boot SSD model and protocol: Samsung 970 evo
- First DIMM model: Crucial Something
- Display port(s) used: Usb-C with portable display
- Display resolution(s): 1920x1080
- Any TB3 devices: 0
- Any USB devices: Usb wireless keyboard and mouse reciever from logitech

**Modifications**
none

**Panic log**
none

**Comment by jonseppanen** [comment]
Attempted to reinstall.

When selecting network as ethernet and continuing, the nuc reboots and starts the setup again.

**Comment by haakon-nergaard** [comment]
I have the same issue on a 8i7HNK. Skipping network config lets me finish setup, but still no ethernet card. Using USB ethernet card for now

**Comment by ts1g** [comment]
> Using USB ethernet card for now

Does your USB Ethernet adapter show up in your Network preferences, @haakon-nergaard ? I skipped the Ethernet to complete an install, but when I attempt to add any service in the Network preferences, I get an error message that there’s an issue with the Network preferences

**Comment by haakon-nergaard** [comment]
Yes, the USB adapter shows up when plugged in. No drivers or mods necessary

**Comment by jonseppanen** [comment]
Is there any way for us to debug this? What should we be looking for?

**Comment by ts1g** [comment]
> What should we be looking for?

Into which of the two ports did you plug your Ethernet cord? And what version of macOS are you using? 

Ask because it appears that @osy86 has two kexts, the Intel one for port 1 and the SmallTree one for port 2. Bug #54 showed an error in the config.plist for a version of 2.1, but the config error doesn't appear to be present in the most recent HaC-Mini 2.1 build that was provided to you @jonseppanen (and which I also used to finally get a proper install for Mojave which recognizes a USB Ethernet adapter like @haakon-nergaard is using). Haven't tried it yet with Catalina.

**Comment by haakon-nergaard** [comment]
Neither of the ports worked for me. Latest Mojave and first 2.1 build. Will try again with the newer build of 2.1 a bit later

**Comment by ts1g** [comment]
> the newer build of 2.1

This one (https://github.com/osy86/HaC-Mini/files/3683149/HaCMini.pkg.zip) from #63 is the one that worked for me to install Mojave 10.14.6 and also allowed me to do the supplemental update via Software Update after installation once I put an USB-to-Ethernet adapter in the front-most USB-C port. It doesn't seem to have been uploaded as the official 2.1 version yet.

**Comment by osy86** [comment]
Ethernet drivers might be wrong. Try the two Ethernet kext from the 1.x release.

**Comment by ts1g** [comment]
> Try the two Ethernet kext from the 1.x release

Can they be added in post-install, or does it require a full re-install of Mojave?

**Comment by osy86** [comment]
Just mount the EFI partition and replace the two files in EFI/OC/Kexts

**Comment by haakon-nergaard** [comment]
> Just mount the EFI partition and replace the two files in EFI/OC/Kexts

This worked for me. I now have two working etc ports

**Comment by SNGDude** [comment]
> Just mount the EFI partition and replace the two files in EFI/OC/Kexts

same issue, but what two files ??

**Comment by haakon-nergaard** [comment]
IntelMausiEthernet.kext and SmallTreeIntel82576.kext from release 1.4. The ones in 2.1 seems to be broken

**Comment by HorstBrack75** [comment]
> * HaC Mini version: 2.1+

What does the + mean?

NUC8i7HVK, Mojave 10.14.6 (18G103), HaC Mini 2.1, Ethernet works fine.

**Comment by SNGDude** [comment]
> > * HaC Mini version: 2.1+
> 
> What does the + mean?
> 
> NUC8i7HVK, Mojave 10.14.6 (18G103), HaC Mini 2.1, Ethernet works fine.

i think + means further version. currently 2.1 is latest.

followed those steps, i fixed my ethernet ,its working very well now.

**Comment by soyoh** [comment]
Hello!
I'm having the same issue after upgrading to the 2.1 (I only managed to install with the 2.0)

```
Just mount the EFI partition and replace the two files in EFI/OC/Kexts
```

those are some new concepts for me, is there a guide on how to do it?

**Comment by haakon-nergaard** [comment]
> those are some new concepts for me, is there a guide on how to do it?
There are several. This was the top hit when I googled "macos mount efi":
https://www.modmy.com/how-mount-your-efi-partition-macos

**Comment by osy86** [comment]
https://github.com/osy86/HaC-Mini/releases/download/v2.1/HaCMini.pkg

There was an issue with the package builder on Catalina. It was not properly including the networking kexts. Please try this re-upload.

**Comment by osy86** [comment]
Fixed in latest installer.
