### ISSUE TITLE
Ethernet not working

### ISSUE THREAD

**Issue by SNGDude** [osy86/HaC-Mini#67]
**Describe the bug**
After skip ethernet setup(skipped, Ethernet not working at all for both port)

**Expected behavior**
can not use ethernet both ports.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.1
- OSX version [e.g: 10.14.6]: 10.14.6 latest
- NUC model [e.g: NUC8i7HNK]: NUC8i7 hades canyon that expensive one.
- Boot SSD model and protocol Samsung nvme oem model
- Second SSD model and protocol (if installed)  intel 760p 512g
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: ddr4 2666 16gb (dell)
- Second DIMM model (if installed): ddr4 2666 16gb (dell)
- Display port(s) used [e.g: USB-C, mini DP]: mini dp and usb-c
- Display resolution(s) [e.g: 4K, 5K]: 2k
- Any TB3 devices: no
- Any USB devices: mouse keyboard

**Modifications**
nope

**Panic log**

**Comment by haakon-nergaard** [comment]
Same as #65?

**Comment by SNGDude** [comment]
> Same as #65?

hmm, actually not exactly the same.

I experienced another bug , i used a kingston USB stick to install OSX, but after finished, i couldn't boot without that USB Stick.

but i reinstalled with another usb stick, this time i could boot . so i changed my topic to report taht Ethernet and Bluetooth not working issue.

**Comment by haakon-nergaard** [comment]
Not to be snarky, but after you succeeded with installing and booting you are left with no working ethernet ports, exactly as in #65? Have you tried replacing the kexts as described in the last few comments in #65?

**Comment by SNGDude** [comment]
> Not to be snarky, but after you succeeded with installing and booting you are left with no working ethernet ports, exactly as in #65? Have you tried replacing the kexts as described in the last few comments in #65?

yes, but also no bluetooth.

**Comment by haakon-nergaard** [comment]
Bluetooth and wifi live together on the same board and is unfortunately not supported in MacOS. Have a look at this:
https://osy.gitbook.io/hac-mini-guide/post-installation/wifi

**Comment by SNGDude** [comment]
I'm not satisfied with current solution, i'll ask my friend help me with this issue, maybe i could post some solution about this driver.

**Comment by osy86** [comment]
Please keep this open as I don’t think the issue has been resolved.

**Comment by osy86** [comment]
Please try https://github.com/osy86/HaC-Mini/releases/download/v2.1/HaCMini.pkg

There was an issue with the build.

Please move discussion to #65 as this is a duplicate ticket.

**Comment by SNGDude** [comment]
okay, will try it tmr. with fresh installation.

**Comment by osy86** [comment]
You can run the installer over an existing one. But if your installation already works you don’t need to do anything. This is mostly for future people not to hit the same issue.

**Comment by SNGDude** [comment]
from my experience, if you have 2.1 mojave installed, upgrade is very smooth using apple store.

no further action needed.



ke@fairnode.org
 
From: osy86
Date: 2019-10-11 03:36
To: osy86/HaC-Mini
CC: SNGDude; State change
Subject: Re: [osy86/HaC-Mini] Ethernet not working (#67)
You can run the installer over an existing one. But if your installation already works you don’t need to do anything. This is mostly for future people not to hit the same issue.

**Comment by ts1g** [comment]
@osy86 is there a way to rerun the 2.2 installer on an existing installation, to gain the better USB power management? Or is it a specific kext that needs to be replaced? Thx!

**Comment by osy86** [comment]
Yeah you can rerun it
