### ISSUE TITLE
Panic after macOS Preboot

### ISSUE THREAD

**Issue by vitolio00** [osy86/HaC-Mini#69]
I am trying to install macOS 10.14.0 (Mojave) on my Hades Canyon i7-8809G.

I am using Crucial MX500 1TB (SATA) + USB stick  Cruzer 16GB, with Clover + HacMini 1.4.1.

The installer runs fine, I even went as far as "pre-booting" after installation, i.e. macOS Pre-boot but whenever I select macOS, the system just boots then panics straight away.

I have attached three videos:

1. No personalised boot-args
2. -disablegfxfirmware
3. agpdmod=vit9696

None of them produce success in booting. Where do I go from now?

Thanks!

**Comment by osy86** [comment]
10.14.0 is not supported. It will not boot with HaC mini. Please follow https://osy.gitbook.io/hac-mini-guide/installation-guide/installation
