### ISSUE TITLE
Extreme display artifacting/flickering when using dual 4k 60hz displays

### ISSUE THREAD

**Issue by jonseppanen** [osy86/HaC-Mini#71]
**PLEASE READ THE FOLLOWING**

**Describe the bug**
When using dual 4k 60hz displays with any combination of ports/cables, the displays flicker with extreme artifacting as if experiencing a GPU failure. This artifacting is not similar to the metal driver issues in the readme. Occasionally, a display will temporarily power down.
Flickering appears to be more extreme during hardware accelerated chrome pages and electron apps.

**Expected behavior**
Displays to work normally.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.1+
- OSX version [e.g: 10.14.6]: Latest Mojave
- NUC model [e.g: NUC8i7HNK]: Hades Canyon GH
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung 970 evo
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Kingston
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: Combinations of mini-dp to dp 1.2, hdmi 2.0, dp 1.2 to hdmi 2.0, thunderbolt to dp 1.2, and thunderbolt to hdmi 2.0
- Display resolution(s) [e.g: 4K, 5K]: Dual 4k 60hz
- Any TB3 devices: 
- Any USB devices: 

**Modifications**

**Panic log**.

**Comment by jonseppanen** [comment]
Note that flicker reduces substantially when using lower refresh rates, and no flickering appears with a single display.

**Comment by jonseppanen** [comment]
Also note, flicker appears on Both Displays at the same time

**Comment by osy86** [comment]
Is this related to #7

**Comment by jonseppanen** [comment]
Don't think so, as this happens immediately on cold boot.

**Comment by osy86** [comment]
Changing resolution does nothing?

**Comment by jonseppanen** [comment]
Reducing the refresh rate drastically reduces the flickering, and so does lowering the resolution, but it is still present.
Im willing to bet it is power package or voltage related, as it is similar in appearance to artifacting caused by overclocking a gpu too far without upping voltage.
Is there a way I can disable the vega and try the intel graphics temporarily?

**Comment by osy86** [comment]
Not possible, intel igpu isn’t physically connected to any outputs. You can only use it for compute.

**Comment by deepmining** [comment]
> Also note, flicker appears on Both Displays at the same time

Are you resolved? I have the problem the same to you.

**Comment by deepmining** [comment]
> Not possible, intel igpu isn’t physically connected to any outputs. You can only use it for compute.

I have dual 4k display , but the displays flicker . Can you help me?

**Comment by osy86** [comment]
@deepmining try workaround in #7

**Comment by K-telj** [comment]
ive only seen this when i use the HDPI version of a resolution, whenever I select the non HDPI version it works ok, with multiple monitors
![Screen Shot 2019-10-11 at 6 56 42 PM](https://user-images.githubusercontent.com/6404667/66689477-087a7b80-ec59-11e9-871c-00d785ae9cbc.png)

**Comment by osy86** [comment]
I think the root cause is the same as #7 so let's keep the conversation there.

**Comment by deepmining** [comment]
> I think the root cause is the same as #7 so let's keep the conversation there.

You closed this issue. But it not resolved.  Use #7 resolution to test,  It's not works. I think this is different issue. Can you help me ?

**Comment by osy86** [comment]
> I think this is different issue.

Why do you think so? It is very likely the same issue and if you read #7 you can see that it is an OSX driver/framebuffer issue and is unlikely to be fixed anytime soon. My suggestion is to use another resolution that does not flicker.

**Comment by deepmining** [comment]
> > I think this is different issue.
> 
> Why do you think so? It is very likely the same issue and if you read #7 you can see that it is an OSX driver/framebuffer issue and is unlikely to be fixed anytime soon. My suggestion is to use another resolution that does not flicker.

I using dual 4k 60hz displays.  other resolution only reduces the flickering.  and so does lowering the resolution, but it is still present.

**Comment by osy86** [comment]
Try different ports/cables.

**Comment by deepmining** [comment]
I have try all of ports/cables, It still not works.

**Comment by deepmining** [comment]
When using dual 4k 60hz displays with MacBook Pro , It works perfectly. I think it is not OSX problem.

**Comment by jonseppanen** [comment]
Also tried the fix, it is definitely not resolved with that issue. Completely different.

It appears to be a problem with the hidpi scaling that apple does. Seems to be over time the data becomes more and more corrupted. Perhaps apple is doing some change tracking for the hidpi image updates that isnt working right. Likely related to the baffin fixes done for this installer.

As per the different ports/cables comment - we just spent $200 on multiple different cables today to fix it, mixtures of HDMI2.0, mini DP to DP 1.4, etc etc. No difference.

99% sure it is something wrong with baffin driver hidpi scaling function.

**Comment by osy86** [comment]
That is unfortunate, but unless #7 is resolved, I don't think there's a fix. I'm pretty sure it's the same root cause, it's just in some situation the issue is more severe. I will prioritize this issue after TB is working.

**Comment by deepmining** [comment]
I'm sure the issue cause is the  driver hidpi scaling. @osy86 , can you resolve the hidpi problem.

**Comment by osy86** [comment]
> I will prioritize this issue after TB is working.

**Comment by deepmining** [comment]
@osy86  thanks a lot . I'm waiting for you .

**Comment by osy86** [comment]
Can either of you try to disable the Polaris22MetalFixup.kext from config.plist and see if that affects the flickering?

**Comment by deepmining** [comment]
> Can either of you try to disable the Polaris22MetalFixup.kext from config.plist and see if that affects the flickering?

I have tried . but have another problem.

**Comment by K-telj** [comment]
ill check it out after work, wasn't really suffering from this issue though.

**Comment by deepmining** [comment]
@osy86 I tried to remove from the EFI/OC/kexts directory. and the metal app's icon shows graphic artifacting.

**Comment by osy86** [comment]
So we know that 1) this is the same issue as #7 as I suspected and 2) it has nothing to do with my patches and is an OSX driver issue. It will be very difficult to fix.

**Comment by deepmining** [comment]
1) when I set the resolution with hidpi, it flickering. the others resolution without hidpi, it's OK.
I think this issue is  related to hidpi . Can you  resolve this issue?////

**Comment by deepmining** [comment]
I think it should not be  problem of  OSX driver .   Maybe  occur in patches.

**Comment by osy86** [comment]
It is an OSX issue. You can disable every single patch and still see the issue.
