### ISSUE TITLE
Boot hangs on white apple logo loading stage after upgraded from Hac Mini v2.1 to 2.2

### ISSUE THREAD

**Issue by iiicwx** [osy86/HaC-Mini#73]
**Describe the bug**
Boot hangs on white apple logo loading stage after upgraded from Hac Mini v2.1 to 2.2

**Expected behavior**
On Hac Mini v2.1, everything works fine.

**Configuration**
Scenarios tested: 2
HaC Mini version: 2.2
OSX version: Catalina 10.15
NUC model: NUC8i7HVK
Boot SSD model and protocol: sandisk extreme pro 500g m.2 for macos
Second SSD model and protocol: samsung 970 evo plus 500g m.2 for win10
First DIMM model: micron SODIMM 8GB 2666Mhz
Second DIMM model: none
Display port(s) used: mini dp to dp
Display resolution(s): 3440x1440
Any TB3 devices: -
Any USB devices: logitech g810 and g502

**Modifications**
tried several times of v2.2 on different ways to make sure the config.plist is upgraded, all resulted at the same issue:
1. used hacmini.pkg to upgrade directly, without making changes.
2. downloaded the efi.zip to replace the files in the efi folder.
3. deleted all the files in the efi folder and copied only the files from the downloading efi.zip
no other kexts were added.
WIFI: Intel 8265ac, no wifi, but BT works fine on v2.1.

*Panic log**
![IMG_2965](https://user-images.githubusercontent.com/56515855/66738137-15bc8380-ee6e-11e9-9b85-3ad4d1a1df3d.jpeg)

**Comment by osy86** [comment]
Can you try replacing WhateverGreen.kext with the one from v2.1?

**Comment by iiicwx** [comment]
> Can you try replacing WhateverGreen.kext with the one from v2.1?

I got the same issue with the same messages in -v mode.

and I tried the rest nvram too, but no difference.

**Comment by osy86** [comment]
The ACPI errors are weird because it implies the ACPI isn't being patched correctly. Can you upload your config.plist here just so I can confirm nothing weird happened to the patches?

**Comment by iiicwx** [comment]
1. This one is directly from the downloaded efi.zip file 
[config.plist.zip](https://github.com/osy86/HaC-Mini/files/3725695/config.plist.zip)

2. This one I used first and the seria# was changed to my previous one and added 2 entries of timeout and showpicker under the boot section.
[config.plist modded.zip](https://github.com/osy86/HaC-Mini/files/3725709/config.plist.modded.zip)

Both of the two config.plists resulted in the same error.

and below is the one from v2.1, which works fine, the seria# was changed and added 2 entries of timeout and showpicker under the boot section.
[config.plist v2.1.zip](https://github.com/osy86/HaC-Mini/files/3725720/config.plist.v2.1.zip)

Thank you so much!

**Comment by osy86** [comment]
Can you try booting with something plugged into the TB3 port?

**Comment by iiicwx** [comment]
yes, I did try this before with or without a type-c to lightning cable connect with the nuc through the front and one of the rear ports to my iphone, though it is not a TB3 cable.

**Comment by osy86** [comment]
How long do you wait after it hangs? Sometimes after a few minutes it’ll print more messages about the error.

**Comment by iiicwx** [comment]
It was about 15 minutes I think. I just reboot it and let it run one hour this time to see if can get any more info, since it took about one hour for the loading bar to run out at the first time.

**Comment by osy86** [comment]
In the past I’ve seen this kind of error from WhateverGreen issues and with SATA SSDs. But neither seems to be the issue here. Any way you can dump your acpi tables? Was wondering if maybe there’s some weird difference there.

Also you’re on the latest bios?

**Comment by iiicwx** [comment]
The bios is 86A or v0058, it is the latest.

Let me see if I can dump the acpi tables and get back to you later.

**Comment by iiicwx** [comment]
When I searched for the error message, it came up that a guy had the same issue when he tried to upgrade the clover, he managed to solve it with a fresh os installation.

I had Mojave and v2.1, and upgraded to Catalina directly under v2.1 a few days ago. 

Do you think it is relevant?

**Comment by osy86** [comment]
It may be but it could be a coincidence. Try a second install if you want.

**Comment by iiicwx** [comment]
I will download the Catalina image and try it with the v2.2 tomorrow.

By the way, there are no more new messages from the -v mode screen, the screenshot is all it generated.

Thank you!

**Comment by iiicwx** [comment]
Hi @osy86 ,

tried to install a new copy of 10.15 with v2.2, ended up with the same issue at loading the installer.
![IMG_2970](https://user-images.githubusercontent.com/56515855/66827691-84254280-ef4f-11e9-8cdd-bff893fe9363.JPG)

**Comment by iiicwx** [comment]
Hi @osy86,

after added an entry "change PNP0C09 to PNPFFFF"under ACPI>Patch, V2.2 now works fine with me. 

But the TB still shows No drivers are loaded.

**Comment by iiicwx** [comment]
System information shows as below when connecting iphone with a type c to lightning cable to the NUC
1. Front USB C port, shows iphone under USB3.1 Bus
2. Rear Left TB3 port, iphone indicates connected, but nothing shows up in System Information.
3. Rear Right TB3 port, shows iphone under USB3.0 Bus.

**Comment by osy86** [comment]
I think 2.3 fixes this because it forces lilu and VSMC to be loaded first.

**Comment by iiicwx** [comment]
Hi @osy86 
the problem persists with me, still have to add the entry "change PNP0C09 to PNPFFFF" .

In win10, there is an Unsupported Device in the Device Manager, I can't find a driver for it, not sure whether it is related.

![IMG_3011](https://user-images.githubusercontent.com/56515855/68048774-93431900-fce1-11e9-8d6b-fb0ace7fef81.JPG)

**Comment by iiicwx** [comment]
![871E50AD-076E-4370-AB3E-F66B401CFDFD](https://user-images.githubusercontent.com/56515855/68049164-7f4be700-fce2-11e9-8fb2-01ed6eaf5532.jpeg)

**Comment by osy86** [comment]
That’s due to your rename.

**Comment by osy86** [comment]
Did you run 2.3.2 installer?

**Comment by iiicwx** [comment]
yes, It is on 2.3.3

**Comment by iiicwx** [comment]
2.3.2

**Comment by osy86** [comment]
Just to make sure nothing weird is going on can you upload your EFI directory?

**Comment by iiicwx** [comment]
@osy86 

the file is too big, can you download it here, https://www.dropbox.com/s/h06ua1fctoe3yq1/EFI.zip?dl=0

**Comment by osy86** [comment]
This is the problem
```
			<dict>
				<key>BundlePath</key>
				<string>AppleALC.kext</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/AppleALC</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>BundlePath</key>
				<string>VirtualSMC.kext</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VirtualSMC</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>BundlePath</key>
				<string>IntelMausi.kext</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/IntelMausi</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
			<dict>
				<key>BundlePath</key>
				<string>Lilu.kext</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/Lilu</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
```

As you can see, Lilu is not first. I thought I fixed this in 2.3. Can you run the installer again and this time post /var/log/install.log? I want to see why the script failed to place Lilu first.

**Comment by iiicwx** [comment]
@osy86 
the new EFI folder:
https://www.dropbox.com/s/zm501kiduu55p9i/EFI2.zip?dl=0

Log file:
[install.log](https://github.com/osy86/HaC-Mini/files/3799506/install.log)

**Comment by iiicwx** [comment]
my options when run the installer:
![Screenshot 2019-11-01 at 21 25 34](https://user-images.githubusercontent.com/56515855/68054712-3a7a7d00-fcef-11e9-8c97-67ba0261d125.png)

**Comment by osy86** [comment]
After you run it, post /var/log/install.log

**Comment by osy86** [comment]
Thank you I will debug. In the meantime you can turn off secure boot, and manually move Lilu to the first entry.

**Comment by osy86** [comment]
I see you are installing to a USB. Is the EFI from the same usb?

**Comment by osy86** [comment]
Please try 2.3.3

**Comment by iiicwx** [comment]
@osy86 

the issue is still here with me, the secure boot was always turned off in bios, and lilu is the first entry.
![IMG_3013](https://user-images.githubusercontent.com/56515855/68057925-be386780-fcf7-11e9-961c-488c9063e8d6.JPG)
[install.log](https://github.com/osy86/HaC-Mini/files/3799704/install.log)

**Comment by iiicwx** [comment]
[EFI.zip](https://github.com/osy86/HaC-Mini/files/3799723/EFI.zip)

EFI folder 2.3.3

**Comment by nagaitsev** [comment]
I had the same issue. It looks that you have old bios. After update firmware to last version freeze solved

**Comment by iiicwx** [comment]
> I had the same issue. It looks that you have old bios. After update firmware to last version freeze solved

you are right!!! though I have the latest bios version, but after I did a reset in bios, it works fine now.

Thank you and @osy86 , for all the time of helping me in this issue!
