### ISSUE TITLE
About This Mac identifies unit as "iMac" and not Mac mini anymore.

### ISSUE THREAD

**Issue by Malumen** [osy86/HaC-Mini#74]
Installed using HaC mini .pkg v2.1 and said correct info. Now after using v2.2 info refers system as iMac, is this intentional?
![Screen Shot 2019-10-15 at 10 06 04 PM](https://user-images.githubusercontent.com/56620641/66887781-5107a100-ef99-11e9-97c4-be6d0fe26f7a.jpg)

**Comment by osy86** [comment]
No, but I think it's the same bug as #59 Can you run your serial on https://everymac.com/ultimate-mac-lookup/ ? Also did you regenerate the serial on the installer?

**Comment by Malumen** [comment]
> No, but I think it's the same bug as #59 Can you run your serial on https://everymac.com/ultimate-mac-lookup/ ? Also did you regenerate the serial on the installer?

Using my current serial number:

![Screen Shot 2019-10-16 at 12 09 18 AM](https://user-images.githubusercontent.com/56620641/66892585-5240ca00-efa9-11e9-8c52-a4169a90a943.png)

I can try re-running the pkg and I'll select the `generate unique identifiers`

**Comment by osy86** [comment]
Tracking in #59 

Don't re-run the pkg, the `macserial` program is out of date.
