### ISSUE TITLE
Cannot shutdown properly. Restarts instead.

### ISSUE THREAD

**Issue by Malumen** [osy86/HaC-Mini#76]
Unsure if this is a known-bug with macOS/hackintosh, but I tried using the 
`change Method(_PTS,1,N) to ZPTS: 5F505453 01 to 5A505453 01`
EFI/ACPI/Add
EFI/ACPI/Patch
And perhaps I just did it wrong. 

In macOS select shutdown, spins shutdown grey wheel -> looks like it is shutting down but LEDs do not turn off and just engages a restart instead. BIOS flashes and it will attempt to load my Windows 10 SSD.

Interestingly if I mash F10 at this time and select macOS it will greet me with an improper shutdown error.

In this loop, I cannot shutdown normally at all. It will just loop back to restart.

**Configuration**
- HaC Mini version: 2.2 
- OSX version: 10.14.6 
- NUC model: NUC8i7HVK 
- Boot SSD model and protocol: Intel 760p 1TB NVMe
- _Second SSD_ model and protocol: Samsung 970 Pro 512GB NVMe (_Windows 10_)
- First DIMM model: Kingston HyperX 2400MHz 16GB
- Second DIMM model: Kingston HyperX 2400MHz 16GB 
- Display port(s) used: miniDP to HDMI2.0 
- Display resolution: 4k60
- Any TB3 devices: n/a
- Any USB devices: Logitech USB unifying receiver (K830 keyboard synced)

**Comment by osy86** [comment]
I have no idea what that patch is supposed to do.

**Comment by Malumen** [comment]
> I have no idea what that patch is supposed to do. But it is bad.

OK. I will use your .pkg to return to stock settings.
Is the panic log useful to find out what is causing the panic? Seems to perhaps be related to IONVMeFamily??

`*** Panic Report ***
panic(cpu 6 caller 0xffffff7f98eb3b30): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0x4e VID/DID=0xf1a58086
. FW Revision= PSF121C\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-387.270.1/IONVMeController.cpp:5334
Backtrace (CPU 6), Frame : Return Address`.....

**Comment by osy86** [comment]
1. You wrote a patch to disable ACPI shutdown code then complain that shutdown isn’t working. Do not blindly write patches or you’ll end up destroying your machine.
2. I’m not sure about the panic but it’s probably related to #22 please search before posting a new issue.
3. Please keep relevant discussion to their respective tickets. It’s impossible to keep track of things otherwise.
