### ISSUE TITLE
Can't disable SIP

### ISSUE THREAD

**Issue by Deftaudio** [osy86/HaC-Mini#78]
Just installed Mojave 10.14.6 with HacMini2.1 and then upgraded with HacMini2.2.
Sorry, totally confused I can't disable SIP. I'm able to load recovery partition and I run csrutil disable, however on the normal restart it's enabled again. Am I doing something wrong? Sorry, my first time with Hac-mini.

**Comment by osy86** [comment]
For hackintoshes, that is not how you disable SIP. Please see https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/config.plist/kaby-lake#nvram

**Comment by osy86** [comment]
New proposal to make SIP disable work as expected: https://github.com/acidanthera/bugtracker/issues/575
