### ISSUE TITLE
Aerial connections to BCM94360CS2

### ISSUE THREAD

**Issue by hepto** [osy86/HaC-Mini#79]
While replacing the wireless card with a BCM94360CS2, is there a preferred combination of the wires and the connectors?

The card has two connectors (labelled 0 and 1), and the NUC has two wires (black, and a white-labelled one).

Just wondered if there was a system or whether just connecting them was OK.  Currently I have white -> 0, black -> 1.

**Comment by jingquanquan2018** [comment]
two connectors are just connect two same antennas, they have no difference
