### ISSUE TITLE
TB3.0 unblocker integrate with an installer

### ISSUE THREAD

**Issue by Deftaudio** [osy86/HaC-Mini#81]
Hi, would it be possible to integrate Thunderbolt unblocker with the installer or patch TB kext to enable unsupported hardware? 
thanks!

**Comment by osy86** [comment]
I don’t like how the unblocker works currently. It’s very messy and breaks other things. If anyone makes a better one (i.e. as a kext you add) I will consider including it as an installer option.

**Comment by Deftaudio** [comment]
Would be better then just to patch the driver with this script? https://github.com/KhaosT/tb3-enabler

**Comment by osy86** [comment]
The script is bad because it breaks with SIP and won’t survive an upgrade. But I just saw https://github.com/rgov/Thunderbolt3Unblocker linked from that page. That’s acceptable. I’ll consider adding it as an option in the future.

**Comment by Deftaudio** [comment]
Thank you

**Comment by KrisCris** [comment]
> Thank you, I'll be happy to test that.

Have you tried to output video via tb-3? I am planning to buy this PC so I want to make sure whether it works.

**Comment by Deftaudio** [comment]
I did not. Why would I if there are plenty of minidisplay ports?

**Comment by osy86** [comment]
I've used TB3 display port exclusively.

**Comment by KrisCris** [comment]
> I've used TB3 display port exclusively.

Thanks.
