### ISSUE TITLE
Display output seems totally broken in 10.15.1 beta 2

### ISSUE THREAD

**Issue by 22dm** [osy86/HaC-Mini#83]
**Describe the bug**
After updated to 10.15.1 beta 2, there's no any display output, have tried:

- HDMI(both)
- TB3(both)
- TB3 to HDMI
- Mini-DP to HDMI

All of these worked fine in 10.15.1 beta 1.

Apple logo and progress bar showed normal, then I only got a black screen, I can only access my computer by ssh and vnc / teamviewer. After installing the 10.15 stable version, everything works fine. (Oh my God, I never knew that it could be downgraded directly.) 

10.15.1 [increased the support of eGPU](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_1_beta_2_release_notes), perhaps because of this.

**Expected behavior**
I only want to see something on my screen.

**Configuration**
- HaC Mini version: 2.1 / 2.2
- OSX version: 10.15.1 beta 2
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: Samsung 970 Pro 512GB NVME
- Second SSD model and protocol: Another Samsung 970 Pro 512GB NVME
- First DIMM model: Samsung DDR4-2666 16GB (overclocked to 3200)
- Second DIMM model: Same as the 1st one
- Display port(s) used: TB3 / HDMI
- Display resolution(s): 3K(via TB3) / 2K 120Hz(via HDMI)

**Modifications**
Nothing.

**Panic log**
Just as I not plugged any display in, can't find any panic / error log.

**Comment by a13302211596** [comment]
delete WhateverGreen.kext

**Comment by a13302211596** [comment]
> **Describe the bug**
> After updated to 10.15.1 beta 2, there's no any display output, have tried:
> 
> * HDMI(both)
> * TB3(both)
> * TB3 to HDMI
> * Mini-DP to HDMI
> 
> All of these worked fine in 10.15.1 beta 1.
> 
> Apple logo and progress bar showed normal, then I only got a black screen, I can only access my computer by ssh and vnc / teamviewer. After installing the 10.15 stable version, everything works fine. (Oh my God, I never knew that it could be downgraded directly.)
> 
> 10.15.1 [increased the support of eGPU](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_1_beta_2_release_notes), perhaps because of this.
> 
> **Expected behavior**
> I only want to see something on my screen.
> 
> **Configuration**
> 
> * HaC Mini version: 2.1 / 2.2
> * OSX version: 10.15.1 beta 2
> * NUC model: NUC8i7HVK
> * Boot SSD model and protocol: Samsung 970 Pro 512GB NVME
> * Second SSD model and protocol: Another Samsung 970 Pro 512GB NVME
> * First DIMM model: Samsung DDR4-2666 16GB (overclocked to 3200)
> * Second DIMM model: Same as the 1st one
> * Display port(s) used: TB3 / HDMI
> * Display resolution(s): 3K(via TB3) / 2K 120Hz(via HDMI)
> 
> **Modifications**
> Nothing.
> 
> **Panic log**
> Just as I not plugged any display in, can't find any panic / error log.

delete WhateverGreen.kext

**Comment by osy86** [comment]
This is the same issue as #1 but the workaround is no longer working. Needs more work to figure out the root cause.

**Comment by osy86** [comment]
Apparently the latest WG resolves this.

**Comment by osy86** [comment]
Added WG 1.3.4 to fix black screen issues.

**Comment by ts1g** [comment]
> Added WG 1.3.4 to fix black screen issues.

Is there a way to install the "updated WhateverGreen to 1.3.4 (to fix black screen issues with 10.15.1) on a machine that's been effected by the black-screen issue, short of pulling the HDD or SSD and connecting it to another machine, then mounting EFI and replacing the old WG? Like some form of old-school Target Disk Mode?

**Comment by osy86** [comment]
Yes install it to a usb OS X installer. Enable boot picker. But boot into OS X instead of the installer.

**Comment by ts1g** [comment]
> Yes install it to a usb OS X installer. Enable boot picker. But boot into OS X instead of the installer.

Worked like a charm, and kept me from having to disassemble the NUC. Thanks! Back up and running after updating to WG 1.3.4 via HaCmini 2.3.3 with no black screen...

**Comment by kachunkachunk** [comment]
Just in case others run into this and don't want to reboot into (or even recreate) the installer - I was able to log in via SSH (TeamViewer/VNC would probably work too), wget/SCP over an updated HaCMini.pkg release into ~/Downloads, then install it: `sudo installer -pkg ~/Downloads/HaCMini.pkg -target /`

`sudo reboot` then watch the screen come alive afterwards.
