### ISSUE TITLE
Cannot Boot: OC: Configuration requires vault but no vault provided!

### ISSUE THREAD

**Issue by songlairui** [osy86/HaC-Mini#84]
**Describe the bug**
A clear and concise description of what the bug is. What is the installation destination (boot drive, USB installer drive, other drive)? What installation options are selected?
the installer cannot boot.
it shows: 

```
...
...
OC: Configuration requires vault but no vault provided!
```

Clover was OK

After install with Clover, the OC error presist.

**Expected behavior**

**Environment:**
 - Running OSX version: 
 - Target drive OSX version: 
 - HaC Mini installer version: 
 10.14.6

**Additional context**

**Logs**
Please attach `/var/log/install.log`

**Comment by songlairui** [comment]
something here: https://www.insanelymac.com/forum/topic/338516-opencore-discussion/?do=findComment&comment=2677709

it says the `vault.plist` file should create

**Comment by osy86** [comment]
Did you modify config.plist? I have use vault set to false so it shouldn’t require it.

**Comment by songlairui** [comment]
> Did you modify config.plist? I have use vault set to false so it shouldn’t require it.

Yes, I changed it with the clover config.plist(which able to boot).

Then I reset the OC files and boot/bootx64.efi
The screen was lighted(backlight was on) with nothing. 

When press ctrl + alt + del, it can reboot.

---------
another detail:
My wifi card to replace has not arrive me, the original wifi card was left on the mainboard, would this be the key problem?

**Comment by osy86** [comment]
Clover config.plist != OC config.plist. They do not work. You cannot use Clover config.plist. You cannot use Clover Configurator. You cannot use any guides that refer to Clover. HaC Mini 1.x supports Clover. You should use that if you wish to use Clover. There is NO clover support on 2.x.

**Comment by songlairui** [comment]
sorry about that

**Comment by songlairui** [comment]
Yes, I have just know OC from the guide.

My operation misleading the problem.

I'll try again with wifi card replaced.

Thank you very much.
