### ISSUE TITLE
Boot a black screen with V2.2

### ISSUE THREAD

**Issue by rhtect** [osy86/HaC-Mini#88]
**Environment:**
 - Running OSX version: 10.14.6
 - Target drive OSX version: 10.14.6
 - HaC Mini installer version: 2.1

**Additional context**
My current operating system is 10.14.6 using the V1.4.1 version. Now update the V2.2 version, directly replace the EFI folder, and restart the computer with a black screen. How do I update the OPEN CORE guide?

**Logs**
Please attach `/var/log/install.log`

**Comment by jingquanquan2018** [comment]
change your config 
Root/Misc/Boot 
like this by Xcode
```
<dict>
	<key>ConsoleBehaviourOs</key>
	<string></string>
	<key>ConsoleBehaviourUi</key>
	<string></string>
	<key>ConsoleMode</key>
	<string></string>
	<key>HibernateMode</key>
	<string>none</string>
	<key>HideSelf</key>
	<true/>
	<key>PollAppleHotKeys</key>
	<true/>
	<key>Resolution</key>
	<string>1920x1080@60</string>
	<key>ShowPicker</key>
	<true/>
	<key>Timeout</key>
	<integer>15</integer>
	<key>UsePicker</key>
	<true/>
</dict>
```

**Comment by rhtect** [comment]
> change your config
> Root/Misc/Boot
> like this by Xcode
> 
> ```
> <dict>
> 	<key>ConsoleBehaviourOs</key>
> 	<string></string>
> 	<key>ConsoleBehaviourUi</key>
> 	<string></string>
> 	<key>ConsoleMode</key>
> 	<string></string>
> 	<key>HibernateMode</key>
> 	<string>none</string>
> 	<key>HideSelf</key>
> 	<true/>
> 	<key>PollAppleHotKeys</key>
> 	<true/>
> 	<key>Resolution</key>
> 	<string>1920x1080@60</string>
> 	<key>ShowPicker</key>
> 	<true/>
> 	<key>Timeout</key>
> 	<integer>15</integer>
> 	<key>UsePicker</key>
> 	<true/>
> </dict>
> ```

thank you

**Comment by rhtect** [comment]
> change your config
> Root/Misc/Boot
> like this by Xcode
> 
> ```
> <dict>
> 	<key>ConsoleBehaviourOs</key>
> 	<string></string>
> 	<key>ConsoleBehaviourUi</key>
> 	<string></string>
> 	<key>ConsoleMode</key>
> 	<string></string>
> 	<key>HibernateMode</key>
> 	<string>none</string>
> 	<key>HideSelf</key>
> 	<true/>
> 	<key>PollAppleHotKeys</key>
> 	<true/>
> 	<key>Resolution</key>
> 	<string>1920x1080@60</string>
> 	<key>ShowPicker</key>
> 	<true/>
> 	<key>Timeout</key>
> 	<integer>15</integer>
> 	<key>UsePicker</key>
> 	<true/>
> </dict>
> ```

I changed the information, but it didn't work. Can you share your revised EFI?

**Comment by osy86** [comment]
Installer for v2.3 lets you enable boot picker. Also updated https://osy.gitbook.io/hac-mini-guide/post-installation/support#black-screen-after-post-when-booting-up-or-after-selecting-boot-drive with directions for getting past black screen boot.
