### ISSUE TITLE
DW1820A support as an installer option

### ISSUE THREAD

**Issue by osy86** [osy86/HaC-Mini#91]
Since many users have this configuration, we should add an option in the installer.

Since I do not have this to work with, I need help from someone who has gotten it working. Please provide me with the kexts, patches, and anything else required for the card to work Wifi+BT.

@22dm can you help?

**Comment by 22dm** [comment]
Well, DW1820A have many versions, like CN-0VW3T3, CN-096JNT and CN-08PKF4. It seems that different versions have slightly different compatibility.

<img width="274" alt="DW1820A" src="https://user-images.githubusercontent.com/7871070/67630575-d3129680-f8c4-11e9-8e78-cadb432c249e.png">

I only have a CN-08PKF4, in order to get this work, I did these changes:

The kexts need to be added:
- for Wi-Fi
  - `AirportBrcmFixup`
- for Bluetooth
  - `BrcmPatchRAM3.kext`
  - `BrcmBluetoothInjector.kext`
  - `BrcmFirmwareData.kext`

These can be found at:
- https://github.com/acidanthera/AirportBrcmFixup
- https://github.com/acidanthera/BrcmPatchRAM

Also, `config.plist` needs to be modified:
- Add kexts to `Kernel -> Add`
- Add these to `DeviceProperties -> Add`:
```
<key>PciRoot(0x0)/Pci(0x1c,0x2)/Pci(0x0,0x0)</key>
<dict>
	<key>AAPL,slot-name</key>
	<string>WLAN</string>
	<key>compatible</key>
	<string>pci14e4,4353</string>
	<key>device_type</key>
	<string>Airport Extreme</string>
	<key>model</key>
	<string>DW1820A (BCM4350) 802.11ac Wireless</string>
	<key>name</key>
	<string>Airport</string>
</dict>
```
- Add `brcmfx-country=#a brcmfx-driver=1` to `boot-args`

By the way, there is a bug: if you boot into Linux / Windows and comeback to macOS, Wi-Fi and Bluetooth will be unusable (appears but won't work). In order for it to work again, you need to unplug the power cord and wait a few seconds before plugging it in.

This is the EFI I am using (removed the UUID, SN and MLB):
[EFI.zip](https://github.com/osy86/HaC-Mini/files/3775564/EFI.zip)

These website is also useful:
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
https://osxlatitude.com/forums/topic/11540-dw1820a-the-general-troubleshooting-thread/

**Comment by HorstBrack75** [comment]
Really depends on the "flavour" of the card. I can conform that what @22dm wrote works for me as well. Some people claim they had to mask some pins using duct tape though. (Never had to do this.)
 
> By the way, there is a bug: If you boot into Linux / Windows and comeback to macOS, Wi-Fi and Bluetooth will be unusable (appears but won't work). In order for it to work again, you need to unplug the power cord and wait a few seconds before plugging it in.

Did you try using the same firmware version in Windows / Linux / Mac OS? (This seems to have solved the issue for me.)

**Comment by 22dm** [comment]
> Really depends on the "flavour" of the card. I can confirm that what @22dm wrote works for me as well. Some people claim they had to mask some pins using duct tape though. (Never had to do this.)
> 
> > By the way, there is a bug: If you boot into Linux / Windows and comeback to macOS, Wi-Fi and Bluetooth will be unusable (appears but won't work). In order for it to work again, you need to unplug the power cord and wait a few seconds before plugging it in.
> 
> Did you try using the same firmware version in Windows / Linux / Mac OS? (This seems to have solved the issue for me.)
> 
> [99V46.zip](https://github.com/osy86/HaC-Mini/files/3775723/99V46.zip)
It works, thx 👍

**Comment by msedek** [comment]
@22dm i have the same model CN-08PKF4 but not sure what to do to make it work.. evey time i plug the card macos goes boot loops and when ever it makes it to the os the card is no where to be founf.. im pretty new thi hackingtosh and dont knwo whats all thise kext etc about..

theres a hac-mini version i think its 2.2.2 that has an option for installing the driver but doesnt work.. would LOVE to have that card working so my hac mini would be perfect 100%.. i have 1 drive for windows and 1 drive for macos and dual boot currently using a common usb drive for both system with no bluetooth =/

**Comment by 22dm** [comment]
> @22dm i have the same model CN-08PKF4 but not sure what to do to make it work.. evey time i plug the card macos goes boot loops and when ever it makes it to the os the card is no where to be found.. im pretty new to hackingtosh and dont know whats all this kext etc about..

**Warning, misuse may cause your system to fail to boot or even data lost.**
**Warning, misuse may cause your system to fail to boot or even data lost.**

1. mount the EFI partition:
  - open Terminal
  - sudo diskutil mount EFI
  - enter your password (no echo while you're typing) and press return
  - then you'll see EFI partition in Finder
2. add kexts:
   - download my [kexts.zip](https://github.com/osy86/HaC-Mini/files/3802666/kexts.zip)
   - unzip and put the four kexts to /EFI/OC/Kexts in your EFI Partition
3. edit /EFI/OC/config.plist:
  - open /EFI/OC/config.plist
  - Add these to this place (1/3)
```
<key>PciRoot(0x0)/Pci(0x1c,0x2)/Pci(0x0,0x0)</key>
<dict>
	<key>AAPL,slot-name</key>
	<string>WLAN</string>
	<key>compatible</key>
	<string>pci14e4,4353</string>
	<key>device_type</key>
	<string>Airport Extreme</string>
	<key>model</key>
	<string>DW1820A (BCM4350) 802.11ac Wireless</string>
	<key>name</key>
	<string>Airport</string>
</dict>
```
<img width="446" alt="截屏2019-11-0412 26 37" src="https://user-images.githubusercontent.com/7871070/68099613-5dc74700-fefe-11e9-877e-afbae4f6d4ca.png">

  - Add these to this place (2/3)
```
<key>BundlePath</key>
	<string>AirportBrcmFixup.kext</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/AirportBrcmFixup</string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>BundlePath</key>
	<string>BrcmBluetoothInjector.kext</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>BundlePath</key>
	<string>BrcmFirmwareData.kext</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/BrcmFirmwareData</string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>BundlePath</key>
	<string>BrcmPatchRAM2.kext</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/BrcmPatchRAM2</string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
```

<img width="427" alt="截屏2019-11-0412 28 58" src="https://user-images.githubusercontent.com/7871070/68099692-b26ac200-fefe-11e9-95b9-996bf809f27d.png">

  - Add these to this place (3/3)

```
 brcmfx-country=#a brcmfx-driver=1
```

<img width="920" alt="截屏2019-11-0412 30 05" src="https://user-images.githubusercontent.com/7871070/68099713-d62e0800-fefe-11e9-88b5-cfd148110337.png">

4. shutdown, unplug power cable, wait a while, plug in again, boot, enjoy

**Comment by runninglol** [comment]
Mine is CN-096JNT, Wifi and BT both work for me.
Attached 99V46.zip works for windows.
Thank you so much guys.

**Comment by HorstBrack75** [comment]
> @22dm i have the same model CN-08PKF4 but not sure what to do to make it work.. evey time i plug the card macos goes boot loops and when ever it makes it to the os the card is no where to be found.. im pretty new to hackingtosh and dont know whats all this kext etc about..
> 
> theres a hac-mini version i think its 2.2.2 that has an option for installing the driver but doesnt work.. would LOVE to have that card working so my hac mini would be perfect 100%.. i have 1 drive for windows and 1 drive for macos and dual boot currently using a common usb wifi card for both system with no bluetooth =/

This sounds really strange. If I boot without the kexts, bluetooth will just not work. No boot loop. (WiFi works OOB on my 08PKF4.) If you disable WiFi and Bluetooth devices in BIOS, will it boot again?

**Comment by goodbest** [comment]
@22dm I've also got my DW1820A working, described in https://github.com/osy86/HaC-Mini/issues/113
Maybe you can also try those steps ?

The main difference with your solution is that:
1. I disable PCIE ASPM in bios, which is suggested in [this post](https://osxlatitude.com/forums/topic/12169-bcm4350-cards-registry-of-cardslaptops-interop/)
2. I don't need to add property pci14e4,4353 into the config.plist.
  - As a result, my system is natively loading BrcmNic.kext, rather than Brcm4360 in your system. However, I think this won't cause boot loop. And I don't need to add `brcmfx-driver=1` in boot-arg (becasue it's default).
 - The loaded kext info can be found by `about this mac`->`Software, Extensions`

**Comment by msedekhyh** [comment]
I could not Make it work with the provided steps, the card Works perfectly in windows, im just punished to use a trash low speed usb wifi and having no bluettoth

**Comment by 22dm** [comment]
> @22dm I've also got my DW1820A working, described in #113
> Maybe you can also try those steps ?
> 
> The main difference with your solution is that:
> 
> 1. I disable PCIE ASPM in bios, which is suggested in [this post](https://osxlatitude.com/forums/topic/12169-bcm4350-cards-registry-of-cardslaptops-interop/)
> 2. I don't need to add property pci14e4,4353 into the config.plist.
> 
> * As a result, my system is natively loading BrcmNic.kext, rather than Brcm4360 in your system. However, I think this won't cause boot loop. And I don't need to add `brcmfx-driver=1` in boot-arg (becasue it's default).
> * The loaded kext info can be found by `about this mac`->`Software, Extensions`

Thanks, It works very well. I have tried a similar attempt, but I have not disabled PCIE ASPM, and if I don't disable it, it will cause bootloop.

BrcmPatchRAM3 (2.5.0) seems still prevent me from connecting to my mouse (M590) and keyboard (K375) via bluetooth. However, I can connect to my iPad Pro, while AirDrop and Sidecar are also working.

**Comment by msedekhyh** [comment]
@22dm I followed your steps and it didnt work, then changed the PCIE ASPM in biod, did your steps and boom.. everything working 100%,, would love if you add the DW1820 driver as an option in the hac-mini installation.. now i got a GOLD build, no adapters no anything, 2 m.2 nvme samsungs 1 with windows and 1 with macos'
Hands down the hades canyon is the best hackintosh in the world

**Comment by 22dm** [comment]
> @22dm I followed your steps and it didnt work, then changed the PCIE ASPM in bios, did your steps and boom.. everything working 100%,, would love if you add the DW1820 driver as an option in the hac-mini installation.. now i got a GOLD build, no adapters no anything, 2 m.2 nvme samsungs 1 with windows and 1 with macos'
> Hands down the hades canyon is the best hackintosh in the world

So what’s the version of your card? Is it CN-08PKF4 or CN-096JNT?

**Comment by osy86** [comment]
Please test: https://github.com/osy86/HaC-Mini/issues/113#issuecomment-552291341

**Comment by osy86** [comment]
Please test the pkg in the pull request (above)

**Comment by msedek** [comment]
> CN-08PKF4
CN-08PKF4

**Comment by SSebo** [comment]
CN-0VW3T3 works like a charm! THX

**Comment by zdaxie** [comment]
@SSebo Hi, I wanna know if I want to work with CN-0VW3T3, is there anything need to be changed according to what mentioned in this issue?
Thanks a lot!

**Comment by chatelp** [comment]
Hi there,

 I'm also trying to make my DW1820A (model CN-08PKF4) work under Catalina. After following the advices here, my Wifi is working, but can't connect to bluetooth devices. Like many of you it seems. Is there any new advice/solution in Feb 2020?

- My loaded BT firmware version is v7 c44689, although it looks like that BrcmPatchRAM is not able to connect to the device at boot time (see boot log bellow)
- On the kext site, I'm using BrcmPatchRAM-2.5.1-RELEASE in S/L (BrcmBluetoothInjector.kext, BrcmFirmwareRepo.kext and BrcmPatchRAM3.kext). I also tried first the vanilla / boot injection first with clover (swapping BrcmFirmwareRepo.kext with BrcmFirmwareData.kext) but same result.
- My device properties is as follows:
```
<key>PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0,0x0)</key>
            <dict>
                <key>AAPL,slot-name</key>
                <string>WLAN</string>
                <key>compatible</key>
                <string>pci14e4,4353</string>
                <key>device_type</key>
                <string>Airport Extreme</string>
                <key>model</key>
                <string>Dell DW1820 (BCM4350) 802.11ac wireless</string>
                <key>name</key>
                <string>Airport</string>
                <key>pci-aspm-default</key>
                <integer>0</integer>
            </dict>
```
- My boot args are as follows:
```
<key>Arguments</key>
        <string>kext-dev-mode=1 amfi_get_out_of_my_way=1 dart=0 -igfxnohdmi brcmfx-country=#a rtcfx_exclude=56-58 brcmfx-driver=1</string>
```
- I didn't see any ASPM option to disable in my BIOS, but there is the pci-aspm-default/0 entry in clover. Is that enough?

What's less clear to me:
**- I saw multiple advices on forums about checking USB? My System Informations says that BCM2045AO is "internal". Is that enough?**
**- Is there anything else I can try?**

Boot log from BrcmPatchRAM:
```
Filtering the log data using "process == "kernel" AND composedMessage CONTAINS[c] "brcm""
Skipping info and debug messages, pass --info and/or --debug to include.
Timestamp                       (process)[PID]
2020-02-04 22:36:05.093980+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211Controller::init(OSDictionary*)> AirPort_BrcmNIC::init AirPortFamily_kexts-1580.2 "AirPortFamily_kexts-1580.2" Jan  9 2020 21:50:21
2020-02-04 22:36:05.094015+0100  localhost kernel[0]: (AirPortBrcmNIC) <AirPortBrcmNIC`osl_iolog_withtimestamp> ARPT: 1.094012: AirPort_Brcm43XX:probe:, this[0x5726cc79de9f6595]  score[2048]
2020-02-04 22:36:05.094030+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211Controller::init(OSDictionary*)> AirPort_BrcmNIC::init AirPortFamily_kexts-1580.2 "AirPortFamily_kexts-1580.2" Jan  9 2020 21:50:21
2020-02-04 22:36:05.094048+0100  localhost kernel[0]: (AirPortBrcmNIC) <AirPortBrcmNIC`osl_iolog_withtimestamp> ARPT: 1.094046: AirPort_Brcm43XX:probe:, this[0x5726cc79dfeca595]  score[1400]
2020-02-04 22:36:05.094060+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211Controller::init(OSDictionary*)> AirPort_Brcm4360::init AirPortFamily_kexts-1580.2 "AirPortFamily_kexts-1580.2" Jan  9 2020 21:50:21
2020-02-04 22:36:05.094076+0100  localhost kernel[0]: (AirPortBrcm4360) <AirPortBrcm4360`osl_iolog_withtimestamp> ARPT: 1.094074: AirPort_Brcm43XX:probe:, this[0x8dfdfc16f0fb27f7]  score[1110]
2020-02-04 22:36:08.302842+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211Controller::init(OSDictionary*)> AirPort_BrcmNIC::init AirPortFamily_kexts-1580.2 "AirPortFamily_kexts-1580.2" Jan  9 2020 21:50:21
2020-02-04 22:36:08.302895+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211Controller::init(OSDictionary*)> AirPort_BrcmNIC::init AirPortFamily_kexts-1580.2 "AirPortFamily_kexts-1580.2" Jan  9 2020 21:50:21
2020-02-04 22:36:08.302919+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211Controller::init(OSDictionary*)> AirPort_Brcm4360::init AirPortFamily_kexts-1580.2 "AirPortFamily_kexts-1580.2" Jan  9 2020 21:50:21
2020-02-04 22:36:08.302990+0100  localhost kernel[0]: (AirPortBrcm4360) <AirPortBrcm4360`osl_iolog_withtimestamp> ARPT: 5.398926: AirPort_Brcm43XX:probe:, this[0x8dfdfc16f0edf7f7]  score[1110]
2020-02-04 22:36:08.320802+0100  localhost kernel[0]: (kernel) BrcmPatchRAM: Version 2.5.1 starting on OS X Darwin 19.3.
2020-02-04 22:36:08.441690+0100  localhost kernel[0]: (AirPortBrcm4360) <AirPortBrcm4360`osl_iolog_withtimestamp> ARPT: 5.537627: BRCM tunables:
2020-02-04 22:36:08.942980+0100  localhost kernel[0]: (BrcmFirmwareRepo) <BrcmFirmwareRepo`BrcmFirmwareStore::loadFirmwareFile(char const*, char const*)> BrcmPatchRAM: Loaded firmware "BCM4350C5_003.006.007.0222.4689_v8785.zhx" from resources.
2020-02-04 22:36:08.943266+0100  localhost kernel[0]: (BrcmFirmwareRepo) <BrcmFirmwareRepo`BrcmFirmwareStore::loadFirmware(unsigned short, unsigned short, OSString*)> BrcmPatchRAM: Decompressed firmware (12582 bytes --> 31740 bytes).
2020-02-04 22:36:08.943524+0100  localhost kernel[0]: (BrcmFirmwareRepo) <BrcmFirmwareRepo`BrcmFirmwareStore::loadFirmware(unsigned short, unsigned short, OSString*)> BrcmPatchRAM: Firmware is valid IntelHex firmware.
2020-02-04 22:36:09.045125+0100  localhost kernel[0]: (kernel) BrcmPatchRAM: uploadFirmware could not open the device!
2020-02-04 22:36:09.045131+0100  localhost kernel[0]: (kernel) BrcmPatchRAM: Processing time 0.101 seconds.
2020-02-04 22:36:09.049014+0100  localhost kernel[0]: (kernel) BrcmPatchRAM: Version 2.5.1 starting on OS X Darwin 19.3.
2020-02-04 22:36:09.149684+0100  localhost kernel[0]: (kernel) BrcmPatchRAM: [0a5c:6412]: USB [F828196A1998 v274] "BCM2045A0" by "Broadcom Corp"
2020-02-04 22:36:09.152125+0100  localhost kernel[0]: (kernel) BrcmPatchRAM: [0a5c:6412]: Firmware upgrade not needed.
2020-02-04 22:36:09.152257+0100  localhost kernel[0]: (kernel) BrcmPatchRAM: Processing time 0.103 seconds.
2020-02-04 22:36:09.668802+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211Controller::logDebug(char const*, ...)> AirPort_Brcm4360::getSSIDData(): Get failure: APPLE80211_IOC_SSID: 6
2020-02-04 22:36:12.820869+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211VirtualInterface::init(IO80211Controller*, ether_addr*, unsigned int, char const*)> IO80211VirtualInterface::AirPort_Brcm4360_P2PInterface::init name <p2p0> role 1
2020-02-04 22:36:12.821841+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211P2PInterface::init(IO80211Controller*, ether_addr*, unsigned int, char const*)> AirPort_Brcm4360_P2PInterface::init <p2p> role 1
2020-02-04 22:36:12.823553+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211VirtualInterface::init(IO80211Controller*, ether_addr*, unsigned int, char const*)> IO80211VirtualInterface::AirPort_Brcm4360_P2PInterface::init name <awdl0> role 4
2020-02-04 22:36:12.823572+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211P2PInterface::awdlAttachToBpf()> AirPort_Brcm4360_P2PInterface::awdlAttachToBpf name <awdl0> role 4 successful attach to bpf type 147
2020-02-04 22:36:12.839765+0100  localhost kernel[0]: (IO80211Family) <IO80211Family`IO80211P2PInterface::init(IO80211Controller*, ether_addr*, unsigned int, char const*)> AirPort_Brcm4360_P2PInterface::init <awdl> role 4
```

**Comment by chatelp** [comment]
Found solution: https://osxlatitude.com/forums/topic/12392-solved-7490-catalina-dw1820a-bluetooth-problem/

**Comment by songssam** [comment]
It is not available

**Comment by captainz236** [comment]
> Mine is CN-096JNT, Wifi and BT both work for me.
> Attached 99V46.zip works for windows.
> Thank you so much guys.

What model is your notebook?
I want to buy a wirelesscard for omen by hp-15ce008tx.I already install a hackintosh for it.But I don't know which one can work on my notebook.

**Comment by swatchie-1** [comment]
Hi guys. Got the DW1820a too. But can Apple WAtch's Auto Unlock feature work reliably each time you sleep and wake your machine?

**Comment by deftdawg** [comment]
Just installed an DW1820A (CN-08PKF4), downloaded the latest HaCMini.pkg and ran it adding the DW1820A support, rebooted and I wifi and bluetooth, however the bluetooth had dropouts (tested a bluetooth speaker and a magic pad). 

Various versions of kexts on [this thread](https://www.tonymacx86.com/threads/the-solution-dell-dw1820a-broadcom-bcm94350zae-macos-15.288026/page-6#post-2070368), however wasn't successful...  (I didn't modify my config.plist, just swapped kexts into the EFI kexts folder)

Finally I tried the set that @chatelp suggested and I removed `BrcmPatchRAM3.kext` as `BrcmPatchRAM2.kext` was included with the bunch, rebooted and audio drop outs stopped, now playing songs on my speaker 10 ft away no problem.  

For the magic pad, I thought I'd try changing the batteries and that seemed to do it, so looks like it's good. 

Attached is the kexts at the link:
[BT for DW1820A Ver.2.zip](https://github.com/osy86/HaC-Mini/files/4784607/BT.for.DW1820A.Ver.2.zip)

**Comment by lmshsqlc** [comment]
@deftdawg im curious what’s your macos version. According to BrcmPatchRAM, BrcmPatchRAM3.kext should be there for 10.15. And only one of the three BrcmPatchRAMs should exist.

**Comment by deftdawg** [comment]
@lmshsqlc 10.15.4 (19E287), I have `BrcmPatchRAM2.kext`, #3 was there but I deleted it.  I also have `BT4LEContinuityFixup.kext` that came with one of the previous ones on the tonymacx86 thread I mentioned in my last post, but it didn't help with the Bluetooth audio drops, so I assume it isn't actually doing anything.

**Comment by lmshsqlc** [comment]
@deftdawg try use the original BrcmPatchRAM repository as your manual as tonymacx86 is not a legit manual. It might have some deprecated solutions. 
In this case, the continuity fixup is no longer needed. And BrcmPatchRAM3 needs BrcmBluetoothInjector in order to make it work in macOS 10.15. 

Follow this manual and you should be alright. 
https://github.com/acidanthera/BrcmPatchRAM/blob/master/README.md

**Comment by deftdawg** [comment]
@lmshsqlc, it's not particularly important to me what version number is on the bits as long as the work...  😄  
If they break down the line,  I'll try that repo.  'til then I'll leave them be.  Thanks though.

**Comment by jack338c** [comment]
> By the way, there is a bug: If you boot into Linux / Windows and comeback to macOS, Wi-Fi and Bluetooth will be unusable (appears but won't work). In order for it to work again, you need to unplug the power cord and wait a few seconds before plugging it in.

@HorstBrack75  my dw182pa have this bug too
Could you tell me how to apply this https://github.com/osy86/HaC-Mini/files/3775723/99V46.zip ? is thiis only for windows or for all:windows ,mac and linux?

thanks

**Comment by jack338c** [comment]
hello @22dm 

I have make my wndows 10 and linux use same firmware BCM4350C5_003.006.007.0222.4689.hex.
but I don't how to make it on my mac big sur

please help  me

thanks

**Comment by HorstBrack75** [comment]
> > By the way, there is a bug: If you boot into Linux / Windows and comeback to macOS, Wi-Fi and Bluetooth will be unusable (appears but won't work). In order for it to work again, you need to unplug the power cord and wait a few seconds before plugging it in.
> 
> @HorstBrack75 my dw182pa have this bug too
> Could you tell me how to apply this https://github.com/osy86/HaC-Mini/files/3775723/99V46.zip ? is thiis only for windows or for all:windows ,mac and linux?
> 
> thanks

That is the windows driver. I don´t think that you need to mess around with this any longer. It seems to be fully supported and integrated in the installer since quite a while now.

**Comment by jack338c** [comment]
> That is the windows driver.
> I don´t think that you need to mess around with this any longer. It seems to be fully supported and integrated in the HacMini installer since quite a while now and seems not to depend on the windows firmware any longer.

Thanks for your reply
well,Actually I use DW1820A on my X250 https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore ,not from HacMini installer.
This issue is really annoying to me. and I asked the above github code owner.he had no idea too.
