### ISSUE TITLE
installer fails to make bootable usb 2.2  / opencore doesnt boot in bios bootloader

### ISSUE THREAD

**Issue by K-telj** [osy86/HaC-Mini#94]
**Describe the bug**
repeatedly made the installer catalina usb and it fails. manually add the efi, set/double check bios and it never boots into opencore, it always goes to clover. In previous attempts i've tried to finish the install to the external drive with the clover booted usb and it works but never gets opencore to work
**Expected behavior**
boot usb into opencore, run installer, make bootable external drive catalina with opencore. 
make sure it works, then repeat on internal.

**Environment:**
 - Running OSX version: mojave 10.4.6
 - Target drive OSX version: no install
 - HaC Mini installer version: 2.2 [but i tried each version so far]

**Additional context*
2 internal drives OS X and Windows, Im using the BCM wfi solve.
[install.log](https://github.com/osy86/HaC-Mini/files/3776113/install.log)

**Logs**
Please attach `/var/log/install.log`
attached -

**Comment by osy86** [comment]
Are you following https://osy.gitbook.io/hac-mini-guide/installation-guide/installation#installing-macos

**Comment by K-telj** [comment]
yes, repeatedly.

**Comment by osy86** [comment]
I’m not sure how Clover gets in. OC is on the usb and in the first step, you wipe the SSD which would remove any trace of clover.

**Comment by K-telj** [comment]
the computer has two internal drive with active installations using clover, Im trying to get this to work on an external drive first and opencore never takes control of the boot process. with f10 it goes black then to the bios boot manager then only working on clover.
I've been following this guide since you started it and Ive made multiple versions of the installer based on release changes here and by apple updates to catalina. I did update the current mojave booting drive to the 1.41 release but havent gotten past there. none of them have been successful.

thanks for any additional information with this, Im trying to not to have to take this apart just to have a upgrade pathway.

**Comment by osy86** [comment]
I see. I think OC is still pretty buggy. I’ll include a new build in the next release. In the meantime, enable the boot picker menu and see if that helps.

**Comment by K-telj** [comment]
got to the installer booting though opencore, updated the opencore efi to the latest and it seemed to make the usb work. thanks for the help. still working on install now.

**Comment by K-telj** [comment]
got it to install catalina to internal and opencore to show
