### ISSUE TITLE
CPU temperature sensor not showing up

### ISSUE THREAD

**Issue by lisongzhou19** [osy86/HaC-Mini#95]
有着2个参数无法启动
PciRoot(0x0)/Pci(0x15,0x1）i2c-channel-number
PciRoot(0x0)/Pci(0x15,0x2) i2c-channel-number
传感器只有ssd无cpu

**Comment by osy86** [comment]
You've deleted the issue template. I've made it for a reason. It is hard to help when I do not know what your configuration is, what modifications you've made, and so on.

When you delete those two entries, it works?

**Comment by lisongzhou19** [comment]
I'm sorry it was wrong before 
Now try it 
The new upgrade can enter MAC without any modification. 
Modify config.plist to add a driver or modify UUID to disable Mac. After the MAC flag flashes, start

**Comment by lisongzhou19** [comment]
![Xnip2019-10-28_13-56-06](https://user-images.githubusercontent.com/56990075/67655543-ec324a80-f98b-11e9-9376-0c077fb738ed.jpg)

**Comment by lisongzhou19** [comment]
![Xnip2019-10-28_14-07-53](https://user-images.githubusercontent.com/56990075/67655659-5f3bc100-f98c-11e9-9c39-9caeff20b8e7.jpg)

**Comment by lisongzhou19** [comment]
[config.plist.zip](https://github.com/osy86/HaC-Mini/files/3777358/config.plist.zip)

**Comment by lisongzhou19** [comment]
To configure

Memory Kingston 8g * 2

Hard disk Intel ssdpekw010t8 1T

Wi Fi dw1830

**Comment by osy86** [comment]
Do not use that configuration tool. I just diffed the config.plist and it added many useless and maybe outdated entries. You should always manually edit config.plist. If you do not know how, ask the community and refer to https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf

**Comment by lisongzhou19** [comment]
Thanks for compiling with plistedit Pro

Sensor has no CPU, only SSD

**Comment by lisongzhou19** [comment]
![Xnip2019-10-28_16-23-22](https://user-images.githubusercontent.com/56990075/67662911-47ba0380-f99f-11e9-96cf-a0599709a16b.jpg)

**Comment by osy86** [comment]
Can you modify the config.plist and move the entry for SMCProcessor.kext to be right after the entry for VirtualSMC.kext?

**Comment by lisongzhou19** [comment]
Can change position display
thanks

**Comment by osy86** [comment]
Okay I will fix positioning in the next release.

**Comment by HorstBrack75** [comment]
> Okay I will fix positioning in the next release.

I changed the kext order like you recommended. I see the sensors attached in the screenshot. Is it normal that I don't see the fan?

![Screenshot 2019-10-31 at 10 23 14](https://user-images.githubusercontent.com/2854956/67934701-b1692600-fbc8-11e9-8eb3-a0940175439c.png)

**Comment by osy86** [comment]
Did you see it before?

**Comment by osy86** [comment]
Right that’s an known issue with virtualsmc

**Comment by keatliang2005** [comment]
I came across this about VirtualSMC plugins, seems like something new (maybe ?)

SMCSuperIO.kext, Used for monitoring fan speed

maybe can add this too ?? For add fan speed monitoring capabilities on next update ?

https://dortania.github.io/OpenCore-Install-Guide/ktext.html#virtualsmc-plugins

**Comment by osy86** [comment]
Fan speed requires custom drivers. That kext doesn’t work for us.
