### ISSUE TITLE
USB installer patching fails due to permission issues

### ISSUE THREAD

**Issue by unsek** [osy86/HaC-Mini#96]
**Describe the bug**
I've tried with v2.3 and v2.2 with SIP enabled and both failed to install during running package scripts. However, disabling SIP will allow the installation to succeed.

**Expected behavior**
It shouldn't matter if SIP is enabled/disabled.

**Environment:**
 - Running OSX version: macOS Catalina 
 - Target drive OSX version: macOS Mojave (10.14.6)
 - HaC Mini installer version: 2.3

**Additional context**
N/A

**Logs**
Unfortunately do not have the log for when it failed anymore because I successfully got to install it in the end.

**Comment by osy86** [comment]
Please still attach /var/log/install.log. Even if it’s successful in the end, the log is not erased, it is only appended to. I can still see the error.

**Comment by boredchinese** [comment]
I see.

[install.log](https://github.com/osy86/HaC-Mini/files/3783452/install.log)

**Comment by osy86** [comment]
The problem is here
```
2019-10-28 19:02:30+08 CFs-iMac installd[2126]: ./postinstall: rmdir: /Volumes/Install macOS Mojave: Resource busy
2019-10-28 19:02:30+08 CFs-iMac installd[2126]: PackageKit: Executing script "./postinstall" in /private/tmp/PKInstallSandbox.ocTH7L/Scripts/com.osy86.hacmini.patchinstaller.SxMGcL
2019-10-28 19:02:31+08 CFs-iMac installd[2126]: ./postinstall: find: /Volumes/Install macOS Mojave/.Spotlight-V100: Operation not permitted
```

For some reason, your install USB appeared to be empty after the install. My guess is it had something to do with the EFI unmounting. I'm not sure how it's related to SIP though. This may be an OSX bug.

**Comment by boredchinese** [comment]
The computer I was using when it failed was an iMac. Making the installer on a Hackintosh works just fine though without disabling SIP.

**Comment by hansthefox** [comment]
Based on this issue I tried to use v2.3 and later versions, with different OSX (10.13, Mojave and Catalina, even I disable SIP), I found that I finally made it by Clover Bootloader to make an EFI folder first in the USB, then the Installer will finish the patch successfully. I don't know if there is any point to address this issue.
