### ISSUE TITLE
Ui, can you be more refined, now the ui font is a bit fuzzy

### ISSUE THREAD

**Issue by gaowenzhen** [osy86/HaC-Mini#97]
Ui, can you be more refined, now the ui font is a bit fuzzy

**Comment by osy86** [comment]
Please provide screenshot. Please provide configuration details that you deleted from the issue template.

**Comment by osy86** [comment]
Are you talking about the OS X feature? Use ```defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO```
To disable

**Comment by osy86** [comment]
Closing due to lack of information.
