### ISSUE TITLE
Black screen on upgrade to Catalina 10.15.1 (fixed)

### ISSUE THREAD

**Issue by Jase-NZ** [osy86/HaC-Mini#99]
**Describe the bug**
Black screen on upgrade to Catalina 10.15.1

**Expected behavior**
Concise screen

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.0
- OSX version [e.g: 10.14.6]: 10.15.1

I am still on 2.0 as I have no issues with it, When upgrading to the latest release of Catalina 10.15.1 you end up with just a black screen.

I changed whatevergreen to version 1.3.4 and we are all good again.

This was just a more fyi you may have already changed the main installer.

**Comment by osy86** [comment]
#83
